### ISSUE TITLE
asset helper with favicon

### ISSUE THREAD

**Issue by kongdigital** [TryGhost/Ghost#9095] opened 2017-10-04 08:02 UTC
### Issue Summary

When calling `{{asset 'favicon.ico}}` I expected it to return `/assets/favicon.ico` however it always returns `/favicon.ico` regardless of where I put the asset. For example if I put the asset under `folder/favicon.ico` it still returns `/favicon.ico`

This is not mentioned in the docs for the asset helper. Nor can I see it mentioned anywhere on the docs site. It is very confusing.

* Ghost Version: 1.10
* Node Version: 6.11

**Comment by AileenCGN** [comment] 2017-10-04 08:09
Hey @kongdigital 👋 

Since Ghost 1.0 theme favicons are not supported anymore, but are a custom blog setting instead and can be uploaded in General -> Settings -> Publication icon

If no Publication icon is uploaded, `{{asset "favicon.ico"}}` will render a default Ghost favicon.

See [here](https://themes.ghost.org/docs/changelog#section-miscellaneous). 

If you have questions, please swing by in our [slack](https://slack.ghost.org) to ask, rather than opening issues, as we sorely use GitHub for bugs and not for questions, feature requests, or support.

Closing this as it's not a bug.

**Closed by AileenCGN** 2017-10-04 08:09 UTC

**Comment by kongdigital** [comment] 2017-10-04 08:28
Thanks @AileenCGN  I raised an issue because I thought the docs should clearly state this behaviour. Having a helper return a value completely unexpected is a very frustrating.

Where should I raise issues with the docs?

**Comment by AileenCGN** [comment] 2017-10-04 10:38
You can suggest edits on themes.ghost.org when you find the documentation not completed.

The usage of favicons in themes pre Ghost 1.0 is documented [here](https://themes.ghost.org/v0.11.11/docs/asset#section-favicons) and then in the change log for Ghost 1.0 as mentioned above.
