### ISSUE TITLE
Can't close modal after click on suscribe

### ISSUE THREAD

**Issue by nachovdk** [TryGhost/Ghost#11387] opened 2019-11-12 14:55 UTC
### Technical details: Hi guys, when you click on subscribe on the top of the site, you cannot close the modal. 

* Ghost Version: 3.0.3
* Node Version: v10.17.0
* Browser/OS: Chrome/Mac OS 15.1
* Database: MySQL

**Comment by nachovdk** [comment] 2019-11-12 14:58
Only works when you click just above of "X"

**Comment by kevinansfield** [comment] 2019-11-12 17:28
Closing as a duplicate of https://github.com/TryGhost/Casper/issues/630

**Closed by kevinansfield** 2019-11-12 17:28 UTC
