### ISSUE TITLE
Error alert when activiting a new theme

### ISSUE THREAD

**Issue by hzb** [TryGhost/Ghost#10764] opened 2019-05-29 06:35 UTC
When I upload a new theme it will show error like this

![Screen Shot 2019-05-29 at 13 31 25](https://user-images.githubusercontent.com/535675/58534793-ca873880-821e-11e9-8601-526b3196f94c.png)

But actually, there's no `{{@blog}}` in files.

![Screen Shot 2019-05-29 at 13 33 01](https://user-images.githubusercontent.com/535675/58534871-fc000400-821e-11e9-8397-dfa25a1acb38.png)

More information:

* Ghost Version: 2.23.1

* Environment development

* Node Version: v10.13.0

* Browser/OS: Firefox 67.0 / Chrome 74.0.3729.169 (Official Build) (64-bit)

* Database: sqlite3

**Comment by kevinansfield** [comment] 2019-05-29 08:46
@hzb `{{@blog}}` itself is never used as it's a holder for other properties such as `{{@blog.url}}`, you can see the full list here https://docs.ghost.org/api/handlebars-themes/helpers/site/. You should adjust your search to look for `{{@blog` instead. Also if you click on the error you will get more information such as which files are failing the deprecation check.

Closing as this is not a bug. If you feel the error message is too confusing feel free to open an issue to that effect on the theme-validation project https://github.com/TryGhost/gscan 🙂

**Closed by kevinansfield** 2019-05-29 08:46 UTC
