### ISSUE TITLE
Writing out a heading that starts with an ordinal number strips heading markup

### ISSUE THREAD

**Issue by javorszky** [TryGhost/Ghost#11813] opened 2020-05-12 09:26 UTC
### Issue Summary

On the current version available on Ghost(pro) (3.15.3)

when I write an article that's a listicle, and
I want the 2nd level headings to look like a numbered list
the editor strips the heading block when using markdown notation:

What I want:
```
Here's my top 5 of X

## 1. One of the five titles

Text about the first one...
```

What I get:
```
Here's my top 5 of X

1. One of the five titles

Text about the first one...
```
See this gif:

![Screen Capture on 2020-05-12 at 10-21-45](https://user-images.githubusercontent.com/1196299/81666858-8181c180-943a-11ea-869c-b3d88c6f4a51.gif)

### To Reproduce

1. Start writing a post
2. Try to create a second heading that starts with an ordinal number
3. Witness the heading being stripped

### Technical details:

* Ghost Version: 3.15.3
* Node Version: whatever is on (pro)
* Browser/OS: Firefox 76.0.1 (64-bit) / macOS Catalina 10.15.4 (19E287)
* Database: whatever is used on (pro)

**Comment by javorszky** [comment] 2020-05-12 09:29
I can get around the issue by adding a markdown block with the (+), and then writing out `## 1. heading text goes here`, but then I don't expect that to autoformat while I'm editing it.

See this other gif:

![Screen Capture on 2020-05-12 at 10-29-16](https://user-images.githubusercontent.com/1196299/81667709-82ffb980-943b-11ea-94c1-5bfde91ea621.gif)

**Comment by kevinansfield** [comment] 2020-05-12 11:21
The markdown-like text expansions are only shortcuts, they are not a full markdown replacement, as such they cover the most common use-case for `1. `at the beginning of a paragraph which is to create a numbered list.

However, the expansions are undoable so you can type `## ` which transforms to a heading, then start typing your heading. At the `1. ` point which transforms to a list, press <kbd>Cmd+Z</kbd> to undo the list transformation and then continue typing the rest of the heading.

We don't have enough context within the editor to know exactly what is intended for formatting text-expansions in every situation which is why we target the most-common use-cases and have the undo ability for when it doesn't quite match what was intended.

This is the first report around this issue we've had in nearly 2 years which suggests the most-common use case is right the majority of the time. The only way to change would be to introduce inconsistent behaviour through guessing at the expected transformation or to remove the expansions altogether, neither of which are particularly good options. As such I'm going to close this but I'll keep an eye out for any other reports.

**Closed by kevinansfield** 2020-05-12 11:21 UTC
