### ISSUE TITLE
npm install ghost@0.7.2 fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by sdaitzman** [TryGhost/Ghost#6157] opened 2015-12-01 22:50 UTC
I use Ghost on a server running Ubuntu 14.04, node@v0.10.25, npm@3.5.0.

`$ npm install ghost@latest` fails, while `$ npm install ghost@0.7.1` works as expected (but with many warnings. I've tried installing `ghost@latest` with node v4.2.2 using NVM but this did not work either.

Here's the part of `npm-debug.log` that says what is failing:
```log
53996 error Tell the author that this fails on your system:
53996 error     npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()"
```

If you want the rest of `npm-debug.log`, please let me know. I'd be happy to gist it for you.

**Comment by ErisDS** [comment] 2015-12-01 23:27
Please can you gist the full output from the commandline as well as the npm-debug.log. The piece you posted says which line failed but is missing any indication as to why.

**Comment by sdaitzman** [comment] 2015-12-01 23:37
Here's me installing ghost@latest, `$ cat npm-debug.log`, then trying again but with 0.7.1 https://gist.github.com/sdaitzman/738b138415f9a2c8cd2b

**Comment by sdaitzman** [comment] 2015-12-02 01:19
That log is everything in one place, which I've now realized is a jumbled mess :sob: 

If it's more helpful I can gist the commandline output and `npm-debug.log` separately?

**Comment by ErisDS** [comment] 2015-12-02 03:24
I've got enough info now, thanks. I can reproduce the issue, and have found a similar issue on the [npm repo here](https://github.com/npm/npm/issues/10565).

The issue is not reproducible with npm@3.4, so I'd recommend downgrading and using a previous version to get Ghost installed for now. As far as I can tell, this is an issue with npm and not Ghost.

**Comment by jgillich** [comment] 2015-12-08 02:36
Looks like a npm bug, but maybe we should just bundle semver? Calling npm from npm is a bit weird anyway.

**Comment by ErisDS** [comment] 2015-12-08 10:51
I'm not sure what you mean by 'bundle semver'? Looking at the repo, it really seems npm is overwhelmed with support issues at the moment. The technical jump between npm 2 and npm 3 is huge and I think it's pretty much to be expected that you might run into bugs if you use the very latest version.

For now, I recommend downgrading to npm 3.4. I'm going to close this as we can't influence npm, but I will keep an eye on the bug and if more people run into it, or we find out we're doing something wrong then I'll reopen / suggest a fix.

**Closed by ErisDS** 2015-12-08 10:51 UTC

**Comment by jgillich** [comment] 2015-12-08 11:04
I meant include it as a submodule so the preinstall hook becomes less fragile. semver is just a single file with no deps.

**Comment by ErisDS** [comment] 2015-12-08 11:29
I don't think that's necessary. It's a bug with npm, they should fix it, we shouldn't be adding workarounds IMO.

**Comment by naoyak** [comment] 2016-03-21 18:41
Getting a similar error:
```
56750 verbose stack Error: ENOTEMPTY: directory not empty, rename '/Users/naoya/Nebia/website/nebia.com/node_modules/.ghost.DELETE/node_modules/semver' -> '/Users/naoya/Nebia/website/nebia.com/node_modules/ghost/node_modules/semver'
56750 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/action/finalize.js:64:7
56750 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
56750 verbose stack     at Array.forEach (native)
56750 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
56750 verbose stack     at Array.forEach (native)
56750 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
56750 verbose stack     at moveModules (/usr/local/lib/node_modules/npm/lib/install/action/finalize.js:61:5)
56750 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/action/finalize.js:56:70
56750 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:48:26
56750 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
56750 verbose stack
56750 verbose stack Error: ENOTEMPTY: directory not empty, rename '/Users/naoya/Nebia/website/nebia.com/node_modules/.ghost.DELETE/node_modules/semver' -> '/Users/naoya/Nebia/website/nebia.com/node_modules/ghost/node_modules/semver'
56750 verbose stack     at Error (native)
```

**Comment by kimroen** [comment] 2016-05-06 08:57
For others ending up here, here's the issue that is tracking the root cause of this issue, as far as I can tell: https://github.com/npm/npm/issues/10379

**Comment by ErisDS** [comment] 2016-05-07 14:07
@kimroen that's a slight different npm bug to the one that I believe caused the original report here, but we're tracking that here #6691
