### ISSUE TITLE
URL Date Bug

### ISSUE THREAD

**Issue by benheb** [TryGhost/Ghost#7655] opened 2016-11-01 04:28 UTC
There seems to be a bug with dates and date urls. A bit funky to explain, but here's an attempt. 

Yesterday I published a blog post at 7pm MDT. The url at that point looked like: /2016/10/30/winter-2016-2017-reason-for-concern/, as expected. 

Today I went to the blog post and it had changed to /2016/10/31/winter-2016-2017-reason-for-concern/. You'll note it's October 31 now, instead of October 30, as expected. 

I checked the timezone for our ghost setup and it's set to Mountain Time, as expected. When I go back to the published post in the admin content, the settings show the correct date/time: 

<img width="332" alt="editor_-_weather5280_" src="https://cloud.githubusercontent.com/assets/910495/19878256/12e9f1c4-9fac-11e6-97e8-40eb2ec93ba6.png">

It seems to only happen with posts that are published late in the day? Maybe some weird UTC conversion somewhere? Changing the time and re-saving typically will correct the url. 

Not really sure where to look. I'm running version 0.11.2.

**Comment by kirrg001** [comment] 2016-11-01 15:07
Hey @benheb Sorry to hear you are having trouble. I would like to ask you to confirm what i understood from your issue:

You published your post on day 1 and the path was `/2016-10-30/winter...`.
You visited your post on day 2 and the path changed to `/2016-10-31/winter...`.
**You did not change your blog timezone between day 1 and day 2.**

**Comment by benheb** [comment] 2016-11-01 16:26
@kirrg001 correct. I made no changes to the timezone or the post between day 1 and 2. 

When I checked the settings on the post on day two, the date was still correct (see screenshot), but the url had changed from 30 to 31. 

I then changed the publish time to 15:00 (instead of 19:00), saved the post, and the url was correct. The URL date change seemed to happen auto-magically overnight. I've seen this happen several times recently, dating back a release or two.

**Comment by kirrg001** [comment] 2016-11-01 16:30
Ok thanks will look into this closer 👍

**Comment by benheb** [comment] 2016-11-01 16:33
Thanks @kirrg001! I'll also maybe try setting the time earlier in the day with the next post I publish and see if I still see it? Haven't paid close enough attention, but seems to have only happened with posts I publish later in the evening on Sundays. /shrug

**Comment by kirrg001** [comment] 2016-11-01 17:01
@benheb 
I also was not able to reproduce this issue. Hmm I looked at the affected code section, which calculates the path with the date permalink, but i cannot see an obvious bug.

Could you swing by our [slack channel](https://ghost.org/slack/) and write me a direct message?
Leaving this issue open until it's clear if it's a bug.

**Comment by kirrg001** [comment] 2016-11-01 17:34
We found this issue. Thanks for your help @benheb .
https://github.com/TryGhost/Ghost/blob/lts/core/server/config/url.js#L107 is reading the active timezone from the config. The active timezone was correct in the database, but somehow was not correctly updated in the config `ghostConfig.theme.timezone`. After just re-saving the timezone from Ghost-Admin it worked. I will look some minutes if i can find something obvious how this can happen.

**Comment by kirrg001** [comment] 2016-11-01 18:08
@benheb one last question. Did you ever change your timezone via Ghost-Admin (except of today)? Because i remember that we are setting the timezone automatically to your server timezone.

**Comment by benheb** [comment] 2016-11-01 18:37
@kirrg001 Good question. I'm not sure, but good chance I never did. I suspect I went and looked and saw that Mountain was selected so never touched it / saved it when I first set things up. 

What I did today was 1. Selected the drop down and re-clicked on Mountain, then 2. clicked saved in upper right, and all was good again.

**Comment by kirrg001** [comment] 2016-11-01 19:09
@benheb Thanks! I am still not able to reproduce. The settings and config cache get's updated for me. So it's unknown why your config value was not updated after updating to a newer Ghost version. I assume the value of the timezone config was still `Etc/Utc` for your case.

As we found an easy workaround for you and i am not able to reproduce this, I would like to close this issue for now. If more people report a similar issue, i will investigate furthermore. Thanks for your fast support.

**Comment by benheb** [comment] 2016-11-01 19:17
Thank you @kirrg001

**Comment by benheb** [comment] 2016-12-10 17:41
@kirrg001 just FYI, I am able to reproduce these days. Basically every time I restart the ghost server this happens. 

1. Restart node server 
2. Go to published post and see that url is wrong (7 hours ahead) if published late in day 
3. Check settings, confirm that drop down is set to Mountain time (as expected) 
4. Press save on that page and and all timezone issues are resolved

Maybe just me, but happens reliably.

**Comment by benheb** [comment] 2017-01-10 17:21
Anyone else see this? @kirrg001 Can we reopen and address?

**Comment by kirrg001** [comment] 2017-01-10 18:43
@benheb Hey! Sorry for late response. I will re-open the issue 👍 

If somebody is interested in reproducing and fixing this issue, this would be very welcome!

**Comment by acburdine** [comment] 2017-01-20 05:00
Note: #7858 also has a case of this, along with data for reproduction.

**Comment by kirrg001** [comment] 2017-02-08 11:44
I was able to reproduce - fix is coming 👍

**Comment by benheb** [comment] 2017-02-08 22:51
Awesommeeee!! 🎉

**Comment by kirrg001** [comment] 2017-02-08 23:18
closed via #7960 - will be released in `0.11.5` 🙃

**Closed by kirrg001** 2017-02-08 23:18 UTC
Labels: fix wanted, LTS, server
