### ISSUE TITLE
Remove query strings from assets

### ISSUE THREAD

**Issue by Xosmond** [TryGhost/Ghost#7093] opened 2016-07-14 15:23 UTC
Hello, I'm getting this on pingdom tools:
**Resources with a "?" in the URL are not cached by some proxy caching servers. Remove the query string and encode the parameters into the URL for the following resources**

because of this:
https://mysite.com/assets/css/myasset.css?v=12aae8e2c2

How can i solve this?
### Technical details:

* Ghost Version: 0.8
* Node Version: 0.10.46
* Server:  On Heroku Nginx.
* Database: Postgres

**Comment by acburdine** [comment] 2016-07-14 15:24
@Xosmond those query strings are precisely so those files aren't cached. In the case that one of them changes, you would want those changes to be available to those viewing your blog.

Is it causing actual errors with pingdom or is it just outputting warnings?

**Comment by Xosmond** [comment] 2016-07-14 15:29
Just warnings about them. But i want them to be cached because the site is finished, is there any way to do it?

i think the right way should be https://mysite.com/assets/css/myasset-v=12aae8e2c2.css

**Comment by kevinansfield** [comment] 2016-07-14 15:40
> those query strings are precisely so those files aren't cached

Not quite, they are there so the files *are* cached but they have a unique identifier so that when the file contents change a new identifier can be produced as a cache-busting mechanism.

> i think the right way should be https://mysite.com/assets/css/myasset-v12aae8e2c2.css 

That's an alternative way, there is no "right" way 😉 

@Xosmond The warnings are just that - warnings, indicators that you should look into something rather than something being wrong.

If you are running a caching server/service in front of your site then you can configure it to cache or not cache query-string URLs as you see fit, in general the majority of cache servers are set up to cache query-string URLs by default so you should be good. If you're not running a caching server in front of your site then you have nothing to worry about as it won't have any affect either way 😄

I'm going to close this issue as it's not a bug. If you need any further help setting up your server environment please head over to our [slack channel](https://ghost.org/slack/) where the community is at hand.

**Closed by kevinansfield** 2016-07-14 15:40 UTC
