### ISSUE TITLE
Code injection while using side by side preview not working

### ISSUE THREAD

**Issue by squadramunter** [TryGhost/Ghost#8951] opened 2017-08-28 21:55 UTC
I have a css style inserted in my code injection. Everything looks good but when I am using the side by side preview modus in ghost the html code don't show up.

Can this be fixed?

I really like when I see my working html code in live preview modus.

**Comment by acburdine** [comment] 2017-08-28 22:02
@squadramunter This is by design - the side-by-side preview is meant to be a simple preview of what the post content would look like. However, implementing this has the potential to mess up other things - e.g. if you write some css in the post code injection and it gets rendered, it could potentially mess up how Ghost-Admin functions. If you're wanting more of a live-preview, there is the preview link which you can access from the PSM.

All that aside, I'm going to close this because we use Github to track bugs and ongoing feature work - if you wish to submit a feature request please use https://ideas.ghost.org. Thank you! 😄

**Closed by acburdine** 2017-08-28 22:02 UTC
