### ISSUE TITLE
Sitemap.xml returns 404 on private blog

### ISSUE THREAD

**Issue by NistorCristian** [TryGhost/Ghost#8947] opened 2017-08-27 23:26 UTC
Hi,
I have a blog that is private at this moment. Somehow I wrote sitemap.xml in the url and I saw that the blog was redirected to a 404 page. I have the default Casper theme and inside the 404 I can see the last 3 posts. I tested on 2 blogs, with the same version of Ghost, and it was the same.

I guess that it should return nothing. Or maybe a redirect to /private ?

### Technical details:

* Ghost Version: 1.7.0

**Comment by kevinansfield** [comment] 2017-08-28 07:09
Hey @NistorChristian, a 404 is the expected behaviour for sitemap.xml when a blog is in private mode. Closing as this isn't a bug.

**Closed by kevinansfield** 2017-08-28 07:09 UTC

**Comment by NistorCristian** [comment] 2017-08-28 07:17
Yes, a 404 is expected. But isn't a little bit strange that I can see the styles and some posts from the blog ? I mean you shoudn't see much about a website when it is in private mode.

**Comment by kevinansfield** [comment] 2017-08-28 08:08
Hmm, I think the posts being visible problem is [in Casper](https://github.com/TryGhost/Casper/blob/master/error-404.hbs#L42-L52)

**Comment by NistorCristian** [comment] 2017-08-28 08:19
In my opinion if the blog is private you shoudn't be able to see anything from it, except for that /private page. 

This way I can view source of the page and get the CSS/JS from the blog. I know that I can't do much with CSS and JS, but still. One might actually put his menu, a search box (with GhostHunter), a newsletter/contact form that can be placed in footer and be visible on that 404 page. Even when the blog is private. So information that shoudn't be visible on a private blog is visible there.

**Comment by kevinansfield** [comment] 2017-08-28 11:44
You're free to edit the 404 page in your theme to match your expectations for a 404 page for a private site.

It's not possible to redirect a 404 to /private because it would no longer be a 404, you would also have a redirect loop problem if any logged in user accesses a page that returns a 404.
