### ISSUE TITLE
Email Template Header Icon Image Missing Alt Tag

### ISSUE THREAD

**Issue by willkramer** [TryGhost/Ghost#12652] opened 2021-02-15 18:08 UTC
https://github.com/TryGhost/Ghost/blob/21bea798486fa115aa1bfe178cb71df1ea5cae4a/core/server/services/mega/template.js#L887

For accessibility purposes, the icon image that is inserted in the header of the email template should include an empty alt tag to indicate that the image is purely decorative per the [guidelines at W3](https://www.w3.org/WAI/tutorials/images/decorative/#image-used-as-part-of-page-design).

Line 887 should be modified to:
```
<td class="site-icon"><a href="${site.url}"><img src="${site.iconUrl}" alt="" border="0"></a></td> 
```

**Comment by ErisDS** [comment] 2021-02-23 19:31
Thanks for the suggestion, if you'd like to submit a PR (and with GitHub's tools these days it'd prob be quicker for us both!) we'll be happy to review it.

Closing as we don't need to track this as an issue (it's not a bug as measured by the fact it didn't fit the template).

**Closed by ErisDS** 2021-02-23 19:31 UTC
