### ISSUE TITLE
Ghost Admin：favicon.ico content should also be served over HTTPS.

### ISSUE THREAD

**Issue by ky0ncheng** [TryGhost/Ghost#9162] opened 2017-10-19 06:50 UTC
Welcome to Ghost's GitHub repo! 👋🎉

### Issue Summary

Mixed Content: The page at 'https://xxx.org/ghost/' was loaded over HTTPS, but requested an insecure image 'http://xxx.org/favicon.ico?t=1508400300xxx'. This content should also be served over HTTPS.

https://github.com/TryGhost/Ghost/issues/8571 

This issue in 1.14.1 need reopen， ghost admin error. 

Error in line 7762 with `assets/vendor.min-87477a1d2baf934c445571d66b0baed9.js`

In template files, exist favicon html code, do not use `vendor.min.js` to request again.
`/ghost/core/server/admin/views/default.html`
`/ghost/core/server/admin/views/default-prod.html`

------

Ghost do not host static files for path `/` without nginx or any another http proxy program.

Please add static files hosting function and custom host path, i think install node only is enough, not need nginx.

### Technical details:

* Ghost Version: 1.14.1

**Comment by kevinansfield** [comment] 2017-10-19 15:49
@ky0ncheng if you want yoursite.com/favicon.ico to be served over https then you need to [configure your url](https://docs.ghost.org/docs/config#section-configuration-options) to be https.

Closing this as it's expected behaviour.

**Closed by kevinansfield** 2017-10-19 15:49 UTC

**Comment by ky0ncheng** [comment] 2017-10-19 17:25
@kevinansfield
I use cloudflare crypto for my pure http site.
Useless http request can be removed.

**Comment by ky0ncheng** [comment] 2017-10-19 18:02
Or use ‘//’ as protocol.

**Comment by kevinansfield** [comment] 2017-10-19 18:06
If you're serving your site on https you need to configure your url in Ghost's config to be https otherwise all links will be https.

Using `//` as a protocol won't work because it's perfectly possible to have your admin on https but your main site only available via http - the admin client doesn't know that so it has to use the protocol as configured in Ghost.

**Comment by zackify** [comment] 2017-12-06 14:50
I'm serving my ghost over https (url is https) and it all works great, yet the favicon in admin panel is still being requested over http.

![image](https://user-images.githubusercontent.com/449136/33667437-d5a3e982-da6a-11e7-8a6f-87e29c4b04a0.png)


config:


```
  "url": "https://blah.io/blog/",
  "admin": {
    "url": "https://blah.io/blog/"
  },
```

**Comment by zackify** [comment] 2017-12-06 15:53
Yes, I'm using the latest docker image and recreated it with that config.

**Comment by RowanKaag** [comment] 2018-01-28 01:11
I am facing the same issue on Ghost (1.20.3) from within the `/ghost` section. On any other page there are no issues.

```
server {
        return                          301 https://$server_name$request_uri;
        server_name                     ngineering.nl;
        access_log                      /var/log/nginx/nl.ngineering.http.log;
        listen                          80;
}

server {
        server_name                             ngineering.nl;
        access_log                              /var/log/nginx/nl.ngineering.https.log;
        listen                                  443 ssl http2;

        location / {
                proxy_set_header                X-Real-IP $remote_addr;
                proxy_set_header                HOST $http_host;
                proxy_set_header                X-NginX-Proxy true;
                proxy_pass                      http://localhost:2368;
                proxy_redirect                  off;
        }

	add_header                              Strict-Transport-Security "max-age=15768000;includeSubDomains; preload" always;
        add_header                              X-Frame-Options "DENY";

        ssl_certificate                         /etc/letsencrypt/live/ngineering.nl/fullchain.pem;
        ssl_certificate_key                     /etc/letsencrypt/live/ngineering.nl/privkey.pem;
        ssl_trusted_certificate                 /etc/letsencrypt/live/ngineering.nl/chain.pem;
        ssl_session_timeout                     1d;
        ssl_session_cache                       shared:SSL:10m;
        ssl_protocols                           TLSv1.1 TLSv1.2;
        ssl_ciphers                             'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
        ssl_prefer_server_ciphers               on;
        ssl_dhparam                             dh4096.pem;
        ssl_stapling                            on;
        ssl_stapling_verify                     on;
}
```

```
"url": "http://ngineering.nl",
"server": {
    "port": 2368,
    "host": "127.0.0.1"
 },
```

```
Mixed Content: The page at 'https://ngineering.nl/ghost/' was loaded over HTTPS, but requested an insecure image 'http://ngineering.nl/favicon.ico?t=1517101247532'. This content should also be served over HTTPS.
```

![screen shot 2018-01-28 at 02 00 49](https://user-images.githubusercontent.com/6907625/35477951-4e267b52-03d0-11e8-802c-a4027ac844a2.png)
![screen shot 2018-01-28 at 02 00 41](https://user-images.githubusercontent.com/6907625/35477952-4e3f1b08-03d0-11e8-8c77-5eedc4cc4359.png)
