### ISSUE TITLE
[Docker] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by Strit** [TryGhost/Ghost#13225] opened 2021-08-15 16:50 UTC
Welcome 👋   
Please keep in mind that GitHub is our office. We invite you to share any bug reports here 🐛..  
For anything else please use https://forum.ghost.org 👫

### Issue Summary

Sometimes, my docker install of Ghost crashes and restarts the container.
The docker logs show this error:
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
```
Followed by this output:
```
    at ServerResponse.setHeader (_http_outgoing.js:561:11)
    at ServerResponse.header (/var/lib/ghost/versions/4.11.0/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/var/lib/ghost/versions/4.11.0/node_modules/express/lib/response.js:170:12)
    at /var/lib/ghost/versions/4.11.0/core/server/web/shared/middlewares/error-handler.js:200:32
    at /var/lib/ghost/versions/4.11.0/node_modules/express-hbs/lib/hbs.js:635:23
    at /var/lib/ghost/versions/4.11.0/node_modules/express-hbs/lib/resolver.js:29:5
    at tryCatcher (/var/lib/ghost/versions/4.11.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/4.11.0/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/lib/ghost/versions/4.11.0/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/4.11.0/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/var/lib/ghost/versions/4.11.0/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/var/lib/ghost/versions/4.11.0/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/var/lib/ghost/versions/4.11.0/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/var/lib/ghost/versions/4.11.0/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/lib/ghost/versions/4.11.0/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:464:21)
```
After that, the service is restarted and it functions fine again.

### To Reproduce

1. Setup Ghost using official Docker image
2. Run it with docker-compose that restarts the container on failure.
3. At some point the user gets a half loading page on the first visit. Refreshing with F5 gives a 404 error.
4. After a few minutes you can press F5 again and Ghost will be back up and running.

### Technical details:

* Ghost Version: 4.11.0 (docker)
* Node Version: What is in the 4.11.0 docker container
* Browser/OS: Server runs Manjaro ARM with Docker. Client runs Manjaro x64 using Firefox.
* Database: What is in the 4.11.0 docker container.

**Comment by milgradesec** [comment] 2021-09-14 06:39
Having the same issue running Ghost on Docker

**Comment by ruhrscholz** [comment] 2021-09-24 17:39
On my servers, while this bug still persists after the latest update for the container (4.15), it doesn't lead to the container crashing anymore. Only the log message is still there.

**Comment by tq-bit** [comment] 2021-10-04 15:22
Hi @Strit 

I'd like to reproduce this issue. Could you please tell me on which page exactly you're receiving this error?

**Comment by Strit** [comment] 2021-10-05 08:35
The error is in my log `docker log <container-id>`.

I haven't had it happen in a while though (now running 4.16). When it does happen, the main page will not be loading any pictures properly. And hitting F5 just after that, results in a Bad Gateway error, because the container is rebooting.
When the container is done rebooting, everything works fine.

**Comment by scolear** [comment] 2021-10-31 10:43
Hey, I have figured it out! Well, a cloud architect friend of mine did. **Its the images.** 

Ghost does not warn about it, but it appears to be related to the image sizes. Upon reload, it works probably due to some internal caching, or something. But all I had to do was remove my profile picture, and now there is no errors. 

Still have to see if only the profile pictures, or if the same will happen with images of posts etc.

**Comment by Strit** [comment] 2021-10-31 14:56
While image size does sound like a likely symptom, the pictures I use in my blog posts are usually around 100 kb in size and my profile picture is 160 kb.

**Comment by ruhrscholz** [comment] 2021-11-05 10:47
> Also this is obviously not a good enough answer, as I have no idea whats the size limit that will not crash ghost, or if the same problem will arise with images of posts etc. As I am reading your logs, it seems like not only the profile pictures have this issue.

Thanks to this comment I removed my profile picture (which was not big, as it is just a redownloaded Twitter profile picture). This was 5 days ago and the server appears to be running smoothly so far. This applies to both the Casper and the Alto theme.

**Comment by Strit** [comment] 2021-11-05 10:53
So the issue seems to be related to just having a profile picture set?

**Comment by milgradesec** [comment] 2021-11-06 16:52
Tested with and without a profile image, i can see crashes with both.

**Comment by milgradesec** [comment] 2021-11-16 23:18
`GET /content/images/size/w2000/2021/10/image.webp`

This type of requests asking ghost for an image with specific size triggers the crash.
I configured my proxy to respond directly to requests like above and redirect to `/content/images/2021/10/image.webp`.
The issue is mitigated and the container never crashes.

**Comment by ErisDS** [comment] 2021-11-22 13:23
Hey everyone 👋 ,

Really sorry for the radio silence here, we got a bit behind with triaging. 
There's a lot of people reporting this but without a lot of information. The original report states that Ghost is being run on Manjaro ARM, which is not our official [recommended stack](https://ghost.org/docs/install/ubuntu/).

As far as I know, the problem you're running into is the same as these two:

https://github.com/TryGhost/Ghost/issues/11129
https://github.com/TryGhost/Ghost/issues/12967

Where there is some sort of problem with the `sharp` library and/or libvips on your distro that causes the Ghost process to crash in a way that we cannot catch or do anything with.

I did raise this crashing issue upstream: https://github.com/lovell/sharp/issues/1942 and improvements were made, but there was never a reproducible case that I could provide, which meant it wasn't possible to fully fix.

I'm going to close this because as far as I know it's not affecting Ubuntu - which is our officially supported stack and it's also not a bug in Ghost itself that we can do anything about. 

However, if this is still affecting you there are a couple of things you can do other than switching to Ubuntu:

1. If this is affecting you on Ubuntu, raise a new bug against Ghost with as much detail as possible.
2. Update https://github.com/lovell/sharp/issues/1942 with a reproduction case, so that they can look at solving the issue
3. If you can find/diagnose the problem or any related logs, share them here and on https://github.com/lovell/sharp/issues/1942 so we can keep track in case a solution becomes possible.

**Closed by ErisDS** 2021-11-22 13:23 UTC
Labels: needs triage

**Comment by Strit** [comment] 2021-11-22 20:25
> I'm going to close this because as far as I know it's not affecting Ubuntu - which is our officially supported stack and it's also not a bug in Ghost itself that we can do anything about.

I thought docker was suppose to get around the Operating System dependency issues.

Guess I was wrong there. No worries.
