### ISSUE TITLE
SQLITE_ERROR: no such table: posts_authors

### ISSUE THREAD

**Issue by kirkone** [TryGhost/Ghost#9539] opened 2018-03-28 17:11 UTC
### Issue Summary

I want to update my blog from 1.21.7 to 1.22.0 with the ghost-cli but the update fails on the database migrations step. The error in the log file says:
```
MESSAGE: delete from `posts_authors` - SQLITE_ERROR: no such table: posts_authors
```

Logfile: [ghost-cli-debug-2018-03-28T16_59_34_613Z.log](https://github.com/TryGhost/Ghost/files/1856929/ghost-cli-debug-2018-03-28T16_59_34_613Z.log)

### Steps to Reproduce

1. run `ghost update --no-restart` on a version 1.21.7 blog
2. wait for the error

### Technical details:

Debug Information:
OS: Microsoft Windows, v10.0.14393
Node Version: v8.11.0
Ghost-CLI Version: 1.6.0
Environment: production
Command: 'ghost update --no-restart'

Maybe this has something to do with #9426

**Comment by kirrg001** [comment] 2018-03-28 18:22
Hey @kirkone!

I can't reproduce this. Not on Ubuntu/Mac, nor in production/development or with MySQL/SQlite3.

Running Ghost on Windows in production with SQlite3 is nothing we support. Please read [here](https://docs.ghost.org/docs/install#section-pre-requisites) about it.

I would still like to help you, can you please swing by our [slack channel](https://slack.ghost.org) and leave a message in the `#help` channel? Then we can try to find out why you are running into this. Thanks! 

I am going to close this issue for now. We can either re-open this issue if we find a bug in Ghost or raise an issue in the [CLI repository](https://github.com/TryGhost/Ghost-CLI).

**Closed by kirrg001** 2018-03-28 18:22 UTC
