### ISSUE TITLE
Markdown command break

### ISSUE THREAD

**Issue by ScreamZ** [TryGhost/Ghost#10759] opened 2019-05-25 11:17 UTC
Hello there, I would like to report that I'm unable to make ghost parse correctly markdown as described in the documentation right here : https://docs.ghost.org/faq/using-the-editor/

As you can seen there is, highlight and subtext.

Using the editor this syntax is not doing anything. I didn't tested some others but this might also happen.

Thank you in advance :p

### Technical details:

* Ghost version: 2.22.3
* Node Version: v8.10.0
* Browser/OS: Chrome Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by kevinansfield** [comment] 2019-05-27 21:10
The highlight syntax is a slight docs error. Highlight syntax works inside of a markdown card but it's never been recognised syntax for a text expansion inside of the rich-text editor because the `<mark>` element is not supported in the [underlying library and document format](https://github.com/bustle/mobiledoc-kit/issues/473).

I've tested and confirmed that subtext text expansion and all the other supported expansions are working correctly, as such I'm going to close this issue. If you continue to have problems, please provide detailed reproduction steps.

**Closed by kevinansfield** 2019-05-27 21:10 UTC
