### ISSUE TITLE
API:  get 400 without any precision when trying to upload a theme through the API

### ISSUE THREAD

**Issue by allan-simon** [TryGhost/Ghost#12637] opened 2021-02-11 14:02 UTC
### Issue Summary

Trying to upload a theme produce a error 400, though I'm following the documentation

### To Reproduce

1. Install ghost
2. add an admin
3. create an integration and get its token
4. use the script  (it's the one copy pasted from the documentation)

```
#!/usr/bin/env bash
set -e
set -u

# Admin API key goes here
KEY="602530bd672ec401488956e2:f65308ba8b79eccaa62f21bb0bb74cb77ee6fbf82df349d205bb5029fcd750e2"

# Split the key into ID and SECRET
TMPIFS=$IFS
IFS=':' read ID SECRET <<< "$KEY"
IFS=$TMPIFS

# Prepare header and payload
NOW=$(date +'%s')
FIVE_MINS=$(($NOW + 300))
HEADER="{\"alg\": \"HS256\",\"typ\": \"JWT\", \"kid\": \"$ID\"}"
PAYLOAD="{\"iat\":$NOW,\"exp\":$FIVE_MINS,\"aud\": \"/v3/admin/\"}"

# Helper function for perfoming base64 URL encoding
base64_url_encode() {
    declare input=${1:-$(</dev/stdin)}
    # Use `tr` to URL encode the output from base64.
    printf '%s' "${input}" | base64 | tr -d '=' | tr '+' '-' |  tr '/' '_'
}

# Prepare the token body
header_base64=$(base64_url_encode "$HEADER")
payload_base64=$(base64_url_encode "$PAYLOAD")

header_payload="${header_base64}.${payload_base64}"

# Create the signature
signature=$(printf '%s' "${header_payload}" | openssl dgst -binary -sha256 -mac HMAC -macopt hexkey:$SECRET | base64_url_encode)

# Concat payload and signature into a valid JWT token
TOKEN="${header_payload}.${signature}"


curl -F 'file=@/vagrant/theme.zip' -H "Authorization: $TOKEN" http://172.17.0.2:2368/ghost/api/v2/admin/themes/upload -v
```

and I get a 400 error, without further explanation 

I've tried  `v0.1` and `v3` but same error 

### Technical details:

* Ghost Version: 3.41.4
* Node Version: 12.20.1
* Browser/OS: ubuntu
* Database: sqlite3

**Comment by ErisDS** [comment] 2021-02-11 15:21
I can't reproduce the bug here - which is the API returns a 400 without explanation. 

If I try your script I get errors but they are all clear and explained. They are caused by differences between the code you have and the example in the docs.

Here are the 3 errors I got as I fixed the script:

- 401 - Auth header is missing "Ghost"`{"errors":[{"message":"Authorization header format is \"Authorization: Ghost [token]\"","context":null,"type":"UnauthorizedError","details":null,"property":null,"help":null,"code":"INVALID_AUTH_HEADER","id":"28ef9820-6c7b-11eb-ad9f-b5f1da470168"}]}`
- 401 -  Your claim is for the v3 API but you're using the v2 API: `{"errors":[{"message":"Invalid token: jwt audience invalid. expected: /\\/?v2\\/admin\\/?$/","context":null,"type":"UnauthorizedError","details":null,"property":null,"help":null,"code":"INVALID_JWT","id":"5b611b80-6c7b-11eb-ad9f-b5f1da470168"}]}`
- 422 - I typed the path to a theme wrong and got: `{"errors":[{"message":"Please select a theme.","context":null,"type":"ValidationError","details":null,"property":null,"help":null,"code":null,"id":"7dfafcb0-6c7b-11eb-ad9f-b5f1da470168"}]}`

Closing as a support request, not a bug. Happy to provide any more help needed to get this working via the forum :)

**Closed** 2021-02-11 15:22 UTC
Labels: support-request

**Comment by allan-simon** [comment] 2021-02-11 15:47
sorry for  the 401, indeed the removed Ghost was from me trying to debug what was happening ,  and for the v2, you get me wrong, i said i *also* tried to put `v3` and `v0.1` (in addition to the `v2` in my request) 

I will post through the forum for further help then , thanks for your first look into it :)
