### ISSUE TITLE
Uploading jpg image with '\' in file name say it's not a supported file type

### ISSUE THREAD

**Issue by Tyriar** [TryGhost/Ghost#6340] opened 2016-01-14 04:56 UTC
I tried uploading an image named "3\.jpg" via drag and drop using Chrome v46 on Debian 8/Gnome 3.14.1 and I got the unsupported image type message:

> The image type you uploaded is not supported. Please use .PNG, .JPG, .GIF, .SVG.

The server itself I believe is Ghost 0.7.5 on Ubuntu 14.04 (month old DitigalOcean droplet without modification).

**Comment by halfdan** [comment] 2016-01-14 09:02
Hi @Tyriar,
Thanks for your report. I am able to reproduce the issue and will look into a solution. I would however advise against using filenames with '\' in them as this character is not valid in the path segment of a URL. The solution will probably involve catching this early and providing a better error message. An alternative would be to replace invalid characters after upload.

**Comment by halfdan** [comment] 2016-01-14 09:04
What's interesting is that while the browser correctly sends the filename "nora\.jpg" it ends up getting passed to the upload.add api as:

```
{"uploadimage":{"type":"image/jpeg","encoding":"7bit","name":".jpg","path":"/var/folders/y4/kz59xtt17wdg1tx63l1hpn7r0000gn/T/145276163720625b2916b5c49db617f52fa5ea48efee7"},"context":{"user":1}}
```

**Comment by halfdan** [comment] 2016-01-14 10:04
I tracked this down to be caused by busboy: https://github.com/mscdex/busboy/blob/master/lib/types/multipart.js#L160-L161 and https://github.com/mscdex/busboy/blob/master/lib/utils.js#L180-L185

The above lines treat the filename as a windows path `nor` followed by a path separator and a file with the name `.jpg`. Since busboy is only giving us the filename and not the "path" we don't have an easy way to check for invalid characters (like path separators).

**Comment by Tyriar** [comment] 2016-01-14 16:56
So the right fix might be for busboy to sanitize file names based on the OS so they work for all OS'?

**Comment by ErisDS** [comment] 2017-03-10 20:47
We switched to using multer ages ago, however this still happens.

As halfdan explained, we never get the real filename passed to us - just `.jpg` in this case, and then `path.extname` here: https://github.com/TryGhost/Ghost/blob/7eb316b7865d658021ce7065eb3b5de1a7d04472/core/server/api/utils.js#L313-L313 returns an empty string, causing the validation to fail.

This bug has been open for over a year, and as far as I'm aware no one else has run into it. I think this is a pretty extreme edgecase, enough that neither busboy nor multer have proper handling.

If someone wants to submit a fix that would be great, however I don't think this bug is serious enough to warrant keeping the bug report open any longer, particularly given that the issue needs to be resolved inside of busboy & multer.

**Closed by ErisDS** 2017-03-10 20:47 UTC
