### ISSUE TITLE
Unhandled rejection TypeError: Cannor read property 'define' of undefined

### ISSUE THREAD

**Issue by nevi-me** [TryGhost/Ghost#6551] opened 2016-02-20 04:02 UTC
Welcome to Ghost's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫. Got an idea for a new feature? Please add it to our wishlist: http://ideas.ghost.org 🌟. Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

For a few weeks now I have been getting an error with Ghost when starting it with an Express app.
I get an error on /`ghost/core/server/index.js:100:28` where Node throws an unhandled rejection typeerror. I have added the stack trace at the bottom.

I haven't been able to diagnose the issue because Ghost starts up properly in my Windows dev environment.

I removed all node_modules and reinstalled everything as at Ghost@0.7.8, but still got the same error after the fresh install.

### Steps to Reproduce

1. Install ghost as Express.js middleware
2. Start Express.js server
3. Get error

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

Below is a stack trace:

```
Unhandled rejection TypeError: Cannot read property 'define' of undefined
    at /home/ubuntu-user/var/expressapp/node_modules/ghost/core/server/index.js:100:28
    at tryCatcher (/home/ubuntu-user/var/expressapp/node_modules/ghost/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu-user/var/expressapp/node_modules/ghost/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/ubuntu-user/var/expressapp/node_modules/ghost/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/home/ubuntu-user/var/expressapp/node_modules/ghost/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/ubuntu-user/var/expressapp/node_modules/ghost/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/ubuntu-user/var/expressapp/node_modules/ghost/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
### Technical details:

* Ghost Version: 0.7.6 - 0.7.8
* Node Version: 4.3.1
* Browser/OS: any/Ubuntu LTS 14.04
* Database: sqlite

**Comment by ErisDS** [comment] 2016-02-20 12:42
This doesn't sound like a Ghost bug, but rather a conflict between your top level express app and Ghost.

The line of code that is throwing error is:
`express.static.mime.define({'application/font-woff': ['woff']});`

This indicates that something about your top level express app is different to Ghost's as `express.static.mime` is undefined for your app. `serve-static` is a default dependency of express, and I'm not sure what you could do to remove it.

Do you have any dependency conflicts - e.g. dependencies which are the same as Ghost but your app defines a different version. The key one being express?

**Comment by nevi-me** [comment] 2016-02-20 12:53
Hi @ErisDS, I'll check now. I presumed that since I'm still using NPM 2 I wouldn't have a conflict in modules.

Current `serve-static` is `"serve-static": "^1.10.2"`. 
Using it as `app.use(require('serve-static')(config.root + '/public'));`

**Comment by ErisDS** [comment] 2016-02-20 13:15
Hi @nevi-me, this is almost certainly a conflict issue with your top level app & not a bug with Ghost. 

Therefore, I'm going to close this issue, and recommend you use [slack](https://ghost.org/slack) to get help debugging the issue as going back and forth debugging a config issue doesn't work on GitHub.

If the result is uncovering a bug, we can reopen.

**Closed by ErisDS** 2016-02-20 13:15 UTC
