### ISSUE TITLE
Internal tags are now output as public tags

### ISSUE THREAD

**Issue by oryowen** [TryGhost/Ghost#8938] opened 2017-08-26 16:25 UTC
### Issue Summary

Internal tags no longer work as expected. All tags are now being treated as public regardless of the hash symbol. Previously Internal tags are now output as public tags. 

### Steps to Reproduce

1. Create a new internal tag
2. Tag is output as a public tag

### Technical details:

* Ghost Version: 1.7.1
* Node Version: 6.9.5
* Browser/OS: Safari / macOS Sierra 10.12.6
* Database: MySQL

**Comment by ErisDS** [comment] 2017-08-27 09:46
Hi @oryowen, thanks for this bug report. I found this a couple of days ago and didn't get chance to finish raising it yet - I have raised a slightly more specific report here: #8943 so going to close this as a duplicate of #8943.

**Closed by ErisDS** 2017-08-27 09:46 UTC
