### ISSUE TITLE
Bug: Enable to change user right

### ISSUE THREAD

**Issue by Foutchy** [TryGhost/Ghost#6236] opened 2015-12-17 00:59 UTC
### Issue Summary
Change user from Editor to admin isn't working

### Steps to Reproduce

1. Change any user from Editor to admin.  

Work around, edit database table.

### Technical details

* Ghost Version: master - 55045ae (0.7.2)
* Client OS: OSX 10.11.2
* Server OS:  Ubuntu 14
* Node Version: 4.2.0
* Browser:  Chrome Version 47.0.2526.80 (64-bit)
* Database:  Postgres

**Comment by novaugust** [comment] 2015-12-17 01:31
Duplicate of #6171 - already fixed, hopefully out soon

**Closed by novaugust** 2015-12-17 01:31 UTC

**Comment by ErisDS** [comment] 2015-12-17 08:39
Please upgrade to 0.7.3, which was released yesterday 😉
