### ISSUE TITLE
Support of newer versions of Node.js 5

### ISSUE THREAD

**Issue by lordmetroid** [TryGhost/Ghost#6295] opened 2016-01-05 21:33 UTC
Using ghost-0.7.1-3 on an updated Archlinux as of Jan 2016-01-05:

Jan 05 22:25:30 gorilla npm[16766]: ERROR: Unsupported version of Node
Jan 05 22:25:30 gorilla npm[16766]: Ghost needs Node version ~5.0 you are using version 5.3.0

**Comment by Ferrari** [comment] 2016-01-06 02:13
I guess Ghost will focus on LTS only!? 
https://github.com/TryGhost/Ghost/issues/5821#issuecomment-149870041

**Comment by ErisDS** [comment] 2016-01-06 10:07
This is a duplicate of #6169 and more. Please read the full error message it links you to a document http://support.ghost.org/supported-node-versions/. Searching GitHub or Googling would also have found this.

**Closed by ErisDS** 2016-01-06 10:07 UTC

**Comment by mudrii** [comment] 2016-05-15 22:12
New version 6 of the Node.js is out . Any plans to get traction ?

**Comment by AliMD** [comment] 2016-05-17 20:45
check this http://blog.z-proj.com/running-ghost-with-node-v5/
