### ISSUE TITLE
[Bug] "Sort by Newest" doesn't work in Ghost 1.22.4

### ISSUE THREAD

**Issue by 1c7** [TryGhost/Ghost#9608] opened 2018-04-29 11:31 UTC
I also post in forum: https://forum.ghost.org/t/bug-ghost-admin-sort-by-newest-doesnt-work/1115

### Issue Summary
Admin panel "Sort by Newest" doesn't work.
it should sort by time, from top to bottom it should be:
edit 3 minute ago
edit 2 hours ago
edit 9 days ago

but now it's
edit 7 minute ago
edit 6 months ago
edit 14 second ago

it's wrong

### Example
![image](https://user-images.githubusercontent.com/1804755/39406108-10114bd8-4be4-11e8-910e-c3d1e3c8c9a1.png)
![image](https://user-images.githubusercontent.com/1804755/39406111-203d0a38-4be4-11e8-863e-86170aa54fcf.png)

### Steps to Reproduce

1. just write couple article, both publish and draft
2. in Admin panel you would see the sorting is wrong

### Technical details:

* Ghost Version: 1.22.4
* Node Version:
* Browser/OS: Chrome 66 /  macOS high Sierra 10.13.4

**Comment by 1c7** [comment] 2018-04-29 11:34
I post here because no one reply anything in forum.
even a simple "got it, would fix in next version, next version come out in 2 week"

**Comment by kevinansfield** [comment] 2018-04-30 10:00
Hey @1c7 👋 Thanks for reporting, however this is a duplicate of https://github.com/TryGhost/Ghost/issues/8495 so I'm going to close this one

**Closed by kevinansfield** 2018-04-30 10:00 UTC
