### ISSUE TITLE
Add Navigation does not work in v0.11.4 

### ISSUE THREAD

**Issue by VivekRagunathan** [TryGhost/Ghost#7966] opened 2017-02-08 19:58 UTC
Hi

I upgraded from v0.11.3 to v0.11.4 ghost. Adding a navigation URL in the Settings/Navigation tab no longer works in the new version. I checked the Network tab, actually no call is made. There are no errors in the console. However, there are a few warnings:

![image](https://cloud.githubusercontent.com/assets/292160/22754707/580ee448-edf5-11e6-806c-d648ca7e93b0.png)

```
Environment:

node - v6.9.5
npm - v3.10.10
nvm - v0.33.0
```

Is this a known issue? Or is there something wrong in my environment? Please advise.

Thanks
Vivek Ragunathan

**Comment by acburdine** [comment] 2017-02-08 20:09
@VivekRagunathan I just tried this on my production blog running 0.11.4, and was not able to reproduce 😕 

Did you remember to click the "Save" button at the top of the page? The navigation will only save if you click it 😉 

At any rate, if you could provide more information other than "it doesn't work" such as a more explicit description of what you entered, where you clicked, etc., that would help us get to the bottom of this issue if it in fact exists.

**Comment by VivekRagunathan** [comment] 2017-02-10 05:04
@acburdine Yes, I clicked on the Save button and that's when I mentioned that there was no network call record in the Network tab. I tried adding a link to one of the posts (also pages) in my blog.

I am preparing to record a licecap video to show the problem. Get back with the video soon.

**Comment by kirrg001** [comment] 2017-02-14 08:57
@VivekRagunathan Do you have any update on this? Thanks 👋

**Comment by VivekRagunathan** [comment] 2017-03-12 19:28
@kirrg001 Very sorry about the delay. Too bad I forgot to update you. Actually, I had to blow up my server (moving servers), so I did not get a chance to reproduce (0.11.3 - 0.11.4).

But I will be upgrading 0.11.5 soon. Will share with you what happens.

**Comment by kirrg001** [comment] 2017-03-13 08:58
@VivekRagunathan Thanks the update 👋
I will close this issue for now. If you experience this behaviour again, just let us know here.

**Closed by kirrg001** 2017-03-13 08:58 UTC
