### ISSUE TITLE
Blog title breaks site if title is a float

### ISSUE THREAD

**Issue by mrkwse** [TryGhost/Ghost#8776] opened 2017-07-29 18:43 UTC
### Issue Summary

If blog title is a float (e.g. `5.0`), blog will not load, and error page will not render, instead the following error page returns at URL root. `[url]/ghost`still loads, so possible to work around. I haven't reproduced this on a completely fresh blog, but this is definitely the case if importing/migrating a prior blog.

### Error message
```
Oops, seems there is an error in the error template.

Encountered the error:

[error.hbs] (title || "").trim is not a function

whilst trying to render an error page for the error:

undefined
[error.hbs] (title || "").trim is not a function
```

### Steps to Reproduce

1. Set up blog
2. (Import previous content using `labs`)
3. (Set blog title to a float)

### Technical details:

* Ghost Version: 1.1.0
* Node Version: 6.11.1
* Browser/OS: Verified on Safari 11.0/Chrome 59.0.3071.115
* Database: MySQL

**Comment by ErisDS** [comment] 2017-08-02 08:47
I'm sorry but we are not able to reproduce this issue on 1.0 or LTS. I'm going to close it for now, until we can get some more reproduction details.

**Closed by ErisDS** 2017-08-02 08:47 UTC
Labels: admin-client, bug
