### ISSUE TITLE
Ghost CMS outputting junk data in Google results

### ISSUE THREAD

**Issue by JamesTheHacker** [TryGhost/Ghost#8087] opened 2017-03-02 13:28 UTC
### Issue Summary

When submitting a post, it's eventually picked up by Google. But, the description that Google picks up includes some junk data. I've added an image to show what's happening:

![Example of incorrect Google description](http://i.imgur.com/n06IthP.png)

As you can see it includes "menu", the posts title and the date followed by the description. In terms of SEO it should be:

    [date] [description]

eg:

    01 March 2017 In this lesson I will teach you ...

Doing it the second way makes it easily readable to any users who stumble upon blog posts via Google.

I am currently modifying the meta data for each post, but it's still outputting incorrect descriptions.

**Comment by kevinansfield** [comment] 2017-03-02 14:07
> As you can see it includes "menu", the posts title and the date followed by the description. In terms of SEO it should be:

This is because you haven't given a custom meta description, if there's no meta description Google will pick up _any_ text on the page for the description and try to match it to your query. From the looks of it you did a `site:musictheory.blog` query so Google doesn't have any text to match against so it will output whatever text it finds on the page.

If you give it a more descriptive query, e.g. `site:musictheory.blog major scale intervals` then the description starts to become more relevant...

<img width="611" alt="screen shot 2017-03-02 at 14 06 28" src="https://cloud.githubusercontent.com/assets/415/23510431/7f018548-ff51-11e6-9cc6-c73735bd382e.png">

> I am currently modifying the meta data for each post, but it's still outputting incorrect descriptions.

If you enter a custom meta description then Google will use that instead of the page text unless it thinks the page text is more relevant for the current query. It will also take some time between adding a meta description and seeing the change in Google - you'll have to wait for Google to crawl your site and update it's index.

I'm going to close this as it's not a bug but normal search engine behaviour. If you want any further help or advice please head over to our [slack channel](https://slack.ghost.org) 😄

**Closed by kevinansfield** 2017-03-02 14:07 UTC
