### ISSUE TITLE
Blog keeps reverting to "private mode" randomly. 

### ISSUE THREAD

**Issue by LanceMaverick** [TryGhost/Ghost#10645] opened 2019-03-29 17:41 UTC
I am running ghost v2.16.3 (CLI v1.9.9) and the blog keeps randomly reverting to a private blog (needs a password to access the site). When I log in to the admin panel, private blog mode is OFF and I have to turn it on, save changes, and then turn if back off to make my site public again.
I am not sure exactly what triggers this, it appears to happen randomly, but also happens if I restart ghost and sometimes nginx, which I am using to host the site.

Host is Ubuntu 18.04.1 LTS

**Comment by kevinansfield** [comment] 2019-03-29 21:24
@LanceMaverick there was a bug in 2.16.3 that caused this, fixes have been released in later versions. I would recommend upgrading to the latest which is 2.19.1.

Changelogs are listed on the releases page (https://github.com/TryGhost/Ghost/releases), they're useful to see if a bug you're experiencing has been fixed, as is the issues search. Closing as a duplicate of https://github.com/TryGhost/Ghost/pull/10576 and https://github.com/TryGhost/Ghost/pull/10606.

**Closed by kevinansfield** 2019-03-29 21:24 UTC
