### ISSUE TITLE
Ghost 0.9 Database Migration Error

### ISSUE THREAD

**Issue by kirtan403** [TryGhost/Ghost#7162] opened 2016-07-30 21:04 UTC
### Issue Summary

While updating to ghost to 0.9 from 0.8, I got the following error:
![screenclip](https://cloud.githubusercontent.com/assets/7900938/17273081/b670a74a-56c6-11e6-984d-4f59380e8d92.png)

Using Ghost blog as Module.

### Steps to Reproduce

1. Just the sample ghost blog with 0.8
2. Change package file ghost dependency version to 0.9
3. delete node_modules
4. run `npm install --production`
5. Boom! You have an error as shown

### Technical details:

* Ghost Version: 0.8 -> 0.9 (while migration)
* Node Version: v4.3.0
* Browser/OS: Chrome/Windows 10
* Database: SQLite

**Comment by kirrg001** [comment] 2016-07-31 15:27
I am not able to reproduce the error. 
This error message looks like an error we have fixed 9 days ago, see https://github.com/TryGhost/Ghost/pull/7121.

**Comment by kirtan403** [comment] 2016-07-31 15:48
I don't know why but, on my server also the error was there. It shows version is 0.9 and I can see internal tag beta option available. But, I am not seeing an option for scheduling post (which supposed to be under "Save Draft", right?). I thought, migration error make this option unavailable?

**Comment by kirrg001** [comment] 2016-07-31 18:04
Scheduling is available when you: create a post (or take an existing draft post) and choose publish date in the future (minimum 3 minutes). Then click on the arrow next to "safe draft", "schedule post" should be available.

**Comment by kirtan403** [comment] 2016-07-31 19:06
Okay, thanks. I missed that. Should I be worried about the error, or my database is just fine?

**Comment by acburdine** [comment] 2016-08-01 03:40
@kirtan403 if your blog starts up fine, then I wouldn't worry about it 😄  Closing this for now but can reopen if it continues to be an issue

**Closed by acburdine** 2016-08-01 03:40 UTC

**Comment by kirtan403** [comment] 2016-08-01 10:43
Yup, it opens up fine! Thank you
