### ISSUE TITLE
stories list sort bug. unpulished post always at the top.

### ISSUE THREAD

**Issue by hxsf** [TryGhost/Ghost#9390] opened 2018-01-11 03:59 UTC
https://github.com/TryGhost/Ghost/blob/b9d3f45402f9fe5f120820bc6e27236ef0fc627f/core/server/models/post.js#L420

1. publish a post
2. make it unpublished (`published_at` in DB is still not NULL)
3. visit the Admin's stories.
4. the post always at the top of list.

**Comment by kevinansfield** [comment] 2018-01-11 09:11
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/8495

**Closed by kevinansfield** 2018-01-11 09:11 UTC
