### ISSUE TITLE
OEmbed parsing does not correctly pass URL parameters

### ISSUE THREAD

**Issue by TeNNoX** [TryGhost/Ghost#12671] opened 2021-02-18 15:55 UTC
_This is a copy of the stale-bot-closed  #11785_

### Issue Summary

I pass URL parameters to embedded content (in my case vimeo embed), but when pasting the URL it resolves only the plain URL (as oembed needs the parameters passed as actual parameters - not as part of the URL parameter)

### To Reproduce

1. Paste URL with params into Koenig: `https://vimeo.com/193244589?muted=true`
2. See that embedded video is not muted

When I get manually the oembed info - it works only when I put the original parameters as separate parameters:
`GET https://vimeo.com/api/oembed.json?url=https%3A%2F%2Fvimeo.com%2F260321751&muted=true`  
(instead of `https://vimeo.com/api/oembed.json?url=https%3A%2F%2Fvimeo.com%2F260321751%3Fmuted%3Dtrue`)

### Technical details:

* Ghost Version: 3.13.4
* Node Version: v12.16.1
* Browser/OS: Firefox Dev on elementary OS Juno
* Database: SQLite

Vimeo reference:
https://developer.vimeo.com/api/oembed/videos

**Comment by ErisDS** [comment] 2021-02-23 19:18
Closing as a duplicate of #11785 (you said so yourself!) please do not open duplicate issues.

**Closed by ErisDS** 2021-02-23 19:18 UTC
