### ISSUE TITLE
"Field length of `customer_id` in `members_stripe_customers` is too long!" occurs with mysql utf8mb4

### ISSUE THREAD

**Issue by sapphi-red** [TryGhost/Ghost#12202] opened 2020-09-13 17:08 UTC
### Issue Summary

``Field length of `customer_id` in `members_stripe_customers` is too long!`` error occurs with mysql utf8mb4 encoding.

### To Reproduce
Install ghost with mysql utf8mb4 encoding. (It also occured migrating to 3.23.2 from 3.27.0)

```
[2020-09-13 16:18:58] ERROR Field length of `customer_id` in `members_stripe_customers` is too long!

Field length of `customer_id` in `members_stripe_customers` is too long!

"This usually happens if your database encoding is utf8mb4.\nAll unique fields and indexes must be lower than 191 characters.\nPlease correct your field length and reset your database with knex-migrator reset.\n"
"Read more here: https://github.com/TryGhost/knex-migrator/issues/51\n"

Error ID:
    300

Error Code:
    ER_TOO_LONG_KEY

----------------------------------------

MigrationScriptError: Field length of `customer_id` in `members_stripe_customers` is too long!
    at MigrationScriptError.KnexMigrateError (/srv/ghost/node_modules/knex-migrator/lib/errors.js:7:26)
    at new MigrationScriptError (/srv/ghost/node_modules/knex-migrator/lib/errors.js:25:26)
    at /srv/ghost/node_modules/knex-migrator/lib/index.js:1045:23

Error: ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
    at Query.Sequence._packetToError (/srv/ghost/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/srv/ghost/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/srv/ghost/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/srv/ghost/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/srv/ghost/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/srv/ghost/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/srv/ghost/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/srv/ghost/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
    --------------------
    at Protocol._enqueue (/srv/ghost/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/srv/ghost/node_modules/mysql/lib/Connection.js:198:25)
    at /srv/ghost/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:135:18
    at Promise._execute (/srv/ghost/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/srv/ghost/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/srv/ghost/node_modules/bluebird/js/release/promise.js:103:10)
    at Client_MySQL._query (/srv/ghost/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:129:12)
    at Client_MySQL.query (/srv/ghost/node_modules/knex-migrator/node_modules/knex/lib/client.js:169:17)
    at Runner.query (/srv/ghost/node_modules/knex-migrator/node_modules/knex/lib/runner.js:151:36)
    at Runner.queryArray (/srv/ghost/node_modules/knex-migrator/node_modules/knex/lib/runner.js:248:31)
    at async /srv/ghost/node_modules/knex-migrator/node_modules/knex/lib/runner.js:277:18
```

### Technical details:

* Ghost Version: 3.32.2
* Node Version:
* Browser/OS:
* Database: mysql utf8mb4

refs #6197
refs https://github.com/TryGhost/knex-migrator/issues/51

### Additional Information
https://github.com/TryGhost/Ghost/blob/7b5401b26841fbed839b5d964f27897b8bb15cf3/core/server/data/schema/schema.js#L397
https://github.com/TryGhost/Ghost/blob/7b5401b26841fbed839b5d964f27897b8bb15cf3/core/server/data/schema/schema.js#L408
These lines declare a unique column which has a max length longer than 191.

**Comment by wollio** [comment] 2020-09-28 10:02
I've fixed this error by performing an upgrade from mysql 5.6 to 5.7 as described here
[https://github.com/TryGhost/knex-migrator/issues/51#issuecomment-671519494](https://github.com/TryGhost/knex-migrator/issues/51#issuecomment-671519494)

**Comment by kevinansfield** [comment] 2020-09-28 16:01
@sapphi-red the error message has a link which contains [instructions for fixing the problem](https://github.com/TryGhost/knex-migrator/issues/51#issuecomment-671519494), this error is expected on some systems and not a bug. As such I'm going to close this PR. If you need support updating your MySQL config please head by [our forum](https://forum.ghost.org) 🙂

**Closed by kevinansfield** 2020-09-28 16:01 UTC

**Comment by sapphi-red** [comment] 2020-09-29 08:40
I'm sorry I overlooked it. Thank you.
