### ISSUE TITLE
You need to be an active forum user before you can submit feature requests

### ISSUE THREAD

**Issue by mattl** [TryGhost/Ghost#21441] opened 2024-10-28 20:44 UTC
### Issue Summary

Trying to submit a new feature request to Ghost, I'm unable to do so without being an "active forum user" -- I have just activated my new account, so I'm assuming you want me to have a minimum post count to post feature requests? What is that minimum post count? Could maybe use better wording here on the error message. 

### Steps to Reproduce

1. Register a new forum account 
2. Be able to post feature requests

### Ghost Version

5.98.0

### Node.js Version

20.15.0

### How did you install Ghost?

local install on macOS

### Database type

Other

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by cathysarisky** [comment] 2024-10-29 00:40
feel free to start a thread in a different category and I'll be glad to move it for you. :)

**Comment by kevinansfield** [comment] 2024-10-29 12:03
The "active user" requirement is an automatic feature of the forum software that we don't have much control over but the requirements are minimal, essentially you just have to have read a few topics and is there as a basic spam control mechanism. Any user posting in the Ideas category _typically_ will have achieved the required trust level automatically by searching for their proposed idea and reading what's already been said about it.

I've bumped your user to the required trust level so you should be able to post in the Ideas topic now.

Closing this issue as it's not a bug with the Ghost software per-se.

**Closed by kevinansfield** 2024-10-29 12:03 UTC
Labels: needs:triage
