### ISSUE TITLE
Blog Spam Injection via Public API

### ISSUE THREAD

**Issue by karai17** [TryGhost/Ghost#9268] opened 2017-11-23 08:49 UTC
### Issue Summary

When I use the Public API to pull posts from my Ghost blog to place on my other website, I get very unsettling requests that follow.

### Steps to Reproduce

1. Install Ghost via the [Docker image](https://github.com/docker-library/ghost)
2. Create a 100% custom theme (not using any other theme as a base)
3. Enable the Public API
4. Use the Public API to fetch posts

![image](https://user-images.githubusercontent.com/590332/33164348-b4113bec-d008-11e7-9a45-177aa1c42cbe.png)

This issue is happening on multiple Ghost blogs that I've deployed. I was worried that perhaps the Docker image was compromised but the folks [over there](https://github.com/docker-library/ghost/issues/110) said it isn't an issue on their end.

### Technical details:

* Ghost Version: Latest (via Docker image)
* Node Version: Latest (via Docker image)
* Browser/OS: Chrome, Fedora 26 (hosted on CentOS 7 server)
* Database: SQLite

**Comment by kevinansfield** [comment] 2017-11-23 09:06
@karai17 this isn't coming from Ghost. It's likely something in your theme or a browser extension.

I'm closing this issue as it's a support request not a bug, please use our [Slack community](https://slack.ghost.org) for questions/help/support. If you ask for help there provide a URL where the problem can be seen, you should also check in a different browser to rule out the likelihood of a browser extension injecting the blogtoplist.com content.

**Closed by kevinansfield** 2017-11-23 09:06 UTC

**Comment by karai17** [comment] 2017-11-23 09:32
I checked multiple browsers and I built the theme from scratch.

**Comment by kevinansfield** [comment] 2017-11-23 09:51
@karai17 please move the discussion to [Slack](https://slack.ghost.org) and provide some information that will allow someone to help diagnose, without a URL to test no-one will be able to do anything
