### ISSUE TITLE
KnexMigrator trying to load up sqlite3 instead of MySQL in production

### ISSUE THREAD

**Issue by joshuajbouw** [TryGhost/Ghost#10765] opened 2019-05-29 22:40 UTC
### Issue Summary

I followed all the steps necessary as provided in the Ghost documentation for Ubuntu setup. For whatever reason even though I'm donig a production install, I am getting the error:

```
Message: Migration lock was never released or currently a migration is running.
Help: If you are sure no migration is running, check your data and if your database is in a broken state, you could run `knex-migrator rollback`.
```

When I run `knex-migrator rollback --force` in the `current` folder, it can not find the table in the sqlite3 database. From what I understand, production runs on MySQL and upon opening the MySQL db the table certainly is there. 

### To Reproduce

1. ghost install
2. Follow steps as laid out exactly in documentation

For whatever reason it appears that knex-migrator appears to not be checking mySQL.

### Technical details:

* Ghost Version: Latest
* Node Version:  v10.16.0
* Browser/OS: Ubuntu 18
* Database: MySQL

**Comment by acburdine** [comment] 2019-05-30 00:43
@joshuajbouw this appears to be a duplicate of https://github.com/TryGhost/Ghost-CLI/issues/936, so I'm going to close this. If it turns out that it's not a duplicate then we can reopen it 😄

**Closed by acburdine** 2019-05-30 00:43 UTC
