### ISSUE TITLE
Database Backup

### ISSUE THREAD

**Issue by owner** [TryGhost/Ghost#9650] opened 2018-05-25 15:52 UTC
Hello! I need download a DB from Ghost server.
Self-hosted variant on Ubuntu 16.04 LTS.

**Comment by acburdine** [comment] 2018-05-25 20:50
@owner There are a couple of way you can go about this

- go to <your blog url>/ghost/#/settings/labs and "export" all of your content. This will give you a JSON file that you can then import into another Ghost blog
- log onto your self-hosted server and:
  - if you're using MySQL, use mysqldump to dump the contents of your ghost database (see [here](https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html) for docs on mysqldump)
  - if you're using sqlite3, copy the ghost.db file from your ghost instance

Closing this issue as it's not a bug or ongoing feature work. Please use our forum -https://forum.ghost.org - if you have any further questions.

**Closed by acburdine** 2018-05-25 20:50 UTC
