### ISSUE TITLE
Font Smoothing flickers when auto-savings on OS X and Safari

### ISSUE THREAD

**Issue by smandell** [TryGhost/Ghost#5901] opened 2015-09-29 23:23 UTC
OS: OS X 10.10
Browser: Safari

When editing or composing a new post, whenever an auto-save draft is triggered the font-smoothing goes away and all the text appears thinner (see screenshot). This causes the text to flicker every time that a draft is saved. It's a very distracting experience. 

(the flicker happens at the end of the gift, maybe 15-20 seconds in). 
![ghost_draft_bug](https://cloud.githubusercontent.com/assets/9664395/10180858/a6232e64-66ce-11e5-9534-36f95cc77828.gif)

**Comment by lcamacho** [comment] 2015-10-01 17:25
I can't reproduce this bug on master

**Comment by dbhowell** [comment] 2015-10-01 22:54
This is because the save button spinner is using a transform in the animation. Adding "-webkit-transform: translate3d(0,0,0)" to the rendered-markdown will stop the flickering, however it will also change the appearance of the rendered text to the lighter weight. Googling "safari translate3d text flicker" will return a lot of results around this.

**Comment by kevinansfield** [comment] 2015-10-07 16:17
I believe this has been fixed in Safari 9 as I'm unable to reproduce it.

**Comment by smandell** [comment] 2015-10-07 16:20
Same!

**Comment by ErisDS** [comment] 2015-10-07 16:48
In that case, I'm gonna close the issue. No need to add a workaround for a browser bug that's already fixed by the vendor :wink:

**Closed by ErisDS** 2015-10-07 16:48 UTC
