### ISSUE TITLE
First article not clickable where overlapping header

### ISSUE THREAD

**Issue by hsand** [TryGhost/Ghost#8893] opened 2017-08-14 11:06 UTC
It's not possible to click on the first article where it overlaps with the header near the top.

You can see this issue at http://demo.ghost.io/

![image](https://user-images.githubusercontent.com/14326961/29269334-340b7a04-80f1-11e7-86c8-da61f6a5cb2a.png)

Anywhere above the black line near the "Welcome to Ghost" text is not clickable, though below it works as expected.

**Comment by kevinansfield** [comment] 2017-08-14 11:15
Closing as a duplicate of https://github.com/TryGhost/Casper/issues/349 - The fix is already in Casper master and will be included in the next release.

**Closed by kevinansfield** 2017-08-14 11:15 UTC
