### ISSUE TITLE
Client request for 4.8 does not match server version 4.0.0

### ISSUE THREAD

**Issue by lperrious** [TryGhost/Ghost#13104] opened 2021-06-30 16:43 UTC
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.
When trying to go to http://localhost:2368/ghost/. I got the error : Client request for 4.8 does not match server version 4.0.0. And I couldn't get the admin dashboard.

### To Reproduce

1. ghost: "^4.3.3" in package.json of the blog's repo.
2. delete node_modules and package-lock.json
3. npm i at the root of the project
3. npm start
4. go to localhost:2368 or whatever port your site is located at.
5. Then you get the error (see picture below).

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
All works well with a specific version like ghost: "=4.6.6" in the package file.

<img width="1439" alt="Capture d’écran 2021-06-30 à 18 38 30" src="https://user-images.githubusercontent.com/57103034/123999595-fadbcb00-d9d2-11eb-9b55-7e7de05ec96f.png">

### Technical details:

* Ghost Version: ^4.3.3
* Node Version: 14.17.1
* Browser/OS: macOS 11.3.1 and Brave
* Database: sqlLite3

**Comment by ErisDS** [comment] 2021-07-01 12:46
> ghost: "^4.3.3" in package.json of the blog's repo.

I don't know what this means?

It sounds like you're running Ghost in some non-standard way?

**Comment by sawilde** [comment] 2021-08-24 02:00
I came across this type of error when I had to manually upgrade my ghost to v4 (I was previously using https://github.com/snathjr/ghost-on-heroku to host my blog on heroku)

I got it to work locally (and on heroku) by getting the version of my package to match the ghost version - I am not sure why it cares that these two numbers align but it does.

![image](https://user-images.githubusercontent.com/297165/130543081-b071cd62-58cb-4ad5-81c4-fcb0c693321a.png)

**Comment by ErisDS** [comment] 2021-08-24 08:08
This error means that your Ghost admin client and Ghost core APIs (the server) are mismatched & aren't able to understand each other properly. It's saying you haven't completed the upgrade - you've upgraded one part and not the other.

This is clearly being caused by non standard installs and upgrades, not happening incorrectly after a successful upgrade - i.e. it is not a bug. Closing as a support request for non standard upgrade help that belongs on the forum.

**Closed** 2021-08-24 08:09 UTC
Labels: support-request

**Comment by sawilde** [comment] 2021-08-25 00:02
@ErisDS all I can say is that that is what worked for me - I have the new admin panel (I was v3 before (*) now it's v4) and all works well on Heroku. I don't know enough about Ghost and its setup to explain it but I thought if others come across this issue (as I did via google) then this may work for them. 

(*) My original setup was a template to host Ghost v3 on Heroku and I expect I am not alone in using the template.
