### ISSUE TITLE
Bug: When PSM Open, Scrolling Focus Still on Background

### ISSUE THREAD

**Issue by dbalders** [TryGhost/Ghost#5713] opened 2015-08-25 01:01 UTC
### Issue Summary

Device: iPhone 6

When you open the PSM, and try to scroll, you still scroll the background until you deliberatly tap on the PSM itself

![psm background scrolling](https://cloud.githubusercontent.com/assets/4715098/9456270/1ff1ca72-4a8a-11e5-9797-885ca8df1848.gif)

### Steps to Reproduce

1. Log into the admin interface on an iPhone\
2. Open anything like a new post or tags
3. Open the PSM and try to scroll

### Technical details:

* Ghost Version: Master
* Client OS: Mac 10.10
* Server OS: Mac 10.10
* Browser: Safari Mobile
* Database: SQLite

**Comment by kevinansfield** [comment] 2016-01-08 15:49
I've been unable to reproduce this on 0.7.4 on an iPhone 6s running iOS 9.2. Are you able to replicate the issue?

It's only the PSM that would exhibit this behaviour now that the tags screen has changed so anyone testing would need to open a long post in order to have "background" that's scrollable. When I tested I'm still able to scroll the main screen behind the PSM but only if I touch the extreme left of the screen which is covered by the PSM.

**Comment by ErisDS** [comment] 2016-01-12 20:26
Ok, let's close this and reopen it if we get a new reproduction case :+1:

**Closed by ErisDS** 2016-01-12 20:26 UTC
Labels: bug, fix wanted
