### ISSUE TITLE
Ghost-admin CALL_AND_RETRY_LAST Allocation failed 

### ISSUE THREAD

**Issue by guoshencheng** [TryGhost/Ghost#9128] opened 2017-10-11 09:05 UTC
hi. when i run `ember build` show error below:
```bash
<--- Last few GCs --->

[2032:0x103000000]    80839 ms: Mark-sweep 1412.4 (1466.4) -> 1412.3 (1450.4) MB, 4662.8 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 4663 ms) last resort 
[2032:0x103000000]    85083 ms: Mark-sweep 1412.3 (1450.4) -> 1412.3 (1450.4) MB, 4243.9 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x138f5229891 <JS Object>
    2: keysForTree [/Users/guoshencheng/Documents/others/Ghost-Admin/node_modules/_broccoli-kitchen-sink-helpers@0.3.1@broccoli-kitchen-sink-helpers/index.js:~27] [pc=0x13f62378f2bd](this=0x3e8eef88b309 <JS Global Object>,fullPath=0x3aba1601fa39 <String[879]: /Users/guoshencheng/Documents/others/Ghost-Admin/node_modules/_babel-core@6.26.0@babel-core/node_modules/babel-register/node_modules/babel...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::Factory::NumberToString(v8::internal::Handle<v8::internal::Object>, bool) [/usr/local/bin/node]
 6: v8::internal::Runtime_NumberToString(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x13f62328437d
 8: 0x13f6232cb000
 9: 0x13f62378f2bd
10: 0x13f6233682cb
Abort trap: 6
```
could some one help me ?

**Comment by kevinansfield** [comment] 2017-10-11 09:27
@guoshencheng this sounds like it's a local environment issue or a bug in an upstream dependency.

I notice you're trying to build Ghost-Admin outside of a Ghost install - I'd suggest following our [Ghost-Admin contributing guide](https://docs.ghost.org/docs/working-with-the-admin-client) for proper development instructions.

I'm going to close this as it's not a bug in Ghost, if you need help with getting set up please swing by our [Slack channel](https://slack.ghost.org) 😄

**Closed by kevinansfield** 2017-10-11 09:27 UTC

**Comment by guoshencheng** [comment] 2017-10-12 05:01
got it, thanks for reply
