### ISSUE TITLE
config url http vs https

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost#8635] opened 2017-06-26 11:05 UTC
### Issue Summary

If `config.production.json` starts with
` "url": "http://www.example.com"`
everything works fine

But let's say I want SSL-only connections so I setup my nginx to always redirect http requests to https address. It will still work just fine. However it appears that the "url" parameter (with "http" instead of "https") is used at least in two more places:

- under "home" links on blog page
![image](https://user-images.githubusercontent.com/5560454/27536333-ee02047c-5a6e-11e7-9a07-92cf24dc632b.png)

- in email sent from ghost
![image](https://user-images.githubusercontent.com/5560454/27536366-15f98e00-5a6f-11e7-9795-af6d7225cff3.png)

I tried to change URL in `config.production.json` from "http" to "https", but even though ghost starts it's not possible to open page due to errot `ERR_TOO_MANY_REDIRECTS`.

* Ghost Version: beta2
* Node Version: 6
* Browser/OS: Chrome / Centos 7 + nginx + SSL
* Database: MariaDB

**Comment by ErisDS** [comment] 2017-06-26 11:06
This is an nginx configuration error and a duplicate of https://github.com/TryGhost/Ghost/issues/4370.

You must use the correct proxy settings. 

This is a large part of the reason why ghost-cli does this stuff for you 😉

**Closed by ErisDS** 2017-06-26 11:06 UTC

**Comment by PaszaVonPomiot** [comment] 2017-06-26 12:33
@ErisDS thanks! I have fixed my nginx settings and it seems to work for blog. The email still shows http address but that's minor issue.
