### ISSUE TITLE
White screen when logging in or loading Ghost although dark mode is turned on

### ISSUE THREAD

**Issue by iamsanteri** [TryGhost/Ghost#11564] opened 2020-02-01 17:09 UTC
### Issue Summary

When dark mode is on, as the user logs into the admin panel, the login form and the loading screen are completely white. 

For external visitors the blog is dark (Casper theme) and for the admin-side of things the editor is also dark, but when logging into the platform the loading page with the spinner is fully white, thus blasting the admin user with sudden bright light for a second or two. This happens only during login or loading and before dark mode returns (when enabled). 

### To Reproduce

1. The issue is more irritating if your blog runs a theme which supports dark mode
2. Go to your ghost blog. 
3. Add "/ghost" to the URL in order to log into the admin panel
4. Notice that the login form is white if you aren't logged in or if you are, notice that the page blasts you with a white screen while you are logging for a second or two before turning dark again 

I think Ghost should be smarter about this and also enable dark mode for the Admin login and loader pages if the dark mode is turned on. 

### Technical details:

* Ghost Version: Latest
* Browser/OS: Chrome, Safari

Could we fix this at some point in future updates?

**Comment by oreniko26** [comment] 2020-02-11 06:38
I want to open a pull request to fix this but I can't. Any help on what I'm missing?

**Comment by gargol** [comment] 2020-02-11 08:18
Hey @oreniko26, following our [contributor guide](https://github.com/TryGhost/Ghost/blob/master/.github/CONTRIBUTING.md) should work. What exactly are you having a problem with?

**Comment by oreniko26** [comment] 2020-02-11 08:28
I missed the fact I need to fork the project into my **_personal account_**. From here on out things should flow smoothly. Thanks, @gargol!

**Comment by aman-kumar-jh** [comment] 2020-02-14 06:59
I want to fix the issue but need some help
First in which file should I look for the bug? From my point file path should be `'Ghost-Admin/app/styles/app-dark.css` .

**Comment by kevinansfield** [comment] 2020-02-14 10:10
> First in which file should I look for the bug?

It's not a bug but expected behaviour at the moment, a CSS change will not be able to "fix" it.

The night-shift preference is stored per-user. The login screen has no access to that preference because you are not logged in yet so it displays with the default stylesheet, only once you log in and your user preferences are loaded does the app know to switch over to the night shift stylesheet.

We may in the future be able to auto-toggle based on OS-level preferences but some design work needs to be done for how that will interact with the user-level preference in the admin area.

I'm closing this issue for now as it's not a bug but a feature request. I suggest opening a topic on the [Ideas board](https://forum.ghost.org/c/Ideas/5) so that it can be voted on and prioritised.

**Closed by kevinansfield** 2020-02-14 10:10 UTC
Labels: admin-client, design

**Comment by dm17** [comment] 2021-04-06 19:36
> > First in which file should I look for the bug?
> 
> It's not a bug but expected behaviour at the moment, a CSS change will not be able to "fix" it.
> 
> The night-shift preference is stored per-user. The login screen has no access to that preference because you are not logged in yet so it displays with the default stylesheet, only once you log in and your user preferences are loaded does the app know to switch over to the night shift stylesheet.
> 
> We may in the future be able to auto-toggle based on OS-level preferences (these weren't generally available when we built the night-shift feature) but some design work needs to be done for how that will interact with the user-level preference in the admin area.
> 
> I'm closing this issue for now as it's not a bug but a feature request. I suggest opening a topic on the [Ideas board](https://forum.ghost.org/c/Ideas/5) so that it can be voted on and prioritised.

I see the problem more as Dark Reader, which works on basically every site I've been to, does not work on the latest version of ghost.
