### ISSUE TITLE
Issue with {{next_post}} and {{prev_post}} helpers

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#10385] opened 2019-01-15 20:59 UTC
### Issue Summary

{{next_post}} and {{prev_post}} helpers do not give results

### To Reproduce

Install Ghost 2.11.0 and open any post (with Casper theme) - check section "next post" - you can also see on the official demo - [demo.ghost.io](https://demo.ghost.io)

### Technical details:

* Ghost Version: 2.11.0
* Node Version: 10.13.0
* Browser/OS: Safari / macOS 10.14.2
* Database: SQLite

**Comment by allouis** [comment] 2019-01-18 09:05
Closing as this is a dupe of #10389 and that issue contains a little more info :relaxed:

**Closed by allouis** 2019-01-18 09:05 UTC
