### ISSUE TITLE
Heading ID

### ISSUE THREAD

**Issue by NistorCristian** [TryGhost/Ghost#8878] opened 2017-08-11 11:49 UTC
Hello,

Everytime we use headings inside Ghost editor on the client side we get an id based on the text inside of it. But the text is not show in a pretty way. For example:

h3 -> There are a few things that you should know up-front
id="thereareafewthingsthatyoushouldknowupfront"

Woudn't be nice if we could get a more human friendly way ? 
id="there-are-a-few-things-that-you-should-know-up-front".

Is there a reason why the space isn't replaced with a separator?

* Ghost Version: >1.0.0

**Comment by kevinansfield** [comment] 2017-08-11 12:11
@NistorCristian I agree it's not that nice but it was done this way to maintain backwards compatibility with 0.11.x so that anyone upgrading doesn't end up with broken links on all of their posts.

Closing as it's not a bug but intended behaviour.

**Closed by kevinansfield** 2017-08-11 12:11 UTC

**Comment by meleu** [comment] 2020-01-04 05:35
@NistorCristian @kevinansfield 
I've posted a "feature request" that can probably solve this issue.
You can check it here:
https://forum.ghost.org/t/extended-markdown-card-in-the-editor/11146
