### ISSUE TITLE
Unable to type story body using Gboard autocomplete / swiping on iOS

### ISSUE THREAD

**Issue by Gulci** [TryGhost/Ghost#9398] opened 2018-01-15 03:02 UTC
### Issue Summary

This occurs when I'm using Google's Gboard on iOS. I can type regularly just fine, but when I attempt to use Gboard's autocorrect feature or swipe to type, I'm suddenly unable to input text, and instead it only inserts spaces. I'm also unable to type the first letter I try to type normally, which can be seen in this video reproducing the bug.

[GFY of the bug](https://gfycat.com/ChiefIndolentLemming)

### Steps to Reproduce

1. Start typing in a story body.
2. Attempt to swipe or use autocorrect.

This makes it pretty hard to compose posts on my iPhone... :)

### Technical details:

* Ghost Version: 1.20.0
* Node Version: 8.9.4
* Browser/OS: Safari iOS 11
* Database: mysql

**Comment by kevinansfield** [comment] 2018-01-15 09:19
Hi @Gulci 👋 Unfortunately this is a known limitation of the markdown editor which is based on CodeMirror, please search for and/or open an issue on [their repo](http://github.com/codemirror/CodeMirror) if you want to track it. We're working on a replacement rich-text editor but the issue will likely remain in the markdown card.

Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/9311

**Closed by kevinansfield** 2018-01-15 09:19 UTC

**Comment by Gulci** [comment] 2018-05-25 00:34
Hey @kevinansfield, I'm still having this issue with the new editor, but I see mobile browsers aren't supported. Still, just wanted to let you know. Cool stuff! :)
