### ISSUE TITLE
Provide URL for post image

### ISSUE THREAD

**Issue by ScottHelme** [TryGhost/Ghost#9408] opened 2018-01-19 10:25 UTC
### Issue Summary

When creating a new post you can only upload an image, you can't provide a URL for it. I've had many posts recently with the same post image and I have to keep uploading copies of the same image, rather than specifying the URL of the existing image. 

Specifying the URL would allow me to use existing images, saving an upload and storage of a duplicate image on Ghost, and also allow readers to fetch the image from cache instead of my blog.

### Steps to Reproduce

1. Create a new post.
2. Can't provide URL for post image.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: Pro
* Node Version: ?
* Browser/OS: All
* Database: ?

**Comment by kirrg001** [comment] 2018-01-19 11:30
Duplicate of #8653 and #8838, this feature was removed in 1.0. See conversations and reasonings in #8032.

Please use the search before posting a new issue. Thanks!

**Closed by kirrg001** 2018-01-19 11:30 UTC
