### ISSUE TITLE
Add support for Node v4

### ISSUE THREAD

**Issue by pensierinmusica** [TryGhost/Ghost#5823] opened 2015-09-10 08:57 UTC
Hi,

Could you please add support for [Node v4](https://nodejs.org/en/blog/release/v4.0.0/)?

When I try to install Ghost through [npm](https://www.npmjs.com/) it currently generates lots of errors.

Thanks!

**Comment by sebgie** [comment] 2015-09-10 09:05
Closing as duplicate of #5821.

You can find an explanation why it doesn't work yet in this comment https://github.com/TryGhost/Ghost/issues/5821#issuecomment-138995279.

**Closed by sebgie** 2015-09-10 09:05 UTC
