### ISSUE TITLE
SVG as blog logo made button disappear in Admin Control Panel

### ISSUE THREAD

**Issue by kassius** [TryGhost/Ghost#5147] opened 2015-04-15 22:46 UTC
Hello, I set a .svg file as blog logo, it worked but after this the button to change the logo disappeared from Administration cp.

**Comment by PaulAdamDavis** [comment] 2015-04-15 22:57
Hi @kassius, welcome to Ghost! :smiley:

We've had this issue before, in #4959. The consensus was that a malformed SVG is the cause, but a fix was implemented to handle this.

It's be great if you could update this issue with the version of Ghost you're running and a few other details, that way we have a bit more information we need. There's a handy template in the [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bug-reports).

**Comment by ErisDS** [comment] 2015-04-19 15:01
Hi @kassius please can you confirm which version of Ghost you were using, and if possible provide the file or try validating it to ensure it is well formed?

Without more info, it's not possible to reproduce this so I'm going to close it for now. Will reopen when more info is provided. Thanks :+1:

**Closed by ErisDS** 2015-04-19 15:01 UTC
