### ISSUE TITLE
Imported Posts not editable in Alpha

### ISSUE THREAD

**Issue by gomesphoto** [TryGhost/Ghost#8408] opened 2017-04-26 13:03 UTC
### Issue Summary

When importing posts from Wordpress using the Ghost plugin and importing them, it's not possible to edit them as the Editor only shows the title, and the content is empty. If we save the post will be empty afterwards but if we leave the editor without saving, the post stays intact.

### Steps to Reproduce

1. Export Wordpress posts using latest plugin from Ghost
2. Import JSON file to Ghost under Labs > Import Content
3. All the posts are now imported and visible in the Blog
4. Go to stories
5. Select any of the imported posts for editing
5. Inside post editor, you only see the Title but no content

Note: This issue only occurs in Alpha, imported Wordpress posts are correctly formatted and editable in latest stable version. The issue is directly related to the post editor in Alpha

### Technical details:

* Ghost Version: 1.0.0-alpha.20
* Node Version: 7.9.0
* Browser/OS: Chrome 57 / macOS 10.12.4 
* Database: development (sqlite)

**Comment by kevinansfield** [comment] 2017-04-26 13:04
Closing, duplicate of https://github.com/TryGhost/Ghost/issues/8407

**Closed by kevinansfield** 2017-04-26 13:04 UTC
