### ISSUE TITLE
Ran into performance issues with too large images,need multi-size images storage

### ISSUE THREAD

**Issue by leapit** [TryGhost/Ghost#9109] opened 2017-10-07 10:54 UTC
Generally i upload image to blog use camera original image,the large size will cause a slow load when the site is open,you can try this,and see the home page load speed with many large images.

[http://tabenren.com/](http://tabenren.com/)

the question is obvious,

**we do not need load the full size image in home page,just thumbnail image is ok.**

so,any plans about this in further dev?

**Comment by kevinansfield** [comment] 2017-10-07 12:36
@leapit Ghost doesn't do any image processing, you should be optimising any images before uploading to your blog.

Closing as a duplicate of #4453

**Closed by kevinansfield** 2017-10-07 12:36 UTC
