### ISSUE TITLE
Icons not showing in the admin panel

### ISSUE THREAD

**Issue by laite** [TryGhost/Ghost#5034] opened 2015-03-14 12:47 UTC
The icons on the admin panel do not show on Firefox (Iceweasel 31.5.0, Linux 64bit). With Google Chrome (41.0.2272.76 (64-bit)) icons work as supposed. 

Attached a picture where firefox is on the left, chrome on the right.

![screenshot](https://cloud.githubusercontent.com/assets/666799/6651708/f0d98060-ca58-11e4-8ac4-0ec2559ac9f0.png)

Ghost version 0.5.10 (production)

**Comment by PaulAdamDavis** [comment] 2015-03-14 13:10
Hi @laite, thanks for reporting this!

I'm not too familiar with Linux, is 31.5.0 the latest version of Firefox? I ask because the latest version on OS X is 36.0.1, where the icons work as expected.

**Comment by laite** [comment] 2015-03-14 14:21
I'm sorry, it was probably just a caching issue. I restarted the server application and now everything's working once again.

Sorry for the trouble.

**Comment by letsjustfixit** [comment] 2015-03-14 15:41
Hey, I've noticed this lot of times already: it has nothing to do with linux. its because of the cache expire times: you dont need to restart the application just reset the browser cache: ctrl-shift-r in firefox for example. ive got these when I've restarted ghost a whole bunch of times and changed a few things here and there..

**Comment by Ardakilic** [comment] 2015-03-27 10:27
I'm having a similar issue, using the latest version of Chrome (Version 41.0.2272.104 (64-bit)) on OSX, ghost is self-installed. Instead of weird icons, I can't see the icons at all.

I've tried command+shift+r combo several times, no help.

Any ideas?

Thanks in advance,

**Comment by PaulAdamDavis** [comment] 2015-03-27 10:46
Hi @Ardakilic, could you give us a few more technical details about your environment at all? Version, where you downloaded, server, etc. There's a template [here](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bug-reports) :)

I just installed a fresh copy of Ghost 0.5.10 from ghost.org/download, on OS X with Chrome 41.0.2272.104 64bit, and it all worked fine, though I'm really keen to work out what this issue is.

**Comment by Ardakilic** [comment] 2015-03-27 11:20
@PaulAdamDavis 

Hello, thanks for the interest.

Here's the template, filled as requested

### Issue Summary
Admin panel icons are not shown. Clearing the cache does not change the situation.

### Steps to Reproduce
1. Sign in to the admin panel.
2. Various icons are not shown

Some screenshots:
http://prntscr.com/6lxmmv
http://prntscr.com/6lxmu4

In freshly installed firefox (I've installed just to test, first time installed in this OS), icons are shown, but like this: http://prntscr.com/6lxntt

### Technical details

* Ghost Version: 0.5.10, installed from release, updated from older versions. Self-hosted on a VPS.
* Client OS: Mac OSX Yosemite
* Server OS: Ubuntu 14.04.2 LTS x64
* Node Version: v0.10.38, npm version: 1.4.28, my node source is `deb-src https://deb.nodesource.com/node_0.10 trusty main`
* Browser: Chrome (Version 41.0.2272.104 (64-bit)) on OSX, Vivaldi 1.0.135.2 (Developer Build) OSX,  
* Database: SQLite

**Comment by letsjustfixit** [comment] 2015-03-27 11:20
@PaulAdamDavis:
The reason I tough it might have something to do with expry times is because it only occured to me with installs that has been around for at least a few hours (5+) :)

**Comment by aruizca** [comment] 2015-03-30 03:19
It is happening to me too. In firefox when I upgraded to 0.5.10 on Digital Ocean instance. chrome works fine:

![content_-_aruizca_s_blog___brain_collect_ idea_-__post_idea_](https://cloud.githubusercontent.com/assets/246477/6889708/bd6d99aa-d6e7-11e4-977e-ad7de5e7a3a6.png)

**Comment by Ardakilic** [comment] 2015-03-30 08:11
@letsjustfixit @PaulAdamDavis 

I have updated (actually re-installed) my ghost version, downloaded from http://ghost.org/download, updated according to this link:

http://support.ghost.org/how-to-upgrade/#how-to-upgrade

Same issue keeps on happening.

Any ideas ? Should I download from GitHub Release instead ?

Thanks in advance,

**Comment by PaulAdamDavis** [comment] 2015-03-30 08:12
As there's been a few new reports of this here and in #5057, I'm going to reopen this and investigate.

**Comment by letsjustfixit** [comment] 2015-03-30 08:22
Hey,
I'm only a simple user and force-redownloading the static assets always solved this issue in my case both in linux (Debian 7.8 wheezy, or 8 Jessie),windows 7&8.1 so my only advise is try downloading the css and font files and check if they work as they should..
You should also check your browser addons which might modify the displayed end results. (just a tought).
Sorry I cant be of any more help.

**Comment by PaulAdamDavis** [comment] 2015-03-30 10:18
I have not been able to reproduce this by upgrading from 0.5.9 to 0.5.10. However, I have briefly seen the squares when loading the page via a slow proxy. I can also manually simulate the effect by toggling `font-family: "GhostIcons";` on the icons in the dev tools.

Between 0.5.9 and 0.5.10 the icon font was regenerated to change the unicode range prefix from `"\e..."` to `"\f..."` (to fix a an issue where Emoji would replace the icons on iOS). It's possible that the process there caused this issue, though it seems to affect some people and not others, so I don't think it's that.

Other than the older icon font being heavily cached, I'm at a loss as to the cause :disappointed: From what I can see, nothing else that should affect this was [changed between 0.5.9 & 0.5.10](https://github.com/TryGhost/Ghost/compare/0.5.9...0.5.10).

**Comment by ErisDS** [comment] 2015-03-30 10:25
@PaulAdamDavis I am quite certain that this is a caching issue, as icon fonts are the only thing which are not currently managed by Ghost's internal asset handing. We have heavy caching of assets, a hard refresh should resolve the issue in the majority of cases, but there is no way to guarantee that all caches will behave the same.

To resolve this, my recommendation would be to add a versioning query string to the icon file path inside the scss files.  i.e. change `src:url('fonts/icons.woff')` to `src:url('fonts/icons.woff?v=0.1')` [here](https://github.com/TryGhost/Ghost/blob/master/core/client/app/styles/modules/icons.scss#L29) and bump the version number each time the icon font gets regenerated. This will ensure that every cache will fetch a new copy of the file. 

Long term, Ghost should have an asset pipeline which handles all of this automatically. Short term this will prevent these issues from occuring.

**Comment by sjahl** [comment] 2015-03-30 12:20
Just wanted to add that I saw this issue on Firefox 36.0.4 on OSX 10.10.2. Hard refresh /did not/ fix the problem, emptying my browser cache /did/ fix the problem. I also found that (while Firefox was exhibiting the issue) I couldn't reproduce the problem in a fresh installation of Chrome that I had never visited my admin interface with. I'd have to agree that this is a caching issue.

**Comment by PaulAdamDavis** [comment] 2015-03-30 12:29
@sjahl Brilliant, thanks for the clarification!
And thank you @ErisDS :) Will do that now.

**Comment by Ardakilic** [comment] 2015-03-30 12:50
@ErisDS Thanks for the reply! 

@PaulAdamDavis I have altered the `ghost.min.css`manually like this commit that you've just did: https://github.com/TryGhost/Ghost/commit/72ad4f72c640da61eabd78bf871c4ebb5270f12c and I can confirm icon issue is fixed on my case. :smile:

**Comment by aruizca** [comment] 2015-03-30 22:44
HI, 
I just installed the empty cache plugin in Firefox and after running it once, the icons were back.
https://addons.mozilla.org/en-US/firefox/addon/empty-cache-button/
Cheers,

**Closed** 2015-03-31 10:26 UTC
