### ISSUE TITLE
Group importer problems

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#9787] opened 2018-08-15 19:08 UTC
If you are importing a larger database, it can happen that you will see lot's of warnings.

> Entry was imported, but we were not able to resolve the following user references

We could group these warnings and optimise the messages in general.

Like

> Entry was imported, but we were not able to resolve the user references.
> Entries: [{id: 'ObjectId', keys: ['updated_at']}]

@peterzimon even reported that he got so many warnings, that his browser almost freezes.

Ghost: master

**Comment by dexterleng** [comment] 2018-12-17 06:13
Should the grouping be done only on the client side?
Or should a hash table be used where `message` key maps to a list of `entries`?

**Comment by dexterleng** [comment] 2018-12-17 07:35
Should we ignore the `problem.help` when grouping?

**Comment by kirrg001** [comment] 2018-12-17 14:08
Yeah i think so. But maybe we can achieve this? 🤔 

e.g.

```
message: 'grouped-error-message-1',
context: JSON.stringify(
  {
    posts: [post, post, post],
    users: [user, user]
  }
)
```

**Comment by kirrg001** [comment] 2019-03-17 14:59
Not stale

**Comment by gargol** [comment] 2019-06-17 08:36
Not stale

**Comment by ErisDS** [comment] 2019-08-21 06:08
Duplicate of #9584

**Closed by ErisDS** 2019-08-21 06:08 UTC
Labels: help wanted, import-upgrade, optimisation, server
