### ISSUE TITLE
I see a notification to upgrade to ghost 1.9.0 while running Ghost 1.9.0.

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/Ghost#9046] opened 2017-09-24 21:08 UTC
### Issue Summary

I see a notification to upgrade to ghost 1.9.0 while running Ghost 1.9.0.

It's good to know that I follow Ghost update via Docker images so I don't use Ghost update.

### Steps to Reproduce

click on about ghost

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 1.9.0
* Node Version: 6.2
* Browser/OS: Version 61.0.3163.100 (Official Build) (64-bit) 
* Database: Sqlite
* via the official docker container

Cheers!
Pascal

![screen shot 2017-09-24 at 5 03 45 pm](https://user-images.githubusercontent.com/6694151/30786872-e59a0cd0-a14a-11e7-8d4c-6606f8e3a466.png)

**Comment by kevinansfield** [comment] 2017-09-25 08:23
Closing as a duplicate of #9040.

This is a known issue and is being worked on as part of a larger overhaul of upgrade checks and notifications.

**Closed by kevinansfield** 2017-09-25 08:23 UTC

**Comment by pascalandy** [comment] 2017-09-25 13:29
thanks!
