### ISSUE TITLE
Scroll bar showing up in wrong place in editor

### ISSUE THREAD

**Issue by cs50curtis** [TryGhost/Ghost#9736] opened 2018-07-17 00:00 UTC
### Issue Summary

Double scroll bar issue arrises when trying to print with chrome on Windows 10.

### To Reproduce

1. Open Chrome on Windows 10
2. Navigate to the Ghost "New Post" page and begin editing a post (paste a long snippet of Lorem Ipsum).
3. Click the "preview" button which looks like an eye.
4. Use CTRL + P to try to print, and then cancel it when the screen comes up.
5. A random unmovable/non functioning scroll bar appears on the site of the editor

### Technical details:

Version: 1.24.8
Environment: production
Database: mysql
Windows10/Chrome

**Comment by kirrg001** [comment] 2018-08-19 21:07
@kevinansfield Could you please either label this issue or close? Thanks :)

**Comment by kevinansfield** [comment] 2018-08-20 13:18
@cs50curtis the Ghost 1.x editor is not designed to be printed and will not work well when attempted, if you want a printable version of a post you should use the preview link in the post settings menu (⚙️ icon in the top right) to see the post as it's displayed on your site.

I am unable to reproduce the double-scrollbar issue with Ghost 2.0.0 in Chrome 68 on Windows 10 1803 so I'm going to close this.

**Closed by kevinansfield** 2018-08-20 13:18 UTC
