### ISSUE TITLE
"Internal server error, cannot edit member. Cannot read property 'find' of undefined"

### ISSUE THREAD

**Issue by jakobgreenfeld** [TryGhost/Ghost#14079] opened 2022-01-27 18:30 UTC
### Issue Summary

When I try to give a member a complimentary subscription I get the error message

`Internal server error, cannot edit member. Cannot read property 'find' of undefined`

I already disconnected and reconnected Stripe but the problem still persists.

In my Stripe dashboard I can see that a new customer is added whenever I click on the "Add complimentary subscription" button. But customers that get added this way have no active subscription. Also there does not seem to be a $0/mo plan available for selection in Stripe (only regular ones $5/mo etc.) which seems to be the root of the issue. 

I manually created a plan called "Complimentary" priced at $0 in Stripe and added it to a test user and then it indeed shows up in the Ghost admin panel. But I still can't give anyone a complimentary plan using the Ghost admin panel. The error message is still the same. It's also not possible to remove a complimentary plan.

### Steps to Reproduce

Connect Stripe.
Select Member.
Click on "Add complimentary subscription"

### Ghost Version

4.33.2

### Node.js Version

N/A

### How did you install Ghost?

Gloat Host

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by realandrew** [comment] 2022-01-30 20:10
I had the same problem. Enabling tiered subscriptions fixed it for me but that resulted in another issue (#14082).

**Comment by jakobgreenfeld** [comment] 2022-01-31 05:33
This worked, thanks!

**Comment by matthanley** [comment] 2022-01-31 10:17
Hey @jakobgreenfeld 👋🏼 Thanks for the report! I've reopened this one because Tiers is a beta feature, and this issue is a regression in current functionality.

**Comment by daniellockyer** [comment] 2022-02-01 09:00
Hey @jakobgreenfeld! This is fixed and released in v4.34.1, so please update using Ghost-CLI 🙂

**Closed by daniellockyer** 2022-02-01 09:00 UTC
Labels: bug, p2 - major
