### ISSUE TITLE
Google AMP "You must specify a value for the image field."

### ISSUE THREAD

**Issue by ubuntutest** [TryGhost/Ghost#9555] opened 2018-04-07 19:33 UTC
Hi after the last update, to version 1.22.1 I am experiencing the following error with AMP:
"X Error-> image -> You must specify a value for the image field."

I do not use images on my blog. I never had problems.
I really do not know how to solve the problem.
Any suggestions?

```
{
        "@context": "https://schema.org",
   X    "@type": "Article",
        "publisher": {
            "@type": "Organization",
            "name": "******",
            "logo": {
                "@type": "ImageObject",
                "url": ""******",",
                "width": 60,
                "height": 60
            }
        },
        "author": {
            "@type": "Person",
            "name": "******",
            "url": ""******",",
            "sameAs": []
        },
        "headline": ""******",",
        "url": ""******",",
        "datePublished": "2017-05-02T22:24:41.000Z",
        "dateModified": "2018-03-28T08:58:11.000Z",
        "keywords": ""******",",
        "description": ""******",",
        "mainEntityOfPage": {
            "@type": "WebPage",
            "@id": ""******","
        }
}
```

``

**Comment by AileenCGN** [comment] 2018-04-09 02:39
This looks like a duplicate of #7558 to me.

@ubuntutest can you please provide some more information?

> "X Error-> image -> You must specify a value for the image field."

Where do you get this error?

AMP really needs images and Google will complain a lot if you don't provide a publisher logo and article image. This is less strict for non-AMP url. You can check this out for yourself [here](https://developers.google.com/structured-data/testing-tool/). If you really don't want to use images, I recommend to disable AMP for your blog.

**Comment by ubuntutest** [comment] 2018-04-09 09:41
> "X Error-> image -> You must specify a value for the image field."
>Where do you get this error?

I get this error here:
https://search.google.com/structured-data/testing-tool/

I really should disable AMP just because I do not use the images? The thing I do not understand is that I have never received these emails and I have been online for about a year. Always without any images.

**Comment by AileenCGN** [comment] 2018-04-09 11:17
> I really should disable AMP just because I do not use the images?

This is only a workaround I'm suggesting, as Google wants to have images for AMP. I referenced your issue to an existing one, as I thought these are related.

Without more information it's really hard to debug your use case. I do understand that obviously images are missing, but without a URL itself (e. g. one of your affected article URLs), it's hard to reproduce this.

**Comment by ubuntutest** [comment] 2018-04-09 13:41
Ok, thank you for your help, I'll send you the link to the site by email. Thank you

**Comment by AileenCGN** [comment] 2018-04-10 01:12
@ubuntutest isn't it a public site? I don't understand, why you didn't link it here in first place.

Anyway, I received your mail and checked the links and yes, the missing images is something that Google wants for schema type `article`.

There is not so much we can do about it now (Google even complains with the non-AMP version). As said in the original issue #7558 the only way would be to implement a default fallback image, which could be the blog cover or logo. 

Please keep an eye on the linked issue, as any solutions will be posts there. I will close this issue as a duplicate of it.

**Closed by AileenCGN** 2018-04-10 01:12 UTC
Labels: needs info

**Comment by ubuntutest** [comment] 2018-04-10 09:40
Sorry if I answer here even if you closed, but I think it's right to answer you.

My site is public but it is still in process for this I do not yet give the link around.

I hope you will solve by implementing a fallback with logo, I'll keep an eye on that conversation.

Do you suggest to disable AMP in the meantime so as not to make me hate from Google?

Thanks so much.

**Comment by AileenCGN** [comment] 2018-04-11 01:49
> Do you suggest to disable AMP in the meantime so as not to make me hate from Google?

That depends on you. But if you're not planning to use images for your articles, then I'd say you should disable it.
