### ISSUE TITLE
Uploaded images are not purged and may be duplicated

### ISSUE THREAD

**Issue by BeanBagKing** [TryGhost/Ghost#9661] opened 2018-06-04 01:32 UTC
### Issue Summary

Images that are uploaded to Ghost persist after being removed or replaced. For example, if I upload an image, decide the size is wrong, remove it and upload a new version, the original persists. Even if I, for some reason, uploaded exactly the same image, same file hash, it will create a new copy of the file on the server and never remove the previous one. 

Beyond unnecessarily using disk space, which may be an issue on both a bare-bones server with limited disk space and a large blog where a multitude of edits to image heavy pages may take place, this just makes a mess out of the file system.

This issue is also spelled out here: https://attilathedud.me/removing-unused-photos-on-a-ghost-blog/ which includes a link to an issue that no longer seems to exist (or link has moved). After searching here and not finding it, I'm opening this. If there is a currently issue for this opened, please let me know. 

### To Reproduce

1. Start a new post and upload an image
2. Remove the link to this image, and upload the same image a second time
3. Look in /var/www/ghost/content/images/<year>/<month> for two copies of the image.

### Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

While this doesn't impact front-end functionality and I would not consider it to be high priority, I do feel like this is not the behavior a user would expect. The expected behavior is for the system to remove unused images. 

### Technical details:

* Ghost Version: 1.23.1

**Comment by vikaspotluri123** [comment] 2018-06-04 01:37
Hey 👋 this is a duplicate of the [media library feature request](https://forum.ghost.org/t/media-library-manage-all-files-in-one-place/675) over on the [forum](https://forum.ghost.org)

**Comment by kirrg001** [comment] 2018-06-04 08:37
Hi @BeanBagKing!

Thanks for the idea!

@vikaspotluri123 Thanks for the reference.

We only keep Github issues open for bugs and in-progress feature work. 
You can [vote](https://forum.ghost.org/t/media-library-manage-all-files-in-one-place/675) on the idea in the forum.

**Closed by kirrg001** 2018-06-04 08:37 UTC
