### ISSUE TITLE
Unable to write some diacritical characters in markdown editor

### ISSUE THREAD

**Issue by SixBytesUnder** [TryGhost/Ghost#9215] opened 2017-11-05 13:59 UTC
### Issue Summary

I write in Polish and am not able to type in some Polish diacritical characters. Keyboard shortcuts are preventing writing those characters. 
I’m assuming this is happening for all languages where a diacritical character collides with keyboard shortcuts. 

### Steps to Reproduce

1. Make sure your system keyboard is set to `Polish (Programmers)`.
2. Login to Ghost admin area.
3. Create a new story or edit existing one.
4. Click to markdown editor and type:
`Alt + L` should output `ł` but is applying a Numbered list which has a shortcut `Ctrl + Alt + L`
`Alt + S` should output `ś` but is running Spellcheck which has a shortcut `Ctrl + Alt + S`
`Alt + C` should output `ć` but is running Inline Code which has a shortcut `Ctrl + Alt + C`

To write Polish diacritical characters I can only use the **right** Alt. Ideally, the Ctrl + Alt shortcuts would stay, but would not be triggered by just the right Alt alone. Alternatively, an option to disable markdown keyboard shortcuts in general settings would work as well.

### Technical details:

* Ghost Version: 1.16.2
* Node Version: v6.11.3
* Browser/OS: Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
* Database: mysql
* Windows 10
* Ghost self hosted and desktop app

**Comment by kevinansfield** [comment] 2017-11-06 09:57
Closing as a duplicate of #8687, the issue is currently being tracked in an upstream dependency at  https://github.com/sparksuite/simplemde-markdown-editor/issues/616

**Closed by kevinansfield** 2017-11-06 09:57 UTC
