### ISSUE TITLE
Editor not working on iOS

### ISSUE THREAD

**Issue by foffer** [TryGhost/Ghost#8699] opened 2017-07-15 10:20 UTC
### Issue Summary

When using Safari in iOS 10 / 11 the post Title and the 'Cog' in the editor doesn't work. I found a similar issue which has [been closed](https://github.com/TryGhost/Ghost/issues/8192) suggesting it is solved, but it doesn't seem to be solved on my end.

### Steps to Reproduce

1.  Log into the Ghost Admin
2. Create new post
3. Try to edit the title and click the cog
Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 1.0.0-rc1
* Node Version: 6.11.1
* Browser/OS: iOS 10.3 / iOS 11 beta 3 - Safari
* Database: MySQL

**Comment by kevinansfield** [comment] 2017-07-15 10:21
Hey @foffer 👋 Thanks for reporting! I'm going to close this as a duplicate of https://github.com/TryGhost/Ghost/issues/8657

**Closed by kevinansfield** 2017-07-15 10:21 UTC

**Comment by foffer** [comment] 2017-07-15 10:23
@kevinansfield apologies, I did not see that post. Thanks Kevin
