### ISSUE TITLE
#foreach @blog.navigation does return wrong URLs (IMHO)

### ISSUE THREAD

**Issue by fmaida** [TryGhost/Ghost#10527] opened 2019-02-24 14:46 UTC
Hello.

Sorry to bother you. I'm not exactly 100% sure this is a bug, but yesterday I wanted to put a list of my navigation links in the footer of my website, so I wrote this into `partials/footer.hbs`:

```html
{{#foreach @blog.navigation}}
<li>
    <a href="{{url absolute='true'}}">
        <span class="fa fa-caret-right" aria-hidden="true"></span>
        {{label}}
    </a>
</li>
{{/foreach}}
```

And this code is correctly displaying all the links I have created under Design -> Navigation, but the `{{url absolute='true'}}` property for each of these links is not correct: instead of pointing to the correct URL, it is instead pointing to the root URL of my website. I don't know if I have explained this concept properly, however just to make an example, instead of having a URL like this:

`https://www.cesco.it/my-products`

The returned URL value is just:

`https://www.cesco.it/`

I'm getting the same behavior even when I try to use `{{url}}` instead of `{{url absolute='true'}}`.

If you want to see this in action, just pay a visit to my website on https://www.cesco.it and scroll down to the end and try any link in the section "Link rapidi" (that's would be the italian translation of "quick links", I'm still not sure about that translation...)

### Technical details:

* Ghost Version: 2.15.0
* Node Version: 8.15.0
* Browser/OS: Chrome 72.0.3626.109 on macOS 10.14
* Database: MySQL

I'm also attaching the complete `partials/footer.hbs` file for completeness.
[footer.hbs.zip](https://github.com/TryGhost/Ghost/files/2898009/footer.hbs.zip)

**Comment by fmaida** [comment] 2019-02-24 14:57
Never mind, I just saw that using just `{{url}}` instead of `{{url absolute='true'}} works as expected.

**Comment by kirrg001** [comment] 2019-02-25 06:22
Duplicate of https://github.com/TryGhost/Ghost/issues/5162.

**Closed by kirrg001** 2019-02-25 06:22 UTC
