### ISSUE TITLE
Editor: Images with transparency are shows with grey backgrounds

### ISSUE THREAD

**Issue by ConnorKrammer** [TryGhost/Ghost#5835] opened 2015-09-13 22:48 UTC
## Issue description

Inserting an image with transparency into the editor results in it being displayed in the preview pane with a grey background.

## Steps to reproduce

Create a new post, and write the following:
```
![Transparency Test](http://www.clker.com/cliparts/a/5/8/e/1298546227709322759png-transparency.png)
```

The image will show up with a grey background. You can verify this by opening the image directly in your browser or by previewing the post.

## Technical details

**Ghost**: 0.7.0
**Firefox**: 40.0.3
**OS**: Windows 7

**Comment by schuer** [comment] 2015-09-28 21:33
That is expected behaviour, caused by the grey image wrapper. What’s so bad about it?

**Comment by ErisDS** [comment] 2015-10-09 14:50
Closing this as it is the expected behaviour. The image upload interface will be revisited very soon as part of a bigger overhaul, and so I don't think there's any short term need to look at changing the behaviour here.

**Closed by ErisDS** 2015-10-09 14:50 UTC
