### ISSUE TITLE
Link to public post from the "Published" text

### ISSUE THREAD

**Issue by danielbachhuber** [TryGhost/Ghost#8942] opened 2017-08-26 22:51 UTC
As a Ghost author, it's not clear to me how I get to frontend URL of my published blog post:

![image](https://user-images.githubusercontent.com/36432/29745662-2d3f6170-8a76-11e7-9c35-10ab834ddf4e.png)

Once sensible way to make this possible would be to link the "Published" text in the top left:

![image](https://user-images.githubusercontent.com/36432/29745669-53c22828-8a76-11e7-862e-7df5adcbdbb9.png)

**Comment by gmmoraes** [comment] 2017-08-27 04:03
@acburdine  
If possible I would like to try to add the post link url attribute to the text that stays on top of the page of published posts.

@danielbachhuber 
Currently you could get the post url by clicking on the "gear" icon on the right top of the published post screen(see the images bellow), is this what you are looking for?

![img1](https://user-images.githubusercontent.com/16384897/29747048-628d2216-8ac3-11e7-8d68-5dcc9104409f.png)

![pic2](https://user-images.githubusercontent.com/16384897/29747049-658a7946-8ac3-11e7-8390-3e84868bd0f0.png)

**Comment by danielbachhuber** [comment] 2017-08-27 15:50
> Currently you could get the post url by clicking on the "gear" icon on the right top of the published post screen(see the images bellow), is this what you are looking for?

Yes. I don't believe this is an intuitive location for it though.

**Comment by AileenCGN** [comment] 2017-08-28 09:51
Hey @danielbachhuber!

As mentioned above, the post URL is visible (and editable) in the post settings menu. You should also see a notification popping up, whenever you published or updated a blog post:

![image](https://user-images.githubusercontent.com/8037602/29768502-b6561558-8c10-11e7-90ef-757cc921d47d.png)

I'm closing this as it's not a bug. Feel free to reopen it, when you think that this should be taken care of. You can also submit and vote for feature requests on https://ideas.ghost.org.

**Closed by AileenCGN** 2017-08-28 09:51 UTC
