### ISSUE TITLE
Error when saving a post is shown as a notification rather than an alert

### ISSUE THREAD

**Issue by ManuelRauber** [TryGhost/Ghost#6509] opened 2016-02-15 08:47 UTC
While I was changing some post settings and wondering, why it did not work, I asked within Slack, if someone could help me. While preparing a screenshot with the issue, I noticed a little red box in the bottom left corner "Ajax authorization failed". After reloading, everything worked as expected. 

Since I have a high resolution (Apple Cinema Display) and a quite big browser, that little box on the bottom left corner does not draw any attention to me, especially for errors. 

Would it be possible to get a more present ui notification style (at least for errors)?

**Comment by kevinansfield** [comment] 2016-02-15 08:51
Hey @ManuelRauber, errors do have an alert style already, however in the particular case you ran into  the error was incorrectly being displayed as a notification rather than an alert. I've updated your issue title to reflect that, hope you don't mind :smile:

**Comment by ManuelRauber** [comment] 2016-02-15 08:54
@kevinansfield Ah thanks! Didn't know that, since I have never encountered such an error. :)

**Comment by yash14123** [comment] 2016-02-18 20:18
Any help on this? I would like to work on this.

**Comment by ryrych** [comment] 2016-03-13 19:27
@kevinansfield is this already fixed? Pasting some random text as a post title (invalid when length > 150) I got this error:
![screen shot 2016-03-13 at 20 26 28](https://cloud.githubusercontent.com/assets/278637/13730784/f256e470-e959-11e5-8f62-30c13ff63e3d.png)

which I suppose is correct. /cc @theaverageguy

**Comment by ManuelRauber** [comment] 2016-03-16 06:30
@ryrych That is not about all error alerts, just the special one mentioned in the beginning. As @kevinansfield said, it's only the "AJAX Authorization Error" which is displayed in the wrong style. :-)

**Comment by KyRaiken** [comment] 2016-03-21 16:25
Is anyone working on this? I would like to pick it up

**Comment by acburdine** [comment] 2016-05-12 00:39
@KyRaiken if you want to pick this up, go for it 😄

**Comment by acburdine** [comment] 2016-05-12 01:49
Hey @ManuelRauber, would you mind sharing what you did to get this error? There's been several changes to the ajax handling since then which makes me think that this could possibly have been solved. I wasn't able to reproduce this locally.

**Comment by ManuelRauber** [comment] 2016-05-12 17:23
@acburdine I just had this error one time at the time of writing this issue here. I think it happened after opening the browser pointing to the Ghost Admin and trying to change something much much later.

**Comment by acburdine** [comment] 2016-07-14 00:18
@ManuelRauber just merged in a pretty large error refactor, so will close this for the time being. Comment if it happens again and we can reopen this 😄

**Closed by acburdine** 2016-07-14 00:18 UTC
Labels: beginner, ember
