### ISSUE TITLE
Updating to 2.18.2 makes Publication icon disappear

### ISSUE THREAD

**Issue by Caucasus-and-Mercury** [TryGhost/Ghost#10621] opened 2019-03-19 12:15 UTC
### To Reproduce

This is very straightforward:

1. Update to 2.18.2
2. Take a look at Settings - General: there's no Publication icon anymore
3. Check: the Publication icon no longer shows up in the browser adress bar etc. Gone -

(Edit: turns out re-uploading the icon fixes it).

### Technical details:

* Ghost Version: 2.18.2
* Browser/OS: Safari
* Database: mysql

**Comment by kirrg001** [comment] 2019-03-19 18:56
I wasn't able to reproduce.

@rishabhgrg Could you please test & triage? Thanks 💅🏼

**Comment by rishabhgrg** [comment] 2019-03-20 07:33
Hey @Caucasus-and-Mercury, I am unable to reproduce it either and will like to get some more info from you.

- Which version were you on before updating to 2.18.2 ?
- Did you have a publication icon already uploaded in the previous version ?
- Did you use Ghost-CLI update to 2.18.2 ?

**Comment by Caucasus-and-Mercury** [comment] 2019-03-20 11:10
Hi ok well maybe (hopefully) this is only me, then. But fact is: site was normal - I updated - this issue emerged.

_Which version were you on before updating to 2.18.2 ?_
The previous one, 2.18.1

_Did you have a publication icon already uploaded in the previous version ?_
Yes

_What were the steps you used for updating to 2.18.2? Did you use Ghost-CLI for the update to 2.18.2 ?_
Digital Ocean droplet yes, console, simply using the ghost update command

**Comment by rishabhgrg** [comment] 2019-03-21 08:40
Hey @Caucasus-and-Mercury, thanks for the info, I'll see if I can reproduce it again with the above steps. Are you using any storage adapter or any other custom adapters with your setup ?

**Comment by Caucasus-and-Mercury** [comment] 2019-03-21 10:19
@rishabhgrg,

No, no custom adapters or snaything such.

**Comment by rishabhgrg** [comment] 2019-03-25 07:24
@Caucasus-and-Mercury Thanks again for the info. Closing this for now as its not reproducible, will re-open if any other such case pops up. :)

**Closed by rishabhgrg** 2019-03-25 07:24 UTC
Labels: needs info
