### ISSUE TITLE
Author slug with one letter causes failed filter

### ISSUE THREAD

**Issue by betschki** [TryGhost/Ghost#20133] opened 2024-05-05 17:07 UTC
### Issue Summary

A staff member that signs up with a single-letter first name upon invitation will not be able to use Ghost at all. They only see an error message in the Ghost admin:

```
Request not understood error, cannot list posts. Error parsing filter
```

![CleanShot 2024-05-05 at 19 03 18@2x](https://github.com/TryGhost/Ghost/assets/25703384/52fe6ae4-32bd-487d-99d7-4ee759370d79)

Looking at the network requests, the request to `/ghost/api/admin/posts/?formats=mobiledoc%2Clexical&limit=30&page=1&filter=status%3A%5Bdraft%2Cscheduled%2Cpublished%2Csent%5D%2Bauthors%3Aj` fails.

As soon as the last filter is removed, the API request succeeds:

`https://tireless-buzzard.pikapod.net/ghost/api/admin/posts/?formats=mobiledoc%2Clexical&limit=30&page=1&filter=status%3A%5Bdraft%2Cscheduled%2Cpublished%2Csent%5D`

I have then tried to change the author slug in the database from "j" to "jb" – and things started to work.

This has been tested in different environments, both locally with development configurations, as well as on different managed hosts. Ghost v5.82.2 and v5.82.6 have been tested, both from the CLI as well as Docker images.

### Steps to Reproduce

1. Invite a new staff member as contributor
2. Accept the invitation and register – IMPORTANT: Set the name to have a single-letter first name, e.g. "J Doe" instead of "John Doe"
3. See the error

### Ghost Version

v5.82.6

### Node.js Version

18 LTS

### How did you install Ghost?

Ghost CLI

### Database type

MySQL 8

### Browser & OS version

Mac OS 14.4.1, latest Chrome and latest Safari tested

### Relevant log / error output

```shell
[2024-05-05 16:55:19] ERROR "GET /ghost/api/admin/posts/?formats=mobiledoc%2Clexical&limit=30&page=1&filter=status%3A%5Bdraft%2Cscheduled%2Cpublished%2Csent%5D%2Bauthors%3Aj" 400 12ms


Error parsing filter


Error ID:

415527a0-0b00-11ef-96dc-2bc1b8db7476


----------------------------------------


Error: Query Error: unrecognized text "j" in filter at char 24

at Child.applyDefaultAndCustomFilters (/var/lib/ghost/versions/5.82.2/node_modules/@tryghost/bookshelf-filter/lib/bookshelf-filter.js:66:23)

...ished,sent]+authors:j)+type:post

-----------------------^

at lexer.parseError (/var/lib/ghost/versions/5.82.2/node_modules/@tryghost/nql-lang/dist/parser.js:760:11)

at Object.next (/var/lib/ghost/versions/5.82.2/node_modules/@tryghost/nql-lang/dist/parser.js:625:25)

at Object.lex (/var/lib/ghost/versions/5.82.2/node_modules/@tryghost/nql-lang/dist/parser.js:635:22)

at lex (/var/lib/ghost/versions/5.82.2/node_modules/@tryghost/nql-lang/dist/parser.js:246:27)

at Parser.parse (/var/lib/ghost/versions/5.82.2/node_modules/@tryghost/nql-lang/dist/parser.js:259:26)

at exports.parse (/var/lib/ghost/versions/5.82.2/node_modules/@tryghost/nql-lang/lib/nql.js:18:44)

at api.parse (/var/lib/ghost/versions/5.82.2/node_modules/@tryghost/nql/lib/nql.js:15:31)

at api.querySQL (/var/lib/ghost/versions/5.82.2/node_modules/@tryghost/nql/lib/nql.js:49:44)

at Builder.<anonymous> (/var/lib/ghost/versions/5.82.2/node_modules/@tryghost/bookshelf-filter/lib/bookshelf-filter.js:63:24)

at Object.query (/var/lib/ghost/versions/5.82.2/node_modules/bookshelf/lib/helpers.js:164:14)

at Child.query (/var/lib/ghost/versions/5.82.2/node_modules/bookshelf/lib/model.js:1387:22)

at Child.applyDefaultAndCustomFilters (/var/lib/ghost/versions/5.82.2/node_modules/@tryghost/bookshelf-filter/lib/bookshelf-filter.js:56:22)

at Function.getFilteredCollection (/var/lib/ghost/versions/5.82.2/core/server/models/base/plugins/filtered-collection.js:13:32)

at Function.findPage (/var/lib/ghost/versions/5.82.2/core/server/models/base/plugins/crud.js:83:41)

at PostsService.browsePosts (/var/lib/ghost/versions/5.82.2/node_modules/@tryghost/posts-service/lib/PostsService.js:81:44)

at Object.query (/var/lib/ghost/versions/5.82.2/core/server/api/endpoints/posts.js:73:33)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by Tanu1201** [comment] 2024-05-14 04:24
Hey, I am Tanu sharma having 2 year of exp in SDE field can I take this issue?

**Comment by StanTraykov** [comment] 2024-06-30 16:30
Can confirm with current Ghost(Pro) trial; disagree somewhat with the 'low' categorization. It's stressful to a new user as the error message is so unrelated as to cause general alarm of having broken everything :). Once the cause is known (thanks for submitting this issue!), it can be resolved easily for the existing user.

**Comment by cathysarisky** [comment] 2024-10-08 18:03
This looks to be deep within @tryghost/nql-lang...

**Comment by vikaspotluri123** [comment] 2024-10-08 18:48
Speaking of which... I'm pretty sure this is a duplicate of https://github.com/TryGhost/NQL/issues/20

**Comment by cathysarisky** [comment] 2024-10-08 18:53
Agreed. Should retitle this issue “bad slugs generated on user creation”…. Sent from my iPhoneOn Oct 8, 2024, at 2:48 PM, Vikas Potluri ***@***.***> wrote:﻿
Speaking of which... I'm pretty sure this is a duplicate of TryGhost/NQL#20

**Closed** 2024-10-17 15:35 UTC
Labels: needs:triage, P4 - Low
