### ISSUE TITLE
Members Cookie ghost-members-ssr not found

### ISSUE THREAD

**Issue by Xunzhuo** [TryGhost/Ghost#12796] opened 2021-03-20 09:09 UTC
Welcome to Ghost's GitHub repo! 👋🎉

We use GitHub only for bug reports 🐛

Anything else should be posted to https://forum.ghost.org 👫

🚨For support, help & questions use https://forum.ghost.org/c/help
💡For feature requests & ideas you can post and vote on https://forum.ghost.org/c/Ideas

If your issue is with Ghost CLI, please report it on the CLI repo ➡️ https://github.com/TryGhost/Ghost-CLI/issues/new.

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

![image](https://user-images.githubusercontent.com/48784001/111864948-fac53b80-899e-11eb-98dc-33b721c58679.png)

![image](https://user-images.githubusercontent.com/48784001/111864960-031d7680-899f-11eb-811e-6c7cd35454ae.png)

![image](https://user-images.githubusercontent.com/48784001/111864971-10d2fc00-899f-11eb-95d2-03dc54cd6406.png)

### To Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version:
* Node Version:
* Browser/OS:
* Database:

**Comment by khassel** [comment] 2021-03-20 22:39
duplicate of #12793

**Closed** 2021-03-21 07:47 UTC
