### ISSUE TITLE
Undefined binding(s) detected on setup

### ISSUE THREAD

**Issue by sptdigital** [TryGhost/Ghost#9228] opened 2017-11-09 13:29 UTC
### Issue Summary

Unable to finish setup, after entering details, the following message is returned ...

All subsequent logins fail. Occurs after installing from source and using ghost-cli.
Clicking "Last Step: Invite your team" results in the following error message ...

"Undefined binding(s) detected when compiling SELECT query: select `clients`.* from `clients` where `clients`.`slug` = ? limit ?"

### Steps to Reproduce

1. Setup run as normal, out of the box.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: v1.17.0
* Node Version: v6.12.0
* Browser/OS: Windows 10 & Google Chrome
* Database: MySQL 5.6

**Comment by kevinansfield** [comment] 2017-11-09 14:19
@sptdigital closing this as a duplicate of #8613. There is a fix for the server-side error going out in the next Ghost release. If you still see a problem after upgrading please reply and we can look into it further.

**Closed by kevinansfield** 2017-11-09 14:19 UTC

**Comment by sptdigital** [comment] 2017-11-13 12:05
I am now seeing a different error. When it would normally take you to the 2nd part of the setup, it displays "Access Denied" before redirecting you to the login page. If you login it will start to load up "Your Stories" before redirecting back to the login page again.

**Comment by kirrg001** [comment] 2017-11-13 20:25
@kevinansfield any idea?

**Comment by sptdigital** [comment] 2017-11-14 14:28
Is there any session or cookie variables I could dump out to help with debugging?

**Comment by sptdigital** [comment] 2017-11-20 10:37
I tried updating to 1.17.3 and I can now login successfully. I will test all other functionality today. Thank you for your help.
