### ISSUE TITLE
Display invited team member immediately

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost#8647] opened 2017-07-01 12:38 UTC
### Issue Summary

When invitation is sent to new team member you have to click away from team menu and go back to see new member on the list.

Ghost: beta.2

**Comment by kevinansfield** [comment] 2017-07-07 08:15
Hey @PaszaVonPomiot 👋 Thanks for reporting.

There does seem to be a bit of an issue here but it seems a little deeper than the list not being auto-updated. I have seen two scenarios so far:

1. 500 response from Ghost - takes a while for the modal to close but the invite list is automatically updated
2. 502 response from proxy - takes even longer for the modal to close but the list isn't auto-updated, clicking away then back sometimes shows the invite depending on whether the request was actually handled by Ghost

For some reason my local install isn't sending mail now but it was working before 😖 Once I have that sorted out I'll test the successful path

**Comment by kevinansfield** [comment] 2017-07-07 15:09
@PaszaVonPomiot I've now tested this with a successful invite and the newly invited user was immediately added to the "Invited users" list when the modal closed itself.

Can you double-check please to see if the issue is related to a failed request or if there's some other factor to add to the reproduction steps?

<img width="1209" alt="screen shot 2017-07-07 at 16 06 25" src="https://user-images.githubusercontent.com/415/27963986-9a314c18-632e-11e7-8965-3c92e0f69703.png">

**Comment by PaszaVonPomiot** [comment] 2017-07-07 20:54
![image](https://user-images.githubusercontent.com/5560454/27975710-9e91afb6-6363-11e7-8886-086e8a41aad7.png)

**Comment by PaszaVonPomiot** [comment] 2017-07-11 23:28
So I finally managed to replicate it and it appears that when there is an error with sending email it will not update the list immediatelly. In my case I got following error 500 that probably prevented the list from updating:
`{"errors":[{"message":"Error sending email: The server has encountered an error. Please check your email settings and resend the invitation.","errorType":"EmailError"}]}`

When I click away from team page and go back then new invitee appears.

**Comment by PaszaVonPomiot** [comment] 2017-07-12 13:36
I can confirm now that after fixing mail configuration users are displayed immediately.

**Comment by JohnONolan** [comment] 2017-07-31 11:57
Glad you got to the bottom of it!

**Closed by JohnONolan** 2017-07-31 11:57 UTC
