### ISSUE TITLE
Ctrl+S doesn't work on the latest Chrome

### ISSUE THREAD

**Issue by alexbagirov** [TryGhost/Ghost#6259] opened 2015-12-23 11:02 UTC
Hi!

It seems that Ctrl+S combination doesn't save the article and opens Chrome save page dialogue.
It still works on Firefox but not on Chrome. Any solution?

Alex

**Comment by ErisDS** [comment] 2015-12-23 11:34
Hi @alexbagirov, this issue is not reproducible from the info you have provided, please could you update to include all the relevant details? There is a [bug report template](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs) in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md) that should give you a good idea what sorts of info to include.

**Comment by alexbagirov** [comment] 2015-12-23 13:09
Hi @ErisDS. Sure. Here's what I have. Let's go through the template :smiley: 

### Issue Summary

When using **Ctrl+S** hotkey in Chrome, Ghost doesn't save the article but opens savepage window.

### Steps to Reproduce
Open your editor in latest Chrome and hit **Ctrl+S**.

### Technical Details

* Ghost Version: 0.7.4 (the same for all downto 0.7.0)
* Client OS: Windows 10
* Browser: Google Chrome 47.0.2526.106 m

### Screencast
![ghost](https://cloud.githubusercontent.com/assets/6885864/11977006/29f661c0-a9a0-11e5-9339-3173ee6b5f51.gif)
_That's what happens when I edit article in the editor and try to save it using shortcut._

**Comment by ErisDS** [comment] 2016-01-04 10:03
@alexbagirov Can you test this out in an incognito window without any extensions enabled? I've checked this out on a Win 7 machine with the exact same Chrome version, and cannot reproduce. It may be a Windows 10 specific thing but it would be good to rule out other causes first.

Can anyone with Win 10 reproduce this?

**Comment by AlexKVal** [comment] 2016-01-04 16:09
`Windows 10 Pro`
`ghost@0.7.4`
`Chrome 47.0.2526.106 m`
`Ctrl`+`S` works fine. As it should. It saves posts.
:sparkle:

**Comment by alexbagirov** [comment] 2016-01-07 11:54
@ErisDS I've just checked it. Works fine in incognito :disappointed:

**Comment by ErisDS** [comment] 2016-01-07 12:43
@alexbagirov Thanks for getting back to us. I recommend going through your extensions disabling one-by-one to identify which one it is as it would be great to know.

**Comment by ErisDS** [comment] 2016-01-09 16:35
Going to close this in the meantime, as it's unlikely we can fix it.

**Closed by ErisDS** 2016-01-09 16:35 UTC

**Comment by alexbagirov** [comment] 2016-01-26 15:07
Hi, @ErisDS. Today I've tried to look up for my extensions and I've found the problem.
That is caused by [this](https://chrome.google.com/webstore/detail/snipandshare/adleiklellkmjhmnnoccodmonjdmbhhi?utm_source=chrome-app-launcher-info-dialog) one but I don't know why does it open this window as it shouldn't (that is a screenshot app actually :smiley:). Anyway, that's the problem cause.
