### ISSUE TITLE
Gallery not properly styled on the website

### ISSUE THREAD

**Issue by ltribolet** [TryGhost/Ghost#9858] opened 2018-09-08 15:26 UTC
### Issue Summary

When adding a gallery to post, it doesn't get styled properly on the website. Every photo are at their max height and constrained by post content width.

### To Reproduce

1. Add a gallery
2. Go on preview or published post
3. See unstyled gallery

Can be seen here: https://blog.tribolet.fr/p/caac7644-d323-4ae4-93c2-19bacaf3dcd0/

https://screenshots.firefox.com/V85Omqxk14VAhBKA/blog.tribolet.fr

### Technical details:

* Ghost Version: 2.1.1
* Node Version: v6.14.4
* Browser/OS: Firefox 63.0b4 (64-bit) and Chrome 69.0.3497.81 (Official Build) (64-bit) / Windows 10
* Database: mysql

**Comment by acburdine** [comment] 2018-09-09 10:55
@ltribolet based on that post it _looks_ like you're using Casper, which should have image gallery support. However, I don't see any of the styles for the gallery images in your theme's CSS, which leads me to believe you're using an outdated version of Casper or a fork of it. Either way, you will need to update to the latest version of Casper in order to get the changes necessary for galleries.

Going to close this as the issue should be fixed with an update of Casper (Use the [forum](https://forum.ghost.org) for help if you run into issues updating Casper). If you find that the issue is not fixed after updating Casper, we can reopen this and investigate further 😄

**Closed by acburdine** 2018-09-09 10:55 UTC

**Comment by ltribolet** [comment] 2018-09-09 14:27
Do I need to manually update Casper theme even while using `ghost update`? Because I don't remember doing any customization to this theme.
