### ISSUE TITLE
Error when applying complimentary plan to member

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#11765] opened 2020-04-22 11:58 UTC
Originally reported at https://forum.ghost.org/t/complimentary-premium-plan-return-an-error/13738/1

> The only problem I have at the moment is in the complimentary Premium Plan. When I select a member, change the toggle and hit save it return this.
>
> Internal server error, cannot edit a member. Cannot read property ‘id’ of undefined
> But I’m able to add notes change the name and save just not a complimentary option.

```
TypeError: Cannot read property 'id' of undefined
        at StripePaymentProcessor.setComplimentarySubscription (/home/ghost/node_modules/@tryghost/members-api/lib/stripe/index.js:252:45)
```

(Internal discussion for future reference https://ghost.slack.com/archives/C02G9E68C/p1587559818050500)

**Comment by kevinansfield** [comment] 2020-04-28 11:59
There appear to be two causes for this so far:

1. If the monthly/yearly price is set to `0` we have a hash collision with plan identifiers that results in the complimentary plan not being created
2. Something within the upgrade process resulting in the complimentary plan not being created

**Comment by allouis** [comment] 2020-06-12 17:21
This is in progress in this WIP PR: https://github.com/TryGhost/Members/pull/167/files

Was a little slower than I'd have liked due to looking at the new "Prices" from Stripe and trying to use that, I think it's worth it though as this cleans up a lot of things!

**Comment by allouis** [comment] 2020-06-16 12:42
Closing in favour of https://github.com/TryGhost/Members/issues/168

**Comment by matthanley** [comment] 2020-06-25 08:11
Repro case from @kevinansfield:

> My repro steps:
> 1. change yearly pricing to 0 + save
> 2. change currency to one not used before + save
> 3. create a new member
> 4. try to apply complimentary plan

Monthly/yearly plans set to zero-value isn't a valid use-case with the current plan implementation, so this can be fixed with additional validation on plan prices.

**Comment by allouis** [comment] 2020-06-25 09:07
https://stripe.com/docs/currencies#minimum-and-maximum-charge-amounts <-- resource for when we do validation

**Comment by ErisDS** [comment] 2020-06-25 11:09
The solution to this should be validating that the values are not < 1. This works for all currencies we support. There will be a larger refactor of currency support soon.

**Comment by allouis** [comment] 2020-07-03 08:39
The [Ghost API](https://github.com/TryGhost/Ghost/pull/11976) & [Admin](https://github.com/TryGhost/Ghost-Admin/pull/1625) no longer allow creating plans with an amount of 0. So future installs/setups should not run into this problems.

We have not removed existing 0 amount plans, but they may still cause issues with Complimentary plans, the fix would be to update your plans to have an amount of 1 or more :relaxed:

**Closed by allouis** 2020-07-03 08:39 UTC
Labels: bug, members

**Comment by sbounmy** [comment] 2020-08-04 13:45
This is still occuring for me on `3.27.0`. Any idea ?
Plan is on 5e / month
![Image of screensot](https://i.ibb.co/Jxtt2nV/Screenshot-2020-08-04-at-15-37-05.jpg)

**Comment by sbounmy** [comment] 2020-08-18 08:47
@allouis bump ! still occuring with `3.29.1`

I made sure my plan's price is > 0
![Screenshot 2020-08-18 at 10 45 46](https://user-images.githubusercontent.com/159814/90491378-23066680-e140-11ea-807f-b1a9cc938dc6.jpg)

**Comment by allouis** [comment] 2020-08-19 11:23
@sbounmy If you think this is still a bug on the latest version, would you be able to open an issue with reproducible steps and stack traces from the errors and any other useful info? Thanks :relaxed:
