### ISSUE TITLE
Unsplash button not working

### ISSUE THREAD

**Issue by timscha** [TryGhost/Ghost#8909] opened 2017-08-16 09:10 UTC
### Issue Summary

I updated to Ghost 1.6 and tried the Unsplash button. I created a new application which got all rights.
When I click on the button in the editor I see the following screen.

Testetd with latest versions of Chrome and Firefox

### Steps to Reproduce

1. Create a application on Unsplash, added them to the options in the Apps.
2. Click on the Unsplash button

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 1.6.0
* Node Version: 6.11.2
* Browser/OS:  Chrome / Firefox Latest Versions
* Database:  MariaDB 10.2
![screenshot 5](https://user-images.githubusercontent.com/4650393/29356115-77595dde-8273-11e7-881c-1142f3e58bf4.png)

**Comment by kevinansfield** [comment] 2017-08-16 09:11
Duplicate of #8905 - fix is already in master, will be in the next release.

**Closed by kevinansfield** 2017-08-16 09:11 UTC
