### ISSUE TITLE
Custom Config Support

### ISSUE THREAD

**Issue by andrewmur** [TryGhost/Ghost#9428] opened 2018-01-26 14:40 UTC
### Issue Summary

Themes developers Struggle with the inventing workarounds in order to pass custom variables and use those into the templates _(via jquery, ghost hacking, apps, etc.)_.

Please Guys, pass through `custom` property via `@config` which would be dedicated object to any custom variables, that developers might use across their templates in a simple convenient way e.g. `{{@config.custom.social.instagram}}` or through the dedicated helper `{{@misc.instagram}}`

### Steps to Reproduce

1. open theme _package.json_
2. add any property in `"config": { "foo": "bar" }`
3. access it in template `{{@config.foo}}`

**Actual:**
Only  `{{@config.posts_per_page}}` would be passed 😭

**Expected**
All properties mentioned in dedicated scope has to be available 🌞

### Technical details:

* Ghost Version: 1.4.1
* Node Version: 6.10.0
* Browser/OS: All

**Comment by ErisDS** [comment] 2018-01-26 14:45
Duplicate of #9375

**Closed by ErisDS** 2018-01-26 14:45 UTC
