### ISSUE TITLE
Bug: Importer - archives with invites are not mapped

### ISSUE THREAD

**Issue by cobbspur** [TryGhost/Ghost#8512] opened 2017-06-01 11:16 UTC
### Issue Summary

If you invite a user on alpha then create an export in labs you get a JSON file with invites. These invites are not then mapped anywhere during import. 

For lts exports the users are still in the users block of the export and added as locked users requiring a password reset to activate them.  

### Technical details:

* Ghost Version: master e2dcdd28661caaae743b12c0c9e199f328b50ad6

**Comment by kirrg001** [comment] 2018-08-19 21:40
Closing. This is actually not a bug, it's a missing feature. We do not import invites. Let's wait if people vote for it on forum.ghost.org :)

**Closed by kirrg001** 2018-08-19 21:40 UTC
Labels: help wanted, importer, optimisation, server
