### ISSUE TITLE
Navigation strips the subdirectory name while trying to create a navigation item

### ISSUE THREAD

**Issue by truekasun** [TryGhost/Ghost#19795] opened 2024-03-04 18:48 UTC
### Issue Summary

Navigation strips the subdirectory name when trying to create a navigation item.

Let's say:
- **Site URL:** https://domain.com/blog

When trying to create a navigation item with the target "https://domain.com/blog/about",
The editor strips away the word "blog" from the navigation item URL (as soon as the user clicks away from the URL field)

### Steps to Reproduce

https://github.com/TryGhost/Ghost/assets/278469/f6ad573c-44d9-4196-8a84-981f706b27e4

### Ghost Version

5.80.0

### Node.js Version

18.19.1

### How did you install Ghost?

Self-hosted | Subdirectory | Ubuntu 20.04.6 (LTS)

### Database type

MySQL 8

### Browser & OS version

Microsoft Edge 122.0.2365.52 | Mozilla Firefox 123.0

### Relevant log / error output

```shell
No browser console errors are present
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment] 2024-04-01 13:55
Hey there, thank you so much for the bug report.

That does look like something that shouldn't happen! A PR to fix this issue would be very welcome 🙂

**Comment by truekasun** [comment] 2024-07-30 03:46
**Additional info:** This is happening on both Primary & Secondary Navigation options.

**Comment by ningthoujamSwamikumar** [comment] 2024-10-07 15:38
Interested. Anyone working on this? Please assign this to me. I will work on it. Thanks.

**Comment by cathysarisky** [comment] 2024-11-01 11:43
Hey @truekasun ,

Thanks for the video - that made the problem super clear.  Or at least, it should have.  I am trying to replicate this, and I can't.  

Would you mind checking on Ghost 5.98 or 5.97 to see if the problem is still there?  When I set up Ghost as a subsite, the url fields all include the subsite path, and editing or adding new ones doesn't stripe the path, in my setup.

**Comment by truekasun** [comment] 2024-11-01 12:37
> Hey @truekasun ,
> 
> Thanks for the video - that made the problem super clear.  Or at least, it should have.  I am trying to replicate this, and I can't.  
> 
> Would you mind checking on Ghost 5.98 or 5.97 to see if the problem is still there?  When I set up Ghost as a subsite, the url fields all include the subsite path, and editing or adding new ones doesn't stripe the path, in my setup.

Hi @cathysarisky ,

Sure, I'll try this and will update the findings here. I still have a few environments that I haven't updated yet.

**Comment by truekasun** [comment] 2024-11-01 14:31
@cathysarisky @daniellockyer 
I have checked this issue on v5.98.1 and it seems it's **already fixed**. Guess it's safe to close this issue.

Thank you @cathysarisky for giving it a shot.

**Closed** 2024-11-03 03:52 UTC
Labels: bug
