### ISSUE TITLE
Cannot update from 2.38.1 to 3.17.1 due to 'ER_NO_SUCH_TABLE' error

### ISSUE THREAD

**Issue by andrewmatveychuk** [TryGhost/Ghost#11855] opened 2020-05-27 18:19 UTC
### Issue Summary

Cannot update from 2.38.1 to 3.17.1 due to 'ER_NO_SUCH_TABLE' error while using 'ghost update'.

`Message: show columns from 'emails' - ER_NO_SUCH_TABLE: Table 'ghost_production.emails' doesn't exist`

### To Reproduce

Run 'ghost update'

Part of the output containing the error:

```
? Are you sure you want to proceed with migrating to Ghost 3.17.1? Yes
✔ Updating to a major version
+ sudo systemctl stop ghost_138-68-140-172
✔ Stopping Ghost
✔ Linking latest Ghost and recording versions
+ sudo systemctl start ghost_138-68-140-172
+ sudo systemctl stop ghost_138-68-140-172
✖ Restarting Ghost
A GhostError occurred.

Message: show columns from `emails` - ER_NO_SUCH_TABLE: Table 'ghost_production.emails' doesn't exist
Suggestion: journalctl -u ghost_138-68-140-172 -n 50

Debug Information:
    OS: Ubuntu, v20.04 LTS
    Node Version: v10.20.1
    Ghost Version: 3.17.1
    Ghost-CLI Version: 1.14.0
    Environment: production
    Command: 'ghost update'

Additional log info available in: /home/ghost-mgr/.ghost/logs/ghost-cli-debug-2020-05-27T14_38_53_512Z.log

? Unable to upgrade Ghost from v2.38.1 to v3.17.1. Would you like to revert back to v2.38.1? Yes
+ sudo systemctl is-active ghost_138-68-140-172
+ sudo systemctl reset-failed ghost_138-68-140-172
✔ Checking system Node.js version
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
✔ Checking for available migrations
✔ Checking for latest Ghost version
ℹ Downloading and updating Ghost [skipped]
+ sudo /var/www/ghost/current/node_modules/.bin/knex-migrator-rollback --force --v 2.38.1 --mgpath /var/www/ghost/current
✖ Rolling back database migrations
A ProcessError occurred.

Message: It's not possible to roll back database changes from 3.17.1 to 2.38.1. Please restore from a backup instead

Debug Information:
    OS: Ubuntu, v20.04 LTS
    Node Version: v10.20.1
    Ghost Version: 3.17.1
    Ghost-CLI Version: 1.14.0
    Environment: production
    Command: 'ghost update'
```

#### Versions

```
Debug Information:
    OS: Ubuntu, v20.04 LTS
    Node Version: v10.20.1
    Ghost Version: 2.38.1
    Ghost-CLI Version: 1.14.0
    Environment: production
    Command: 'ghost doctor'

```
#### Log output

```
ghost-mgr@ghost-s-1vcpu-1gb-lon1-01:/var/www/ghost$ cat  /home/ghost-mgr/.ghost/logs/ghost-cli-debug-2020-05-27T14_38_53_512Z.log
Debug Information:
    OS: Ubuntu, v20.04 LTS
    Node Version: v10.20.1
    Ghost Version: 3.17.1
    Ghost-CLI Version: 1.14.0
    Environment: production
    Command: 'ghost update'
Message: show columns from `emails` - ER_NO_SUCH_TABLE: Table 'ghost_production.emails' doesn't exist
Suggestion: journalctl -u ghost_138-68-140-172 -n 50
Stack: Error: show columns from `emails` - ER_NO_SUCH_TABLE: Table 'ghost_production.emails' doesn't exist
    at Server.server.close (/usr/local/lib/node_modules/ghost-cli/lib/utils/port-polling.js:38:28)
    at Object.onceWrapper (events.js:286:20)
    at Server.emit (events.js:198:13)
    at emitCloseNT (net.js:1619:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

#### Debug information

```
ghost-mgr@ghost-s-1vcpu-1gb-lon1-01:/var/www/ghost$ ghost run
The `ghost run` command is used by the configured Ghost process manager and for debugging. If you're not running this to debug something, you should run `ghost start` instead.
+ sudo node current/index.js
[2020-05-27 14:42:28] INFO Blog is in maintenance mode.
[2020-05-27 14:42:28] INFO Ghost is running in production...
[2020-05-27 14:42:28] INFO Your site is now available on https://andrewmatveychuk.com/
[2020-05-27 14:42:28] INFO Ctrl+C to shut down
[2020-05-27 14:42:28] INFO Ghost boot 4.109s
[2020-05-27 14:42:28] INFO Creating database backup
[2020-05-27 14:42:28] INFO Database backup written to: /var/www/ghost/content/data/andrews-blog.ghost.2020-05-27-14-42-28.json
[2020-05-27 14:42:28] WARN Adding table: posts_meta
[2020-05-27 14:42:28] INFO Adding 3 entries to posts_meta
[2020-05-27 14:42:28] INFO Dropping posts.meta_title
[2020-05-27 14:42:29] INFO Dropping posts.meta_description
[2020-05-27 14:42:30] INFO Dropping posts.og_image
[2020-05-27 14:42:31] INFO Dropping posts.og_title
[2020-05-27 14:42:32] INFO Dropping posts.og_description
[2020-05-27 14:42:33] INFO Dropping posts.twitter_image
[2020-05-27 14:42:33] INFO Dropping posts.twitter_title
[2020-05-27 14:42:34] INFO Dropping posts.twitter_description
[2020-05-27 14:42:35] INFO Adding posts.type
[2020-05-27 14:42:35] INFO Updating posts, setting "type" column to "page" where "page" column is "true"
[2020-05-27 14:42:35] INFO Updating posts, setting "type" column to "post" where "page" column is "false"
[2020-05-27 14:42:35] INFO Removing posts.page
[2020-05-27 14:42:36] ERROR "GET /" 503 61ms

Site is currently undergoing maintenance, please wait a moment then retry.

Error ID:
    4e3dcb30-a028-11ea-be89-29c3fa4d4211

----------------------------------------

MaintenanceError: Site is currently undergoing maintenance, please wait a moment then retry.
    at new MaintenanceError (/var/www/ghost/versions/3.17.1/node_modules/ghost-ignition/lib/errors/index.js:162:23)
    at maintenance (/var/www/ghost/versions/3.17.1/core/server/web/shared/middlewares/maintenance.js:8:21)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:317:13)
    at /var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:275:10)
    at filterPrivateRoutes (/var/www/ghost/versions/3.17.1/core/frontend/apps/private-blogging/lib/middleware.js:54:20)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:317:13)
    at /var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:275:10)
    at checkIsPrivate (/var/www/ghost/versions/3.17.1/core/frontend/apps/private-blogging/lib/middleware.js:40:20)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:317:13)
    at /var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:275:10)
    at servePublicFile (/var/www/ghost/versions/3.17.1/core/server/web/site/middleware/serve-public-file.js:75:20)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:317:13)

[2020-05-27 14:42:36] WARN Table labels does not exist
[2020-05-27 14:42:36] WARN Table emails does not exist
[2020-05-27 14:42:36] WARN Table emails does not exist
[2020-05-27 14:42:36] WARN Table emails does not exist
[2020-05-27 14:42:36] WARN Table emails does not exist
[2020-05-27 14:42:36] WARN Table emails does not exist
[2020-05-27 14:42:36] WARN Table emails does not exist
[2020-05-27 14:42:36] WARN Table emails does not exist
[2020-05-27 14:42:36] WARN Table emails does not exist
[2020-05-27 14:42:36] INFO Updating posts, setting '' in mobiledoc to 'null'
[2020-05-27 14:42:36] INFO Updating posts, setting '' in html to 'null'
[2020-05-27 14:42:36] INFO Updating posts, setting '' in comment_id to 'null'
[2020-05-27 14:42:36] INFO Updating posts, setting '' in plaintext to 'null'
[2020-05-27 14:42:36] INFO Updating posts, setting '' in feature_image to 'null'
[2020-05-27 14:42:36] INFO Updating posts, setting '' in locale to 'null'
[2020-05-27 14:42:36] INFO Updating posts, setting '' in updated_by to 'null'
[2020-05-27 14:42:36] INFO Updating posts, setting '' in published_by to 'null'
[2020-05-27 14:42:36] INFO Updating posts, setting '' in custom_excerpt to 'null'
[2020-05-27 14:42:36] INFO Updating posts, setting '' in codeinjection_head to 'null'
[2020-05-27 14:42:36] INFO Updating posts, setting '' in codeinjection_foot to 'null'
[2020-05-27 14:42:36] INFO Updating posts, setting '' in custom_template to 'null'
[2020-05-27 14:42:36] INFO Updating posts, setting '' in canonical_url to 'null'
[2020-05-27 14:42:36] INFO Updating posts_meta, setting '' in og_image to 'null'
[2020-05-27 14:42:36] INFO Updating posts_meta, setting '' in og_title to 'null'
[2020-05-27 14:42:36] INFO Updating posts_meta, setting '' in og_description to 'null'
[2020-05-27 14:42:36] INFO Updating posts_meta, setting '' in twitter_image to 'null'
[2020-05-27 14:42:36] INFO Updating posts_meta, setting '' in twitter_title to 'null'
[2020-05-27 14:42:36] INFO Updating posts_meta, setting '' in twitter_description to 'null'
[2020-05-27 14:42:36] INFO Updating posts_meta, setting '' in meta_title to 'null'
[2020-05-27 14:42:36] INFO Updating posts_meta, setting '' in meta_description to 'null'
[2020-05-27 14:42:36] INFO Updating posts_meta, setting '' in email_subject to 'null'
[2020-05-27 14:42:36] INFO Updating users, setting '' in profile_image to 'null'
[2020-05-27 14:42:36] INFO Updating users, setting '' in cover_image to 'null'
[2020-05-27 14:42:36] INFO Updating users, setting '' in bio to 'null'
[2020-05-27 14:42:36] INFO Updating users, setting '' in website to 'null'
[2020-05-27 14:42:36] INFO Updating users, setting '' in location to 'null'
[2020-05-27 14:42:36] INFO Updating users, setting '' in facebook to 'null'
[2020-05-27 14:42:36] INFO Updating users, setting '' in twitter to 'null'
[2020-05-27 14:42:36] INFO Updating users, setting '' in accessibility to 'null'
[2020-05-27 14:42:36] INFO Updating users, setting '' in locale to 'null'
[2020-05-27 14:42:36] INFO Updating users, setting '' in meta_title to 'null'
[2020-05-27 14:42:36] INFO Updating users, setting '' in meta_description to 'null'
[2020-05-27 14:42:36] INFO Updating users, setting '' in tour to 'null'
[2020-05-27 14:42:36] INFO Updating users, setting '' in updated_by to 'null'
[2020-05-27 14:42:36] INFO Updating roles, setting '' in description to 'null'
[2020-05-27 14:42:36] INFO Updating roles, setting '' in updated_by to 'null'
[2020-05-27 14:42:36] INFO Updating permissions, setting '' in object_id to 'null'
[2020-05-27 14:42:36] INFO Updating permissions, setting '' in updated_by to 'null'
[2020-05-27 14:42:36] INFO Updating settings, setting '' in value to 'null'
[2020-05-27 14:42:36] INFO Updating settings, setting '' in updated_by to 'null'
[2020-05-27 14:42:36] INFO Updating tags, setting '' in description to 'null'
[2020-05-27 14:42:36] INFO Updating tags, setting '' in feature_image to 'null'
[2020-05-27 14:42:36] INFO Updating tags, setting '' in parent_id to 'null'
[2020-05-27 14:42:36] INFO Updating tags, setting '' in meta_title to 'null'
[2020-05-27 14:42:36] INFO Updating tags, setting '' in meta_description to 'null'
[2020-05-27 14:42:36] INFO Updating tags, setting '' in updated_by to 'null'
[2020-05-27 14:42:36] INFO Updating apps, setting '' in updated_by to 'null'
[2020-05-27 14:42:36] INFO Updating app_settings, setting '' in value to 'null'
[2020-05-27 14:42:36] INFO Updating app_settings, setting '' in updated_by to 'null'
[2020-05-27 14:42:36] INFO Updating app_fields, setting '' in value to 'null'
[2020-05-27 14:42:36] INFO Updating app_fields, setting '' in updated_by to 'null'
[2020-05-27 14:42:36] INFO Updating invites, setting '' in updated_by to 'null'
[2020-05-27 14:42:36] INFO Updating webhooks, setting '' in name to 'null'
[2020-05-27 14:42:36] INFO Updating webhooks, setting '' in secret to 'null'
[2020-05-27 14:42:36] INFO Updating webhooks, setting '' in integration_id to 'null'
[2020-05-27 14:42:36] INFO Updating webhooks, setting '' in last_triggered_status to 'null'
[2020-05-27 14:42:36] INFO Updating webhooks, setting '' in last_triggered_error to 'null'
[2020-05-27 14:42:36] INFO Updating webhooks, setting '' in updated_by to 'null'
[2020-05-27 14:42:36] INFO Updating integrations, setting '' in icon_image to 'null'
[2020-05-27 14:42:36] INFO Updating integrations, setting '' in description to 'null'
[2020-05-27 14:42:36] INFO Updating integrations, setting '' in updated_by to 'null'
[2020-05-27 14:42:36] INFO Updating api_keys, setting '' in role_id to 'null'
[2020-05-27 14:42:36] INFO Updating api_keys, setting '' in integration_id to 'null'
[2020-05-27 14:42:36] INFO Updating api_keys, setting '' in last_seen_version to 'null'
[2020-05-27 14:42:36] INFO Updating api_keys, setting '' in updated_by to 'null'
[2020-05-27 14:42:36] INFO Updating mobiledoc_revisions, setting '' in mobiledoc to 'null'
[2020-05-27 14:42:36] WARN Table 'members' does not have column 'uuid'
[2020-05-27 14:42:36] INFO Updating members, setting '' in name to 'null'
[2020-05-27 14:42:36] INFO Updating members, setting '' in note to 'null'
[2020-05-27 14:42:36] WARN Table 'members' does not have column 'geolocation'
[2020-05-27 14:42:36] INFO Updating members, setting '' in updated_by to 'null'
[2020-05-27 14:42:36] INFO Updating members_stripe_customers, setting '' in name to 'null'
[2020-05-27 14:42:36] INFO Updating members_stripe_customers, setting '' in email to 'null'
[2020-05-27 14:42:36] INFO Updating members_stripe_customers, setting '' in updated_by to 'null'
[2020-05-27 14:42:36] INFO Updating members_stripe_customers_subscriptions, setting '' in default_payment_card_last4 to 'null'
[2020-05-27 14:42:36] INFO Updating members_stripe_customers_subscriptions, setting '' in updated_by to 'null'
[2020-05-27 14:42:36] INFO Updating actions, setting '' in resource_id to 'null'
[2020-05-27 14:42:36] INFO Updating actions, setting '' in context to 'null'
[2020-05-27 14:42:37] INFO Starting re-generation of posts html.
[2020-05-27 14:42:37] INFO Finished re-generation of posts html.
[2020-05-27 14:42:37] INFO Adding 12 entries to members
[2020-05-27 14:42:37] INFO Dropping table: subscribers
[2020-05-27 14:42:37] INFO Updating labs setting removing subscribers (was true) settings members to true
[2020-05-27 14:42:37] INFO Adding posts.send_email_when_published
[2020-05-27 14:42:37] WARN Adding posts_meta.email_subject
[2020-05-27 14:42:37] INFO Adding permissions fixtures for email_previews
[2020-05-27 14:42:37] INFO Adding members.subscribed
[2020-05-27 14:42:37] INFO Adding table: emails
[2020-05-27 14:42:37] INFO Adding permissions fixtures for email
[2020-05-27 14:42:38] INFO Adding members.uuid
[2020-05-27 14:42:38] INFO Adding uuid field value to 12 members.
[2020-05-27 14:42:38] WARN (0/3) Adding permissions fixtures for email
[2020-05-27 14:42:38] WARN Adding emails.error_data
[2020-05-27 14:42:38] INFO Adding members_stripe_customers_subscriptions.cancel_at_period_end
[2020-05-27 14:42:38] INFO Adding table: labels
[2020-05-27 14:42:38] ERROR "GET /" 503 9ms

Site is currently undergoing maintenance, please wait a moment then retry.

Error ID:
    4f9fcc30-a028-11ea-be89-29c3fa4d4211

----------------------------------------

MaintenanceError: Site is currently undergoing maintenance, please wait a moment then retry.
    at new MaintenanceError (/var/www/ghost/versions/3.17.1/node_modules/ghost-ignition/lib/errors/index.js:162:23)
    at maintenance (/var/www/ghost/versions/3.17.1/core/server/web/shared/middlewares/maintenance.js:8:21)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:317:13)
    at /var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:275:10)
    at filterPrivateRoutes (/var/www/ghost/versions/3.17.1/core/frontend/apps/private-blogging/lib/middleware.js:54:20)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:317:13)
    at /var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:275:10)
    at checkIsPrivate (/var/www/ghost/versions/3.17.1/core/frontend/apps/private-blogging/lib/middleware.js:40:20)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:317:13)
    at /var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:275:10)
    at servePublicFile (/var/www/ghost/versions/3.17.1/core/server/web/site/middleware/serve-public-file.js:75:20)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:317:13)

[2020-05-27 14:42:38] INFO Adding table: members_labels
[2020-05-27 14:42:38] WARN Permission for read:identity already removed
[2020-05-27 14:42:38] INFO Removing permissions fixtures for member_signin_urls
[2020-05-27 14:42:38] WARN Removing members.geolocation
[2020-05-27 14:42:38] INFO Dropping table: members_labels
[2020-05-27 14:42:38] INFO Dropping table: labels
[2020-05-27 14:42:38] INFO Removing members_stripe_customers_subscriptions.cancel_at_period_end
[2020-05-27 14:42:38] INFO Removing emails.error_data
[2020-05-27 14:42:38] INFO Removing permissions fixtures for emails
[2020-05-27 14:42:38] INFO Removing members.uuid
[2020-05-27 14:42:38] INFO Removing permissions fixtures for emails
[2020-05-27 14:42:38] INFO Dropping table: emails
[2020-05-27 14:42:38] INFO Removing members.subscribed
[2020-05-27 14:42:39] INFO Removing permissions fixtures for email_previews
[2020-05-27 14:42:39] INFO Removing posts_meta.email_subject
[2020-05-27 14:42:39] INFO Removing posts.send_email_when_published
[2020-05-27 14:42:39] ERROR "GET /" 503 5ms

Site is currently undergoing maintenance, please wait a moment then retry.

Error ID:
    509d6610-a028-11ea-be89-29c3fa4d4211

----------------------------------------

MaintenanceError: Site is currently undergoing maintenance, please wait a moment then retry.
    at new MaintenanceError (/var/www/ghost/versions/3.17.1/node_modules/ghost-ignition/lib/errors/index.js:162:23)
    at maintenance (/var/www/ghost/versions/3.17.1/core/server/web/shared/middlewares/maintenance.js:8:21)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:317:13)
    at /var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:275:10)
    at filterPrivateRoutes (/var/www/ghost/versions/3.17.1/core/frontend/apps/private-blogging/lib/middleware.js:54:20)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:317:13)
    at /var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:275:10)
    at checkIsPrivate (/var/www/ghost/versions/3.17.1/core/frontend/apps/private-blogging/lib/middleware.js:40:20)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:317:13)
    at /var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:275:10)
    at servePublicFile (/var/www/ghost/versions/3.17.1/core/server/web/site/middleware/serve-public-file.js:75:20)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/ghost/versions/3.17.1/node_modules/express/lib/router/index.js:317:13)

[2020-05-27 14:42:40] WARN Can't connect to the bootstrap socket (localhost 8000) ECONNREFUSED
[2020-05-27 14:42:40] WARN Tries: 0
[2020-05-27 14:42:40] WARN Retrying...
[2020-05-27 14:42:40] WARN Can't connect to the bootstrap socket (localhost 8000) ECONNREFUSED
[2020-05-27 14:42:40] WARN Tries: 1
[2020-05-27 14:42:40] WARN Retrying...
[2020-05-27 14:42:40] WARN Can't connect to the bootstrap socket (localhost 8000) ECONNREFUSED
[2020-05-27 14:42:40] WARN Tries: 2
[2020-05-27 14:42:40] WARN Retrying...
[2020-05-27 14:42:40] WARN Can't connect to the bootstrap socket (localhost 8000) ECONNREFUSED
[2020-05-27 14:42:40] ERROR alter table `members_labels` add constraint `members_labels_member_id_foreign` foreign key (`member_id`) references `members` (`id`) - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'members_labels_member_id_foreign' are incompatible.

alter table `members_labels` add constraint `members_labels_member_id_foreign` foreign key (`member_id`) references `members` (`id`) - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'members_labels_member_id_foreign' are incompatible.

{"name":"2-add-members-labels-table.js"}
"Error occurred while executing the following migration: 2-add-members-labels-table.js"

Error ID:
    300

Error Code:
    UNKNOWN_CODE_PLEASE_REPORT

----------------------------------------

MigrationScriptError: alter table `members_labels` add constraint `members_labels_member_id_foreign` foreign key (`member_id`) references `members` (`id`) - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'members_labels_member_id_foreign' are incompatible.
    at MigrationScriptError.KnexMigrateError (/var/www/ghost/versions/3.17.1/node_modules/knex-migrator/lib/errors.js:7:26)
    at new MigrationScriptError (/var/www/ghost/versions/3.17.1/node_modules/knex-migrator/lib/errors.js:25:26)
    at /var/www/ghost/versions/3.17.1/node_modules/knex-migrator/lib/index.js:1055:19

Error: UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'member_id' and referenced column 'id' in foreign key constraint 'members_labels_member_id_foreign' are incompatible.
    at Query.Sequence._packetToError (/var/www/ghost/versions/3.17.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/var/www/ghost/versions/3.17.1/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/var/www/ghost/versions/3.17.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/var/www/ghost/versions/3.17.1/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/var/www/ghost/versions/3.17.1/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/var/www/ghost/versions/3.17.1/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/var/www/ghost/versions/3.17.1/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/var/www/ghost/versions/3.17.1/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    --------------------
    at Protocol._enqueue (/var/www/ghost/versions/3.17.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/var/www/ghost/versions/3.17.1/node_modules/mysql/lib/Connection.js:198:25)
    at /var/www/ghost/versions/3.17.1/node_modules/knex/lib/dialects/mysql/index.js:135:18
    at Promise._execute (/var/www/ghost/versions/3.17.1/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/var/www/ghost/versions/3.17.1/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/var/www/ghost/versions/3.17.1/node_modules/bluebird/js/release/promise.js:103:10)
    at Client_MySQL._query (/var/www/ghost/versions/3.17.1/node_modules/knex/lib/dialects/mysql/index.js:129:12)
    at Client_MySQL.query (/var/www/ghost/versions/3.17.1/node_modules/knex/lib/client.js:169:17)
    at Runner.query (/var/www/ghost/versions/3.17.1/node_modules/knex/lib/runner.js:134:36)
    at Runner.queryArray (/var/www/ghost/versions/3.17.1/node_modules/knex/lib/runner.js:231:31)
```

**Comment by andrewmatveychuk** [comment] 2020-05-27 18:22
@kevinansfield This one seems related to https://github.com/TryGhost/Ghost/issues/11597

**Comment by ErisDS** [comment] 2020-05-28 17:53
Closing as a duplicate of #11625

**Closed by ErisDS** 2020-05-28 17:53 UTC
