### ISSUE TITLE
Structured Data Testing Tool

### ISSUE THREAD

**Issue by eoboite** [TryGhost/Ghost#11682] opened 2020-03-21 16:39 UTC
I'm running version 3.11.0 of Ghost. I just stood up a new website yesterday, https://popupshopapp.com . When I test my site using the Structured Data Testing Tool, an error is reported **"ImageObject is not a known valid target type for the url property."** for the @type under logo.

Any way to resolve this issue?

**Comment by gargol** [comment] 2020-03-22 02:50
There was a similar topic raised some time ago on forum - https://forum.ghost.org/t/schema-error-a-value-for-the-url-field-is-required/9723/5 and the bugfix landed in master in version 3.10.0 with this commit - https://github.com/TryGhost/Ghost/commit/3f5daa60c82205b8538a6584b24a9d7ceda593c6. Can you get some more reproducible details for the error you are having?

Fyi, have run a test on the site you've provided and there were no errors - https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fpopupshopapp.com%20

**Comment by eoboite** [comment] 2020-03-22 02:55
I just clicked the link you sent https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fpopupshopapp.com%20  and the error appears on the right for the the website schema which is added by ghost.

I attached a photo highlighting the error.
![803AD740-F224-486D-B4FC-571D4487A3D9](https://user-images.githubusercontent.com/3681575/77241333-f5d07f00-6bc6-11ea-8b35-c5ce185dfa06.jpeg)

**Comment by gargol** [comment] 2020-03-22 03:21
Oh soz, overlooked that. Yes, then it definitely looks like something slipped through the bugfix I referred earlier.

**Comment by gargol** [comment] 2020-03-22 03:28
Weird, but something the person that will be trying to reproduce this might see as well. Was surprised I've missed an obvious red text with an error. And have pulled up the unclosed tab where I looked at it, here it is when I was looking at it:
![Screenshot from 2020-03-22 16-26-17](https://user-images.githubusercontent.com/675397/77241656-21e91000-6c5a-11ea-80ba-d28cb57131ba.png)

But, after a refresh have gotten the same error as above.

**Comment by eoboite** [comment] 2020-03-22 03:35
Ahhh gotcha. Yea that's weird.

 It looks like the object provided for url should be shifted up one level and that should solve the issue.

**Comment by daniellockyer** [comment] 2020-04-10 15:20
Hey @eoboite! :wave: 

I worked on fixing this last time and so I was sure this problem was fixed. I've taken a look at your site in the Structured Data Testing Tool and can't seem to see the issue now (pic below). Google do change their spec occasionally, but I think what you and @gargol were seeing before was a regression in their tool.

If you can still see the problem, feel free to comment here again but I'm going to close this for now :smile:

![2020-04-10-16:19:18](https://user-images.githubusercontent.com/964245/79001792-0ed5ab80-7b47-11ea-960e-c0fc8499787e.png)

**Closed by daniellockyer** 2020-04-10 15:20 UTC
Labels: bug, help wanted, server, themes
