### ISSUE TITLE
Lexical kg-cards missing on website after ghost update with zip

### ISSUE THREAD

**Issue by ASAMedia** [TryGhost/Ghost#18948] opened 2023-11-12 01:51 UTC
### Issue Summary

I updated my custom Ghost to version 5.71.2.
It runs fine in development via `yarn dev`, but upgrading the 5.70 docker with an .tgz file from `yarn archive` brings up some problems.
When editing existing posts (mobiledoc) and saving them with the new editor (lexical) ALL images and other kg-cards will not show up anymore on the website of this post.
There is not a single error in webconsole or `docker-compose logs -f` during/saving editing or while upgrading ghost.
When running the original 5.71 docker image or `yarn dev` everything runs fine without this issue.

~Looking into the sqlite database, I'll found that the lexical code is complete with the image.~

So it seems like an update problem, that I cant narrow down without some help.
Any idea how to fix this?

### Steps to Reproduce

1. create the following DOCKERFILE
``` 
FROM ghost:5.71.0-alpine
WORKDIR /var/lib/ghost
COPY ./ghost-5.71.2.tgz /var/lib
RUN apk add --no-cache git
USER node
RUN yarn --version
RUN yarn cache clean
RUN rm -rf node_modules
RUN yarn
RUN chmod -R 00775 /var/lib/ghost/content &&\
    ghost update --force --zip /var/lib/ghost-5.71.2.tgz
RUN chmod -R 00775 /var/lib/ghost/content
```
2. create the docker-compose.yml
```
version: '3.1'

services:

  lfg-ghost:
    build: .
    container_name: lfg-ghost
    restart: always
    ports:
      - 2368:2368
    volumes:
      -  ./content:/var/lib/ghost/content
      -  ./.env:/var/lib/ghost/.env
    environment:
      NODE_ENV: development
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
      url: 
      mail__transport: SMTP
      mail__from: 
      mail__options__service: SMTP
      mail__options__host: 
      mail__options__port: 587
      mail__options__auth__user: 
      mail__options__auth__pass: 
```
3. Download the release file from [here](https://github.com/ASAMedia/Ghost-LFG/releases/tag/5.71.2-lfg.19)
4. run `sudo docker-compose build`, `sudo docker-compose up -d` 

### Ghost Version

5.71.2

### Node.js Version

18

### How did you install Ghost?

docker-compose

### Database type

SQLite3

### Browser & OS version

Win 11/Ubuntu 20/Chrome/Firefox/Edge

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ASAMedia** [comment] 2023-11-12 01:58
An example from the website I'm running ([lyonel-feininger-gymnasium.de](https://lyonel-feininger-gymnasium.de/)):
It looks like this in the editor 
![grafik](https://github.com/TryGhost/Ghost/assets/41484117/7ae64619-aebd-4858-9ba6-d02f542bfb20)

and lik ethis on the website
![grafik](https://github.com/TryGhost/Ghost/assets/41484117/24c11f2b-89c2-4684-a15c-4d9cb95450bc)

As you can see, the snow picture is nowhere to be seen.

**Comment by ASAMedia** [comment] 2023-11-12 14:29
Ok, I've got some more information:
I looked into the db and found that the images are against my previous claims in fact are NOT present in the lexical field of the post

Here is the code snippet from the working original docker version
```
 receive emails when new content is publishrfed!</p><figure class="kg-card kg-image-card kg-width-wide"><img src="__GHOST_URL__/content/images/2023/11/IMG_2658.jpeg" class="kg-image" alt="" loading="lazy" width="2000" height="1500" srcset="__GHOST_URL__/content/images/size/w600/2023/11/IMG_2658.jpeg 600w, __GHOST_URL__/content/images/size/w1000/2023/11/IMG_2658.jpeg 1000w, __GHOST_URL__/content/images/size/w1600/2023/11/IMG_2658.jpeg 1600w, __GHOST_URL__/content/images/2023/11/IMG_2658.jpeg 2000w" sizes="(min-width: 1200px) 1200px"></figure><figure class="kg-card kg-image-card"><img src="__GHOST_URL__/content/images/2023/11/Screenshot-2023-11-11-at-18-42-13-Studienfahrt-nach-Gillingham--Kent-GB--der-9.-Klassen.png" class="kg-image" alt="" loading="lazy" width="1920" height="673" srcset="__GHOST_URL__/content/images/size/w600/2023/11/Screenshot-2023-11-11-at-18-42-13-Studienfahrt-nach-Gillingham--Kent-GB--der-9.-Klassen.png 600w, __GHOST_URL__/content/images/size/w1000/2023/11/Screenshot-2023-11-11-at-18-42-13-Studienfahrt-nach-Gillingham--Kent-GB--der-9.-Klassen.png 1000w, __GHOST_URL__/content/images/size/w1600/2023/11/Screenshot-2023-11-11-at-18-42-13-Studienfahrt-nach-Gillingham--Kent-GB--der-9.-Klassen.png 1600w, __GHOST_URL__/content/images/2023/11/Screenshot-2023-11-11-at-18-42-13-Studienfahrt-nach-Gillingham--Kent-GB--der-9.-Klassen.png 1920w" sizes="(min-width: 720px) 720px"></figure><hr>
```
And here the one I'm getting with my updated version inside docker
```
 receive emails when new content is publishrfed!</p>
```

**Now the question where does this go wrong?**

**Comment by ASAMedia** [comment] 2023-11-12 21:52
Another Update:
I downloaded the original source files from [5.71.2](https://github.com/TryGhost/Ghost/releases/tag/v5.71.2) build them to an archive with `yarn archive` and used the resulting .tgz (attached) to update the ghost 5.71.0-alpine docker.

Result: 
The problem is still occuring the same way as before :(

So it seems like in the build or update process the reference to the js for the kg-cards/nodes goes missing.
I will attach some log info below, where the missing functions/attr are named:

```
-
```

**Comment by sergiosgc** [comment] 2023-11-28 18:17
Something in the build system is broken. I build my docker instance similar to how you do it, and since 5.71.0, at least, I get two `kg-default-nodes` modules, one in `ghost/node_modules/@tryghost/` and one in `ghost/ghost/core/node_modules/@tryghost`. Removing `ghost/ghost/core/node_modules` fixes the issue.

The duplicate module import creates two definitions of [KoenigDecoratorNode](https://github.com/TryGhost/Koenig/blob/d472dd6f74d5123edb202a51317cb42004e44a13/packages/kg-default-nodes/lib/KoenigDecoratorNode.js). This causes the `instanceof` test in `$isKoenigCard` to fail, which causes [`exportTopLevelElementOrDecorator`](https://github.com/TryGhost/Koenig/blob/d472dd6f74d5123edb202a51317cb42004e44a13/packages/kg-lexical-html-renderer/lib/convert-to-html-string.js#L37) to fail on elements where `$isKoenigCard` should return true but returns false (Images and Cards, at least).

I know very little about Ghost's build system, but someone with more knowledge than me should be able to fix this fairly quickly.

The official images do not exhibit this problem. They may be building ghost differently.

**Comment by ASAMedia** [comment] 2023-11-29 16:05
Wow great! Thanks @sergiosgc
That will solve the issue till a fix is implemented. 

Looks like `kg-default-nodes` is imported here `"@tryghost/kg-default-nodes": "0.2.9",` in the [ghost/core/package.json](https://github.com/TryGhost/Ghost/blob/main/ghost/core/package.json#L105) 
and 
here `const {DEFAULT_NODES} = require('@tryghost/kg-default-nodes');` in the [ghost/core/core/server/lib/lexical.js](https://github.com/TryGhost/Ghost/blob/8fc6fef1685f216eef8eece40c3a38d7225beeb8/ghost/core/core/server/lib/lexical.js#L14)

When I delete the line in the `package.json` and build, everything works as expected.

Maybe this could be a valid **fix**?

**Comment by hsarji** [comment] 2023-12-17 15:03
This problem seems to impact Ghost(Pro) subscribers as well. I have a JavaScript code that uses the Admin API JavaScript Client that updates the content of one post. It used to work but now isn't working. I am seeing no errors. The post history shows that it is being updated but the content isn't changing. If I recall correctly, the source for the blog post used to show that it uses a markdown card. Now, I don't see a markdown class in the post's source. 

I tried troubleshooting the code for several hours with the help of Bing AI to no avail. I agree, partially, with its observation:

> The issue affects the mobiledoc format for posts, which is used by the Ghost API. The mobiledoc format is a JSON document that defines the structure and content of a post using cards, atoms, and markups. The problem is that the Ghost API is not creating the cards correctly, resulting in empty or corrupted posts.

I think the problem is that the API isn't creating the cards, so my post's history shows it is being updated but the Markdown card inside the post isn't changing.

**Comment by daniellockyer** [comment] 2024-05-21 13:46
This should be fixed now!

**Closed by daniellockyer** 2024-05-21 13:46 UTC
Labels: needs:triage
