### ISSUE TITLE
Support video embed from ina.fr

### ISSUE THREAD

**Issue by HLFH** [TryGhost/Ghost#4797] opened 2015-01-13 19:48 UTC
Hi,

I would like to embed this video: http://www.ina.fr/video/I00005844
The embed code for this video is:
```bash
<iframe width='560' height='315' frameborder='0' marginheight ='0' marginwidth='0' scrolling ='no' src='http://player.ina.fr/player/embed/I00005844/1/1b0bd203fbcd702f9bc9b10ac3d0fc21/560/315/1/148db8' ></iframe>
```
This video does not show up on the published post. Instead there is a blank content of 560x315px.

Thanks in advance,

**Comment by ErisDS** [comment] 2015-01-14 12:28
Hi @HLFH, I'm not able to reproduce any issue here. 

Steps I took:

* I pasted the code from the site: `<iframe width='560' height='315' frameborder='0' marginheight ='0' marginwidth='0' scrolling ='no' src='http://player.ina.fr/player/embed/I00005844/1/1b0bd203fbcd702f9bc9b10ac3d0fc21/560/315/1/148db8' ></iframe>` into the Ghost editor
* published the post
* visited the post page - and the video played.

I was using the default casper theme (latest).

I know of no way in which Ghost can interfere with video embeds, therefore I believe this is likely to be a theme issue or user error. I'm going to close this for now, but will reopen if anyone is able to provide reproduction steps with Casper.

**Closed by ErisDS** 2015-01-14 12:28 UTC

**Comment by HLFH** [comment] 2015-01-14 16:58
Pleased to meet you @ErisDS

I'm using also the default Casper theme. It wasn't working yesterday. So I downloaded the ina.fr video with the Video DownloadHelper browser plugin and uploaded it on YouTube. 

**Today is another day and the embed ina.fr code works.**

Thanks,
HLFH
