### ISSUE TITLE
Update to 0.10.0 config.example error

### ISSUE THREAD

**Issue by dyanakiev** [TryGhost/Ghost#7302] opened 2016-09-01 02:18 UTC
### Issue Summary

Cant start ghost without config.example.js file after upgrade.

### Steps to Reproduce

1. upgrade ghost js
2. start ghostjs
3. ghost failing to start
4. reupload config.example.js
5. starting ghost normally

I allready have my old config.js

### Technical details:

* Ghost Version: 1.10
* Node Version: latest 4
* Browser/OS: Internet Explorer 6
* Database: flat

**Comment by kirrg001** [comment] 2016-09-01 11:34
Hey @dyanakiev Sorry to hear you are having trouble and thanks for reporting.

This is caused by our submodule `gscan`, which uses `ghost-ignition`.
The `ghost-ignition` module requires a `config.example` file, see https://github.com/TryGhost/Ignition/blob/master/lib/config/index.js#L4.

I will create an issue in the `ghost-ignition` module.

**Comment by simoncarpinter** [comment] 2016-09-04 23:16
FWIW as a short term fix, I worked around this by ensuring the CWD (`WorkingDirectory` in a systemd `unit` file) was set to the `Ghost` subdirectory (in my case, roughly, a setting like`WorkingDirectory=/opt/ghostd-wrapper/node_modules/ghost/` :)).

**Comment by kirrg001** [comment] 2016-09-07 06:29
Closing, because we have fixed this issue in `ghost-ignition` and updated gscan to `0.0.13`, see https://github.com/TryGhost/Ghost/pull/7328

**Closed by kirrg001** 2016-09-07 06:29 UTC
