### ISSUE TITLE
Korean input issue in Admin Editor

### ISSUE THREAD

**Issue by scott0129** [TryGhost/Ghost#11940] opened 2020-06-22 07:30 UTC
### Issue Summary

Input errors in the editor if the first character of a line is Korean. The behavior is different for every browser tested.

OS: Mac OS X, v10.15.5

### To Reproduce

1. Open the Admin editor to create a new page/post
2. Type in Korean into the body. (Korean in the title works as expected)

This issue occurs on any new line.

#### Expected:
The pipe is used to show cursor position when the letters ㅇ, ㅡ, and ㅅ are typed.
```
|
ㅇ|
으|
읏|
```

#### Chrome (83.0.4103.106):
```
|
|ㅇ
ㅡ|ㅇ
ㅡㅅ|ㅇ
```

#### Safari (13.1.1):
```
|
|ㅇ
으|ㅇ
읏|ㅇ
```

#### Firefox (77.0.1):
```
|
|ㅇ
ㅇ
ㅇ
```
Attempts to erase and re-type the characters show no input on firefox.

### Workaround

On Chrome and Safari, starting the line with a space before typing Korean avoids the issue and results in predictable Korean input. On Firefox, pressing the spacebar doesn't input the space character. An English followed by Korean input, however, does work on Firefox.

### Technical details:
* Node Version: v12.18.0
* Ghost Version: 3.2.0

**Comment by ErisDS** [comment] 2020-06-22 08:30
Closing as a duplicate of #9801 - this is an upstream issue.

**Closed by ErisDS** 2020-06-22 08:30 UTC
