### ISSUE TITLE
Crash when editing a published article

### ISSUE THREAD

**Issue by chrishornmem** [TryGhost/Ghost#11697] opened 2020-03-28 19:19 UTC
* Ghost Version: 3.12.0
Installed from Docker image ghost:latest

I have an article with code highlights and images.  After publishing, I then go back and unpublish.  I start to make some changes (doesn't seem to matter what changes I make).  I observe a crash in the console (attached). At this point the changes are not saved and when I go back to "posts", I receive a warning saying that my changes are unsaved.

This is reproducible, happens every time.

I peered into the code and it seems it's trying to make an animation at that point on an element that does not exist and bombs out.

![Screenshot 2020-03-28 at 10 49 11](https://user-images.githubusercontent.com/11504092/77831734-c969b500-7128-11ea-994b-b86d2268fda7.png)

PS - Congratulations on this excellent project.

**Comment by kevinansfield** [comment] 2020-03-28 19:50
Hey @chrishornmem 👋 This was fixed in Ghost 3.12.1 that was released a couple of days ago, an upgrade should sort it out for you 🙂

Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/11685, https://github.com/TryGhost/Ghost/issues/11689 and https://github.com/TryGhost/Ghost/issues/11693

**Closed by kevinansfield** 2020-03-28 19:50 UTC

**Comment by chrishornmem** [comment] 2020-03-29 10:36
@kevinansfield thanks for quick reply.  Looks like latest docker is still 3.12.0?

https://github.com/docker-library/ghost/blob/698b7407674e87fc0519d173e7da877e02171e71/3/debian/Dockerfile

Do you know when the image will be updated?

Keep up the great work.

**Comment by kevinansfield** [comment] 2020-03-30 13:05
@chrishornmem the docker image is a community project and not supported by the Ghost team. You'll need to ask over on https://github.com/docker-library/ghost

**Comment by chrishornmem** [comment] 2020-03-30 13:06
Ok thank you
