### ISSUE TITLE
Stuck on Password Screen

### ISSUE THREAD

**Issue by gauravggg21** [TryGhost/Ghost#12176] opened 2020-08-30 18:41 UTC
I installed ghost locally on my Ubuntu 20.04 desktop. 

Node Version - 12.18.3

Npm version - 6.14.8

Browser - Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)

When I "Make this site private" from the Advanced Settings menu, it gives me a password. I enter that password on the index page of the blog, and it does not accept it. The same page reloads again. When I input a different password, it prompts wrong password. But does not when the password is correct.

**Comment by ErisDS** [comment] 2020-09-03 12:40
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/12173

**Closed by ErisDS** 2020-09-03 12:40 UTC
