### ISSUE TITLE
Can't switch Night shift

### ISSUE THREAD

**Issue by hzb** [TryGhost/Ghost#9111] opened 2017-10-08 11:50 UTC
### Issue Summary

Can't switch night shift

### Steps to Reproduce

1. add a new user, such as 'newaccount'

2. set its role to administrator

3. login with this new user (newaccount)

4. select 'Night shift' in labs

5. logout

6. login with this blog's owner account

7. set the new user (newaccount)'s role to editor or author

8. logout

9. login with the new user, you will see you already get the dark background model

10. login with this blog's owner account

11. set the new user (newaccount)'s role to administrator

12. logout

13. login with the new user

14. unselect  'Night shift' in labs, you will get the dark background model

15. logout

16. login with this blog's owner account

17. set the new user (newaccount)'s role to editor or author

18. logout

19. login with the new user

20. you will see the background still is dark.

important info: If the new user(newaccount)'s role is adminitrator, the background is right, if the new user(newaccount)'s role is NOT adminitrator, the background is always dark!!!

### Technical details:

* Ghost Version: 1.12.0
* Node Version: 7.0
* Browser/OS: chrome/safari on macOS hight serria
* Database: sqlite3

**Comment by ErisDS** [comment] 2017-10-18 18:23
@kevinansfield would I be right in thinking that this related to #8690? Would it also be correct to say that this is partly due to the fact that nightshift is currently a labs feature rather than a per-user setting? Is it meant to be a per-user setting eventually, and should we perhaps just get it out of labs now and into its proper home to fix these issues? 

Just a thought 🤔

**Comment by kevinansfield** [comment] 2017-10-18 19:00
It's possible that it's related to #8960, I haven't had a chance to reproduce yet.

Although night shift lives on the labs screen it is a per-user setting, whether night-shift is enabled or not is stored on the `accessibility` field on the `user` table.

**Comment by kevinansfield** [comment] 2018-01-12 17:34
I've not been able to reproduce so I think this was also fixed by https://github.com/TryGhost/Ghost-Admin/commit/0ef503f23d923f468b4a61a9b7a7593eebff58b2.

If anyone runs into a similar sticky nightshift option with Ghost 1.20.1 or later please open a new issue.

**Closed by kevinansfield** 2018-01-12 17:34 UTC
Labels: admin-client
