### ISSUE TITLE
Can't save when editor has focus

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8932] opened 2017-08-23 02:45 UTC
In ghost 1.6.2 - CMD+S no longer triggers save if the editor has focus. Works fine if the editor does not have focus

**Comment by JohnONolan** [comment] 2017-08-23 02:59
Actually this isn't accurate. Most of the time it won't save when the editor has focus, but sometimes it does. Other times, no matter what I do I can't make it save. Nothing in console - just really really hit and miss

**Comment by JohnONolan** [comment] 2017-08-23 03:01
I think this is maybe extra confusing because there's no visual indication of when a save is in progress. The original intention was that the word "Draft" in the top left corner would change to "Saving..." while save was in progress

**Comment by JohnONolan** [comment] 2017-08-23 03:27
When I eventually bit the publish button, it just spun for ages (30+ seconds). In that time, 3 separate "post published!" notifications fired, before the button itself finally progressed to "Published"

There's definitely something very out of sync going on here

**Comment by kirrg001** [comment] 2017-08-28 20:50
Any thoughts on this @kevinansfield?

**Comment by kevinansfield** [comment] 2017-08-29 08:43
I've not been able to reproduce the exact scenario - it sounds like the network connection was really bad.

<kbd>Cmd-S</kbd> doesn't trigger the top-left "Saving..." indicator at the moment, it's only triggered by background saves. I'm looking into that and I'll also revisit the concurrency rules as it sounds like a saves were triggered whilst a save was already in progress (hence the multiple "post published!" notifications)

**Comment by kevinansfield** [comment] 2017-08-29 11:03
https://github.com/TryGhost/Ghost-Admin/pull/842 makes sure that we always show "Saving..." in the top left when a save is in progress.

Regarding the '3 separate "post published!" notifications fired' - this occurs because we enqueue every save request, so mashing <kbd>Cmd-S</kbd> multiple times will trigger multiple consecutive saves and if you use the publish menu the spinner will spin until all previous saves finish.

I've had a quick look at allowing on-going saves to be dropped when a new save is started but it's a little more tricky because we have saving and slug generation in an "enqueue group" because in certain circumstances we have to have slug generation finish before the save can be initiated. It can definitely be done but it will need a bit more time devoted to it.

**Comment by kevinansfield** [comment] 2017-09-08 12:49
I'm going to close this issue for now. The main problem with no visual saving indication is fixed. Further improvements to save behaviour will probably need to wait for a larger refactor of the editor and PSM.

**Closed by kevinansfield** 2017-09-08 12:49 UTC
Labels: admin-client, bug
