### ISSUE TITLE
[BUG] Navigation order cannot set in 0.7.4

### ISSUE THREAD

**Issue by Faber73** [TryGhost/Ghost#6281] opened 2016-01-03 14:10 UTC
After the last upgrade cannot change the Navigation order. When I going to Save it, will reload the old order.

**Comment by kevinansfield** [comment] 2016-01-03 14:13
Closing as a duplicate of #6267. If you are experiencing this issue on master please comment on that issue so that we can track it in one place :smile:

**Closed by kevinansfield** 2016-01-03 14:13 UTC
