### ISSUE TITLE
paths:contentPath is oddly set when Ghost is installed via NPM

### ISSUE THREAD

**Issue by seungha-kim** [TryGhost/Ghost#8795] opened 2017-07-31 15:39 UTC
### Issue Summary

When Ghost is installed via NPM, the `paths:contentPath` is set to `(project folder)/node_modules/ghost/content`, not `(project folder)/content`. But `database:connection:filename` is set correctly.

It seems `makePathsAbsolute` is written in wrong way.

I worked around this issue through setting `paths:contentPath` to `content` not `content/`, but it is not a good solution of course.

### Steps to Reproduce

1. Install Ghost via NPM
2. Set `paths:contentPath` to `content/`

### Technical details:

* Ghost Version: 1.2.0
* Node Version: 6.11.1
* Browser/OS: Manjaro
* Database: SQLite3

**Comment by ErisDS** [comment] 2017-07-31 15:41
I think this is a duplicate of https://github.com/TryGhost/Ghost/issues/8754, although this provides some nice extra info - thanks.

Would love a PR to fix this :)

**Closed by ErisDS** 2017-07-31 15:41 UTC
