### ISSUE TITLE
Cannot edit From adress domain in members settings

### ISSUE THREAD

**Issue by Dryusdan** [TryGhost/Ghost#11811] opened 2020-05-11 21:52 UTC
Hello

### Issue Summary

In my problem, my blog URL is www.blog.tld.
But my email is contact@blog.tld.

I edit mail.form like this : `"from": "'Blog.fr' <contact@Blog.fr>",` but in labs > members > email setting it is @www.blog.tld. 
When mail is send, it send with contact@www.blog.tld and email.from and not contact@blog.tld : 

`From: "Blog.tld" <contact@www.blog.tld>`

### To Reproduce

1. Create blog with url in config is www.domain.tlkd
2. Configure email setting with SMTP like this

```
  "mail": {
        "transport": "SMTP",
    "from": "'BLog.tld' <contact@blog.tld>",
    "options": {
        "host": "mail.domain.tld",
        "port": 587,
        "auth": {
            "user": "contact@domain.tld",
            "pass": ""
        }
    }
```
3. Configure members labs to send email and set "Email from" with contact in field (I can't change de @www.blog.tld).
4. GO to newsletters, and register

Email is send with Good `From: "Blog.tld" <contact@www.blog.tld>`

### Technical details:

* Ghost Version: 3.15.3
* Node Version: 10.20
* Browser/OS: Debian 10
* Database: MySQL

If you would like any other information, don't hesitate ;)

Thank :)

**Comment by naz** [comment] 2020-05-18 03:59
Thanks for reporting @Dryusdan, I believe this is a duplicate of this issue here - https://github.com/TryGhost/Ghost/issues/11414 and this specific usecase mentioned there - https://github.com/TryGhost/Ghost/issues/11414#issuecomment-602638621. Closing this one for now, but feel free to ping if I'm mistaken!

**Closed by naz** 2020-05-18 03:59 UTC
