### ISSUE TITLE
Hitting Enter in list item creates NaNundefined

### ISSUE THREAD

**Issue by kennethlimcp** [TryGhost/Ghost#9409] opened 2018-01-19 14:28 UTC
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. Create a list in a new story

```
- Cambodia – Siem Reap
- China - Shanghai, Beijing, Shenzhen
- Japan – Iwate Prefecture, Yokohama, Fukui, Tokyo
- Hong Kong
- India - Mumbai, Agra, Assam, New Delhi
- Korea – Pohang, Seoul
- Malaysia – Johor Bahru, Kedah, Kota Kinabalu, Kluang, Kuala Lumpur, Penang
- Philippines – Ilo Ilo, Bohol, Caticlan, Cebu, Boracay, Manila
- Taiwan - Taipei, Kaohsiung, Tainan, Hua lien, Jia Yi, Tai Chung
- Thailand – Bangkok, Betong, Chiang Mai, Chiang Rai, Hat Yai
- USA – Atlanta, San Francisco
- Vietnam – Ho Chi Minh City
```

2. Go to the end of one line and hit enter

```
- Cambodia – Siem Reap
- China - Shanghai, Beijing, Shenzhen
- Japan – Iwate Prefecture, Yokohama, Fukui, Tokyo
- Hong Kong
- 
NaNundefinedIndia - Mumbai, Agra, Assam, New Delhi
NaNundefinedKorea – Pohang, Seoul
NaNundefinedMalaysia – Johor Bahru, Kedah, Kota Kinabalu, Kluang, Kuala Lumpur, Penang
NaNundefinedPhilippines – Ilo Ilo, Bohol, Caticlan, Cebu, Boracay, Manila
NaNundefinedTaiwan - Taipei, Kaohsiung, Tainan, Hua lien, Jia Yi, Tai Chung
NaNundefinedThailand – Bangkok, Betong, Chiang Mai, Chiang Rai, Hat Yai
NaNundefinedUSA – Atlanta, San Francisco
NaNundefinedVietnam – Ho Chi Minh City

3. `-` will be replaced by `NaNundefined`

```

### Technical details:

* Ghost Version: 1.19.2
* Node Version: 6.5
* Browser/OS: Chrome/MacOS
* Database: SQLite

**Comment by kirrg001** [comment] 2018-01-19 14:34
Duplicate of https://github.com/TryGhost/Ghost/issues/9372 and https://github.com/TryGhost/Ghost/issues/9302. Please use the search before raising a new issue. Thanks 👍 

This was fixed in [1.20.0](https://github.com/TryGhost/Ghost/releases/tag/1.20.0).

**Closed by kirrg001** 2018-01-19 14:34 UTC
