### ISSUE TITLE
Can't upload post image with link at 1.0 later.

### ISSUE THREAD

**Issue by slarkcoder** [TryGhost/Ghost#9352] opened 2017-12-21 14:07 UTC
In the 1.0 version later, I can't upload post image with link, I don't want use image from Unsplash.

**Comment by kevinansfield** [comment] 2017-12-21 14:27
Closing as a duplicate of #8032, #8653, #8838, and #9156.

**Closed** 2017-12-21 14:31 UTC

**Comment by slarkcoder** [comment] 2017-12-22 08:03
thx！
