### ISSUE TITLE
Bug: Markdown image syntax being parsed even inside code blocks

### ISSUE THREAD

**Issue by ConnorKrammer** [TryGhost/Ghost#5834] opened 2015-09-13 22:35 UTC
## Issue summary

Writing valid markdown for an image inside a code block results in it being parsed instead of being left as-is.

## How to reproduce
In the editor pane, this:

    ```
    ![image](www.example.com/image.jpg)
    ```

...results in the following output in the preview pane:

```
<section class="js-drop-zone image-uploader"><img class="js-upload-target" src="www.example.com/image.jpg"/><div class="description">Add image of <strong>image</strong></div><input data-url="upload" class="js-fileupload main fileupload" type="file" name="uploadimage"></section>
```

Publishing the post results in this being embedded in the final HTML:

```
<pre><code>&lt;img src="www.example.com/image.jpg" alt="image" /&gt;
</code></pre>
```

This appears to exclusively be an issue with triple-backtick-denoted code blocks, and not indented code blocks or inline code snippets inserted with single backticks.

## Technical details
**Ghost**: 0.7.0
**Firefox**: 40.0.3
**OS**: Windows 7

Edit: Added that indented code blocks aren't affected.

**Comment by ErisDS** [comment] 2015-09-14 11:12
Hi @ConnorKrammer, thanks for the detailed bug reports. This one is a duplicate of #5039

**Closed by ErisDS** 2015-09-14 11:12 UTC

**Comment by ConnorKrammer** [comment] 2015-09-15 03:28
Ah, so that's where it was. I thought this would already have an issue, but I couldn't find it in search.
