### ISSUE TITLE
Grunt init task fails on shell:ember:dev 

### ISSUE THREAD

**Issue by peterblazejewicz** [TryGhost/Ghost#5107] opened 2015-04-05 20:41 UTC
Hi,

I've been installing Vagrant box and because of problems I've been researching why `Grunt-Vagrant` fails:
https://github.com/TryGhost/Ghost-Vagrant/issues/60
https://github.com/TryGhost/Ghost-Vagrant/issues
So I've made a clean clone of `Ghost` and just followed instructions from README.md and it appears that described procedure fails when running:
```
grunt init
```
```
...
Running "shell:ember:dev" (shell) task
/bin/sh: /Users/piotrblazejewicz/git/Ghost/core/client/node_modules/.bin/ember: No such file or directory
Warning: Command failed: /bin/sh: /Users/piotrblazejewicz/git/Ghost/core/client/node_modules/.bin/ember: No such file or directory
 Use --force to continue.

Aborted due to warnings.
```
https://github.com/TryGhost/Ghost/blob/master/Gruntfile.js#L284-L285

The `init` task is used in other task, so for example `grunt validate` described in `Ghost-Vagrant` docs also fails.

I'm using  up-to-date master with latest commit `6db9826b237e36f72efc03215ac6f2e29cc7769d` and with clean `node_modules` directory.

Can someone confirm this?

**Comment by novaugust** [comment] 2015-04-06 03:24
Hey @peterblazejewicz, sounds like this is an issue with ghost-vagrant, rather than Ghost itself. We aren't actively supporting Ghost Vagrant, and with the recent move to ember-cli it seems to have fallen behind. With that said, I'm going to close this issue, but feel free to open another issue on Ghost Vagrant if there isn't one that applies to you

**Closed by novaugust** 2015-04-06 03:24 UTC

**Comment by peterblazejewicz** [comment] 2015-04-06 08:37
@novaugust I hope I've clearly stated that I had issue with `grunt init` in Ghost.
But I'm not able to repeat that problem if I perform a clean slate install, so I agree to think that something is incorrectly set in box setup for Vagrant.
For the records, the same task succeed on clean install with current version:
```
~  cd git
➜  git  rm -Rf Ghost
➜  git  git clone git://github.com/tryghost/ghost.git
Cloning into 'ghost'...
...
Checking connectivity... done.
➜  ghost git:(master) npm install -g grunt-cli
/usr/local/bin/grunt -> /usr/local/lib/node_modules/grunt-cli/bin/grunt
grunt-cli@0.1.13 /usr/local/lib/node_modules/grunt-cli
➜  ghost git:(master) npm install
> typechecker@2.0.8 preinstall 
...
➜  ghost git:(master) grunt init
Running "shell:ember:init" (shell) task
....
Running "shell:ember:dev" (shell) task
Future versions of Ember CLI will not support v0.10.35. Please update to Node 0.12 or io.js.
version: 0.2.2
0.2.2

Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
BuildingBuilding.Building..Building...BuildingBuilding.Built project successfully. Stored in "dist/".

Done, without errors.
```
Thanks!

**Comment by beaumartinez** [comment] 2015-04-26 22:13
I ran into something similar; deleting `node_modules` inside the `core/client` dir, and running `npm update` (inside the `core/client` dir) resolved it.

**Comment by ErisDS** [comment] 2015-04-27 07:29
`npm install` doesn't always complete properly. Any one of a number of things can go wrong, so when getting errors like this the first thing to do is just try again. Running `npm cache clear` beforehand will delete your local cache of modules to install, just incase something went wrong there.

If that doesn't help you, try deleting the node_modules folders. There's one at  `/node_modules` and one at `/core/client/node_modules`. Alternatively you can do:

`rm -rf core/client`
`git checkout -- core/client`

To delete the client folder, and grab it from git again. This deletes all of the files that have been fetched or built and gives you a clean slate to start from.

**Comment by beaumartinez** [comment] 2015-04-27 10:23
Thanks @ErisDS.

**Comment by sybohy** [comment] 2015-08-30 20:42
`npm update` inside the core/client did the trick for me as well

**Comment by flpms** [comment] 2015-09-16 22:18
I've a problem that I think is related to this issue. When I try install a clone version wich was forked from Ghost, and Ghost itself, I receive a list of troubles. I'll detail more:

My enviroment is a

* Digital Ocean VPS Linux 14.04  
* node -v 10.40
* npm -v 1.4.28
* grunt -v 0.1.13

I run the commands for clone and install grunt, after that I run the commands to `npm install` I receive some warnings and `grunt init` and here the troubles start.

A list of warnings like this 
````
Running "shell:ember:init" (shell) task                                                                                                            
Installing client dependencies...                                                                                                                  
npm WARN deprecated find-file@0.1.4: Use the globby package instead                                                                                
Killed                                                                                                                                             
Warning: Command failed: npm WARN deprecated find-file@0.1.4: Use the globby package instead                                                       
Killed                                                                                                                                             
 Use --force to continue.                                                                                                                          
````

So after search and google and found this issue, I follow sugestions @ErisDS and I cleaned my npm cache and run again `grunt init` and again abort due warnings

````
Running "shell:ember:dev" (shell) task                                                                                                             
/bin/sh: 1: /root/sites/Ghost/core/client/node_modules/.bin/ember: not found                                                                       
Warning: Command failed: /bin/sh: 1: /root/sites/Ghost/core/client/node_modules/.bin/ember: not found                                              
 Use --force to continue.                                                                                                                          
                                                                                                                                                   
Aborted due to warnings.
````

This is one of many other warnings. 
Resuming I try delete `core/client` folder like sugestions above, and run `npm update` without sucess or any progress different `Aborted due to warnings.`

To explain why I think is related allways stop cause `shell:ember:dev`. Can be a bug at Ember?

**Comment by ErisDS** [comment] 2015-09-17 09:32
@flpms This issue only happens if you were upgrading from before we switched over to using ember-cli properly. Warnings can almost always be ignored, your trouble is starting here:

> Killed 

This usually means that the process ran out of memory. Ghost itself doesn't use much memory, but unfortunately the tools used during the install like npm can use a lot. The problem is discussed with solutions here: https://www.digitalocean.com/community/questions/npm-gets-killed-no-matter-what

**Comment by flpms** [comment] 2015-09-17 14:12
Thanks for support @ErisDS was very helpful.

**Comment by RussellUresti** [comment] 2015-09-21 08:22
I had a similar issue with 0.6.4 today. I was getting `ENOENT, no such file or directory 'node_modules/ember-cli-ic-ajax/node_modules/'`. Tried emptying out `core/client/node_modules` a few times but got nothing.

I solved the problem by going into `core/client/node_modules/ember-cli-ic-ajax` and doing an `npm install` there, as the `ic-ajax` dependency listed never seemed to get installed. Ran `grunt init` from the root and everything was fine.

**Comment by n4nagappan** [comment] 2015-09-22 07:45
Thanks @ErisDS

**Comment by carlosrymer** [comment] 2015-10-09 00:59
If you are still having this problem, make sure NODE_ENV is not set. If it's set to "production," then npm install will skip installing anything because the package file only has devDependencies.

**Comment by kildareflare** [comment] 2016-01-07 07:58
I had a similar issue with shell:ember:dev failing as it could not locate path for ember.
I resolved by doing an npm cache clean, then running grunt init on master (not stable) then switching to stable to run grunt prod.

**Comment by JonathanRosado** [comment] 2016-04-05 22:57
Thanks @ErisDS
