### ISSUE TITLE
[iCloud mail setting] From address is not one of your addresses

### ISSUE THREAD

**Issue by thanhpt-25** [TryGhost/Ghost#17012] opened 2023-06-14 03:25 UTC
### Issue Summary

# Issue Summary

iCloud+ plan allow user to use custom domain but if we use the custom domain in ghost's mail config then magic link could not be sent with error "From address is not one of your addresses".

# Reason :
- `getFromAddress` return something `noreply@[yourdomain.com]` instead of your `from` setting in config.production.json file : 

```
function getFromAddress(requestedFromAddress) {
    const configAddress = config.get('mail') && config.get('mail').from;

    const address = requestedFromAddress || configAddress;
    // If we don't have a from address at all
    if (!address) {
        // Default to noreply@[blog.url]
        return getFromAddress(`noreply@${getDomain()}`);
    }

    // If we do have a from address, and it's just an email
    if (validator.isEmail(address, {require_tld: false})) {
        const defaultSiteTitle = settingsCache.get('title') ? settingsCache.get('title').replace(/"/g, '\\"') : tpl(messages.title, {domain: getDomain()});
        return `"${defaultSiteTitle}" <${address}>`;
    }

    return address;
}
``` 

Because of `const address = requestedFromAddress || configAddress`, address will try to use `requestedFromAddress` first and only if `requestedFromAddress` is null then it will be assigned by our `configAddress` value. In my case, `requestedFromAddress` is always `noreply@mydomain.com` that is why my custom config value in json will never be use.

Of course `noreply@mydomain.com` is not a valid email in my icloud email list and that is why `From address is not one of your addresses.` error happened 

# Temporary fix 

```
    const address = configAddress || requestedFromAddress ; 
``` 

### Steps to Reproduce

- Mail Setting 

```
  "mail": {
    "transport": "SMTP",
    "from": "me@your_domain.com",
    "options": {
      "host": "smtp.mail.me.com",
      "port": 587,
      "auth": {
        "user": "your@icloud.com",
        "pass": "your_app_password"
      }
    }
  },
```
- Try to subscribe from web  

### Ghost Version

5.51.0 

### Node.js Version

18.16.0

### How did you install Ghost?

Ubuntu & Ghost CLI 

### Database type

MySQL 8

### Browser & OS version

Mac: Chrome, Firefox; iOS: Safari

### Relevant log / error output

```shell
...at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)","hideStack":false},"msg":"Failed to send email. Reason: Mail command failed: 550 5.7.0 From address is not one of your addresses.","time":"2023-06-13T09:29:53.228Z","v":0}
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by markstos** [comment] 2023-06-14 18:58
This does not appear to be a bug to me. Email systems require that emails be sent from a valid address to avoid email spoofing, and the order of the primary value and default "config" value look correct. 

It seems either you need to set up `noreply` as a valid email address or use a different address.  An email address can be still be valid, yet not respond to replies. It might even bounce messages it receives.

**Comment by daniellockyer** [comment] 2023-06-20 15:37
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/12802

**Closed by daniellockyer** 2023-06-20 15:37 UTC
Labels: needs:triage
