### ISSUE TITLE
Incorrect version upgrade number

### ISSUE THREAD

**Issue by kennethlimcp** [TryGhost/Ghost#9070] opened 2017-09-27 11:55 UTC
Welcome to Ghost's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫. Found a bug? Please fill out the sections below... thank you 👍

If your issue is with Ghost CLI, please report it on the CLI repo ➡️ https://github.com/TryGhost/Ghost-CLI/issues/new.

### Issue Summary

An upgrade to `1.9.1` is shown as `1.9.0` in the admin page

### Steps to Reproduce

<img width="722" alt="screen shot 2017-09-27 at 19 45 11" src="https://user-images.githubusercontent.com/6760914/30912082-c531eaf6-a3bd-11e7-8d11-18c5a11c88cd.png">

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 1.9.0
* Node Version: - 
* Browser/OS: Chrome/Mac
* Database: SQLite

**Comment by kevinansfield** [comment] 2017-09-27 15:09
Hey @kennethlimcp 👋 This was due to a bug in 1.9.0 that was fixed in 1.9.1.

Closing as a duplicate of #9040.

**Closed by kevinansfield** 2017-09-27 15:09 UTC
