### ISSUE TITLE
Getting message to update ghost after updating  also

### ISSUE THREAD

**Issue by nitishk72** [TryGhost/Ghost#10626] opened 2019-03-21 08:55 UTC
### I had updated my ghost still I am getting the message to update ghost.

![Screenshot](https://user-images.githubusercontent.com/15886737/54741623-0bdae680-4be5-11e9-8013-7160556355e3.png)

**Comment by kirrg001** [comment] 2019-03-21 09:46
Duplicate of https://github.com/TryGhost/Ghost/issues/9875.

**Closed by kirrg001** 2019-03-21 09:46 UTC
