### ISSUE TITLE
Add support for Node 4.3.0 LTS

### ISSUE THREAD

**Issue by Simbady** [TryGhost/Ghost#6494] opened 2016-02-12 11:54 UTC
Node v4 LTS is now on version 4.3.0 and so Ghost will not build as it checks for version 4.2.x.

**Comment by halfdan** [comment] 2016-02-12 11:55
Duplicate of #6473 - fixed in #6490. Please use the search function before opening issues.

**Closed** 2016-02-12 11:57 UTC
