### ISSUE TITLE
Markdown syntax in fenced code blocks

### ISSUE THREAD

**Issue by fladd** [TryGhost/Ghost#6504] opened 2016-02-14 18:24 UTC
Ghost has a funny bug when intending to showcase markdown code in a fenced code block:

    ```markdown
    ![Example Picture](./ExamplePicture.png)
    ```

gets rewritten to:

    ```markdown
    <section class="js-drop-zone image-uploader"><img class="js-upload-target" src="./ExamplePicture.png"/><div class="description">Add image of <strong>Example Picture</strong></div><input data-url="upload" class="js-fileupload main fileupload" type="file" name="uploadimage"></section>
    ```

This automatic conversion of the image syntax should of course not happen within code blocks.

Is there actually any current way to get around this problem?

**Comment by acburdine** [comment] 2016-02-14 18:31
@fladd I don't think so at the moment; however, the editor is undergoing a major overhaul at the moment which should allow better customization of things like this

**Comment by ErisDS** [comment] 2016-02-14 18:40
This is a duplicate of #5039 - you can work around it by using the 4-space indent for code blocks instead of fences.

**Closed by ErisDS** 2016-02-14 18:40 UTC

**Comment by fladd** [comment] 2016-02-14 19:02
@acburdine Thanks for the quick answer. 

@ErisDS That will work for non-highlighted code, but when using Prism.js, fenced code blocks are needed to indicate the highlighting language.

**Comment by ErisDS** [comment] 2016-02-14 19:02
You can also just use plain-ol HTML :)

**Comment by fladd** [comment] 2016-02-14 19:04
@ErisDS Oh yeah, of course! :-) *doh*
