### ISSUE TITLE
Webhooks isn't imported when using an export .json

### ISSUE THREAD

**Issue by ollejacobsen** [TryGhost/Ghost#10273] opened 2018-12-12 07:56 UTC
### To Reproduce

1. Export data from a site that has an active webhook
2. Verify in the `export.json` file that a webhook is included
3. Import the `export.json` to an empty site. 
4. Check that the `webhooks` table is empty in the DB.

If I just add the row manually in the db my webhook start working again.

### Technical details:

* Ghost Version: 1.25.6
* Database: MySQL

**Comment by rishabhgrg** [comment] 2018-12-14 07:31
Hey @ollejacobsen 👋 Webhooks(and Integrations) are currently not in of the list of supported content and data handled by import/export, you can check the full supported list here - https://docs.ghost.org/faq/the-importer/.  A PR is welcome to add them to supported list. 😄 

Closing this issue as it's not a bug in Ghost. Please use our forum -https://forum.ghost.org - if you have any further questions

**Closed by rishabhgrg** 2018-12-14 07:31 UTC
