### ISSUE TITLE
Error: No default engine was specified and no extension was provided.

### ISSUE THREAD

**Issue by haowaiwai** [TryGhost/Ghost#8837] opened 2017-08-03 12:14 UTC
### Issue Summary

After update to 1.4,open 127.0.0.1:2368/ghost , show error

```
Error: No default engine was specified and no extension was provided.
    at new View (/Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/view.js:62:11)
    at EventEmitter.render (/Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/response.js:971:7)
    at HTMLErrorRender (/Users/haoyy/work/blog2/versions/1.4.0/core/server/middleware/error-handler.js:86:9)
    at Layer.handle_error (/Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/router/index.js:315:13)
    at /Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/router/index.js:275:10)
    at prepareError (/Users/haoyy/work/blog2/versions/1.4.0/core/server/middleware/error-handler.js:58:5)
    at Layer.handle_error (/Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/router/index.js:315:13)
    at /Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/router/index.js:315:13)
    at /Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/router/index.js:275:10)
    at /Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/response.js:424:7
    at SendStream.onerror (/Users/haoyy/work/blog2/versions/1.4.0/node_modules/express/lib/response.js:1003:5)
```

### Steps to Reproduce

ghost update

### Technical details:

* Ghost Version:1.4
* Node Version:6.5
* Browser/OS: MAC
* Database: SQLITE

**Comment by acburdine** [comment] 2017-08-03 12:15
This is a known issue, a fix is being released in ghost 1.5.0 soon 😁

**Comment by acburdine** [comment] 2017-08-03 12:16
Also, this is a duplicate of #8829

**Closed by acburdine** 2017-08-03 12:15 UTC

**Comment by kirrg001** [comment] 2017-08-03 15:34
`1.5.0` was released.
