### ISSUE TITLE
 Duplicate entry found. Multiple values of '' found for .

### ISSUE THREAD

**Issue by cristiandley** [TryGhost/Ghost#8349] opened 2017-04-18 06:28 UTC
### Issue Summary

I Exported my Data from Wordpress, after that i tried to import them to Ghost.

This is the result on the client:

![errorpanel](https://cloud.githubusercontent.com/assets/1873659/25117078/b71548ac-23e6-11e7-9889-94b60cfbdd08.png)

This is the result on the Server

```bash
ERROR: Duplicate entry found. Multiple values of '' found for . 
 
 Error
    at Error.DataImportError (/home/cristian/proyectos/my_cool_project/node_modules/ghost/core/server/errors/data-import-error.js:6:18)
    at cleanError (/home/cristian/proyectos/my_cool_project/node_modules/ghost/core/server/data/import/index.js:47:12)
    at /home/cristian/proyectos/my_cool_project/node_modules/ghost/core/server/data/import/index.js:64:34
    at arrayEach (/home/cristian/proyectos/my_cool_project/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/home/cristian/proyectos/my_cool_project/node_modules/lodash/lodash.js:9359:14)
    at handleErrors (/home/cristian/proyectos/my_cool_project/node_modules/ghost/core/server/data/import/index.js:57:7)
    at /home/cristian/proyectos/my_cool_project/node_modules/ghost/core/server/data/import/index.js:203:16
    at tryCatcher (/home/cristian/proyectos/my_cool_project/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/cristian/proyectos/my_cool_project/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/cristian/proyectos/my_cool_project/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/cristian/proyectos/my_cool_project/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/cristian/proyectos/my_cool_project/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/home/cristian/proyectos/my_cool_project/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/cristian/proyectos/my_cool_project/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/cristian/proyectos/my_cool_project/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5) 
```

### Steps to Reproduce

1. Using Wordpress plugin to export
2. Import that file to Ghost (Labs -> Select File -> Import)

### Technical details:

* Ghost Version: 0.11.7
* Node Version: 6.9.5
* Browser/OS: Chrome
* Database: MySQL

*EDIT: I tried to parse the file... to find some issues maybe on ID's, stuff like that. Nothing wrong.

**Comment by jmitchell38488** [comment] 2017-04-18 06:46
You should attach the generated wordpress file as well if it isn't too big. 

Is this the ghost hosted version, or self hosted version? If its the self-hosted version, there's a couple of places you can debug what's going on, such as:

`import/utils.js::236 (importPosts)`
`import/utils.js::204 (importTags)`
`import/utils.js::265 (importUsers)`
`import/utils.js::295 (importSettings)`
`import/utils.js::313 (importSubscribers)`

**Comment by kirrg001** [comment] 2017-04-18 12:48
Hey @cristiandley 👋 

Sorry to hear you are having trouble with your Wordpress export 😫.
The error stack you provided doesn't tell me enough to help you. Sorry.
Could you please share your Wordpress export in [slack](https://slack.ghost.org) with me?

**Comment by kirrg001** [comment] 2017-04-18 21:19
@cristiandley has shared his Wordpress export with me. 
The errors were caused by duplicate post slugs.
I have added this issue as subtask to #5422. If one slug fails to insert, the whole import get's rolled back.

**Comment by kirrg001** [comment] 2017-05-21 20:20
This error won't show up anymore with #8473 for Ghost `1.0`. The model layer regenerates existing post slugs. e.g. `horario-de-verano` -> `horario-de-verano-2`. 

If somebody wants to improve the error output for `LTS`, that would be nice.

**Comment by kirrg001** [comment] 2017-07-14 10:59
I am going to close this issue, because we've overhauled the importer in Ghost 1.0. If you experience this problem, please migrate to 1.0 👍 😬

**Closed by kirrg001** 2017-07-14 10:59 UTC
Labels: fix wanted, importer, LTS, server
