### ISSUE TITLE
Ghost cannot connect to Mysql AWS RDS instance with latest CA from AWS

### ISSUE THREAD

**Issue by alexgorb2016** [TryGhost/Ghost#19928] opened 2024-03-26 19:33 UTC
### Issue Summary

We have a setup with Ghost docker container with Mysql RDS instances. Everything works fine with CA names rds-ca-2019. But this RDS (CA) Certificates are expiring on August 22, 2024. If I switch RDS CA to rds-ca-rsa2048-g1 (default) - Ghost is unable to connect to this RDS instance any more.

### Steps to Reproduce

1. Switch AWS RDS CA to rds-ca-rsa2048-g1 (default)
2. Ghost cannot connect to this RDS

### Ghost Version

5.81.0

### Node.js Version

from docker image

### How did you install Ghost?

docker image 

### Database type

MySQL 8

### Browser & OS version

docker image

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by vikaspotluri123** [comment] 2024-03-27 02:35
Seems to be a duplicate of https://github.com/TryGhost/Ghost/issues/19462

**Comment by daniellockyer** [comment] 2024-03-28 10:18
This is fixed in https://github.com/TryGhost/Ghost/commit/ec25aed06f853ad222ebd2706304e66309112270 and will be released with the next version of Ghost 🙂

**Closed by daniellockyer** 2024-03-28 10:18 UTC
Labels: needs:triage
