### ISSUE TITLE
"Use dated permalinks" setting ignored in version 1.13.0

### ISSUE THREAD

**Issue by oryowen** [TryGhost/Ghost#9126] opened 2017-10-10 20:37 UTC
### Issue Summary

When trying to enable the "Use dated permalinks" setting on a fresh v 1.13.0 install, setting is ignored and permalinks do not include the date (in new or existing permalinks).

### Steps to Reproduce

1. New Ghost v 1.13.0 install
2. Attempt to enable "Use dated permalinks" under General settings menu
3. Save settings
4. Check an existing post for updated permalink (no date added)
5. Create a new post to check for new permalink w/date format (still no date in permalink)

### Technical details:

* Ghost Version: 1.13.0
* Node Version: 6.9.0
* Browser/OS: Safari 11.0 on macOS 10.13
* Database: MySQL

**Comment by kirrg001** [comment] 2017-10-11 07:44
Hey @oryowen!

I am unable to reproduce your bug report. When i enable date permalinks and serve any post, i am getting the date permalink in the url. Maybe you didn't save?

You could double check if the date permalink was saved by executing
```select * from settings where `key`='permalinks';``` in your database. It should show `/:year/:month/:day/:slug/`.

I am going to close this issue now, swing by our slack channel if you have further questions.
If it turns out to be a bug, we can always reopen.

**Closed by kirrg001** 2017-10-11 07:44 UTC
