### ISSUE TITLE
Error on parsing Twitter and Instaram URL

### ISSUE THREAD

**Issue by partizan007** [TryGhost/Ghost#12677] opened 2021-02-19 20:26 UTC
Error on parsing Twitter and Instaram URL
Ghost version: 3.41.6
NodeJS v12.20.2
![изображение](https://user-images.githubusercontent.com/25349460/108557442-484b7b80-7301-11eb-90c0-9afb5ea40a65.png)

**Comment by vaiil** [comment] 2021-02-20 14:05
@kevinansfield What about update oembed-parser to latest version? It handles instagram urls properly.

**Comment by partizan007** [comment] 2021-02-20 14:37
> 
> 
> @kevinansfield What about update oembed-parser to latest version? It handles instagram urls properly.

Ghost just installed, by this [instruction ](https://ghost.org/docs/install/ubuntu/). How can i update this parser?

**Comment by vaiil** [comment] 2021-02-23 14:54
@partizan007 You can update it using `yarn oembed-parser@latest` in current dir, but it would be better if ghost maintainers update this package in next release.

**Comment by ErisDS** [comment] 2021-02-23 19:36
@partizan007 when raising an issue you were presented with a template to fill out, please don't delete it.

Am closing this for now as it's not possible for us to bump the oembed-parser dependency as they dropped support for Node.js v10 before it went out of maintance and we strictly follow Node.js's LTS policy (you can ask upstream that oembed parser follows Node LTS in future). It's also, essentially, a duplicate of https://github.com/TryGhost/Ghost/issues/12389

When Node.js LTS goes end of life we will bump the dependency, we do not need an issue to track dependency updates as they are all handled automatically.

**Closed by ErisDS** 2021-02-23 19:36 UTC
