### ISSUE TITLE
Error Running Developer Install - bower: not found

### ISSUE THREAD

**Issue by kevgathuku** [TryGhost/Ghost#7052] opened 2016-06-29 12:26 UTC
### Issue Summary

Running the Developer Install instructions fails in the `grunt init` task

### Steps to Reproduce

1. Follow the `Developer Install (from git)` instructions in README
2. Running the `grunt init` step fails

After running the `grunt init` step, you encounter the following error message:
```sh
Running "shell:bower-install" (shell) task
/bin/sh: 1: bower: not found
Warning: Command failed: /bin/sh -c bower install
/bin/sh: 1: bower: not found
 Use --force to continue.

Aborted due to warnings.
Warning: Failed running "grunt init" in "core/client". Use --force to continue.

Aborted due to warnings.
```

This happens due to `bower` not being installed.

### Technical details:

* Ghost Version: Current Master Branch
* Node Version: 4.4.7
* Browser/OS: Mac OS
* Database: N/A

**Comment by kevinansfield** [comment] 2016-06-29 12:31
This error has been fixed in [Ghost-Admin](https://github.com/TryGhost/Ghost-Admin) master but the submodule reference in Ghost itself hasn't been updated yet.

Closing as a duplicate of #7005 and #7039.

**Closed by kevinansfield** 2016-06-29 12:31 UTC

**Comment by kevgathuku** [comment] 2016-06-29 12:34
Ah, Got it. Thanks 👍

**Comment by kevgathuku** [comment] 2016-06-29 14:44
@kevinansfield What do you recommend to be the best way to keep the submodules updated? Right now I have changed the [Gruntfile](https://github.com/TryGhost/Ghost/blob/master/Gruntfile.js#L328) to `--remote` from the default `--init` to fetch the latest version of the submodules. 

What would it look like if this were the default or are there some implications of doing this that I might be missing?

**Comment by kevinansfield** [comment] 2016-06-29 14:50
The simplest way when you are developing is to `cd core/client && git checkout master` - git submodules pull in the referenced repo the same as if it was checked out so you can treat it as a standard repository.

The reference in Ghost itself is only updated when new versions are released or when cross-repo features are merged, we definitely won't be changing the init scripts as the reference needs to be fixed to ensure a compatible state across both releases and when checking out master branch.

**Comment by kevgathuku** [comment] 2016-06-29 16:23
Got it, I see the case for maintaining compatibility. 

I guess this case qualifies as the corresponding PR in the Ghost-Admin repo that fixes this has been merged. 
https://github.com/TryGhost/Ghost-Admin/pull/92

**Comment by kevinansfield** [comment] 2016-06-29 16:25
Yes, there is also a corresponding PR (#7042) in review that will update the client ref.

**Comment by kevgathuku** [comment] 2016-06-29 16:30
Thanks for clearing things up. Very much appreciated :+1:
