### ISSUE TITLE
How to enable assets admin-auth cards on ghost 5.33.1

### ISSUE THREAD

**Issue by monty88** [TryGhost/Ghost#16214] opened 2023-02-01 08:38 UTC
### Issue Summary

Hello, 

I am using ghost v5.33.1 which means the current latest version on Windows 10, also I tried that with a VPS (Ubuntu)  and I faced the same issue.

I am developing a theme and enabled the below option in package.json  

`{ 
  "config": {
    "card_assets": true
  }
}` 

but it doesn't work, I already checked the `/public` folder and found it was empty.

I thought to add  the cards.min.css and cards.min.js manually to `/public` folder, found it works good but when restart ghost command it deletes all these files

Also tried to enable it with ghost command 
`ghost config card_assets true` but also it doesn't work

Please help, thanks
![Capture](https://user-images.githubusercontent.com/18521185/215992046-95a6fa3c-5639-489d-87d7-945a63f752eb.PNG)

### Steps to Reproduce

1- Installed the ghost CLI as a globally using the below command
`npm install ghost-cli@latest -g`
2- I installed the ghost system with two ways to locally and as a --production with mysql 8.
`ghost install local` and `ghost install --production`
3- start ghost with `ghost start`
 

### Ghost Version

5.33.1

### Node.js Version

16.17.0

### How did you install Ghost?

npm install ghost-cli@latest -g | ghost install ( AND ) ghost install --production

### Database type

MySQL 8

### Browser & OS version

Chrome | Windows 10 and ubuntu 20

### Relevant log / error output

```shell
`ghost install`

Love open source? We’re hiring JavaScript Engineers to work on Ghost full-time.
https://careers.ghost.org

- Inspecting operating system
- Checking for deprecations
Running in development mode
- Checking for deprecations

[10:27:10] Checking for Ghost-CLI updates [started]
[10:27:11] Checking for Ghost-CLI updates [completed]

[10:27:11] Checking system Node.js version [started]
[10:27:11] Checking system Node.js version - found v16.17.0 [title changed]
[10:27:11] Checking system Node.js version - found v16.17.0 [completed]
[10:27:11] Checking current folder permissions [started]
[10:27:11] Checking current folder permissions [completed]
[10:27:11] Checking memory availability [started]
[10:27:11] Checking memory availability [completed]
[10:27:11] Checking free space [started]
[10:27:12] Checking free space [completed]
[10:27:12] Checking for latest Ghost version [started]
[10:27:14] Checking for latest Ghost version [completed]
[10:27:14] Setting up install directory [started]
[10:27:15] Setting up install directory [completed]
[10:27:15] Downloading and installing Ghost [started]
[10:27:15] Downloading and installing Ghost v5.33.2 [title changed]
[10:27:15] Getting download information [started]
[10:27:16] Getting download information [completed]
[10:27:16] Downloading [started]
[10:27:24] Downloading [completed]
[10:27:24] Installing dependencies [started]
[10:27:28] → yarn install v1.22.19
[10:27:28] → [1/5] Validating package.json...
[10:27:28] → [2/5] Resolving packages...
[10:27:31] → [3/5] Fetching packages...
[10:28:07] → [4/5] Linking dependencies...
[10:43:31] → [5/5] Building fresh packages...
[10:44:25] → success Saved lockfile.
[10:44:26] → Done in 1017.75s.
[10:44:26] Installing dependencies [completed]
[10:44:26] Downloading and installing Ghost v5.33.2 [completed]
[10:44:26] Finishing install process [started]
[10:44:26] Linking latest Ghost and recording versions [started]
[10:44:26] Linking latest Ghost and recording versions [completed]
[10:44:26] Linking latest Casper [started]
[10:44:26] Linking latest Casper [completed]
[10:44:26] Finishing install process [completed]
[10:44:28] Configuring Ghost [started]
[10:44:28] Configuring Ghost [failed]
[10:44:28] → Prompts have been disabled, all options must be provided via command line flags
[10:44:28] Setting up instance [started]
[10:44:28] Setting up instance [failed]
[10:44:28] → The "url" argument must be of type string. Received undefined
[10:44:28] Setting up "ghost" mysql user [started]
[10:44:28] Setting up "ghost" mysql user [skipped]
[10:44:28] Setting up Nginx [started]
[10:44:43] Setting up Nginx [skipped]
[10:44:43] → Nginx is not installed. Skipping Nginx setup.
[10:44:43] Setting up SSL [started]
[10:44:43] Setting up SSL [skipped]
[10:44:43] → Nginx setup task was skipped, skipping SSL setup
[10:44:43] Starting Ghost [started]
[10:46:50] Starting Ghost [completed]
One or more errors occurred.

1) SystemError

Message: Prompts have been disabled, all options must be provided via command line flags


2) undefined

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
Debug Information:
    OS: Microsoft Windows 10 Pro, v10.0.19044
    Node Version: v16.17.0
    Ghost Version: 5.33.2
    Ghost-CLI Version: 1.24.0
    Environment: development
    Command: 'ghost install'

Try running ghost doctor to check your system for known issues.

You can always refer to https://ghost.org/docs/ghost-cli/ for troubleshooting.
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment] 2023-02-02 12:57
Duplicate of https://github.com/TryGhost/Ghost/issues/14278.

@monty88 you already posted on the open issue, please don't waste precious maintainer time with duplicates.

**Closed by ErisDS** 2023-02-02 12:57 UTC
Labels: needs triage
