### ISSUE TITLE
Installation from a .zip file breaks images in published posts

### ISSUE THREAD

**Issue by ceecko** [TryGhost/Ghost#19132] opened 2023-11-26 17:58 UTC
### Issue Summary

When a user installs Ghost from a .zip file, images in published posts are not visible

### Steps to Reproduce

1. `git clone --recurse-submodules git@github.com:TryGhost/Ghost && cd Ghost`
2. `yarn setup`
3. `yarn archive`
4. `ghost install --zip <path_to_zip_file> --dir /home/node/blog`
5. Publish a post with an image
6. Open the post in frontend - the image is **not** visible
7. Open the post in the admin dashboard - the image is visible

### Ghost Version

5.74.3

### Node.js Version

18.18.2

### How did you install Ghost?

ghost cli

### Database type

MySQL 8

### Relevant log / error output

During modules installation, the module `kg-default-nodes` is installed in two locations:

1. `current/node_modules/@tryghost/kg-default-nodes`
2. `current/node_modules/@tryghost/kg-lexical-html-renderer/node_modules/@tryghost/kg-default-nodes`

This makes `kg-lexical-html-renderer` incorrectly think the image lexical is not a `KoenigCard` since it refers to the nested `kg-default-nodes` in item 2 and not the `kg-default-nodes` from item 1.

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment] 2023-11-27 07:50
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/18948

**Closed by daniellockyer** 2023-11-27 07:50 UTC
Labels: needs:triage
