### ISSUE TITLE
MathJax and Prism no longer working with 1.15

### ISSUE THREAD

**Issue by sirideain** [TryGhost/Ghost#9163] opened 2017-10-19 15:22 UTC
I updated from 1.14 to 1.15 today. I had originally setup MathJax and Prism on 1.14 and both were working. No other changes were made. 

After the upgrade, none of the math is rendered. In fact, it simply is blank for AsciiMath and Latex, but gives this error for MathML.

`Error parsing MathML: error on line 1 at column 1: Extra content at the end of the document`

For Prism, the code boxes are being shown with a black background, which is not the theme I am using from Prism. And the fonts are hard to read.

I don't see any errors in the browser console.

### Technical details:

* Ghost Version: 1.15
* Node Version:
* Browser/OS: Windows - Chrome, Firefox
* Database:

**Comment by kevinansfield** [comment] 2017-10-19 15:44
@sirideain nothing has changed regarding the rendering between 1.14 and 1.15 so I'm not sure what would have caused this change in behaviour. I'm also not able to reproduce as you haven't supplied any reproduction steps.

I'm going to close this issue because there's no actionable steps here. Please head over to our [Slack channel](https://slack.ghost.org) to get support. We can re-open this issue if an actual bug is found and there are verified steps to reproduce the problem.

**Closed by kevinansfield** 2017-10-19 15:44 UTC

**Comment by sirideain** [comment] 2017-10-19 18:18
Quick update for anybody that sees this in the future. I have Cloudflare in front of the site, and Rocket Loader was enabled. This makes the javascript files load asynchronously and may merge them together. When I was testing this on 1.14, it must not have cached these specific files as they were new enough. Turning off Rocket Loader fixed the issue immediately.
