### ISSUE TITLE
Make the ghost.url.api <script> async

### ISSUE THREAD

**Issue by eexit** [TryGhost/Ghost#8624] opened 2017-06-23 19:29 UTC
Hi there,

How are you? I'd like to know if it's possible to make [this `<script>` tag](https://github.com/TryGhost/Ghost/blob/master/core/test/unit/server_helpers/ghost_head_spec.js#L1099) `async`?

Unless you have particular reasons not to do it and I'd be glad to hear them. I can make a PR if you want too :)

Thank you guys!

**Comment by kirrg001** [comment] 2017-06-24 16:49
Hey @eexit!

I'm going to close this issue as we use github solely for bug tracking and feature development. You can raise any idea on https://ideas.ghost.org.

We can provide better support in our [slack channel](https://slack.ghost.org).

Thanks 👋

**Closed by kirrg001** 2017-06-24 16:49 UTC

**Comment by ErisDS** [comment] 2017-08-18 09:34
Duplicate of #7299
