### ISSUE TITLE
Bad layout in IE11

### ISSUE THREAD

**Issue by peterennis** [TryGhost/Ghost#8768] opened 2017-07-27 18:57 UTC
### Issue Summary

Bad layout in IE11

### Steps to Reproduce

Go to the link:
https://dev.ghost.org/ghost-1-0-0/

### Technical details:

* Ghost Version:
* Node Version:
* Browser/OS: 
* Database: 

![capture052](https://user-images.githubusercontent.com/140737/28687223-9af85e7c-72c2-11e7-9171-d9d472640562.png)

**Comment by acburdine** [comment] 2017-07-27 19:00
@peterennis going to close this is as it isn't strictly a bug with Ghost itself; however the issue is noted and we will work on getting it fixed soon 😄

**Closed by acburdine** 2017-07-27 19:00 UTC
