### ISSUE TITLE
Image src in RSS feeds have a trailing slash

### ISSUE THREAD

**Issue by PaulAdamDavis** [TryGhost/Ghost#4975] opened 2015-03-02 10:29 UTC
Images in RSS feeds have a slash at the end of the `src` attribute, causing the image to not show. You can see it the [demo RSS feed](http://demo.ghost.io/rss/).

```html
<p><img src="http://demo.ghost.io/content/images/2014/09/testimg1.jpeg/" alt="A Full and Comprehensive Style Test"></p>
```

I'm positive this was working as intended in 0.5.8, so could be a regression.

### Technical Details
* Ghost Version: 0.5.9 [on Ghost(Pro)]

**Comment by JohnONolan** [comment] 2015-03-02 10:29
Duplicate of #4888 fixed in #4970

**Closed by JohnONolan** 2015-03-02 10:29 UTC
Labels: bug
