### ISSUE TITLE
Should not keep user logged in, if password was changed on his account.

### ISSUE THREAD

**Issue by wowse** [TryGhost/Ghost#6384] opened 2016-01-25 17:14 UTC
# Ghost should not keep user logged in, if password was changed on his account.
### Issue Summary

When one human changes password for specific user, any other people, who are logged in that user aren't logged out but still logged in and can still do anything.
### Steps to Reproduce (2 humans)
1. One person logs in your website with your account, which is powered by Ghost,
2. You change your password,
3. Another person who has logged in is still there and can do any kind of stuff.

Because of that, I think, ghost needs to log out all people, who are logged in one account, where password was changed, except of the one who changed password.
### Technical details:
- Ghost Version: 0.7.5
- Client OS: Windows 8.1
- Server OS: Ubuntu 15.10, with nginx that adds SSL and some custom error pages, inside Microsoft Azure
- Node Version: 0.10.40
- Browser: Google Chrome Version 48.0.2564.82 m
- Database: SQLite

**Comment by AustinPaquette** [comment] 2016-01-25 17:16
I'm actually a little surprised that Ghost doesn't do this already. Going to spin up a demo instance and test this out.

**Comment by wowse** [comment] 2016-01-25 17:19
AustinPaquette, I tried this on my phone (I reopened browser) while changing password on PC, they are on different networks.

**Comment by AustinPaquette** [comment] 2016-01-25 17:21
@wowse It wouldn't be a network related issue, it would be invalidating the active session(s) when a password change occurs. I don't think device type, or connectivity details would play much (if any?) of a role here.

**Comment by wowse** [comment] 2016-01-25 17:23
**AustinPaquette**, right, I didn't mean to add additional info about devices.

**Comment by kevinansfield** [comment] 2016-01-25 17:34
@wowse If you sign out by clicking the drop-down in the top left and selecting "Sign Out" then you will be signed out on all devices as the session/authorization keys are deleted from the database.

**Comment by wowse** [comment] 2016-01-25 17:40
@kevinansfield, are you talking about Ghost Pro, self-hosted, or both? It doesn't do so for me on self-hosted blog on nginx with sqlite, and despite that, still, it should automatically log out.

**Comment by ErisDS** [comment] 2016-01-25 18:48
@wowse can you please update your issue to include details of your Ghost setup? E.g. are you on 0.7.5 or master? Have you got a cache in front of your blog? etc?

There is a [bug report template](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs) in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md) that should give you a good idea what sorts of info to include.

**Comment by wowse** [comment] 2016-01-25 20:13
@ErisDS, yes, I've updated post so it fits to template, thanks for response.

**Comment by halfdan** [comment] 2016-01-26 09:21
@kevinansfield This is not correct. When you sign out it will only delete the current access_token (https://github.com/TryGhost/Ghost/blob/master/core/server/api/authentication.js#L314). You can easily test this by opening a second tab in incognito mode, logging in, and hitting sign out on your second tab. You will still be logged in on the second tab (as I would expect). Hitting sign out on one devise/browser should not log you out on a different devise/browser. 

Maybe this is a misunderstanding - the issue is specifically talking about changing your password, in which case I agree that we should clear out all access/refresh tokens of that user to log out other currently active sessions.

**Comment by kevinansfield** [comment] 2016-01-26 09:22
Yeah, my bad, I think I'd opened the `user.js` file instead of the `authentication.js` file :flushed:

**Comment by loskiq** [comment] 2016-02-08 09:21
@kevinansfield Why you do not commit on this issue?

**Comment by ErisDS** [comment] 2016-02-08 09:44
@loskiq Ghost is open source, if you want to see something fixed you're more than welcome to submit a PR.

**Comment by wowse** [comment] 2016-02-08 10:14
@ErisDS Isn't that a task of ghost developers?

**Comment by loskiq** [comment] 2016-02-08 10:15
@ErisDS I'm not a programmer. I just use your engine.

**Comment by ErisDS** [comment] 2016-02-08 10:40
This is an Open Source Software project, backed by a not-for-profit foundation. The tiny team of developers who work for the foundation is hard at work managing a balancing act of new features, bug fixing and infrastructure.

If you have an interest in seeing something particular fixed faster than we're going to fix it, you're more than welcome to submit a PR. If you aren't a software developer, then consider contributing in some other way to ease the burden on our developers so that they can fix more things. There's lots of info [here](https://ghost.org/about/contribute/) and [here](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md). 

By writing comments like this here on GitHub, you achieve little more than requiring a team member to put down whatever it is they _are_ working on to come and reply to you.

**Comment by ramiel** [comment] 2016-02-09 14:12
What would be the best approach to this? 
- Deleting all the tokens for the user, generate a new one and let the application update the token.  
or
- Delete all the token except the one of the current session.

In my opinion the latter is the best but has more impact to the code because the token is not passed to the API and is the only value which discriminate the different sessions

**Comment by wowse** [comment] 2016-02-09 14:55
If code impact isn’t too huge, second is the best solution.






Sent from Windows Mail





From: Fabrizio Ruggeri
Sent: ‎Tuesday‎, ‎February‎ ‎9‎, ‎2016 ‎6‎:‎13‎ ‎AM
To: TryGhost/Ghost
Cc: tuturu♪





What would be the best approach to this? 
Deleting all the tokens for the user, generate a new one and let the application update the token.
or
Delete all the token except the one of the current session.

In my opinion the latter is the best but has more impact to the code because the token is not passed to the API and is the only value which discriminate the different sessions

**Comment by ErisDS** [comment] 2019-01-02 16:42
@allouis / @kevinansfield With the new authentication methods on the v2 API, does this become easier to implement?

I suggest we close this as it was suggested by the community 3 years ago.

**Comment by kevinansfield** [comment] 2019-01-02 17:48
It was in the spec for the new auth but I don't think the todo item was checked off. @allouis could you confirm and open a new issue if necessary?

**Comment by allouis** [comment] 2019-01-03 14:37
closing in favour of https://github.com/TryGhost/Ghost/issues/10323

**Closed by allouis** 2019-01-03 14:37 UTC
Labels: api, help wanted, server
