### ISSUE TITLE
Load ghost-sdk.min.js asychronously

### ISSUE THREAD

**Issue by brettdewoody** [TryGhost/Ghost#8918] opened 2017-08-18 08:43 UTC
In testing my site on [Google Pagespeed Insights](https://developers.google.com/speed/pagespeed/insights) Ghost performs relatively well out of the box. However, one of the biggest issues it recommends fixing is:

> Remove render-blocking JavaScript - https://sitename.com/public/ghost-sdk.min.js

This one issue can cause a PageSpeed rating to have a max well below 90, so fixing it would be a huge boost in Pagespeed ranking. 

I've experimented with adding an `async` attribute to the `ghost-sdk.min.js` `<script>` tag. It required adding an `onload()` callback but otherwise works well. 

Could this change be made to Ghost core? Pros? Cons? 

### Technical details:

* Ghost Version: 1.5.2
* Node Version: 6.11.2
* Browser/OS: Chrome
* Database: MySQL

**Comment by ErisDS** [comment] 2017-08-18 09:34
Duplicate of #7299

**Closed by ErisDS** 2017-08-18 09:34 UTC
