### ISSUE TITLE
{{meta_title}} has wrong output for pages

### ISSUE THREAD

**Issue by fueko** [TryGhost/Ghost#11306] opened 2019-10-30 13:59 UTC
### Issue Summary

{{meta_title}} helper gives the same result (for pages) as {{@site.title}} 

Check => https://demo.ghost.io/about/

### Technical details:

* Ghost Version: 3.0.1-3.0.2
* Node Version: 10.16.3
* Browser/OS: all
* Database: sqlite3

**Comment by kevinansfield** [comment] 2019-11-28 13:49
This was resolved in 3.1.0. Intended behaviour for both posts and pages is that `{{meta_title}}` will return the post/page's `meta_title` field with a fallback to its `title` field.

**Closed by kevinansfield** 2019-11-28 13:49 UTC
Labels: bug, server, themes
