### ISSUE TITLE
Problems editing a Markdown card in Safari

### ISSUE THREAD

**Issue by daviddarnes** [TryGhost/Ghost#11162] opened 2019-09-26 13:12 UTC
## Issue Summary
Editing a Markdown card in Safari causes the browser to crash.

## To Reproduce
Steps vary, normally occurs when editing a Markdown card in a post. Following steps where how I discovered it:
1. Create a new post
2. Add a Markdown card
3. Add content to card
4. Attempt to escape the card

## Technical details
- Ghost Version: 2.31.0
- Node Version: -
- Browser/OS: Safari v13.0.1 / macOS Mojave
- Database: Pro account

Originally reported here: https://twitter.com/tehwey/status/1176901401454116864

**Comment by zebity** [comment] 2019-09-30 12:14
Hi Ghoster's,

I can confirm this bug with Safari 13.0.1.

In my case when I add image card and click to add image, Safari hangs with spinning cursor.

I had to do to "Force Quit" to kill browser, which then generated crash report.

To did a ghost update to ensure I had latest and greatest ghost version but problem was still there.

My updated ghost installation is now on: 
Ghost-CLI version: 1.10.1
Ghost version: 2.31.1

As work around I did not editing with FireFox.

Regards,

Zebity.

**Comment by roelvanderkraan** [comment] 2019-10-10 15:57
I also confirm this bug when making a Header on Safari 13.0.2 / Mac Mojave 10.14.6.
### To reproduce: 

1. Create a new post, 
2. select some text
3. change it to a Header using the "H" button

Then Safari crashes, I have to force quit.

### Info
Ghost CLI: 1.11.0
Ghost: 2.34.0

**Comment by octave** [comment] 2019-10-11 16:55
Same issue with same versions.

**Comment by codykrieger** [comment] 2019-10-25 00:07
I believe my comment in #11257 is also applicable here: https://github.com/TryGhost/Ghost/issues/11257#issuecomment-546143195

**Comment by codykrieger** [comment] 2019-10-25 00:08
Which is to say, Safari 13.0.2 (14608.2.40.1.3) fixes this (the “.3” at the end of the WebKit version in parentheses is important).

**Comment by roelvanderkraan** [comment] 2019-10-25 08:21
Yes, for me the issue is fixed on Safari 13.0.2 (14608.2.40.1.3). First thought it was fixed in ghost v3 but on a v2 site it is also working as expected again.

**Comment by zebity** [comment] 2019-10-25 22:02
Hi Ghoster's,

I have  also confirmed with ghost / CLI:
Ghost-CLI version: 1.11.0
Ghost version: 2.31.1 (at /var/www/ghost)

and Safari 13.0.2 (15608.2.30.1.1) on MacOS Catalina that ghost posting and editing is now working.

I believe that this issue can be closed.

Cheers,

Zebity

**Comment by kevinansfield** [comment] 2019-10-28 16:20
I'm also no longer experiencing issues. Closing this as it was a bug in Safari itself that has been fixed in Safari 13.0.2 (15608.2.30.1.1).

**Closed by kevinansfield** 2019-10-28 16:20 UTC
Labels: admin-client, bug, help wanted
