### ISSUE TITLE
Pressing enter no longer works on user-account creation

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8663] opened 2017-07-07 14:40 UTC
Previously, pressing enter in this box would submit the form -- that no longer works (1.0-beta2)

![image](https://user-images.githubusercontent.com/120485/27962652-71c5a0d4-632a-11e7-932c-93bc95d5211a.png)

**Comment by kevinansfield** [comment] 2017-07-07 14:48
Same root cause as https://github.com/TryGhost/Ghost/issues/8588 and https://github.com/TryGhost/Ghost/issues/8639. There is a PR open in https://github.com/TryGhost/Ghost-Admin/pull/771 so I'll close this for now to keep the issue list clear.

**Closed by kevinansfield** 2017-07-07 14:48 UTC
Labels: admin-client, bug
