### ISSUE TITLE
Problem with attribute values that have `==` text in them

### ISSUE THREAD

**Issue by theoros** [TryGhost/Ghost#7647] opened 2016-10-31 00:22 UTC
### Issue Summary

Hello guys, I'm evaluating Ghost as a platform for highly interactive posts. Topic is mostly UI engineering & data visualization using D3 and Angular.

So I was experimenting with it and noted that some HTML attribute values get transformed as if they were markdown.

When publishing a post, it somehow transforms this:

``` html
<div class="fluid-svg" ng-if="vm.demo == 'fluid-svg'">
```

Into this:

``` html
<div class="fluid-svg" ng-if="vm.demo </mark> 'fluid-svg'">
```

You can see the problem in action here: http://theoria-ui.ghost.io/theoria-ui-exp1/
### Steps to Reproduce

I added the following code into a Ghost post (it's somewhat big):

``` html
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.1/angular-material.min.css">

<script src="https://d3js.org/d3.v4.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-animate.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-aria.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-messages.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.1/angular-material.min.js"></script>

<script>
  ( function() {
    'use strict';

    // Add Angular Material dependency
    angular.module( 'ui.theoria', ['ngMaterial'] );
  } )();

  ( function() {
    'use strict';

    // This controller is used only to drive the demo
    // You should not be using embedded controllers in your views
    // It's recommended that you move away from that, and use them for router states, and inside components
    //
    // I will use this controller for setting demo variables

    angular.module( 'ui.theoria' ).controller( 'AppController', AppController );

    function AppController( $log ) {
      var vm = this;

      vm.$onInit = $onInit;
      vm.setAspectRatio = setAspectRatio;
      vm.doubleValues = doubleValues;


      function $onInit() {
        $log.info( 'AppController', vm );

        vm.demos = ['fluid-svg', 'configurable-svg'];

        // Set initial demo
        vm.demo = vm.demos[1];

        // Set initial width and height
        vm.width = 12;
        vm.height = 12;

        // List of known aspect ratios
        vm.commonAspectRatios = [
          {
            value: '21:9',
            label: 'Cinema'
          },
          {
            value: '16:9',
            label: 'Modern monitor'
          },
          {
            value: '4:3',
            label: 'Old monitor'
          }
        ];
      }

      function doubleValues() {
        vm.width = vm.width * 2;
        vm.height = vm.height * 2;
      }

      function setAspectRatio( aspectRatio ) {
        var items = aspectRatio.split( ':' );
        vm.width = parseInt( items[0] );
        vm.height = parseInt( items[1] );
      }
    }
  } )();

  ( function() {
    'use strict';

    var configurableSvg = {
      bindings: {
        height: '<', // you should be using one-way bindings!
        width: '<'
      },
      controller: controller,
      controllerAs: 'vm',
      template: '<div class="container"></div>'
    };

    angular.module( 'ui.theoria' ).component( 'configurableSvg', configurableSvg );


    function controller( $element, $log ) {
      var vm = this;

      vm.$onChanges = $onChanges;
      vm.$onInit = $onInit;
      vm.$postLink = $postLink;


      function $onChanges( changes ) {
        var updateViewBox = false;

        if( changes.height && !changes.height.isFirstChange() ) {
          updateViewBox = true;
        }

        if( changes.width && !changes.width.isFirstChange() ) {
          updateViewBox = true;
        }

        if( updateViewBox ) {
          viewBoxUpdate();
        }
      }

      function $onInit() {
        $log.info( 'configurableSvg', configurableSvg );
      }

      function $postLink() {
        visualizationSetup();
        demoAddRect();
      }

      function demoAddRect() {
        vm.svg.append( 'rect' )
          .classed( 'little-rect', true )
          .attr( 'x', 1 )
          .attr( 'y', 1 )
          .attr( 'width', 5 )
          .attr( 'height', 5 )
      }

      function viewBoxUpdate() {
        vm.svg
          .transition()
          .duration( 750 )
          .attr( 'viewBox', '0 0 ' + vm.width + ' ' + vm.height );
      }

      function visualizationSetup() {
        vm.container = $element[0].querySelector( '.container' );

        vm.svg = d3.select( vm.container )
          .append( 'svg' );

        viewBoxUpdate();
      }
    }
  } )();

</script>

<div ng-cloak ng-app="ui.theoria">
  <md-content class="md-padding" ng-controller="AppController as vm">
    <pre>Demo {{ vm.demo | json }}</pre>
    <md-button class="md-raised" ng-class="{ 'md-primary': demo == vm.demo }" ng-click="vm.demo = demo" ng-repeat="demo in vm.demos">{{ demo }}</md-button>
    <div class="fluid-svg" ng-if="vm.demo == 'fluid-svg'">
      <md-card>
        <md-card-header>
          <md-card-avatar>
            <md-icon>widgets</md-icon>
          </md-card-avatar>
          <md-card-header-text><span class="md-headline">Fluid SVG</span><span class="md-subhead">UI Theoria</span></md-card-header-text>
        </md-card-header>
        <md-card-content>
          <div class="demo" layout="row" layout-align="space-between center">
            <div class="demo-item" flex="30"><small>.demo flex=30</small>
              <fluid-svg></fluid-svg>
            </div>
            <div class="demo-item" flex="60"><small>.demo flex=60</small>
              <fluid-svg></fluid-svg>
            </div>
          </div>
          <div class="demo" layout="row" layout-align="space-between center">
            <div class="demo-item" flex><small>.demo flex=100</small>
              <fluid-svg></fluid-svg>
            </div>
          </div>
        </md-card-content>
      </md-card>
    </div>
    <div class="configurable-svg" ng-if="vm.demo == 'configurable-svg'">
      <md-card>
        <md-card-header>
          <md-card-avatar>
            <md-icon>widgets</md-icon>
          </md-card-avatar>
          <md-card-header-text><span class="md-headline">Configurable SVG</span><span class="md-subhead">UI Theoria</span></md-card-header-text>
        </md-card-header>
        <md-card-content>
          <p>The width and height below, are not the real width and height of the SVG element. They represent the aspect ratio you want it to have.<br>Nevertheless, they will determine the quantities you use for positioning stuff in it (that is, until you start using D3 scales, then it won't matter much).</p>
          <div class="inputs">
            <md-button class="md-accent md-raised md-icon-button" href ng-click="vm.doubleValues()"><span>x2</span></md-button>
            <md-input-container>
              <label>Width</label>
              <input min="1" ng-model="vm.width" size="7" type="number">
            </md-input-container>
            <md-input-container>
              <label>Height</label>
              <input min="1" ng-model="vm.height" size="7" type="number">
            </md-input-container><span> Aspect ratio: <strong>{{ vm.width/vm.height | number:3 }}:1</strong></span>
          </div>
          <blockquote>
            <p>What this means is: I want its <strong>width</strong> to be {{ vm.width/vm.height | number:3 }} times as it's tall.<br>It also means: I want its <strong>height</strong> to be {{ vm.height/vm.width | number:3 }} times as it's wide.</p>
          </blockquote>
        </md-card-content>
        <md-divider></md-divider>
        <md-card-content>
          <div class="buttons">
            <p>Here are some common <strong>aspect ratio</strong> samples:</p>
            <md-button class="md-raised" href ng-click="vm.setAspectRatio( aspectRatio.value )" ng-repeat="aspectRatio in vm.commonAspectRatios"><span>{{ aspectRatio.label }}</span><small> {{ aspectRatio.value }}</small></md-button>
            <p>Here below you'll see three instances of the <strong>configurable-svg</strong> component that react to width and height changes.<br>
            <p><em>The small yellow square is 5x5 and it's positioned at (1,1) coordinates.</em></p>
            </p>
          </div>
          <div class="demo" style="width: 100px; float:left"><small>.demo 100px</small>
            <configurable-svg width="vm.width" height="vm.height"></configurable-svg>
          </div>
          <div class="demo" style="width: 200px; float:left"><small>.demo 200px</small>
            <configurable-svg width="vm.width" height="vm.height"></configurable-svg>
          </div>
          <div class="demo" style="width: 400px; float:left"><small>.demo 400px</small>
            <configurable-svg width="vm.width" height="vm.height"></configurable-svg>
          </div>
        </md-card-content>
      </md-card>
    </div>
  </md-content>
</div>
```

If you observe the source code on the post after you publish, you'll see this:

``` html
<md-button class="md-raised" ng-class="{ 'md-primary': demo <mark> vm.demo }" ng-click="vm.demo = demo" ng-repeat="demo in vm.demos">{{ demo }}</md-button>
<div class="fluid-svg" ng-if="vm.demo </mark> 'fluid-svg'">
```

I would expect the `==` that's inside HTML not to be transformed into `<mark>` and `</mark>`.

I'm new to Ghost, if I'm missing something please let me know.
### Technical details:
- Ghost Version: Latest online
- Node Version: N/A
- Browser/OS: N/A
- Database: N/A

**Comment by disordinary** [comment] 2016-11-01 11:24
Hi @theoros,

Our markdown rendering code is based on a list of regular expressions which are unfortunately largely indiscriminate and highly dependent on order. There are a number of similar bugs and I'll recommend we close this one in favor of issue #5587, they are not identical but fixing one will fix the other.

Ghost 1.0 will be released this year and has the ability to render multiple content types, including standard HTML which is unprocessed by any markdown converter, this should make what you're trying to do much easier if you can wait until then.

**Closed** 2016-11-01 11:36 UTC

**Comment by theoros** [comment] 2016-11-02 03:27
@disordinary Thank you for the response.

Yes, I can wait. Too bad my 14 day trial period is going to expire, or is it coming pretty soon?

**Comment by ErisDS** [comment] 2016-11-02 09:24
@theoros we're not going to be shipping fixes to our old editor as our focus is on replacing it. 

You can work around this issue by including your script via a custom post template in your theme, rather than adding all the script content into the editor (this isn't really what it's intended for!). so if your post is called "my awesome post", it will have a slug of my-awesome-post, and so if you add a template called `post-my-awesome-post.hbs` to your theme, which includes all of your custom javascript, that will render for just this post. Theme docs can be found here: http://themes.ghost.org/docs/templates

**Comment by theoros** [comment] 2016-11-02 12:29
Thanks for the explanation @ErisDS, hope that takes care of my problem.

Although the problem isn't with the JavaScript rendering, but on some HTML attribute values.

**Comment by ErisDS** [comment] 2016-11-02 12:58
@theoros sure, the issue is with attribute values that are using a templating language that is then being interpreted by JavaScript. The main use-case for Ghost's editor is writing long-form content, however here it is being used as a code-editor to write an angular app! 

In most cases, where small snippets of JS might be added to the editor, these would work - however you've gone far, far beyond what I'd expect to see in the editor and therefore what the editor has been tested against or optimised for.

The use of a custom template is much more suitable for your particular use case.

**Comment by theoros** [comment] 2016-11-02 13:01
@ErisDS Thanks, will try it out and let you know of my findings!
