### ISSUE TITLE
Inclusion of {{tags}} helper corrupts handlebar output

### ISSUE THREAD

**Issue by chrisjpatty** [TryGhost/Ghost#12606] opened 2021-02-07 23:18 UTC
I've forked the latest Casper theme and made a very small change to show all tags on each post in the main list of posts, and I've discovered a bug in the Handelbars helper for tags. When I render this block of html without the `{{tags}}` helper, it works just fine:

```html
<a class="post-card-content-link" href="{{url}}">
  <header class="post-card-header">
    <h2 class="post-card-title">{{title}}</h2>
  </header>
  <section class="post-card-excerpt">
    {{#if feature_image}}
    <p>{{excerpt words="30"}}</p>
    {{else}}
    <p>{{excerpt words="44"}}</p>
    {{/if}}
  </section>
</a>
```

And the HTML that it outputs looks like this:

```html
<div class="post-card-content">
   <a class="post-card-content-link" href="/2021-02-things-are-looking-up/">
      <header class="post-card-header">
         <h2 class="post-card-title">Things Are Looking Up</h2>
      </header>
      <section class="post-card-excerpt">
         <p>Excerpt of the blog post</p>
      </section>
   </a>
</div>
```

BUT as soon as I add the tags helper like this:

```html
<a class="post-card-content-link" href="{{url}}">
  {{tags}}
  <header class="post-card-header">
    <h2 class="post-card-title">{{title}}</h2>
  </header>
  <section class="post-card-excerpt">
    {{#if feature_image}}
    <p>{{excerpt words="30"}}</p>
    {{else}}
    <p>{{excerpt words="44"}}</p>
    {{/if}}
  </section>
</a>
```

The output of the HTML is suddenly all corrupted:

```html
<div class="post-card-content">
  <a class="post-card-content-link" href="/2021-02-things-are-looking-up/">

  </a>
  <header class="post-card-header">
    <a class="post-card-content-link" href="/2021-02-things-are-looking-up/">

    </a>
    <a href="/tag/medical-school/">Medical School</a>,
    <a href="/tag/skylar/">Skylar</a>
    <h2 class="post-card-title">Things Are Looking Up</h2>
  </header>
  <section class="post-card-excerpt">
    <p>Excerpt of the blog post</p>
  </section>
</div>
```

This also happens when using the `{{foreach tags}}` helper. Has anyone else seen this problem? I'm assuming this is actually a bug in the tags helper implementation, but is there something obvious in my handlebars code that would be causing this issue?

Ghost version: Ghost Version: 3.41.3
Casper version: 3.1.2
Node Version: v14.15.4
Browser: Chrome 87 on Mac 10.15.1

**Comment by fueko** [comment] 2021-02-08 14:13
Hi @chrisjpatty, the problem is not the {{tags}} helper but that you are nesting an `<a>` inside an `<a>` which is not allowed in HTML:

> Links and anchors defined by the `<a>` element must not be nested; an `<a>` element must not contain any other `<a>` elements.

**Comment by ErisDS** [comment] 2021-02-08 14:49
There's already a forum post here: https://forum.ghost.org/t/bug-when-using-tags-helper/20051 - closing this as a support request, it's not a bug.

**Closed** 2021-02-08 14:49 UTC
Labels: support-request
