### ISSUE TITLE
Error during upgrade from 3.21.1 to 3.22.1

### ISSUE THREAD

**Issue by Laul0** [TryGhost/Ghost#12005] opened 2020-07-05 00:09 UTC
Because issue seems not be linked to the Docker version, here a link to the concerned bug during the upgrade Ghost from 3.21.1 to 3.22.1.

https://github.com/docker-library/ghost/issues/228

**Comment by ErisDS** [comment] 2020-07-06 10:00
Please do not raise issues without using search and filling out the template.

Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/11993

**Closed by ErisDS** 2020-07-06 10:00 UTC
