### ISSUE TITLE
Firefox editor pane widths don't fit to the viewport

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#5804] opened 2015-09-04 15:54 UTC
Tested in Firefox 40.0.2 - FF ignores the `max-width: 100%` that is set on `img` elements within the editor preview resulting in the split pane and mobile preview sizes being out of whack (see image below).

Adding a `width: 100%` style to images in the preview fixes the pane sizes but is not a viable solution as any small images will now always be full-width.

<img width="1101" alt="screen shot 2015-09-04 at 16 50 04" src="https://cloud.githubusercontent.com/assets/415/9688110/2569f206-5325-11e5-9e3b-48a392b6b311.png">

**Comment by pheinecke** [comment] 2015-09-05 00:46
Just tested it with Internet Explorer 11. Same problem there.

**Comment by ConnorKrammer** [comment] 2015-09-07 00:53
I'd like to mention that I had this as well, though it was sporadic and I couldn't reproduce it.

**Comment by pheinecke** [comment] 2015-09-07 01:37
@ConnorKrammer Did you try to reproduce it with large images (like 2000x2000px)? For me it is a constant issue and nothing sporadic.

**Comment by ConnorKrammer** [comment] 2015-09-07 01:42
@pheinecke I wasn't very rigorous about it at the time because I was in the middle of something and didn't have time to spare, but I did have my suspicions that it had to do with large images. Here's what happened:

- I upgraded Ghost to 0.7.0.
- I hit 'edit' on the changelog draft that automatically gets added after an upgrade.
- I saw that the pane was overflowing the right side.
- I then deleted the draft, and created a new (empty) one to see if it would happen again.
- This time it didn't, so I left it alone.

**Comment by schuer** [comment] 2015-09-07 08:54
Same issue here. Firefox 40 and 42dev.

**Comment by kevinansfield** [comment] 2015-09-09 10:01
I've pushed a tentative fix in #5820. @pheinecke, @ConnorKrammer, @schuer: If you are able to checkout that PR and test (especially in IE as I haven't been able to test that) it would be very much appreciated.

**Comment by pheinecke** [comment] 2015-09-09 12:00
FF 40: 
![screenshot 2015-09-09 13 59 53](https://cloud.githubusercontent.com/assets/11636168/9761140/1a4b6c9a-56fb-11e5-9ed5-f081b4e81311.png)

IE 11: 
![screenshot 2015-09-09 13 57 30](https://cloud.githubusercontent.com/assets/11636168/9761149/2ca733ec-56fb-11e5-8940-36774b681c63.png)

**Comment by schuer** [comment] 2015-09-09 12:43
IE 10 + 11 broken (according to @pheinecke ’s screens).
Edge, FF 40 + FF 42 are fine.

**Comment by kevinansfield** [comment] 2015-09-09 12:53
Thanks guys, thought it might have been a bit of a long shot with IE. I'll get my windows VMs working again and take another shot at it.

**Comment by kevinansfield** [comment] 2015-09-11 12:15
I've pushed an update to that PR which should fix IE11. I've not found a fix for IE10 yet but it seems to have a host of other issues related to flexbox so probably better to handle those separately.

**Comment by ConnorKrammer** [comment] 2015-09-13 20:58
I haven't had a chance to test out the fix by @kevinansfield, but I'd like to mention that creating an open `<pre>` tag has the effect of increasing the edit pane's width and almost pushing the preview pane off the right edge of the screen. Entering  a closing `</pre>` tag makes it go back to normal. (Interestingly, the closing angle bracket doesn't seem to be needed: `</pre` is enough to restore the original widths.)

**Comment by ErisDS** [comment] 2015-09-14 11:45
I can reproduce the `<pre>` tag issue, however it doesn't happen on brand new posts or posts with small images, so I think it is strongly related to overflowing images?

It is happening for me in chrome on the 'you've been upgraded' post, even with the #5820 fix applied.

**Comment by kevinansfield** [comment] 2015-09-14 13:18
The issue with `<pre>` tags is happening because the invalid HTML is output directly in the preview which the browser then attempts to automatically fix by wrapping everything in the preview after the beginning `<pre>` in a `<pre>` tag. That would also explain why it only causes problem with existing content but there are no issues on new/blank posts.

**Comment by ErisDS** [comment] 2015-09-14 18:22
That makes sense. The fact that this causes the editor pane widths to jump around is going to need a fix though :disappointed:

**Comment by JohnONolan** [comment] 2015-09-18 09:23
@kevinansfield it's up to you how to fix this, but it doesn't sound to me like an inherent problem with flexbox. It sounds to me like the editor producing unreliable output so it needs an additional wrapping element to "cushion" it against its flexbox container.

**Comment by kevinansfield** [comment] 2015-09-18 09:33
I've tried that, the problem I've been running into is that everything is % based but the way the browser model works with the current setup is that % width can be influenced by certain children elements without fixed widths which then blows everything out. FF and IE naturally treat this slightly differently to WebKit/Blink and will wilfully ignore % widths/max-widths and calculate based on children elements to an even greater degree.

I'll have another stab at this once I'm done with the navigation fixes but it's looking increasingly like there may need to be a javascript fix in there somewhere to force pixel widths :-1:

**Comment by JohnONolan** [comment] 2015-09-18 09:59
what about just making the entire editor a table? or at least divs styled with display:table ? then wouldn't need to define widths, right?

**Comment by kevinansfield** [comment] 2015-09-18 10:04
I'll try all the options again, it's possible I missed the magic incantation that stopped children's widths leaking up the tree.

**Comment by JohnONolan** [comment] 2015-09-18 10:08
or we just forget the `<pre>` bug until the next iteration of the editor
it's hard to guard against invalid HTML with on the fly rendering

**Comment by schuer** [comment] 2015-09-18 10:10
Hotfix: add `width: 1px` to the first section in main.
Successfully tested in FF 42dev, Chrome 45 and IE 11.

<img width="608" alt="screenshot 2015-09-18 12 08 32" src="https://cloud.githubusercontent.com/assets/1297466/9957130/00118184-5dfe-11e5-85c7-ef8dd0972478.png">

**Comment by kevinansfield** [comment] 2015-09-18 10:15
@JohnONolan I think the large images issue is definitely a higher priority, the fix for that is ready as per #5820 although I think IE10 may still have issues.

@schuer Thanks, I'll look into that, do you have any info on why that hotfix works? I generally like to understand what's happening under the hood for layout issues so that we can avoid hacks where possible or at least know what may trip us up in the future.

**Comment by schuer** [comment] 2015-09-18 10:20
@kevinansfield I can’t explain. It’s just a sort of shrinking flex elements and forcing the browser to recalculate stuff.

**Comment by kevinansfield** [comment] 2015-09-18 10:51
@shuer There's some precedent for the 1px fix here http://stackoverflow.com/questions/8405167/css3-box-flex-box-size-differs-depending-on-inner-content

As per the last answer there I think it essentially boils down to flexing being applied _after_ preferred sizes of the boxes have been calculated (matches the behaviour I've been seeing) and because we were using % widths everywhere the browser doesn't know what to shrink so it just matches the content. With the 1px width applied the browser first forces the content to the guaranteed-to-fit width then applies flexing to expand the boxes to fill the container.

I'll put another PR together and test a bit more thoroughly, it may be that this fix supersedes the fix in #5820 too.

/cc @JohnONolan

**Comment by JohnONolan** [comment] 2015-09-18 11:03
sounds good to me, final call is yours @kevinansfield

**Closed** 2015-09-25 08:08 UTC
Labels: blocker, bug, css
