### ISSUE TITLE
Wrong cursor position when editing a post in Safari. 

### ISSUE THREAD

**Issue by cityhunter14** [TryGhost/Ghost#11276] opened 2019-10-27 07:47 UTC
### Issue Summary

Wrong cursor position when editing a post in Safari. 

---
### To Reproduce

1. Edit a post on safari.
![CursorPositionOnSafari](https://user-images.githubusercontent.com/5357317/67631403-e0358280-f8d0-11e9-92c0-986fd4525a5f.gif)

This does not happen in Chrome.
![CursorPositionOnChrome](https://user-images.githubusercontent.com/5357317/67631406-ecb9db00-f8d0-11e9-8c0c-91511800f5b1.gif)

---
### Technical details:
* Ghost Version: 3.0.0
* Node Version: v10.16.3
* Browser/OS: Safari v13.0.2 (14608.2.40.1.3) / macOS Mojave
* Database: sqlite3
* Environment:  development

**Comment by kevinansfield** [comment] 2019-10-28 09:01
@cityhunter14 I'm not able to reproduce this with Safari 13.0.2 on Mojave using an en-GB keyboard layout. Are you using a non-English keyboard layout?

**Comment by cityhunter14** [comment] 2019-10-28 11:32
> @cityhunter14 I'm not able to reproduce this with Safari 13.0.2 on Mojave using a British keyboard layout. Are you using a non-English keyboard layout?

Thank you for replying.
Yes, I'm using a Japanese keyboard layout(Roma Mode). 
I'm not able to reproduce this using a US keyboard layout too.
Is it a bug of Mojave?

**Comment by kevinansfield** [comment] 2019-10-28 16:00
This sounds like it's another instance of this bug https://github.com/bustle/mobiledoc-kit/issues/589.

It's not Mojave specific, it's more to do with how browsers handle+expose (or don't expose) certain types of keyboard events and how the editor tries to deal with content changes when there's no event. Closing this issue as it's being tracked upstream.

**Closed by kevinansfield** 2019-10-28 16:00 UTC
Labels: needs info
