### ISSUE TITLE
Speed up Casper tests

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#5330] opened 2015-05-25 13:18 UTC
Is it possible to replace our custom casper implementation with something like https://github.com/ronaldlokers/grunt-casperjs to take advantage of *Async Parallel* and speed up our Casper tests significantly?

**Comment by ErisDS** [comment] 2015-05-28 14:01
I have taken a brief look at that module, and it doesn't seem like it's going to work for us. I only tried it briefly but not sure that we can configure it to do the things we want to. 

Second problem - the way the parallellallisation is done is using deprecated features from grunt.

My recommendation would be to rewrite our own casper spawning util, such that each file is split out and run as a parallel/concurrent task, and have the runner start them all and manage them using promises.

This concept of parallelising the tests could be extended to use something like https://github.com/sindresorhus/grunt-concurrent to run the functional tests, unit tests and ember unit tests all at the same time - as they should be safe to run together. 

All of the other tests use the same DB I think, so need to be in series (but are pretty fast anyway).

**Comment by ErisDS** [comment] 2015-06-27 20:38
Rather than trying to run individual bits of the tests concurrently, we should definitely do this: http://docs.travis-ci.com/user/speeding-up-the-build/

Using this mechanism, we could run our unit tests, integration & route tests as one suite and the casper (or whatever we replace them with) tests as a separate 'suite' which only runs once (say on the first build)  sort of how we're discussing here: https://github.com/TryGhost/Ghost/issues/2029#issuecomment-116137159

**Comment by hoxoa** [comment] 2015-06-30 19:13
Will take a look at this.

Another thing regarding speed, on every build (merge and PR) these two task are executed `shell:ember:init`and `shell:bower` which download and install a lot of modules. Why not caching them, too? 

Just tested that, see [`travis.yml`](https://github.com/hoxoa/Ghost/blob/travis-test/.travis.yml) and the build [here](https://travis-ci.org/hoxoa/Ghost/builds/68879699). It's not much faster, but a bit.

**Comment by ErisDS** [comment] 2015-07-01 22:57
Caching in the build was implemented when we only had npm modules, and I don't think anyone's really thought about it since then. This seems like a smart move :)

**Comment by hoxoa** [comment] 2015-07-08 20:26
I have a working version. The average build time currently is `nearly 2 hours`, when running casper test only once it goes down to `nearly 1 hour` (half the time).

I made a script which checks for the first job and then runs the casper tests every build on the first job (merge + pr).  The new travis task is executed by travis on every job and when it's the first, than the functional task is also executed. I changed it this way, because everyone who knows that he runs `npm test` or `grunt validate` can do this furthermore and travis knows what to do, too.

You can see two working builds here, [first](https://travis-ci.org/hoxoa/Ghost/builds/69045933) and [second](https://travis-ci.org/hoxoa/Ghost/builds/69319377).

The first one looks a bit different because I forgot the `-- verbose`.

The different between the both is, that the second has the script in a `.sh file` in the new `scripts` folder and on the first, the script is in the `travis.yml` file.
When you check the output (first [here](https://travis-ci.org/hoxoa/Ghost/jobs/69045935#L2424) and second [here](https://travis-ci.org/hoxoa/Ghost/jobs/69319379#L2639)), the second – in my opinion – is much cleaner because only the `echos` are outputted and not the whole script . 

When whe choose the second, I will put the code coverage script in the scripts folder, too.

**Comment by ErisDS** [comment] 2015-07-09 14:25
Hey there @hoxoa thanks for plugging away on this. I really like that you show different approaches, it's really helpful :+1: 

My personal preference would be to keep the scripts inside the `travis.yml` file - the first option. As the scripts are only used by travis, I think it's better to keep the code in the travis file, so that it's straightforward to understand for anyone new to the repo. Adding more files also adds clutter to the root of the repository.

If the scripts were used in multiple places, it might make more sense, but for now I think stick to the first option.

Otherwise this is looking awesome, cutting our build times in half! :dancers:

**Comment by hoxoa** [comment] 2015-07-10 15:00
@ErisDS Thanks. 

Ok, then I will make a PR with the first option. 

Is the way I implemented this, with the changes in the `Gruntfile` ok?

**Comment by jaswilli** [comment] 2015-07-10 15:40
Why is it okay to only run the functional tests against one configuration in the build matrix?  Just because everything looks alright with node v0.10.40 and sqlite3 doesn't mean it's working for any other combination of node and database versions.

The first priority should be fixing the things that cause the builds to fail.  Only a very, very small number of "random travis failures" are truly caused by a hiccup on travis--most of them are triggered by bugs.

If there's a feeling that the overall build time is too long I'd much rather just drop support for io.js v1.2.0.  Anyone inclined to be using io.js is almost certainly not going to be using version 1.2.0--testing against it likely provides no one any useful information.

**Comment by ErisDS** [comment] 2015-07-10 17:48
I was rather thinking to run the functional tests for one of each DB and node env - so they would run 3 times. node 0.10 + sqlite, node 0.12 + mysql & io.js + pg. I thought I had written that in here :/ 

The database is highly unlikely to affect the functional tests, and therefore I think running these tests 9 times is redundant - I think one per node version is enough?

> Only a very, very small number of "random travis failures" are truly caused by a hiccup on travis--most of them are triggered by bugs.

It seems to me that these are as likely to be bugs in the tests as they are bugs in the code and it concerns me that it's so difficult to track down the cause when an issue does arise. I think moving towards relying more heavily on ember unit tests is a sensible long term plan?

**Comment by ErisDS** [comment] 2015-10-09 15:46
Going to close this as the current plan is to remove the casper.js tests in favour of something else. @kevinansfield is working on the plan for this.

**Closed by ErisDS** 2015-10-09 15:46 UTC
Labels: tests
