### ISSUE TITLE
Copy & paste post title can cause special chars in slug

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost#9826] opened 2018-08-27 09:10 UTC
When a post is created and the title is being copied and pasted from another source, some special chars e.g. control chars or whitespaces, are included in the slug. Ghost can't handle those and returns a 404 for the requested post.

Those special chars (e. g. `0x08`) need to be stripped out from the title & slug.

### Example:

DB:
slug: kp-video-unofficial-201
title: 201柯文哲 北市長選舉非官方競選影片

Visible on site:
slug: kp-video-unofficial-2018%08
title: 2018�柯文哲台�北市長選舉非官方競選影片

**Comment by lunaticmonk** [comment] 2018-08-28 17:52
@AileenCGN I tried copy pasting a title like: "test & test # test", however in the slug, the special characters were removed and the slug was like: `/test-test-test`. Hence, I could not reproduce this one. Am I missing something here? Please let me know and I will give it a try.

**Comment by ErisDS** [comment] 2018-08-29 10:11
The character that is being included is specifically the control char `0x08` (backspace). There may be other control chars that are included incorrectly.

**Comment by adamwatters** [comment] 2018-09-12 19:59
@AileenCGN @ErisDS - can you explain how you got the backspace character onto the clipboard for copy/pasting?

**Comment by Bored0ne** [comment] 2018-10-04 17:37
Has anyone fixed this yet, or do they mind if I take a stab at it?

**Comment by kirrg001** [comment] 2018-10-04 18:00
@Bored0ne Not fixed. The issue is still open.

>  do they mind if I take a stab at it?

👍 Happy about any help :)

**Comment by dexterleng** [comment] 2018-12-06 12:16
I can't replicate this :/

**Comment by kevinansfield** [comment] 2018-12-06 12:45
If you're on macOS it's possible to replicate by using the Character Viewer (https://stackoverflow.com/a/4946245/1163866 - slightly different on recent macOS versions but the principle is the same) to insert the control characters.

**Comment by gargol** [comment] 2018-12-13 11:57
As the non-printable characters in **slugs** issue is being addressed in https://github.com/TryGhost/Ghost/pull/10252, are we also to do the change to strip these characters in post titles or leaving them as is?

**Comment by kirrg001** [comment] 2019-01-02 14:47
> are we also to do the change to strip these characters in post titles or leaving them as is?

@gargol I think this depends what happens if we don't do it? This report is about posts can't be served, because the slug was not correctly stripped. It looks to me this was fixed via https://github.com/TryGhost/Ghost/commit/8c3d29edb2a0a7e8d86e064796ca52ad2de780d3.

**Comment by gargol** [comment] 2019-01-02 15:20
@kirrg001 I think the problem with these characters in titles/content might surface when we try serving them in XML (for example as a part of sitemaps). Would need to investigate this specific use-case, but I remember that's the place I had a problem at.

The original issue is fixed, so I think it could be closed. We'd raise a new one if XML suspicion is confirmed :+1:

**Closed by gargol** 2019-01-02 15:20 UTC
Labels: bug, good first issue, help wanted, server
