### ISSUE TITLE
Static home page: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by netmojo** [TryGhost/Ghost#11318] opened 2019-11-03 19:28 UTC
I'm using Ghost 3.0.2 with the default Casper theme, and a static home page setup according to the [static home page instructions](https://ghost.org/tutorials/custom-home-page/). I get the following error when accessing my static home page:

```
[2019-11-03 19:01:17] INFO "GET /" 304 53ms
[2019-11-03 19:01:17] INFO "GET /favicon.png" 200 3ms
[2019-11-03 19:01:19] ERROR Cannot read property 'name' of null

Cannot read property 'name' of null

----------------------------------------

TypeError: Cannot read property 'name' of null
    at getPostSchema (/var/lib/ghost/versions/3.0.2/core/frontend/meta/schema.js:84:65)
    at getSchema (/var/lib/ghost/versions/3.0.2/core/frontend/meta/schema.js:179:20)
    at /var/lib/ghost/versions/3.0.2/core/frontend/meta/index.js:101:27
    at tryCatcher (/var/lib/ghost/versions/3.0.2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/3.0.2/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/lib/ghost/versions/3.0.2/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/3.0.2/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/var/lib/ghost/versions/3.0.2/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/var/lib/ghost/versions/3.0.2/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/var/lib/ghost/versions/3.0.2/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/var/lib/ghost/versions/3.0.2/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/lib/ghost/versions/3.0.2/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
```

My routes.yaml:
```
routes:
  /:
    data: 
      post: page.welcome
    template: page

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

If I edit schema.js to work-around the null object for name, the same way it does for metaDescription, like so:

```
author: {
            '@type': 'Person',
            name: data[context].primary_author ?
		escapeExpression(data[context].primary_author.name) : null,
            image: schemaImageObject(metaData.authorImage),
            url: metaData.authorUrl,
            sameAs: trimSameAs(data, context),
            description: data[context].primary_author.metaDescription ?
                escapeExpression(data[context].primary_author.metaDescription) :
                null
        },
```

Then it fails on other calls where it assumes ``data[context].primary_author`` is not null. Such as ``data[context].primary_author.website``.

How do I set ``data[context].primary_author?``. In the admin area, I have Full Name set in my "profile". 

It would be good to have data[context].primary_author default to an empty object with all of these properties, in the event that it is null, like my case.

**Comment by gargol** [comment] 2019-11-27 08:50
Hi @netmojo! I think I might have fixed this issue with this commit - https://github.com/TryGhost/Ghost/commit/157820419a947bf99ce1c6d84ed758d3fc718a6b. Let me know if the problem is still reproducible for you on the latest master?

**Comment by gargol** [comment] 2019-12-02 04:10
Closing it for now. Fee free to ping and reopen it if the bug it still happening ;)

**Closed by gargol** 2019-12-02 04:10 UTC
Labels: needs info
