### ISSUE TITLE
Authors not visually shown

### ISSUE THREAD

**Issue by JoeeGrigg** [TryGhost/Ghost#4977] opened 2015-03-02 14:15 UTC
# Users Page

![screen shot 2015-03-02 at 14 02 28](https://cloud.githubusercontent.com/assets/8267620/6442223/fa82bf72-c0e5-11e4-986f-861bbee0d191.png)

It clearly shows who are Owners, Admins and Editors but not Authors

# User Profile Page

![screen shot 2015-03-02 at 14 12 09](https://cloud.githubusercontent.com/assets/8267620/6442253/369130ca-c0e6-11e4-8815-acffafbb0314.png)

It shows Authors as Administrators.

When you press save it doesn't make them admins which is good however feel this should be filled with author from the start.

**Comment by novaugust** [comment] 2015-03-02 14:28
Hi @JoeeGrigg, thanks for the report.
To summarize your first issue, you're referring to the fact that the Author users don't have a badge saying `AUTHOR` next to their name, while every other role has a badge, right?  We had discussions around that when it was originally implemented, and made the conscious decision to go with the current implementation.

As for your second issue, I can't reproduce it. My Author users show the correct role.  Can you check out our [contributing bug reports](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs) guide and add some information on how I can get my page to show what you're seeing, as well as what version of ghost etc you're running.

Cheers

**Comment by ErisDS** [comment] 2015-03-02 14:33
Just to follow up, that second issue was fixed in 0.5.9. @JoeeGrigg if you upgrade you should find the problem gone. :)

**Closed by ErisDS** 2015-03-02 14:33 UTC
