### ISSUE TITLE
Footnotes restart numbering in each markdown card

### ISSUE THREAD

**Issue by redwardstern** [TryGhost/Ghost#12070] opened 2020-07-21 09:25 UTC
Welcome to Ghost's GitHub repo! 👋🎉

We use GitHub only for bug reports 🐛

Anything else should be posted to https://forum.ghost.org 👫

🚨For support, help & questions use https://forum.ghost.org/c/help
💡For feature requests & ideas you can post and vote on https://forum.ghost.org/c/Ideas

If your issue is with Ghost CLI, please report it on the CLI repo ➡️ https://github.com/TryGhost/Ghost-CLI/issues/new.

### Issue Summary
Fueko Keima Theme
Modified with PurrpleMajesty Footnote HBS
Chrome/Koenig/Markdown Card
When I manually give names to footnotes in a markdown card, they resolve a new list.

### To Reproduce
1) create a markdown card
2) create two footnotes (numbered or named)
3) create another markdown card
4) create two new footnotes (numbered or named)
5) the footnotes resolve to 1 and 2 no matter what you name them.

Expected: The Koenig editor would maintain the manual numbering
Actual: The Koenig editor restarts a numbered list.

![image](https://user-images.githubusercontent.com/8069587/88037097-529e6080-caf9-11ea-93a3-abeb85bb5a57.png)

### Technical details:

* Ghost-CLI version: 1.14.1
* Ghost version: 3.25.0 (reproduces at 3.11 as well)
* Node Version: v12.18.2
* Browser/OS: ChromeOS/Chrome
* Database: MYSQL

**Comment by ErisDS** [comment] 2020-07-21 10:37
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/9843

**Closed by ErisDS** 2020-07-21 10:37 UTC

**Comment by redwardstern** [comment] 2020-07-22 00:27
@ErisDS My understanding of the feature is that [^potato] [^tomato] should not convert to [^1] [^2]. 
I just want to have footnotes that I name instead of them being sanitized by the editor.

I'm converting everything to a single Markdown card.
