### ISSUE TITLE
Saying that post is only for subscribers when turning on member feature and then turning it off again

### ISSUE THREAD

**Issue by rblxploit** [TryGhost/Ghost#12006] opened 2020-07-05 21:32 UTC
### Issue Summary

I wanted to test how the member feature would make my website look, so I activated it. I bought a theme that has support for it. It looked like what I was expecting but because I did not need it, and it did remove it. The only problem was that the posts were only accessible to subscribers, at least that's what Ghost said. I know that you can set posts to be visible by everyone in the settings and I did that then saved. It worked but when I deactivate the member option completely, it goes back to saying that the posts were only accessible to subscribers. I could not read the articles. My VPS is Ubuntu 18.04 LTS and my browser is Chrome 83.

### To Reproduce

You need to have a theme that supports members, like [Lyra](https://github.com/TryGhost/Lyra)
1. Enable the member feature
2. Save
3. Disable the member feature 

There is no way to save it after, but it should disable it

You can also try those steps:
1. Enable the member feature
2. Enable the free member signup feature
3. Save
4. Disable the member feature 

### Technical details:

* Ghost-CLI version: 1.14.1
* Ghost version: 3.22.1 (at /var/www/ghost)
* Node Version: v10.21.0
* Browser/OS: Chrome 83 on Windows 10 Home
* Database: MySQL

**Comment by ErisDS** [comment] 2020-07-06 10:25
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/11990

**Closed by ErisDS** 2020-07-06 10:25 UTC
