### ISSUE TITLE
Can't edit links that aren't central

### ISSUE THREAD

**Issue by kevquirk** [TryGhost/Ghost#11389] opened 2019-11-12 17:22 UTC
### Issue Summary

When editing a link that wraps over a line in the admin editor, there is no obvious way to edit the link. This is because the edit popup appears centrally in the page, so when you move the cursor away from the link, the popup disappears.

### To Reproduce

1. Edit an existing link that wraps over top a new line
2. Hover over it to see the edit box (centre of screen)
3. Try to click on the pencil icon to edit the link
4. As soon as you move your mouse away form the link, the popup disappears

### Example screenshot

![](https://files.kevq.uk/link-edit.png)

### Technical details:

I'm using the latest official Ghost docker hub image.

This is similar to issue #10023 but I don't get an error.

**Comment by kevinansfield** [comment] 2019-11-12 17:25
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/9792

**Closed by kevinansfield** 2019-11-12 17:25 UTC
