### ISSUE TITLE
url not getting populated correctly within prev_post and next_post helpers

### ISSUE THREAD

**Issue by jglesner** [TryGhost/Ghost#10554] opened 2019-03-03 03:07 UTC
### Issue Summary
When using the next/prev helpers, {{ur}} populates as "/", rather than the expected post url. This occurs in v2.16.2, and does not appear to have been fixed as part of issue #10389. Other data does populate (e.g. feature_image, title) correctly.

I also noticed 'excerpt' is returning a string == 'undefined' when there is no human provided 'excerpt' in the post metadata.  However, doing a contentAPI query with the javascript client library, I see that a post does return an 'excerpt' even when a human doesn't type one into the excerpt field in the Admin web client. So I think that the {{excerpt}} data helper may not be working as intended in prev/next helpers either? 

### To Reproduce

1. Install 2.16.2
2. Open up a post in Casper theme
3. Scroll down to bottom to view next/previous
4. Notice that the href surrounding the next/previous links is just "/", rather than the post url.  

5. If you clear out the human provided 'except' of a post, you'll see 'undefined' where the excerpt should be on the prev_post and next_post in the casper theme.

### Technical details:

* Ghost Version: 2.16.2
* Node Version: 8.15.1
* Browser/OS: chrome 72.0.3626.10 OS X 10.14.2 Mojave
* Database: Sqlite3

Using the latest docker image for ghost (node:8-alpine) from https://github.com/docker-library/ghost/blob/master/2/alpine/Dockerfile

**Comment by SixBytesUnder** [comment] 2019-03-03 21:02
Came here to report the same. Happens to me on localhost and production. Both environments have Node 8.x if it makes any difference.

**Comment by gargol** [comment] 2019-03-04 05:24
Hey @jglesner wasn't able to reproduce the prev/next helper issue on the latest master. Seems like it was properly fixed at https://github.com/TryGhost/Ghost/issues/10389, could you please try if it occurs for you on master again and provide more specific reproduction steps in case it still happens :+1: New release will be out tomorrow, so might be easier to test again. 

Checking the other `excerpt` problem described here. 

Fyi, the docker image you linked to is [not officially supported](https://forum.ghost.org/t/official-docker-based-ghost-from-ghost-team-itself/1891) by the Ghost team :wink:

**Comment by gargol** [comment] 2019-03-04 05:49
Was able to only get `null` for `excerpt` field when there was no content in the post, wasn't able to reproduce showing `undefined`. Will tackle the `null` bug asap :+1:

**Comment by truekasun** [comment] 2019-03-04 07:19
Same issue. I have checked with few different ghost versions. This issue is not on Release 2.15.0. If you update to the 2.16.1, it comes. I checked the ghost blog to see if the issue persists on that. But it seems ghost blog also use 2.15.0.

If you need any additional information, I'm happy to provide and if possible, test the release too.

**Comment by gargol** [comment] 2019-03-04 07:40
@truekasun does this issue still happen for you in `master`? There is an issue in `2.16.1`, but it should've been fixed with a927aecc3f48aa0ecc898a2540bb13947f968980 , which will be included in next release (tomorrow). Thanks :smiley:

**Comment by truekasun** [comment] 2019-03-04 08:05
@gargol I'm not aware of how to install the master branch, I used to work with ghost-cli. Let's see if the mentioned changeset will fix the issue.

(Meanwhile, if you have documentation about installing (or perhaps setting up a development environment with the master branch, Please be kind enough to reply to me.)

**Comment by gargol** [comment] 2019-03-04 08:18
@truekasun the best way to get the master running locally is following our [Install from Source](https://docs.ghost.org/install/source/) guide.

**Comment by truekasun** [comment] 2019-03-04 08:57
@gargol Congrats! The issue is fixed in the `master`. Thank you very much!

**Closed** 2019-03-04 09:39 UTC
Labels: api, bug, content-api, needs info, server

**Comment by jglesner** [comment] 2019-03-05 01:04
Thank you @gargol for reviewing this issue so quickly and providing feedback.  I look forward to testing the forthcoming release!
