### ISSUE TITLE
Dark Mode - Code Injection - JavaScript unreadable (repeat of Issue 12774)

### ISSUE THREAD

**Issue by petemahon** [TryGhost/Ghost#15363] opened 2022-09-04 18:57 UTC
### Issue Summary

In the Ghost/Settings/Code Injection screen, dark mode makes JavaScript extremely hard to read. Functions are displayed in black on a dark background

### Steps to Reproduce

Put any JavaScript into the box and switch on Dark Mode:

```
<script>
$('a').each(function() {
   var a = new RegExp('/' + window.location.host + '/');
   if(!a.test(this.href)) {
       $(this).click(function(event) {
           event.preventDefault();
           event.stopPropagation();
           window.open(this.href, '_blank');
       });
   }
});
</script>
```
The syntax highlighting should display functions (and all other syntax types) in a readable colour when dark mode is switched on.

### Ghost Version

5.13

### Node.js Version

14.17

### How did you install Ghost?

Linux Mint 19.3

### Database type

MySQL 8

### Browser & OS version

Chrome Version 105.0.5195.52 (Official Build) (64-bit)

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment] 2022-09-05 11:36
As stated in the title - this is a duplicate of #12774, which was a duplicate of https://github.com/TryGhost/Ghost/issues/12831. That issue was closed by stalebot - which steps in after 4 months of an issue not getting any followup or fixes.

Ghost is a large open source project, we aren't able to keep every single bug open indefinitely as it makes it impossible to prioritise issues or get any traction at all on bug fixes from the community. Having 3 issues to track the same bug doesn't make it any more likely that a bug will get fixed - rather the time it takes to triage issues detracts from the time available to fix them.

If you would like to fix this bug or you have other things to add, you can raise a comment or a PR against a closed issue and we can reopen it.

**Closed by ErisDS** 2022-09-05 11:36 UTC
Labels: needs triage

**Comment by petemahon** [comment] 2022-09-05 16:26
Hi @ErisDS , apologies as I thought this had actually received a fix previously and this was a regression issue. I will have a look and see if it's a straightforward fix but I am not a CSS expert by any means.
