### ISSUE TITLE
Multiple upgrade versions at top of page after logging into admin portal

### ISSUE THREAD

**Issue by buildbreakdo** [TryGhost/Ghost#7468] opened 2016-10-02 06:32 UTC
### Issue Summary

Multiple upgrade versions at top of page after logging into admin portal.

![screen shot 2016-10-02 at 11 58 52](https://cloud.githubusercontent.com/assets/1865690/19019114/a4ef8f6a-8897-11e6-9c5f-291639928f1f.png)

### Steps to Reproduce

1. Log in to admin portal
2. Multiple upgrade versions displayed at top

Would only expect the latest version to be advertised as an upgrade.

### Technical details:

* Ghost Version: 0.8.0
* Node Version: -
* Browser/OS: Chrome
* Database: sqlite3

**Comment by kevinansfield** [comment] 2016-10-02 07:28
Hey @buildbreakdo, thanks for taking the time to create an issue, this particular bug [has been raised before](https://github.com/TryGhost/Ghost/issues/7305) was fixed in 0.9.0. Unfortunately because the issue is client-side pre-0.9.0 clients will always show multiple upgrade alerts.

Closing as duplicate+fixed.

**Closed by kevinansfield** 2016-10-02 07:28 UTC

**Comment by buildbreakdo** [comment] 2016-10-02 07:32
@kevinansfield Woops, thanks.. silly of me to open an issue without being on the latest -- mental note to self. Cheers!
