### ISSUE TITLE
[alpha.20] Word count disappears in smaller window

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost#8417] opened 2017-04-26 22:50 UTC
### Issue Summary

If you make ghost editor window small enough the word counter will disappear.

### Technical details:

Ghost Version: alpha.20
ghost-cli Version: 1.0.0-alpha.16
Node Version: v6.10.0
OS: Debian 3.16.39-1+deb8u1
Database: MariaDB 10.0.29 & SQLite3

### Screenshot

![image](https://cloud.githubusercontent.com/assets/5560454/25460221/a0bbeac2-2ae2-11e7-9992-5ea1f68e4359.png)

**Comment by kevinansfield** [comment] 2017-04-27 08:02
Hey @PaszaVonPomiot, that's by design so that the word count does not overlap the editor content. Closing as a non-issue for now.

**Closed by kevinansfield** 2017-04-27 08:02 UTC
