### ISSUE TITLE
Koeing Editor is not compatible with Chinese input software

### ISSUE THREAD

**Issue by S8Cloud** [TryGhost/Ghost#9811] opened 2018-08-22 07:55 UTC
### Issue Summary

The Ghost Koeing Editor is not compatible with Chinese input software.
I tried to write my blog with the new Koeing Editor but it seems there are some problems with it when it comes to Chinese input software.

* The first letter of my Pinyin word will be showed at last (It **should** be shown in the input software interface) 
* When I tried to type `delete` something when using input software , **all** the temporary Pinyin word will show in the editor.

### To Reproduce

1. macOS 10.13 default Chinese Pinyin input software
2. Works well on Markdown Editor

![demo](https://i.imgur.com/2jUXAdI.gif)

### Technical details:

* Ghost Version: 2.0.2
* Node Version: 8.x LTS
* Browser/OS: Chrome 69 on macOS 10.13.6
* Database: MySQL 5.7

**Comment by kevinansfield** [comment] 2018-08-22 08:04
Hey @S8Cloud 👋 Thanks for reporting but I'm going to close this as it's a duplicate of 
https://github.com/TryGhost/Ghost/issues/9801

**Closed by kevinansfield** 2018-08-22 08:04 UTC
