### ISSUE TITLE
Support for newer versions of nodejs (4.0.0)

### ISSUE THREAD

**Issue by danieldiekmeier** [TryGhost/Ghost#5821] opened 2015-09-09 14:53 UTC
Yesterday, nodejs released the first "stable" version, which is 4.0.0. But when I try running Ghost with it, it tells me I need to use at most 0.12.7.

```
ERROR: Unsupported version of Node
Ghost needs Node version ~0.10.0 || ~0.12.0 you are using version 3.3.0
```

What is your plan for supporting future versions?

Also: Can I circumvent this restriction? Running it locally would suffice, on my server I only have 0.12.7.

**Comment by andrewsomething** [comment] 2015-09-09 16:23
Among the dependencies, node-sqlite3 will need to make a new release with support for 4.0.0 (See: https://github.com/mapbox/node-sqlite3/pull/495).

**Comment by ErisDS** [comment] 2015-09-09 18:12
Currently, Ghost does not work with Node 4.0.0, as some of our dependencies are not yet ready (including the mentioned node-sqlite3 module). 

We will update our dependencies as and when they become compatible and once we reach full compatibility will update our build process to & restrictions include Node 4.0.0 support.

Once Ghost is able to support 4.0.0, we will need to do a release - that release will be clearly marked as including support.

You can circumvent the restrictions on node versions in the meantime, but if you do - it'll be up to you to manage getting Ghost to work on the version you choose, which may not even be possible ;)

**Comment by springmeyer** [comment] 2015-09-09 22:18
Working on getting a node-sqlite3 release out today.

**Comment by springmeyer** [comment] 2015-09-10 00:59
node-sqlite3 `v3.1.0` is now out with io.js 3.x and node 4.x support.

**Comment by springmeyer** [comment] 2015-09-10 01:00
One heads up: this node-sqlite3 release does not provide linux 32 bit binaries because I ran out of time getting them working. They have been hard to keep working (the binary building) - so I'm interested if the ghost team thinks they are still useful and I'll try to get them working again /cc @ErisDS

**Comment by ErisDS** [comment] 2015-09-10 08:34
@springmeyer do you know if they get downloaded often? That might be the best stat available. Alternatively, see how it goes without them and if either project gets inundated with support then they can be considered still needed? 

Also, is there something we can do to help?

**Comment by pensierinmusica** [comment] 2015-09-10 09:20
Can you please update `package.json` to include `"sqlite3": "^3.1.0"`?

Thanks!

**Comment by cwonrails** [comment] 2015-09-10 14:06
@pensierinmusica +1 - been running Ghost 0.70 on node 4.0.0 with `"sqlite3": "3.1.0"` in package.json.

**Comment by cwonrails** [comment] 2015-09-10 19:33
Running in prod now, it's fine with the sqlite update.

**Comment by pensierinmusica** [comment] 2015-09-11 02:46
@cwonrails have you tried most of the functionality (e.g. posting new articles, managing tags, creating users, tweaking options, etc.) and it doesn't give you any bug?

If so, I'd be up to switch too  :)

**Comment by di48l069** [comment] 2015-09-11 11:48
@ErisDS hi, does ghost now support nodejs v4.0.0? because package.json says otherwise?

**Comment by cwonrails** [comment] 2015-09-12 14:13
@pensierinmusica I swapped back for reasons other than functionality failures (my one click DigitalOcean install was/is acting up after trying to manually update node, and I don't want to edit the upstart scripts), but for my local dev environment everything was all good.

**Comment by ndaidong** [comment] 2015-09-17 02:30
Confirmed. Updating package.json "sqlite3" version from "^3.0.8" to  "^3.1.0" solves installation issue.

![Failed while installing Ghost with Node.js 4.0.0](http://i.imgur.com/gPbh6fL.png)

**Comment by ChrisRus** [comment] 2015-09-18 17:58
Trying to install the 0.7.0 tagged release on Node v.4.1.0 on CentOS7 DigitalOcean droplet. npm process keeps getting killed leaving no logfile behind. This DO's smallest droplet size I'm attempting to configure. Has anyone else seen this? What are the memory requirements to npm install Ghost?

**Comment by ChrisRus** [comment] 2015-09-18 18:39
Note that after patching package.json to sqlite3 ^3.1.0 it is also necessary to update the required node version constraint in package.json to eliminate the runtime error on npm start.

**Comment by davethemaker** [comment] 2015-09-21 16:47
Updating package.json "sqlite3" version to "^3.1.0", and keeping "node": "~0.10.0 || ~0.12.0", I still get the following error: 
ERROR: Unsupported version of Node
Ghost needs Node version ~0.10.0 || ~0.12.0 you are using version 4.0.0

Please go to http://nodejs.org to get a supported version

**Comment by ErisDS** [comment] 2015-09-22 08:17
Sqlite3 is ready, but what hasn't yet been fully tested (or at least no one has yet reported on) is whether the build tool suite and all the dev dependencies are ready yet.

**Comment by cwonrails** [comment] 2015-09-22 13:28
@ErisDS I just made an asciicinema of a successful install with node v4.1.0:

<a href="https://asciinema.org/a/26668" target="_blank"><img src="https://asciinema.org/a/26668.png" /></a>

**Comment by ErisDS** [comment] 2015-09-25 07:23
I'm tracking this: https://github.com/strongloop/express/issues/2754

**Comment by edsadr** [comment] 2015-10-14 02:55
@ErisDS this looks like we are just waiting for express confirmation of their dependencies to be Node V4 compatible, there is not so far any problem detected with them and they are just waiting to check their dev dependencies, I have been testing Ghost with Node V4 for a week already, in dev and prod envs and so far everything looks really good I even did profiling for it with great results, also did the homework checking dev dependencies for Express (current included version in Ghost) and Ghost 0.7.1

Here are the reports for both projects tested against Node V4.2.0 using https://github.com/nodesource/upgrade-ready by NodeSource (https://nodesource.com/services/upgrade-self-service):

http://upgrade-ready.nodesource.com/summary/afa6e7b0-721c-11e5-97f9-4fabad8c9360
http://upgrade-ready.nodesource.com/summary/afa6e7b0-721c-11e5-97f9-4fabad8c9360

The only dependency failing is as we currently know is sqlite3 as Ghost is using an outdated version and the only blocking thing here is to update that one and the engines section of Ghost package.json

Really looking forward to have Ghost running V4 is the best interest of NodeSource

**Comment by cwonrails** [comment] 2015-10-18 17:56
@ErisDS What holdups remain for Ghost running node 4 now that the sqlite3 dep update has been [merged] (https://github.com/TryGhost/Ghost/commit/c2008aad4204caebc604d30b74176ccaa6a05e90)?

After updating [these lines](https://github.com/TryGhost/Ghost/blob/master/package.json#L24-L26) in package.json to [this](https://github.com/cwonrails/Ghost-Node-4/blob/master/package.json#L24-L26), the only problem I've had is [the node version startup check](https://github.com/TryGhost/Ghost/blob/master/core/server/utils/startup-check.js#L19-L36) when running ``npm start --production``.  

Everything works fine after [commenting those lines out](https://github.com/cwonrails/Ghost-Node-4/blob/master/core/server/utils/startup-check.js#L19-L36), but that's obviously not a long-term solution.

**Comment by edsadr** [comment] 2015-10-18 18:07
@cwonrails you dont need to comment those line, just update the engines section in the package.json

**Comment by ErisDS** [comment] 2015-10-21 12:05
As @halfdan pointed out - there are also memory issues with node 4 that will heavily impact many Ghost users on small VPS setups: https://github.com/nodejs/node/issues/3370

We will need to have very specific documentation for Node 4 to help mitigate this. Upgrading to support the newer version is non-trivial IMO and we will probably only support LTS versions of Node.

**Comment by IamRafy** [comment] 2015-10-26 14:50
Tried changing the sqlite version after changing node version from package.json file and still the same problem .

**Comment by cwonrails** [comment] 2015-10-26 16:49
@IamRafy You have to also update the "node version" section of package.json for it work.

**Comment by cwonrails** [comment] 2015-10-26 17:19
@IamRafy My fork works if you want to check it out.

**Comment by vdemedes** [comment] 2015-10-28 14:40
Here's the summarized information on node v4.x support - https://gist.github.com/vdemedes/618cadc9e191d2519008. Please, let me know if I missed something!

**Comment by epicmiller** [comment] 2015-11-02 09:20
Any way to publish a canary or beta build with the 4.x changes for those of us consuming ghost as a node module?

**Comment by epicmiller** [comment] 2015-11-05 23:14
@ErisDS: Bump :)
>Any way to publish a canary or beta build with the 4.x changes for those of us consuming ghost as a node module?

**Comment by ndaidong** [comment] 2015-11-06 05:28
I can't wait more because I use Ghost for many projects. So this is my solution: 

https://github.com/re-clone/Ghost

**Comment by epicmiller** [comment] 2015-11-06 05:33
Unfortunately I'm using ghost as a node module in part of a larger express app that is deployed automatically to a cluster, so I don't have the luxary of manually installing the latest sqlite3 on each machine :) Fine solution for smaller projects though.

**Comment by ErisDS** [comment] 2015-11-06 08:22
Please read this: https://gist.github.com/vdemedes/618cadc9e191d2519008

Ghost will be adding official support for Node LTS versions as part of our standard release cycle. 

I'd love to see a PR adding node 4.2.0 to the travis build - this is more than a simple text change as the startup checks will need to be overridden in some way when in test mode.

Additionally, I'd love to see a PR adding a pre-install hook to handle node version support, instead of our startup check, to make it easier for people to understand why Ghost isn't installing before they hit a failing dep like node-sqlite3.

**Comment by edsadr** [comment] 2015-11-06 21:32
Ok..  I will work on a PR this Monday..  @ErisDS

**Comment by jgillich** [comment] 2015-11-09 02:44
IMO, Ghost should not refuse to run on newer node versions. There are already several Linux distros shipping newer versions (opensuse 4.x, arch 5.x) and new major releases seem to happen quickly now.

**Comment by cwonrails** [comment] 2015-11-09 14:46
@jgillich +1

**Comment by edsadr** [comment] 2015-11-09 22:37
well .. I would say :+1: @jgillich ..  but Ghost prefers to be really conservative about it... so... better to have at least  LTS support than nothing...

**Comment by jgillich** [comment] 2015-11-09 22:50
FWIW, the tests succeed on both 4 and 5.

@edsadr I'm not saying we should really encourage the latest node. Warn users, make them confirm that they know what they're doing. If something breaks, great, they will report it and we get to fix things early. The longer we wait, the more users will be affected by potential bugs.

**Comment by edsadr** [comment] 2015-11-10 15:02
@ErisDS would be nice if we can discuss ... I am really trying to help, but better if you provide more details, as I said this was the initial one, there was some comments inside asking and I would work on it after your feedback... but just closing it without explaining better... is just feel a bit rude

**Comment by ErisDS** [comment] 2015-11-10 19:18
@edsadr As I explained, the work that is needed is *not* a simple text change. You opened a PR with text-only version changes - the same as previous PRs that I have also closed.

**Comment by devurandom** [comment] 2015-11-15 20:35
Seems to work here after following patch:
```diff
diff --git a/core/client/package.json b/core/client/package.json
index 2f3013c..c403362 100644
--- a/core/client/package.json
+++ b/core/client/package.json
@@ -20,7 +20,7 @@
   "license": "MIT",
   "devDependencies": {
     "broccoli-asset-rev": "^2.1.2",
-    "ember-cli": "1.13.8",
+    "ember-cli": "^1.13.12",
     "ember-cli-app-version": "0.5.0",
     "ember-cli-babel": "^5.1.3",
     "ember-cli-content-security-policy": "0.4.0",
diff --git a/package.json b/package.json
index d899e08..8207866 100644
--- a/package.json
+++ b/package.json
@@ -22,7 +22,7 @@
     "test": "grunt validate --verbose"
   },
   "engines": {
-    "node": "~0.10.0 || ~0.12.0",
+    "node": "~0.10.0 || ~0.12.0 || ~5.x",
     "iojs": "~1.2.0"
   },
   "dependencies": {
```

The former is required, because certain dependencies of Ember 1.13.8 do not compile against the V8 version included in NodeJS 5.0.0. The latter simply adds NodeJS 5.0.0 as an allowed NodeJS version.

**Closed** 2015-11-24 10:14 UTC

**Comment by jgillich** [comment] 2015-11-24 10:42
Yay :thumbsup:

@ErisDS `npm-check-engines` is now on npm.

**Comment by ErisDS** [comment] 2015-11-30 02:14
@jgillich nice :) @boennemann might this (npm-check-engines) be something to include in greenkeeper?

**Comment by lordmetroid** [comment] 2016-01-05 21:29
Jan 05 22:25:30 gorilla npm[16766]: ERROR: Unsupported version of Node
Jan 05 22:25:30 gorilla npm[16766]: Ghost needs Node version ~5.0 you are using version 5.3.0

**Comment by jgillich** [comment] 2016-01-05 21:33
@lordmetroid `GHOST_NODE_VERSION_CHECK=false`

**Comment by zaiddabaeen** [comment] 2016-02-27 14:15
I got it working with Node v5.

See here: http://blog.z-proj.com/running-ghost-with-node-v5/
