### ISSUE TITLE
ghost.url.api not working

### ISSUE THREAD

**Issue by kavyajain996** [TryGhost/Ghost#8607] opened 2017-06-20 05:59 UTC
Firstly, I am getting this error even after enabling public API on admin panel..
Failed to load resource: the server responded with a status of 404 () with ghost-url.min.js
Second, the url it is fetching is localhost and not production url...But ghost blog is running in prduction with my domain name...Please help..
Thank You

**Comment by kirrg001** [comment] 2017-06-20 06:08
Hey @kavyajain996 👋

Sorry to hear you are having trouble, but we need more details to be able to figure out if you are hitting a bug.

It looks like you haven't build your production assets, but i'm just guessing, because i miss the details of how you have installed Ghost, which version are you using etc. 

Please follow our official [installation guide](https://docs.ghost.org/v0.11.9/docs/installing-ghost-on-linux) and our [configuration guide](https://docs.ghost.org/v0.11.9/docs/configuring-ghost#section-url).

My recommendation would be to head to [slack](https://slack.ghost.org) and post as much detail as your specific setup as you can and hopefully someone might spot the issue.

I'm going to close this here because, as far as I am able to determine this is not being caused by a bug in Ghost itself. If we discover that it is a bug I'll reopen.

**Closed by kirrg001** 2017-06-20 06:08 UTC
