### ISSUE TITLE
Email template issues

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#11756] opened 2020-04-20 06:39 UTC
There are several issues with our email templates at the moment:

---

## Mobile font size

Occasionally font size is significantly reduced on mobile devices. It does not appear to matter what size of device, but it does appear to be specific to Apple Mail, or native iOS apps which use the Apple Mail ... mail renderer(?) - screenshots below are of FrontApp, on an iPhone 11 Pro Max

- Normal: https://user-images.githubusercontent.com/120485/79720893-abe4d100-830b-11ea-8040-6cca4998c760.PNG
- Small: https://user-images.githubusercontent.com/120485/79720906-b4d5a280-830b-11ea-9daa-ee45a7a75a3b.PNG

---

## Bookmark cards

There seem to be some spacing issues around bookmark cards, FrontApp, Macbook Pro

- https://user-images.githubusercontent.com/120485/79721032-ef3f3f80-830b-11ea-91c2-3c851e0f568f.png

---

## Video embeds

Currently video embeds don't degrade at all for email, they just break / don't show up. It would be good if, at least, they could degrade to a bookmark card.

---

TODO:

- [x] Fix mobile font size
- [x] Fix bookmark card spacing
- [x] Fix video embed degradation
  - [x] Outlook specific fallback
  - [x] Fix display in gmail mobile

**Comment by JohnONolan** [comment] 2020-04-23 05:27
I was just rooting around in Discourse and, by coincidence, found this right before the closing body tag of their email template:

```
<!-- prevent Gmail on iOS font size manipulation -->
<div style="display:none;white-space:nowrap;font:15px courier;line-height:0">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</div>
```

Have not researched so far, so I don't know if it's related or relevant

**Comment by kevinansfield** [comment] 2020-04-29 15:58
As of next Ghost release video embeds will now render a thumbnail with a play button overlay in emails, the whole thumbnail is a link to the original video url.

Note that this will only work for newly created embed cards, unfortunately we weren't storing thumbnail data alongside old embed cards.

**Comment by kevinansfield** [comment] 2020-05-01 12:52
With the Gmail scaling / font-resizing fix I can't reproduce the bookmark spacing issues so I'm marking it as done and closing. We can revisit with more specific issues if/when we have further reports 🙂

**Closed** 2020-05-01 12:52 UTC
Labels: bug

**Comment by aamatte** [comment] 2020-07-22 21:34
I am experiencing spacing issues with bookmarks on emails. It can be reproduced in the newsletter preview of a post.

<img width="605" alt="Screen Shot 2020-07-22 at 17 31 03" src="https://user-images.githubusercontent.com/7615277/88230963-5937ef80-cc41-11ea-9568-adc19e651f4c.png">

In the image, "Ghost" is the author, and "Test Page" is the publisher.

I tried overriding the CSS classes `kg-bookmark-author` and kg-bookmark-publisher` with no luck.

**Comment by kevinansfield** [comment] 2020-07-23 10:44
@aamatte please open new issues rather than commenting on closed ones
