### ISSUE TITLE
How to remove the trailing slash on the canonical meta tag on the home page?

### ISSUE THREAD

**Issue by michlschmitt** [TryGhost/Ghost#9189] opened 2017-10-29 20:28 UTC
The meta tag rel="canonical" on the home page has a trailing slash, though the blog_url is without trailing slash? How can this be removed?

The canonical url should be http://example.com instead http://example.com/ for SEO purposes.

I use the latest Ghost version.

**Comment by acburdine** [comment] 2017-10-29 20:40
@michlschmitt hey :) Ghost has built-in middleware that automatically redirects all requests without a trailing slash to their corresponding urls that _do_ have a trailing slash. For example, if you go to `http://example.com` (without a trailing slash), you will see that the request is redirected to `http://example.com/` (with a trailing slash). Therefore, the canonical URL is correct based on the intended behavior of Ghost.

Closing this as it is intended behavior and not a bug.

**Closed by acburdine** 2017-10-29 20:40 UTC

**Comment by MiguelCrespo** [comment] 2018-05-11 00:37
Hi, @acburdine Is there a way to remove this trailing slash from the URIs? I don't see any benefit of having the trailing as the default because most people don't write a slash at the end of the URI neither popular websites have this structure

**Comment by kirrg001** [comment] 2018-05-28 13:09
@MiguelCrespo 

This is currently not configureable. Ghost uses for **any** url a trailing slash and will redirect none trailing slashes - originally decided [here](https://github.com/TryGhost/Ghost/issues/448). At the end, with or without trailing slash, SEO treats both as unique urls with unique content, [see](https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html). That means, you as a product need to decide for a format.

Furthermore, Ghost doesn't use any extensions for e.g. pages or collections, which is a good argument for the decision being made in 2013. Also personally speaking, i really like the look of trailing slashes 😜

Feel free to create a new idea/topic in our [forum](https://forum.ghost.org) - then people can up vote for making this configureable.

**Comment by codinggirl** [comment] 2019-11-15 02:32
I need the NO TRAILING SLASH style.

**Comment by danielpacuraru** [comment] 2020-03-26 00:41
i'd like this to be configurable as i prefer the 'no trailing slash' variation

**Comment by Sudospective** [comment] 2020-06-19 03:56
As much as I respect your decision for your software, I absolutely hate trailing slashes in any website's URL, let alone my own. I feel this decision was based on preference and should be left to the preference of the user. This isn't something that will force me to use a difference CMS, I love Ghost, but it certainly left me blindsided not knowing this before I installed.

**Comment by adamhenson** [comment] 2020-07-06 04:13
> Therefore, the canonical URL is correct based on the intended behavior of Ghost.

@acburdine canonicals should not be set for pages that don't have alternate content. Is that a known issue? My URLs are actually being excluded for this reason (including my home page). Search Console screenshot below.

<img width="557" alt="Screen Shot 2020-07-06 at 12 03 11 AM" src="https://user-images.githubusercontent.com/747743/86554768-846dcf80-bf1c-11ea-8578-f2d0df8d0251.png">

Why are canonicals set on every page? Is there a way to disable that?

Perhaps this deserves its own issue (I could open).
