### ISSUE TITLE
Insane typing lag on big blog posts (possibly autosave)

### ISSUE THREAD

**Issue by add1ct3dd** [TryGhost/Ghost#6904] opened 2016-05-29 22:21 UTC
### Issue Summary

Chrome version 50.0.2661.102 m on Windows 10

When writing/editing a blog with a lot of words/pictures, the autosave seems to cause immense lag where typing can take up to 2 minutes to "catch up". It seems to be related to the autosave anyway, it may not be. The more I type the longer the lag gets. I tend to have to write my post in notepad and then paste it in currently.

### Steps to Reproduce

1. Add/edit a blog post with 1000+ words and some images
2. Start typing more sentences, the cursor should start lagging

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 0.7.9
* Node Version: v0.10.33
* Browser/OS:  Chrome version 50.0.2661.102 m on Windows 10
* Database: sqlite?

**Comment by kevinansfield** [comment] 2016-05-30 07:58
@add1ct3dd: Can you upgrade to Ghost version 0.8? There were some significant performance increases made to the editor in that version. Closing for now as the issue is fixed as far as I'm aware. Will re-open if you continue to have the same problem on 0.8.

**Closed by kevinansfield** 2016-05-30 07:58 UTC

**Comment by add1ct3dd** [comment] 2016-05-30 09:37
@kevinansfield fixed thank you so much :)!!
