### ISSUE TITLE
Hanging editor on double clicks

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8155] opened 2017-03-14 11:18 UTC
Getting lots of hanging/delay behaviour when double clicking around the editor to select different areas (Chrome/Mac)

![uh](https://cloud.githubusercontent.com/assets/120485/23898172/c1144be4-08b8-11e7-8868-f4a3798081c6.gif)

**Comment by disordinary** [comment] 2017-03-14 12:05
This was an issue a little while ago so it is interesting that it re-appeared. It was to do with ember runloops.

I'll have to dig into it further as i'm not seeing the same locally.

**Comment by disordinary** [comment] 2017-04-08 06:45
I think this issue can be closed?

**Comment by kevinansfield** [comment] 2017-04-25 14:57
I can't reproduce on master either, closing.

**Closed by kevinansfield** 2017-04-25 14:57 UTC
Labels: bug, editor
