### ISSUE TITLE
When you delete a user, the roles ain't cleaned

### ISSUE THREAD

**Issue by AdrienGiboire** [TryGhost/Ghost#8843] opened 2017-08-04 18:46 UTC
### Issue Summary

When you delete a user, the roles ain't cleaned

### Steps to Reproduce

1. Delete a user;
2. And observe:

```
mysql> select users.id, users.name, roles.name from roles join roles_users on roles_users.role_id=roles.id left join users on users.id = roles_users.user_id;
+--------------------------+----------------+---------------+
| id                       | name           | name          |
+--------------------------+----------------+---------------+
| 1                        | Adrien Giboire | Owner         |
| 5984be102f295b5ab0bef447 | Adrien Giboire | Administrator |
| NULL                     | NULL           | Author        |
+--------------------------+----------------+---------------+
```

### Technical details:

* Ghost Version: `1.5.0`
* Node Version: `6.11.1`
* Database: `mysql  Ver 14.14 Distrib 5.7.19`

**Comment by kirrg001** [comment] 2017-08-08 07:05
Hey @AdrienGiboire, thanks for your report.

I can confirm, the `roles_users` entry is not getting removed when a user is deleted. PR is welcome 🙃

**Comment by AdrienGiboire** [comment] 2017-08-08 10:37
Trying to but having local issues.

**Comment by kirrg001** [comment] 2017-08-08 10:49
@AdrienGiboire Thank you! If you need any help, swing by our [slack channel](https://slack.ghost.org) and ask in the `#contributing` channel.

**Comment by uname-yang** [comment] 2017-09-01 08:29
@kirrg001  Can you assign this issue to me? I want to fix it as my first commit.

**Comment by kirrg001** [comment] 2017-09-08 13:11
@uname-yang I am not able to assign you, because you are not part of the Ghost Contributors group. But a fix for this is very welcome 👍

**Comment by kirrg001** [comment] 2018-01-11 20:33
@uname-yang Any news? 🙃

**Comment by dexterleng** [comment] 2018-12-05 11:03
I would like to work on this!

**Comment by kirrg001** [comment] 2018-12-05 11:37
@dexterleng Thanks 🤩 If you need any help, let us know here!

**Closed** 2019-01-21 11:36 UTC
Labels: api, bug, help wanted, server
