### ISSUE TITLE
Zapier 500 error

### ISSUE THREAD

**Issue by june07** [TryGhost/Ghost#11048] opened 2019-08-23 15:02 UTC
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.
Running Ghost 2.29.1 on Ubuntu Bionic and I'm getting a 500 error when I click on the Zapier "Configure" link in the Integrations settings.

![](https://i.imgur.com/G7mRq5f.gif)

### To Reproduce

1. Click on the Zapier "Configure" link in the Integrations settings.

![image](https://user-images.githubusercontent.com/11353590/63602198-bb90f780-c57b-11e9-9c07-39ec25d77e6a.png)

### Technical details:

* Ghost Version: 2.29.1
* Node Version: dubnium
* Browser/OS: Ubuntu
* Database: Mysql

**Comment by kevinansfield** [comment] 2019-08-23 15:07
@june07 can you please show the full console log? Your screenshots are only illustrating the error page handling and do not give any information as to what the problem may be

**Comment by june07** [comment] 2019-08-23 15:28
![Capture](https://user-images.githubusercontent.com/11353590/63604166-f6952a00-c57f-11e9-9313-67c24b833cf4.PNG)

**Comment by june07** [comment] 2019-08-23 19:52
That was all I got from the console...  Any ideas?

**Comment by kevinansfield** [comment] 2019-08-26 08:36
It seems like somehow your database is missing the automatically-created zapier integration. Can you query your database to confirm? You should see something like this:

```
mysql> select * from integrations where slug="zapier" \G;
*************************** 1. row ***************************
         id: 5d57c5a1f359952f2fb76c90
       type: builtin
       name: Zapier
       slug: zapier
 icon_image: NULL
description: Built-in Zapier integration
 created_at: 2019-08-17 09:15:13
 created_by: 1
 updated_at: 2019-08-17 09:15:13
 updated_by: 1
1 row in set (0.00 sec)
```

**Comment by june07** [comment] 2019-08-26 14:08
Yep,

mysql> select name from integrations;
+-----------------+
| name            |
+-----------------+
| Ghost Backup    |
| Ghost Scheduler |
+-----------------+

What's the best way to rectify this?  And how do you think it may have
happened?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
08/26/19,
07:07:00 AM

**Comment by kevinansfield** [comment] 2019-08-28 14:57
This seems to be a duplicate of https://github.com/TryGhost/Ghost/issues/11047 - the zapier screen erring is incidental. I would suggest undoing your manual change then following the similar approach from the linked issue of removing the rows from the migrations table and re-running them - make sure to back up your db first!

Closing this issue and re-opening the linked one.

**Closed by kevinansfield** 2019-08-28 14:57 UTC
Labels: needs info
