### ISSUE TITLE
Can't create tags from Post Settings

### ISSUE THREAD

**Issue by hissingpanda** [TryGhost/Ghost#8338] opened 2017-04-15 17:33 UTC
### Issue Summary

Unable to create new tags from within a post. When clicking "add [new tag]", the text simply disappears and no tag is created.

![tags](https://cloud.githubusercontent.com/assets/7660115/25065543/a31bf39a-21c6-11e7-8fea-9d097b4e0b04.gif)

### Technical details:

* Ghost Version: Alpha-19
* Node Version:  v4.5.0
* Browser/OS:  Firefox 52.0.2
* Database: MySQL

### Console log:

`tag.get(...) is undefined
addTag/</availableTagNames<@https://dev.konkret.la/ghost/assets/ghost-02f0bed201803c2dc2c17cdac9b78f8a.js:2873:32
Enumerable<.map/<@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:54199:27
Enumerable<.forEach@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:54138:9
Enumerable<.map@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:54198:7
addTag/<@https://dev.konkret.la/ghost/assets/ghost-02f0bed201803c2dc2c17cdac9b78f8a.js:2872:41
tryCatch@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:79708:14
invokeCallback@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:79723:15
then/</<@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:79798:18
@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:59536:16
Queue.prototype.invokeWithOnError@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:20997:9
Queue.prototype.flush@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:21056:9
DeferredActionQueues.prototype.flush@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:21180:9
Backburner.prototype.end@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:21250:7
Backburner.prototype.run@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:21364:11
Backburner.prototype.join@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:21395:14
run.join@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:43383:12
run.bind/<@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:43446:14
.createItem@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:154760:17
.onOptionSelect@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:153854:5
.setup/<@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:153351:77
jQuery.event.dispatch@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:15602:16
jQuery.event.add/elemData.handle@https://dev.konkret.la/ghost/assets/vendor-c1c9bf3c958d9652097c61f83e2237f4.js:15411:6
 vendor-c1c9bf3c958d9652097c61f83e2237f4.js:38659:7`

**Comment by kevinansfield** [comment] 2017-04-15 17:44
@hissingpanda did you do anything before you saw this behaviour? I'm not able to reproduce in Chrome or Firefox using current `master` branches.

**Comment by hissingpanda** [comment] 2017-04-15 18:04
After some more testing I found that it only happens after I create a new tag, go to a post and add that tag, and then try creating a new tag from that post's settings. So certainly an edge-case.

![tags2](https://cloud.githubusercontent.com/assets/7660115/25065821/04856158-21cb-11e7-945e-f300685d7c6d.gif)

**Comment by kevinansfield** [comment] 2017-04-15 18:14
That would explain why I didn't see it, thanks for the detailed investigation!

**Comment by kevinansfield** [comment] 2017-04-17 15:04
Hi @hissingpanda, we've attempted to reproduce this on two different machines against `master` and `alpha.19` and have been unable to reproduce.

I'm going to close this for now, if you can find a reliable reproduction case please comment and provide as much information as possible from the Web Inspector console and network tabs. From the error message you've supplied above it would appear that somehow a "tag" object has been inserted into the local Ember Data store that is not actually a Tag model so the `.get` method isn't available, however we have not been able to replicate this situation.

**Closed by kevinansfield** 2017-04-17 15:04 UTC
Labels: admin-client, beginner, bug
