### ISSUE TITLE
Tour throbber positioning off in editor fullscreen

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8755] opened 2017-07-26 07:02 UTC
![image](https://user-images.githubusercontent.com/120485/28608570-d4fe759c-71f1-11e7-9bd4-5d7f1a508822.png)

**Comment by kevinansfield** [comment] 2017-07-26 07:05
Closing as duplicate of https://github.com/TryGhost/Ghost/issues/8559

**Closed by kevinansfield** 2017-07-26 07:05 UTC
Labels: admin-client, bug, post 1.0.0
