### ISSUE TITLE
Digitalocean points to @latest, which is not latest ghost version!

### ISSUE THREAD

**Issue by satyavh** [TryGhost/Ghost#11477] opened 2019-12-20 15:17 UTC
### Issue Summary

You teamed up with DigitalOcean to enable 1-click deploy of Ghost and it's clearly mentioned in the docs.

However, due to your release system, DigitalOcean points to @latest release which is (currently) not the latest version of Ghost. But on their website they make it seem that the latest version is installed. I believe everytime you change @latest people will deploy a different release when using DO 1-click install.

I've contacted DO as well about this, but you might want to resolve this as it is clearly stated in the docs as one of the best ways to install Ghost.

### To Reproduce
Go here: https://marketplace.digitalocean.com/apps/ghost
Click on link version `latest`, it currently points here:
https://github.com/TryGhost/Ghost/releases/tag/1.26.2

**Comment by kevinansfield** [comment] 2019-12-20 15:28
The [latest](https://github.com/TryGhost/Ghost/releases/latest) link is controlled by GitHub, not us. It points to the most recent release on Github, not necessarily the "latest" in terms of latest release of the most up-to-date version of Ghost.

It would certainly be good for DO to have a better link on their 1-click install page but it's just that, a link. It does not affect what is actually installed as that is all handled by `ghost-cli` inside of the droplet and will pull in the real "latest" release.

Closing as this is not a bug in Ghost. I've passed your observation over to our business team who will follow up with DO if needed.

**Closed by kevinansfield** 2019-12-20 15:28 UTC
