### ISSUE TITLE
500 - Maximum call stack size exceeded when using custom navigation

### ISSUE THREAD

**Issue by JackWillDavis** [TryGhost/Ghost#9205] opened 2017-11-03 09:22 UTC
### Issue Summary

I'm getting a 500 error message when attempting to use a custom navigation in Casper 2.1.6 on Ghost 1.16. I've tried with no changes at all to see and it looks like simply attempting to load the file is causing Ghost to fail.

### Steps to Reproduce

1. Install Casper 2.1.6 (just the theme I'm using) on Ghost 1.16.0
2. Copy the current navigation file into a new one in `./partials/navigation.hbs`
3. Attempt to load any front-end page

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 1.16.0
* Node Version: 6.11.3
* Browser/OS: Ubuntu 16
* Database: Unsure

**Comment by kirrg001** [comment] 2017-11-03 09:39
I am not able to reproduce 🤔  Could you please provide the error from the server log?

**Comment by kevinansfield** [comment] 2017-11-06 09:42
@JackWillDavis I'm able to replicate if I copy `partials/site-nav.hbs` to `partials/navigation.hbs` but that's not what you should be doing if you want to customise the `{{navigation}}` helper 😉

You get a max call stack error because `partials/site-nav.hbs` contains the `{{navigation}}` helper which will render `partials/navigation.hbs`, if your `partials/navigation.hbs` contains the `{{navigation}}` helper again then you get an infinite loop of the helper trying to render the partial that renders the helper again and so on.

Docs for modifying the `{{navigation}}` helper output are available [here](https://themes.ghost.org/docs/navigation#section-changing-the-template)

Closing this as it appears to be a custom theme problem rather than a bug in Ghost.

**Closed by kevinansfield** 2017-11-06 09:42 UTC
Labels: needs info
