### ISSUE TITLE
Crash on the unpkg version

### ISSUE THREAD

**Issue by LivioGama** [TryGhost/Ghost#15569] opened 2022-10-07 22:48 UTC
### Issue Summary

When using:
`<script defer src="https://unpkg.com/@tryghost/portal@latest/umd/portal.min.js" data-ghost="https://<site>.ghost.io"></script>
`it crashes at this line:
![CleanShot 2022-10-08 at 00 44 48](https://user-images.githubusercontent.com/6930498/194672413-79547483-af1f-4e7e-97e0-a74cd17d67a0.png)
It should be:
`if (site.portal_plans?.includes('free')) {`

### Steps to Reproduce

```
<html>
<head>
<script defer src="https://unpkg.com/@tryghost/portal@latest/umd/portal.min.js" data-ghost="https://<site>.ghost.io"></script>
</head>
<body>
	<form data-members-form>
	  <input data-members-email type="email" required="true"/>
	  <button type="submit">Continue</button>
	</form>
</body>
</html>
```

### Ghost Version

latest, but even 2.13.1 and 2.12.0

### Node.js Version

16.17.1

### How did you install Ghost?

Cloud hosted

### Database type

Other

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment] 2022-10-10 12:33
@LivioGama could you please provide the actual error you're seeing and also share what your portal settings are under `/ghost/#/settings/members?showPortalSettings=true` ?

**Comment by LivioGama** [comment] 2022-10-10 16:28
Stacktrace:
```[Portal] Failed to initialize: TypeError: Cannot read properties of undefined (reading 'includes')
    at Si (helpers.js:271:27)
    at api.js:469:16
    at c (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.throw (regeneratorRuntime.js:117:21)
    at h (asyncToGenerator.js:3:20)
    at l (asyncToGenerator.js:29:9)```

Screen:
![CleanShot 2022-10-10 at 18 25 43](https://user-images.githubusercontent.com/6930498/194912426-940f2b4f-884f-4d31-bb9d-9d7dd6e0ee11.png)

Code to reproduce:
```<html>
<head>
<script defer src="https://unpkg.com/@tryghost/portal@latest/umd/portal.min.js" data-ghost="https://blog.galerie-arts-croises.ch"></script>
</head>
<body>
	<form data-members-form>
	  <input data-members-email type="email" required="true"/>
	  <button type="submit">Continue</button>
	</form>
</body>
</html>```

Settings:
![CleanShot 2022-10-10 at 18 27 07](https://user-images.githubusercontent.com/6930498/194912784-319105d9-5b52-4ad9-a316-4916cdb00212.png)

**Comment by ErisDS** [comment] 2022-10-10 18:02
Hi there again @LivioGama. Thanks for providing an update, however I cannot see the settings you have configured (the menu on the left is closed in the screenshot) and I cannot reproduce your issue.

`site.portal_plans` should never be undefined - if nothing is set it should be an empty array.

I also can't see the error by opening your site - when does it happen?

**Closed** 2022-10-12 14:42 UTC
Labels: needs info

**Comment by LivioGama** [comment] 2022-10-12 21:03
This forces to upgrade the plan from 9$ to 25$ per month...

**Comment by ErisDS** [comment] 2022-10-13 15:37
Yes that is correct, as you're depending on using the API from an external site & custom integrations are not supported on the Starter plan 🙂 

In general, if you're having any issue with your **Ghost(Pro)** site, please drop us an email on support@ghost.org and we'll be more than happy to give you a hand directly :slight_smile:
