### ISSUE TITLE
Code Block / Nested Code Indentation

### ISSUE THREAD

**Issue by joshdrink** [TryGhost/Ghost#4893] opened 2015-02-05 20:17 UTC
I'm currently having an issue with the code blocks in the markdown editor. When I use 4 space indentation to create a code block, the output renders the first line of code with the proper spacing, and then all subsequent lines are indented by 1 extra tab.

A secondary issue to this is that it seems to be putting a tab on a new line after the final line of code, creating an awkward space at the bottom of the rendered block.

**Markdown**
![screen shot 2015-02-05 at 4 15 47 pm](https://cloud.githubusercontent.com/assets/6960386/6068426/5661481a-ad52-11e4-8406-fc83334d451b.png)

**Output**
![screen shot 2015-02-05 at 4 16 06 pm](https://cloud.githubusercontent.com/assets/6960386/6068428/5e825f66-ad52-11e4-8040-fe8d1644ab30.png)

**Comment by mikedidthis** [comment] 2015-02-06 16:37
I am experiencing the same issue. It only seems to effect `pre` elements when using `{{content}}` in a partial. The `pre` element renders correctly if used inside in `post.hbs`.

#### partials/post/content.hbs

```
{{#is "post, page"}}
{{content}}
{{/is}}
```

#### post.hbs

```
{{> "post/content" }}
```

#### Markdown

```
// This is the class definition, it defines what a Logger object looks like.
class Logger {
    // The log file, a property that describes which log *this* object logs to.
    String logFile;

    // The log method, a method that defines *how* logging is done.
    void log(String message) { 
        // Write the current time plus the message to the logFile.
        writeToFile(logFile, getTimestamp() + " " + message);
    }
}

// Somewhere else

//Create a new Logger object as defined in the Logger class.
Logger logger1 = new Logger(); 
//And *another* one. This is a completely different logger.
Logger logger2 = new Logger(); 

// Define the state for each logger seperately
logger1.logFile = "/var/log/error.log";
logger2.logFile = "./debug.log";

logger1.log("There was an error!");
logger2.log("I did a thing!");
```

#### Render
![http://i.imgur.com/lyJ0q7n.png](http://i.imgur.com/lyJ0q7n.png)

**Comment by mikedidthis** [comment] 2015-02-06 16:39
I have the same issue, seems it is covered here: https://github.com/TryGhost/Ghost/issues/4364

**Comment by ErisDS** [comment] 2015-02-13 22:35
Closing this as a duplicate of #4364

**Closed by ErisDS** 2015-02-13 22:35 UTC
