### ISSUE TITLE
Couldn't display uploaded image

### ISSUE THREAD

**Issue by hnq90** [TryGhost/Ghost#5925] opened 2015-10-08 03:39 UTC
I faced this error after I upgrade my ghost blog from 0.6 to 0.7.

Actually, the image was uploaded successfully:
![selection_033](https://cloud.githubusercontent.com/assets/1875666/10357097/b062a23e-6da8-11e5-8d5a-288d3155360f.png)
But it couldn't display because of javascript error:
![selection_031](https://cloud.githubusercontent.com/assets/1875666/10357111/d7778826-6da8-11e5-89ff-6d5fa800d45e.png)
![selection_032](https://cloud.githubusercontent.com/assets/1875666/10357116/ddabfce0-6da8-11e5-86cd-4b3eb45d664c.png)

Is there any solution?
Thank you in advance.

**Comment by ErisDS** [comment] 2015-10-08 07:59
This looks like a duplicate of #5895 & is explained in the troubleshooting guide: http://support.ghost.org/troubleshooting/#i-can’t-upload-images (you need to disable CloudFlare's Rocket Loader)

**Closed by ErisDS** 2015-10-08 07:59 UTC

**Comment by hnq90** [comment] 2015-10-08 08:33
@ErisDS Thank you.
