### ISSUE TITLE
Amp components not working

### ISSUE THREAD

**Issue by schtschenok** [TryGhost/Ghost#9453] opened 2018-02-13 04:34 UTC
As far as I understand, {{amp_components}} should check for extended components in {{content}}, but it does not seem to work with amp-soundcloud, amp-youtube and many other amp components at all.

Steps to reproduce:
1. Create new Story
2. Place some amp extended components in it
3. Check amp version of this page
4. Realize, that you don't see any of these components at all

I'm using Ghost 1.21.1 installed with Ghost-CLI 1.5.1 on Node v8.9.4 on Debian Sid.

**Comment by AileenCGN** [comment] 2018-02-14 10:08
Hey @schtschenok 

The `{{amp_components}}` helper currently detects only `.gif` images, `iframe`, and `audio` tags in the content. See https://themes.ghost.org/docs/amp#section--amp_components-helper-

In order to use more, custom components, you would need to add this to a custom amp template.

Nevertheless, we have in mind to support more amp components in the future. For now, I will close this issue, as it's not a bug within Ghost itself.

**Closed by AileenCGN** 2018-02-14 10:08 UTC

**Comment by schtschenok** [comment] 2018-02-14 11:01
@AileenCGN thank you very much for the reply! I hope more amp components will be available soon, and thank you very much for your work.

I have a question though. What exactly do I need to add to a custom amp template to use some extended components? Just required script for each component, such as
`<script async custom-element="amp-soundcloud" src="https://cdn.ampproject.org/v0/amp-soundcloud-0.1.js"></script>` for soundcloud? And if I do so, will Ghost delete my `<amp-soundcloud>` tags from a story just like it does now? Or you talk about something else?

Thanks!

**Comment by AileenCGN** [comment] 2018-02-19 04:33
@schtschenok I just checked the code and Ghost will currently strip out your `<amp-soundcloud>` tags. So what I said is actually wrong (for now). I will add this to my AMP todo list, as it's a super easy quick fix. Once it's no deleted anymore, you can add the the script for `amp-soundcloud` to your custom amp template just before the `{{amp_ghost_head}}` helper. See [here](https://themes.ghost.org/docs/amp#section-template) for more info.

If you have further question or need support, please swing by in our [Slack](https://slack.ghost.org) channel.

**Comment by mustakimali** [comment] 2019-08-19 19:41
Hello is there any update on this? It would be great to be able to embed gist in amp pages. Thanks.
