### ISSUE TITLE
Changes to Meta fields are not triggering webhooks

### ISSUE THREAD

**Issue by TSiege** [TryGhost/Ghost#12094] opened 2020-07-31 23:47 UTC
### Issue Summary
Changing my meta title or meta description is not triggering a webhook call even though the post is saved and updated. I have a work around, which is adding a space to the mobiledoc and saving that as well. I'm not sure if this is related to https://github.com/TryGhost/Ghost/issues/12046 or if it is just a similar bug.

### To Reproduce

1. Go to a post
2. Edit a post's meta title, click save
3. Go to integrations and webhook api, check most recent post update trigger (should be unchanged)
4. Back to post, add space to mobiledoc, save
5. Go back to integrations, see webhook triggered

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
I would expect that changing a post meta field would trigger a post update webhook call

### Technical details:

* Ghost Version: 3.22
* Node Version: node 12
* Browser/OS: Firefox
* Database: Mysql 5.7

**Comment by ErisDS** [comment] 2020-08-03 16:03
Closing as a duplicate of #12046

**Closed by ErisDS** 2020-08-03 16:03 UTC
