### ISSUE TITLE
Web tell me 404 when i add page-about.hbs

### ISSUE THREAD

**Issue by wyx666518** [TryGhost/Ghost#9270] opened 2017-11-24 09:18 UTC
Welcome to Ghost's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫. Found a bug? Please fill out the sections below... thank you 👍

If your issue is with Ghost CLI, please report it on the CLI repo ➡️ https://github.com/TryGhost/Ghost-CLI/issues/new.

### Issue Summary

Ubuntu 16.04

### Steps to Reproduce

1. At http://themes.ghost.org/docs/page-context.

2. For example, if you have an 'About' page with the url /about/, adding a template called page-about.hbs will cause that template to be used for the about page, instead of page.hbs, or post.hbs.

These templates exist in a hierarchy. Ghost looks for a template which matches the slug (page-:slug.hbs) first, then looks for page.hbs and finally uses post.hbs if neither is available.

3.I have page-about.hbs and page.hbs , and write the Example Code into it.

4.No matter myself theme or casper.All tell me 404.

Please tell me why.Thank you very mach!

### Technical details:

* Ghost Version:1.18.0
* Node Version:6.12.0
* Browser/OS:Chromium 62.0.3202.94 / Ubuntu 16.04 x64
* Database:mysql 5.7.20

**Comment by acburdine** [comment] 2017-11-24 15:07
@wyx666518 You also need to go into the Ghost post editor and create a post with the slug "about", mark it as a static page, and then publish it, in order for the page to show up.

Going to close this as it's most likely not a bug in Ghost, and we handle support requests over in our [slack channel](https://slack.ghost.org). If it _does_ turn out to be a bug in Ghost, we can reopen this :)

**Closed by acburdine** 2017-11-24 15:07 UTC
