### ISSUE TITLE
Social Meta Description Issue

### ISSUE THREAD

**Issue by mskian** [TryGhost/Ghost#10453] opened 2019-02-05 17:18 UTC
`og:description`
`twitter:description`
`Schema Mark up Description`
Not updating the Post Description which we provided on SEO Meta Data it was taken from the Post content
previously it showed the Description which we provided on SEO Mata Data Box

#10387

**Comment by gargol** [comment] 2019-02-05 17:44
Sorry, @mskian but I don't understand what is the issue here and it's a duplicate of previously closed one. 

To be able to help you we'd need to get a clear picture of what is the problem that you have found. A good example of an issue - https://github.com/TryGhost/Ghost/issues/10290, should include a clear summary, steps to reproduce and technical details (as pointed in issue template). 

Would recommend first updating your [forum post](https://forum.ghost.org/t/social-meta-description-issue/5230) with more information and if it's a bug then we'll open up an issue here. We can only help you when it's clear what the problem is :+1:

**Closed by gargol** 2019-02-05 17:44 UTC
