### ISSUE TITLE
Can't go to the signup page.

### ISSUE THREAD

**Issue by twtww** [TryGhost/Ghost#4913] opened 2015-02-13 09:54 UTC
When I open mywebsiteurl/signup it will leads me to mywebsiteurl/ghost/signup.
I can't find how to signup for my ghost.

**Comment by tombull** [comment] 2015-02-13 13:20
Looks to me like something in a recently updated npm package broke ghost (admin interface, at least) a couple of days ago. Haven't had time to see what the problem is yet.

**Comment by obsoleted** [comment] 2015-02-13 19:44
It might be the grunt-ember-templates package. When I was trying to run the latest stable branch last night I found the admin page to be blank. But when I locked the grunt-ember-templates version at 0.5.0-alpha the page displayed normally.

**Comment by ErisDS** [comment] 2015-02-13 22:09
Hi @twtww, @tombull and @obsoleted - this issue is a duplicate of #4904. You can find the resolution of the issue there.

**Closed by ErisDS** 2015-02-13 22:09 UTC
