### ISSUE TITLE
Non-breaking spaces are ignored by the editor

### ISSUE THREAD

**Issue by xDEADC0DE** [TryGhost/Ghost#11211] opened 2019-10-08 07:48 UTC
Related to #10757 ?

On Ghost Pro servers, using Chrome on Windows, I cannot add non-breaking spaces to the editor.

Whether I type it with `Ctrl`+`Shift`+`Space`, or paste it from somewhere else nothing gets added to the text (pasting "<nbsp>:" only adds the ":").

Please note that this is not simply a formatting issue ; I'm writing a blog post in French where non-breaking spaces are part of the usual typography.

**Comment by kevinansfield** [comment] 2019-10-28 09:14
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/10757 - this is an upstream issue in https://github.com/bustle/mobiledoc-kit

**Closed by kevinansfield** 2019-10-28 09:14 UTC

**Comment by xDEADC0DE** [comment] 2019-10-28 10:42
Is there an open issue on mobiledoc-kit? This has been a problem since May :/
