### ISSUE TITLE
Rendering navigation twice using Fresca theme

### ISSUE THREAD

**Issue by rbukovansky** [TryGhost/Ghost#8972] opened 2017-09-05 12:27 UTC
### Issue Summary

If my understanding is correct, I can use `{{navigation}}` helper anywhere I want in theme and it will always render navigation, but that's not happening when [Fresca](http://www.augustkleimo.com/fresca-theme/) theme is used. My friend is using this theme for his blog http://lifehacky.ghost.io, where Fresca tries to render navigation twice on page, top, where is rendered correctly, and bottom, where it tries to iterate over `@blog.navigation` to render navigation, but the URLs are not rendered properly using `{{url}}` helper - URL is just http://lifehacky.ghost.io. When I tried to use `{{navigation}}` on bottom instead of iteration over `@blog.navigation`, menu is not rendered at all.

I guess it has probably something to do with #5841

Ghost.io hosted site
Browser: Safari & Chrome
OS: Mac

### Technical details:

* Ghost Version: Ghost.io hosted site
* Node Version: N/A
* Browser/OS: Safari & Chrome on Mac
* Database: N/A

**Comment by kirrg001** [comment] 2017-09-08 14:12
Hey @rbukovansky!

Thanks for your report. 

Closing, because this report is a duplicate of https://github.com/TryGhost/Ghost/issues/5162.

**Closed by kirrg001** 2017-09-08 14:12 UTC
