### ISSUE TITLE
Support for nodejs 4.0.0 and up

### ISSUE THREAD

**Issue by kaustavha** [TryGhost/Ghost#6002] opened 2015-10-25 02:51 UTC
So I tried, struggled and failed to install the default ghost binary from the ../lastest-ghost.zip link on a server where I just installed nodejs.  
Turns out node-sqlite3 v3.0.8 doesn't compile on node 4+ i had. 
[But 3.1.0 does.](https://github.com/mapbox/node-sqlite3/blob/master/CHANGELOG.md#310)
Which the latest on master has as a dependency instead of 3.0.8.
So I cloned and compiled. Seems to work fine on my server. 
Therefore I think it makes sense to add in support for the newer versions of nodejs to `npm start`'s engines.

I'm running node `v4.2.1` on Debian 8.1 Jessie.

**Comment by ErisDS** [comment] 2015-10-25 15:51
Please use search before raising new issues. Closing as a duplicate of #5821

**Closed by ErisDS** 2015-10-25 15:51 UTC
