### ISSUE TITLE
 Editor page cannot get tab key

### ISSUE THREAD

**Issue by Jack-Kingdom** [TryGhost/Ghost#7616] opened 2016-10-24 03:27 UTC
### Issue Summary

Editor page can't get tab key. The page will select some other element if you type.

### Steps to reproduce:
1.  new post
2. type tab button in editor field

### Technical details:

* Ghost Version: v0.11.2
* Node Version:  v4.2.6
* Browser/OS:  Chrome
* Database:  sqlite

**Comment by kevinansfield** [comment] 2016-10-24 08:50
Hi @Jack-Kingdom, thanks for taking the time to create an issue. Tab navigation rather than tabs being entered into the editor is by design - it's important for accessibility and the textarea in the editor will behave the same as any other textarea.

Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/6813

**Closed by kevinansfield** 2016-10-24 08:50 UTC
