### ISSUE TITLE
Bug: Editor freezes after opening the meta data option in posts

### ISSUE THREAD

**Issue by deecube** [TryGhost/Ghost#8646] opened 2017-07-01 10:30 UTC
### Issue Summary
The editor freezes when the Meta Data panel is opened in a new post. The panel itself is active but everything else stops responding to the mouse clicks. Can't even go back to the previous panel
### Steps to Reproduce

1. Open a new post to edit it.
2. The body shouldn't contain any text (Title is fine) 
2. Click on the gear icon and then on the Meta Data option

### Technical details

* Ghost Version: master - v1.0.0-beta.2 ( local install )
* Client OS: Ubuntu 16.04 LTS
* Node Version: 4.5.0
* Browser: chrome Version 59.0.3071.104 (Official Build) (64-bit)
* Database:mysql

**Comment by PaszaVonPomiot** [comment] 2017-07-01 12:32
I'm not able to replicate on Chrome or Firefox. 
Ghost Version: beta.2
Client OS: Centos 7
Node Version: 6
Database: mariadb

**Comment by kevinansfield** [comment] 2017-07-03 17:15
@deecube sorry to hear you are having issues. Are you still able to replicate this? If so would you mind opening Web Inspector console (In Chrome, right click -> `Inspect` -> click `Console` tab) and see if you get an error when opening the meta data panel?

**Comment by ErisDS** [comment] 2017-07-31 18:24
I'm not able to reproduce this on my Mac, Chrome version 59.0.3071.115, in Ghost 1.2.0. 

Going to close this for now. If anyone else experiences it please let us know and we can reopen.

**Closed by ErisDS** 2017-07-31 18:24 UTC
