### ISSUE TITLE
Duplicated entries in /sitemap-pages.xml after uploading routes.yaml

### ISSUE THREAD

**Issue by TonnyORG** [TryGhost/Ghost#9956] opened 2018-10-06 06:41 UTC
### Issue Summary [EDITED]

**NOTE:** After a couple tests, @kirrg001 figured out this only happens when you upload your `routes.yaml` file through the admin. There is a way to fix it, if you restart your ghost server after uploading the routes file.

Using the multi-language feature (dynamic routing), it creates duplicated records on the `/sitemap-pages.xml` file (see image)

![Imgur](https://i.imgur.com/Rb4O7ay.png)

### To Reproduce

Using this `routes.yaml` file:
```
routes:

collections:
  /:
    permalink: /{slug}/
    filter: 'tag:-[en,es]'
    template:
      - index
  /en/:
    permalink: /en/{slug}/
    filter: 'tag:en'
  /es/:
    permalink: /es/{slug}/
    filter: 'tag:es'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

### Technical details:

* Ghost Version: 2.2.0 
* Node Version: v8.12.0
* Browser/OS: Chrome 69.0.3497.100 / MacOS High Sierra
* Database: MySQL

**Comment by kirrg001** [comment] 2018-10-06 09:13
Hey @TonnyORG! 

From the [docs](https://docs.ghost.org/docs/dynamic-routing):

> Beta requirement: Specify inverse filters!
In the current beta version of Dynamic Routing it's necessary to specify the inverse of filters in earlier collections so that pagination is correct.

Could you please update your filters and report back? Thanks!

**Comment by kirrg001** [comment] 2018-10-06 19:44
I can't reproduce what you are reporting.
And the code for it adds exactly one entry per router e.g. for  /es/ and for /en/ to the sitemap.
Not sure what else to test.

**Comment by TonnyORG** [comment] 2018-10-06 19:52
@kirrg001 here is the URL: https://fullstack.mx/sitemap-pages.xml

**Comment by kirrg001** [comment] 2018-10-06 19:54
@TonnyORG I believe you, i just can't reproduce 😞

**Comment by kirrg001** [comment] 2018-10-06 19:57
Does that maybe only happen after uploading the routes.yaml file in the admin client?

**Comment by kirrg001** [comment] 2018-10-06 19:58
Yeah it is. Can reproduce 👍If you restart your blog, this is gone for sure.

**Comment by TonnyORG** [comment] 2018-10-06 19:58
@kirrg001 I'm going to try to reproduce it somewhere else to see if I can find a pattern.

That's a good point, I did upload the routes.yaml from the admin.

**Comment by TonnyORG** [comment] 2018-10-06 19:59
@kirrg001 confirmed, it worked restarting ghost. Thank you very much!

**Comment by kirrg001** [comment] 2018-10-06 20:10
👍 Will be released on Tuesday

**Comment by TonnyORG** [comment] 2018-10-06 20:13
Ty very much 😄

**Closed** 2018-10-08 03:29 UTC
Labels: bug, server

**Comment by rxmc** [comment] 2021-06-02 13:43
Hi guys,

I need some help here ... i'm still having duplicate content on my "sitemap-pages.xml" after uploading my routes file from admin area. I already have restarted ghost and server and i'm not able to solve it (i'm not a developer) how can i solve it?

Now this pages were deleted from google search because indicates duplicate content link from sitemap.

Routes:

  /services/revenue-management/:
      data: page.revenue-management
      template: services-revenue

Links on sitemap-pages.xml:

https://sitedomain.com/services/revenue-management/
https://sitedomain.com/revenue-management/

Could you please help me :-(
