### ISSUE TITLE
Image not showing in Blog Post

### ISSUE THREAD

**Issue by the-mcnaveen** [TryGhost/Ghost#9271] opened 2017-11-24 17:44 UTC
Images in the Post are Not Displaying. Even in Editor & After Publishing.

Permission of Content/Images folder is set to 755. Still facing the issue.

Here is the Screenshot I Have attached. : https://imgur.com/a/nY9lo

### Technical details:

* Ghost Version: 1.18.0
* Node Version: v6.12.0
* Browser/OS: FireFox/Ubuntu 16.04
* Database: MySQL

**Comment by volodymyrlut** [comment] 2017-11-25 09:28
Can you please confirm that you can access your image via direct url in the browser?

**Comment by kevinansfield** [comment] 2017-11-25 09:53
@the-mcnaveen could you please post the markdown of the affected post? If raw markdown is being output in the editor preview and when publishing it sounds like there's something in the markdown that isn't being parsed properly.

**Comment by the-mcnaveen** [comment] 2017-11-26 03:30
@kevinansfield Here you go Buddy: https://imgur.com/a/ZZAck

**Comment by the-mcnaveen** [comment] 2017-11-26 03:32
@volodymyrlut Image is not appearing on Web page buddy. Can't access it via Browser.

**Comment by kevinansfield** [comment] 2017-11-26 10:33
@the-mcnaveen the way you've mixed HTML and markdown isn't valid under the CommonMark markdown spec which is why the markdown is rendering as HTML.

Any HTML should be separated by blank lines if you want to mix markdown into your HTML or vice-versa, eg:

```
<figure>

![](https://example.com/myimage.png)

</figure>
```

You also don't need the `<br>` tags for hard line breaks, newlines in the markdown will be converted to `<br>` for you.

Closing as this is expected behaviour and not a bug.

**Closed by kevinansfield** 2017-11-26 10:33 UTC

**Comment by mydigitalcrown** [comment] 2020-08-07 02:25
I am also facing a kind of issue on my Ghost Website [Trending News wala](https://trendingnewswala.online/)

Please check this URL I have uploaded an image but still, it's not showing

https://trendingnewswala.online/ancient-india-festivals-and-celebrations/
