### ISSUE TITLE
Certain uses of backticks break code block rendering

### ISSUE THREAD

**Issue by hzb** [TryGhost/Ghost#7536] opened 2016-10-11 02:54 UTC
### Issue Summary

When backticks are used in certain ways it can break code block rendering
### Steps to Reproduce
1. Create a new post
2. Add the following content:
   
   ``````
   `` code+` ``
   
   ```second code block```
   
   `third code block`
   ``````
3. Note that the second and third code blocks in the preview both show `second code block`.
4. Remove the very last backtick
5. Note that the second code block shows `undefined`
6. Replace the backtick removed in step 4 and remove the single backtick after the `+` from the first code block
7. Note that all code blocks now render

![backtick-issue](https://cloud.githubusercontent.com/assets/415/19309826/1a423af8-907f-11e6-8a6c-936897dbe616.gif)
### Technical details:
- Ghost Version: 0.9.0
- Node Version: 6.6
- Browser/OS: macOS, Chrome
- Database: Sqlite3

I try in safari, it is all the same.

**Comment by kevinansfield** [comment] 2016-10-12 09:16
Hey @hzb,

Sorry to hear you're having trouble but I'm not entirely sure what you are attempting to achieve. I tried to follow your instructions by writing the code you provided in a markdown code block but both the preview and final post always displayed the full text (see image below). The same text outside of a code block also rendered the full text.

<img width="775" alt="screen shot 2016-10-12 at 10 10 12" src="https://cloud.githubusercontent.com/assets/415/19304460/aafcb3fe-9064-11e6-9550-fad4cba709ff.png">

I'll close this for now as it sounds like it's possibly a theme issue or maybe user error, if you can provide a clear reproduction case I can re-open. I also suggest popping over to [our Slack channel](https://ghost.org/slack) and asking in #help too - it may be easier to explain what you are attempting to do in chat.

**Comment by hzb** [comment] 2016-10-12 10:17
@kevinansfield NO, you can't close this issue, I tested all versions of ghost, from 0.1 to current version, this isn't an issue, i think it's a bug. I have record a video, can you give me your email address, it will send it to you.

**Comment by kevinansfield** [comment] 2016-10-12 10:19
@hzb please attach a link to the video here on this issue or provide concrete reproduction steps, as I said before we can re-open if a bug is found/proven

**Comment by hzb** [comment] 2016-10-12 10:53
@kevinansfield Please download the video from here 

https://www.dropbox.com/s/brl5elvtdow5nc0/markdown_error_ghost.mp4?dl=0

I test it in ghost.io

![screen shot 2016-10-12 at 18 48 40](https://cloud.githubusercontent.com/assets/535675/19307380/b0757594-90ac-11e6-94d6-6be79c5157c3.png)

Write any content like above content in ghost, and then continue coding start with  **`**, and you will find that the first section content will be changed.

**Comment by hzb** [comment] 2016-10-12 11:22
In ghost.io and all ghost version.

![ghost_wrong](https://cloud.githubusercontent.com/assets/535675/19308123/96cd55a4-90b0-11e6-8d63-d94ad910d355.png)

look at two sides content, do you think it's right? 

In other markdown editor, this is real right.

![this_right](https://cloud.githubusercontent.com/assets/535675/19308245/40177662-90b1-11e6-816d-fc969bc352a0.png)


@ErisDS @kevinansfield can you open this issue?

**Comment by kevinansfield** [comment] 2016-10-12 12:26
@hzb thank's for following up with a reproducible test case, I've edited your original issue so that it's clear what the problem is.

We're currently working towards Ghost 1.0 which will have a completely new editor but I've re-opened so that this can be tracked for the LTS branch and for any backwards-compatible markdown support that may be added to the new editor.

**Comment by hzb** [comment] 2016-10-12 15:31
@kevinansfield welcome.

**Closed** 2017-05-15 16:48 UTC
Labels: bug, server, showdown
