### ISSUE TITLE
Inline Partials stopped working sometime after v3.42.5

### ISSUE THREAD

**Issue by gnimmelf** [TryGhost/Ghost#13844] opened 2021-12-05 23:08 UTC
### Issue Summary

[Inline Partials](https://handlebarsjs.com/guide/partials.html#inline-partials) stopped working somtime after v3.42.5.

### Steps to Reproduce

Define inline partial slots in `partials/_templates/cards.hbs` like this

```hbs
{{#> header-slot}}Header-slot{{/ header-slot}}
```

Use the slots in a file like this:
```hbs
{{#> _templates/card}}

        {{#* inline "header-slot"}}Header content{{/ inline}}

{{/ _templates/card}}

```

### Ghost Version

4.9.4

### Node.js Version

14.x (Node v14 Fermium LTS)

### How did you install Ghost?

Official Docker hub image, latest => 4.25.0

### Database type

MySQL 8

### Relevant log / error output

```shell
ghost-theme-docker    | ThemeValidationError: Theme "twt-dev.intergate.io" is not compatible or contains errors.
ghost-theme-docker    |     at getThemeValidationError (/var/lib/ghost/versions/4.9.4/core/server/services/themes/validate.js:69:12)
ghost-theme-docker    |     at Object.checkSafe (/var/lib/ghost/versions/4.9.4/core/server/services/themes/validate.js:65:11)
ghost-theme-docker    |     at async Object.module.exports.activate (/var/lib/ghost/versions/4.9.4/core/server/services/themes/activate.js:57:26)
ghost-theme-docker    | 
ghost-theme-docker    | [2021-12-05 22:20:12] ERROR "PUT /ghost/api/canary/admin/themes/twt-dev.intergate.io/activate/" 422 277ms
ghost-theme-docker    | 
ghost-theme-docker    | Theme "twt-dev.intergate.io" is not compatible or contains errors.
ghost-theme-docker    | 
ghost-theme-docker    | Error ID:
ghost-theme-docker    |     8368fe30-5619-11ec-9bdb-ada0ae4f809a
ghost-theme-docker    | 
ghost-theme-docker    | Details:
ghost-theme-docker    |     checkedVersion: 4.x
ghost-theme-docker    |     name:           twt-dev-intergate-io
ghost-theme-docker    |     path:           /var/lib/ghost/content/themes/twt-dev.intergate.io
ghost-theme-docker    |     version:        1.0.79
ghost-theme-docker    |     errors: 
ghost-theme-docker    |       - 
ghost-theme-docker    |         fatal:    true
ghost-theme-docker    |         level:    error
ghost-theme-docker    |         rule:     Templates must contain valid Handlebars
ghost-theme-docker    |         details:  Oops! You seemed to have used invalid Handlebars syntax. This mostly happens, when you use a helper that is not supported.<br>See the full list of available helpers <a href="https://ghost.org/docs/api/handlebars-themes/helpers/" target=_blank>here</a>.
ghost-theme-docker    |         failures: 
ghost-theme-docker    |           - 
ghost-theme-docker    |             ref:     partials/_templates/card.hbs
ghost-theme-docker    |             message: The partial header-slot could not be found
ghost-theme-docker    |           - 
ghost-theme-docker    |             ref:     partials/_templates/article.hbs
ghost-theme-docker    |             message: The partial meta-slot could not be found
ghost-theme-docker    |         code:     GS005-TPL-ERR
ghost-theme-docker    | 
ghost-theme-docker    | ----------------------------------------
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by tpatel** [comment] 2022-01-12 18:18
On a second read, the issue is a special case that isn't supported yet by gscan, it's the next thing on my todo-list.
Sorry for the false hope, although it will be much easier now that I've release the basic support for inline partials.

**Comment by tpatel** [comment] 2022-01-14 13:32
The inline partials are now marked as valid again in gscan `v4.22.0` and in the Ghost main branch ✅  It will be in the next Ghost release.

**Closed by tpatel** 2022-01-14 13:32 UTC
Labels: bug

**Comment by gnimmelf** [comment] 2022-01-15 11:05
Excellent! Thanks for picking this up!
