### ISSUE TITLE
Couldn't delete 2 posts or more with same title

### ISSUE THREAD

**Issue by dwiyudirayia** [TryGhost/Ghost#8095] opened 2017-03-03 16:05 UTC
## Bugs
Couldn't delete with the same title. expecially when 2 posts or more have the same title or untitled.

**Comment by kirrg001** [comment] 2017-03-03 16:13
Hey @dwiyudirayia 👋 Sorry to hear you are having trouble.

Could you please share a little bit more information:

1. Steps to reproduce
2. The Ghost Version your blog is on.
3. Database
4. The error you see on the server/client.

I've quickly tried to reproduce with latest LTS release, but the case you are describing works for me. 
Thank you!

**Comment by kirrg001** [comment] 2017-03-06 20:37
I will close this issue. 

@dwiyudirayia We can re-open, if we have more information from you.

**Closed by kirrg001** 2017-03-06 20:37 UTC
