### ISSUE TITLE
InternalServerError -The currently active theme "casper" is invalid

### ISSUE THREAD

**Issue by mozfcilla** [TryGhost/Ghost#8465] opened 2017-05-16 23:09 UTC
### Issue Summary
I'm running into InternalServerError related to the active theme with the latest master branch and also with the just released 0.11.9 tag. Details follow 

### Steps to Reproduce
```
git clone git@github.com:TryGhost/Ghost.git ghost
cd ghost
npm install
knex-migrator init
npm start
```

### Technical details:
```

OSX Environment

> ghost@1.0.0-alpha.20 start ghost
> node index

[2017-05-16 22:01:56] ERROR

NAME: InternalServerError
MESSAGE: The currently active theme "casper" is invalid.

level:critical

ERROR DETAILS:
    level: error
    rule:  A template file called index.hbs must be present.
    code:  GS020-INDEX-REQ

```

* Ghost Version: 0.11.9 and development build (HEAD at fc89cf1d49b942d7)
* Node Version: v6.9.1
* Browser/OS: OSX Sierra
* Database: sqllite

**Comment by kevinansfield** [comment] 2017-05-17 08:09
Hey @mozfcilla 👋 If you've followed the install instructions you've provided above then that error is expected. I'm not sure where you found them but they are not correct as they won't pull in the Casper or Ghost-Admin submodules.

Developer (from git) install instructions for the alpha are here https://github.com/tryghost/ghost#ghost-10-alpha-developer-install

Recommended install for the testing the alpha is using the CLI, see the "Testing Ghost alpha with the new installer" section here http://support.ghost.org/v1-0-alpha/

Bear in mind that the alpha is in heavy flux and not recommended for anything other than testing at the moment - there's no upgrade path between alphas and it's expected that things will be broken.

If you want to use the *release* version of Ghost it's recommended to use the release zips. Quick-start install instructions are here https://github.com/tryghost/ghost/tree/lts#quick-start-install

I'm going to close this as it's not a bug and we don't offer install support here on GitHub. If you need any further help please swing by our [Slack channel](https://slack.ghost.org) 😄

**Closed by kevinansfield** 2017-05-17 08:09 UTC

**Comment by mozfcilla** [comment] 2017-05-17 15:03
Thanks @kevinansfield for the instructions. I had them in different forms when I tried looking at howtoinstallghost.com . I realized I was getting the incorrect production version by doing the following
```
git clone git@github.com:TryGhost/Ghost.git ghost
git checkout tags/0.11.9
npm i --production
npm start --production
```
It works well if I just download the released package from https://github.com/TryGhost/Ghost/releases.
