### ISSUE TITLE
Public API: "shared/ghost-url.min.js" not found

### ISSUE THREAD

**Issue by kirkas** [TryGhost/Ghost#6676] opened 2016-04-04 20:38 UTC
Public API ghost-url.min.js not found on live production server.

##### Steps to Reproduce

1. Use Ghost as NPM. 
2. Host Node.js Project on AWS.
3. Use supervisor.
```
[program:ghost]
command = node /www/blog/index.js
directory = /www/blog
user = deploy
autostart = true
autorestart = true
stdout_logfile = /var/log/supervisor/ghost.log
stderr_logfile = /var/log/supervisor/ghost_err.log
environment = NODE_ENV="production"
```
4. In blog settings, enable Public API.

Browser console:
![image](https://cloud.githubusercontent.com/assets/1159783/14262559/060ff020-fa6b-11e5-8b34-a592667eace8.png)

_`/shared/ghost-url.min.js` return a `404` and Public API is not working._

I think this might be because I'm using Ghost as NPM module and therefore it doesn't do a `grunt build --production` but I'm not sure.

* Ghost Version: 0.7.8
* Node Version: v4.4.2
* NPM Version: 3.8.5
* Browser/OS: All
* Database: MySql

**Comment by acburdine** [comment] 2016-04-27 00:16
@kirkas yes, that would be the issue. The `ghost-url-min.js` is not built unless you run grunt build --production`. I think that's because npm bases things off of the .gitignore, and because that specific file is ignored npm doesn't include it when publishing.

**Comment by kirkas** [comment] 2016-04-29 19:38
Ok, but since I used Ghost as NPM, I can't do grunt build (unless I ghost manually in the node_module and do that)

**Comment by ErisDS** [comment] 2016-05-03 21:31
Hi @kirkas, the npm module includes all the pre-built development & production files that the zip download includes, so you should find if you visit `node_modules/ghost/core/shared/`, that the file is there ready to be served.

I'm not sure what is causing the file to return a 404, but I can't reproduce this using the module setup in the wiki & running in production mode, so I'd guess that it must be something to do with your specific environment or setup. 

My recommendation would be to head to [slack](https://ghost.org/slack) and post as much detail as your specific setup as you can and hopefully someone might spot the issue. 

I'm going to close this here because, as far as I am able to determine this is not being caused by a bug in Ghost itself. If we discover that it is a bug I'll reopen.

**Closed by ErisDS** 2016-05-03 21:31 UTC
