### ISSUE TITLE
Giving people hints about what's going on when a test mail fails to send

### ISSUE THREAD

**Issue by BirkhoffLee** [TryGhost/Ghost#9497] opened 2018-03-13 07:52 UTC
### Issue Summary

I used Docker image `ghost:latest` to deploy Ghost and I'm pretty sure I have nothing wrong on my side of setting Mailgun up. But after testing out the 'send test email' feature in labs it just won't work.

### Steps to Reproduce

1. Go deploy Ghost latest version
2. Set up Mailgun correctly
3. Go to labs and send test email
4. It freezes there and eventually says `Server was unreachable`. No output on console side nor logs on Mailgun side.

### Technical details:

* Ghost Version: 1.21.3
* Node Version: v6.13.1
* Browser/OS: `Google Chrome Version 65.0.3325.146 (Official Build) (64-bit)` on macOS High Sierra 10.13.2 (17C88).
* Database: MySQL

**Comment by BirkhoffLee** [comment] 2018-03-13 10:04
I'm referring this issue to #6969.

**Comment by BirkhoffLee** [comment] 2018-03-13 10:08
In fact, I suggest you to give people hints about what's going on instead of freezing the request. I had to debug what have happened.

**Comment by ErisDS** [comment] 2018-03-13 11:18
@BirkhoffLee I mean this in the nicest way possible - no one on the Ghost core team is going to have time to figure out what went wrong for you, what you expected, and what you think should be done differently from the info provided here:

1. None of us uses Docker, it's not "officially" supported. You might find it easier - for us it gets in the way of understanding what's going on.
2. You seem to have resolved the issue, but haven't explained what happened, how it was resolved
3. None of us have ever encountered the issue (else we would have dealt with it).

We close support requests on GitHub and only support a very narrow subset of environments because we are a tiny team trying to accomplish huge things.

If you'd like to submit a PR or at a minimum update this issue to contain enough information to understand & reproduce what you saw, then we can move forward. Else I'm not sure there's anything we can do here.

**Comment by BirkhoffLee** [comment] 2018-03-13 12:01
@ErisDS Sorry for any confusions that I've made. I meant specifically in the labs page - Ghost should tell the user what's going on when the request fails rather than "ignoring" the request and eventually the UI gives the user `Server was unreachable` message, which it's a connection problem between the Ghost server to the, in this case, Mailgun server. And, I'm sorry that I didn't explain how I fixed the issue, I thought referring to the issue which solved my issue was enough. I apologize. 

The point of this issue is that Google Cloud Platform (or, possibly some other VPS providers) *blocks* outgoing packets from port 25. The ultimate solution would be exactly what [this comment in #6969](https://github.com/TryGhost/Ghost/issues/6969#issuecomment-314294719) said -- changing the mailing port to 2525 and everything works.

I hope you can improve the problem I mentioned above, and thanks for making this awesome blogging platform (I love it!).

**Comment by kevinansfield** [comment] 2018-03-13 12:35
> Ghost should tell the user what's going on when the request fails rather than "ignoring" the request and eventually the UI gives the user Server was unreachable message

@BirkhoffLee Ghost already responds with all of the information it has available, all Ghost knows is that  the connection eventually fails because the server was unreachable. What were you expecting to see in the UI?

**Comment by BirkhoffLee** [comment] 2018-03-13 13:09
This is a animated image about what happened, hope this makes everything more clear. I cropped it to be shorter.

![2018-03-13 21_04_52](https://user-images.githubusercontent.com/8148095/37343378-4f88b10e-2702-11e8-965c-13451a281e78.gif)

Ultimately it looks like this:
<img width="1440" alt="screen shot 2018-03-13 at 9 06 17 pm" src="https://user-images.githubusercontent.com/8148095/37343399-661be4fe-2702-11e8-9e3d-7ed1e0221c80.png">
<img width="1440" alt="screen shot 2018-03-13 at 9 06 19 pm" src="https://user-images.githubusercontent.com/8148095/37343403-6803fb94-2702-11e8-86af-060d5ab59414.png">

As you can see, the request to Ghost server completely fails, the `server was unreachable` error means connection from the user to Ghost server couldn't be finished, it doesn't mean the connection from Ghost to mail server failed (like you thought).

**Comment by kirrg001** [comment] 2018-03-28 18:32
> Ghost should tell the user what's going on when the request fails rather than "ignoring" the request and eventually the UI gives the user Server was unreachable message

I agree to that. And i understand the frustration.

But we need steps to reproduce this problem. Plus, without sharing errors from your server log, we can't help you. 

The [Ghost CLI](https://github.com/TryGhost/Ghost-CLI) offers e.g. a [log command](https://docs.ghost.org/docs/cli-log) to watch server errors. 

It seems you already solved the problem. Furthermore, this was never reported elsewhere, not in Github, not in Slack.

@BirkhoffLee If you have steps to reproduce, please swing by our [slack channel](https://slack.ghost.org). We can always re-open this issue.

Closing for now.

**Closed by kirrg001** 2018-03-28 18:32 UTC
Labels: needs info
