### ISSUE TITLE
Publish dialog "Schedule it for later" with past date

### ISSUE THREAD

**Issue by fehwalker** [TryGhost/Ghost#9529] opened 2018-03-23 21:58 UTC
### Issue Summary

Publish dialog suggests "Schedule it for later" with past Publish Date when manually set in Post Settings.

This may just be a UX issue, I would expect the post to still go live immediately if it's scheduled in the past, but the phrasing is confusing.

### Steps to Reproduce

1. Create a new post
2. Change the Publish Date to the past in Post Settings
3. Click publish and note dialog

![image](https://user-images.githubusercontent.com/266142/37854815-e3e38d34-2ec2-11e8-9a90-827108a786f6.png)

### Technical details:

* Ghost Version: 1.21.6
* Node Version: 6.13.1
* Browser/OS: Firefox current/Windows 10 (client)  & FreeBSD 11.1 (server)
* Database: MariaDB 10.0.34

**Comment by kevinansfield** [comment] 2018-03-26 09:04
Hey @fehwalker 👋 The "schedule it for later" radio button is just an option, if you click on it you'll be switching from "publish now" (the option you have selected in the screenshot) to "publish in the future" and the date will be updated to now+5mins after which you can change the future publish date. The date/time fields always show what the published date of the post will be, that's why it has a past date shown for the "Set it live now" option that you have selected.

Closing as this is the intended behaviour for now but there is a re-design of the publish menu on the roadmap.

**Closed by kevinansfield** 2018-03-26 09:04 UTC
