### ISSUE TITLE
Unable to filter stories by tags with single-letter-slug

### ISSUE THREAD

**Issue by frantzypants** [TryGhost/Ghost#9173] opened 2017-10-23 14:18 UTC
### Issue Summary
Error occurs when attempting to filter stories by tags with symbol in title.

![error](https://puu.sh/y59yA/19525885fe.png)

### Technical details:

* Ghost Version: 1.15.0 & 1.14.1
* Browser/OS: Chrome/Mac OS X El Capitan
* Database: mysql

### Steps to Reproduce
1. Create a new story
2. Assign tag with a symbol, e.g. `C#`
3. Publish Story
4. Go to Stories
5. Select tag dropdown and filter by tag with symbol

Expected result should be a list of all stories containing that particular tag, instead an error is produced, and the filtered option remains selected, causing the stories section to be inaccessible until you go back to /ghost/ directly in the URL of the browser

### Relevant Screenshots
**Post has a tag of `C#`**
![Tag C#](https://puu.sh/y59vf/1641dffded.png)

**Select tag `C#` to filter stories**
![Select Tag from List](https://puu.sh/y59wL/12b62f101d.png)

**Error**
![error](https://puu.sh/y59yA/19525885fe.png)

Clicking away to another area within the admin, then going back to stories, error still persists.

**Misc**
![Errors](https://puu.sh/y59E2/9f371a0835.png)

**Comment by ErisDS** [comment] 2017-10-23 14:23
@frantzypants if you still have it available, can you please re-take that screenshot of the network tab, but without the right-side clipped? Or paste the full "requestURL" here, one of the 2 so that I can more easily reproduce. Thanks.

**Comment by frantzypants** [comment] 2017-10-23 14:26
@ErisDS sure thing:

```
Request URL:https://frantztest.ghost.io/ghost/api/v0.1/posts/?limit=30&page=1&status=all&staticPages=all&filter=tag%3Ac&formats=mobiledoc%2Cplaintext&include=tags
```

**Comment by ErisDS** [comment] 2017-10-23 14:48
Ok cool! It looks like this is a duplicate of this issue: https://github.com/TryGhost/GQL/issues/24 over on the GQL repo (the repo that contains all the code for handling filters).

It's not to do with the special character, but that the slug for the tag is "c" - just a single character.

Can you confirm this is always the case where you see this issue? 

I am currently scheduled time to work on improving GQL from next week.

**Comment by frantzypants** [comment] 2017-10-23 17:04
@ErisDS When I had tested a second tag (while trying to see if it was symbols) I made a `b@` tag, which converted to just `b` as the tag slug, and received the same error.

**Comment by kirrg001** [comment] 2018-12-07 15:15
This is still an issue in [NQL](https://github.com/NexesJS/NQL) and [it's already tracked.](https://github.com/NexesJS/NQL-Lang/issues/2)

**Comment by ErisDS** [comment] 2019-01-23 22:45
Closing as it is tracked here: https://github.com/NexesJS/NQL-Lang/issues/2

**Closed by ErisDS** 2019-01-23 22:45 UTC
Labels: NQL, bug, server
