### ISSUE TITLE
Confusing nav item placeholder behaviour

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6440] opened 2016-02-04 18:30 UTC
When creating/editing nav items the `.fake-placeholder` behaviour is a bit confusing because focusing the URL input field and then blurring causes the `url` value to be `/`. This gives the input a value but it's still shown as a placeholder because it matches the base URL. Once the validation is fixed it also increases confusion as it makes it appear as if it's not possible to link to the base url.

![nav-placeholder-issues](https://cloud.githubusercontent.com/assets/415/12891983/ff5d73f2-ce81-11e5-945c-f7c50956fa32.gif)

As you can hopefully see in the screen cap, the URL input will display as if it's empty and contains a placeholder even though it actually contains a value.

I see two options here:

1. Update the `.fake-placeholder` logic to inspect the underlying value and display accordingly. Most likely it would mean only displaying as a placeholder until the field receives focus and then have it act as an actual value.
2. Get rid of the `.fake-placeholder` completely so it looks like it's the default-value that it actually is. We can still keep the current behaviour of deleting the whole content on backspace if the current content matches the configured base URL.

My preference would be on option 2 - it simplifies the code and we don't try to fake a placeholder where we actually have a default value.

**Comment by rajatu** [comment] 2016-02-08 14:51
I am unable to reproduce it. Could you please elaborate it.

**Comment by kevinansfield** [comment] 2016-02-08 16:23
Closing for now, will re-open if it's still an issue once the validation fix and ember-sortable PRs are in.

**Comment by kevinansfield** [comment] 2016-02-08 16:50
After reviewing my other PRs I've updated the description and re-opened. I believe the fix for this is more of a design decision than a coding issue at this point.

/cc @JohnONolan

**Comment by JohnONolan** [comment] 2016-02-09 00:22
Agreed, option 2 sounds good :+1:

**Comment by acburdine** [comment] 2016-02-09 20:42
Another thing to think about too (will likely be fixed by option 2), is that if you mess around with the URL field but end up with the value being the same as the placeholder, and then click in/click out of the label field, the label field will register a validation error. (See [screencap](http://recordit.co/D6WoNQ3En3))

**Closed** 2016-03-22 15:18 UTC
