### ISSUE TITLE
Bug: Tag Cover Image Doesn't Save

### ISSUE THREAD

**Issue by biyanpasau** [TryGhost/Ghost#5880] opened 2015-09-26 05:22 UTC
Ghost 0.7 Localhost - Cover image upload form on "Tags" page doesnt seem to work. Tried uploading one but it didn't save. I have checked the content folder and yes, the image is in there, it just did save on front-end.

**Comment by ErisDS** [comment] 2015-09-26 09:07
Hi @biyanpasau, sorry to hear you're having trouble. I'm afraid I'm not able to reproduce this issue.

Please can you update your bug report to use the [bug report template](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs) in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md) - being sure to include any other relevant details like if you have a storage layer configured, and which theme you are using.

**Comment by ErisDS** [comment] 2015-10-09 14:48
Closing this for now, will reopen if more info is provided.

**Closed by ErisDS** 2015-10-09 14:48 UTC
