### ISSUE TITLE
Editor's update button appears to be un-clickable on iPhone Safari

### ISSUE THREAD

**Issue by farmdawgnation** [TryGhost/Ghost#8740] opened 2017-07-22 18:07 UTC
### Issue Summary

I attempted to edit a blog post on my Ghost blog this afternoon from my iPhone 7, and was unable to actually submit the updates using the update button at the top of the page. It seems that I'm unable to click the button.

### Steps to Reproduce

1. Open a published story.
2. Make a change to it.
3. Attempt to tap update.

Actual results: Nothing appears to happen.

Expected results: I expected the update button to be clicked and the blog post to be changed.

### Technical details:

* Ghost Version: 1.0.0-rc1
* Node Version: 6.11.1
* Browser/OS: Safari / iOS 10.3.3
* Database: MySQL

**Comment by kevinansfield** [comment] 2017-07-22 18:09
Hey @farmdawgnation 👋 Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/8657, it's fixed in master and will be part of the next release.

**Closed by kevinansfield** 2017-07-22 18:09 UTC

**Comment by farmdawgnation** [comment] 2017-07-22 20:53
:rofl: I promise I looked for other occurrences of this ticket before filing it. Thank you!
