### ISSUE TITLE
Markdown Editor - New line and Lists

### ISSUE THREAD

**Issue by Ballrock** [TryGhost/Ghost#6336] opened 2016-01-13 13:31 UTC
Hi,

It seems that I found an issue on the markdown editor for lists and new line.

Explicit exemple :
![test](https://cloud.githubusercontent.com/assets/1423640/12294714/b679ca58-b9fc-11e5-8064-fd19d120bf26.gif)

I use the 0.7.4, so i dont know if it's reproducible on 0.7.5 out today. (I will upgrade this evening)

No issue at : 
* showdownjs/showdown [demo](http://showdownjs.github.io/demo/)
* spec.commonmark.org/
* GitHub Markdown

It seems that showdown-ghost is at 0.3.6 from 7 Mar 2015 on package.json. Is it possible that this issue was solved in showdown in this interval ?

I doesn't find any other post/commit/PR about this but if this problem was already discussed, do not hesitate to close this issue ^^

Edit : 
@Showdown develop branch : 
![test2](https://cloud.githubusercontent.com/assets/1423640/12303741/4976b62a-ba2c-11e5-8542-8fc31681df22.gif)

Antoine Précigout.

**Comment by acburdine** [comment] 2016-01-17 01:32
Hey @Ballrock! Ghost is currently using a fairly old version of showdown; however, there are currently things in the works to replace the current post editor and make it somewhat more configurable, meaning that in the future the markdown parser could be updated. @ErisDS is working on a writeup at the moment, and you can see more details in [this](https://youtu.be/qTsigi72avE?t=4m5s) video.

**Comment by ErisDS** [comment] 2016-01-17 16:31
I think this particular bug is likely a duplicate of #2093.

**Closed by ErisDS** 2016-01-17 16:31 UTC
