### ISSUE TITLE
blank line in <script> blocks adds "<pre><code>	"

### ISSUE THREAD

**Issue by xDEADC0DE** [TryGhost/Ghost#10355] opened 2019-01-09 14:10 UTC
I have a post with a bit of javascript in a Markdown card:
```
<pre><script>
	var FLAGHEIGHT = 260;

	var fieldWidth = 0.76 * FLAGHEIGHT;
```

When this is displayed on the page however,  a  `<pre><code>` is added
```
<pre><script>
	var FLAGHEIGHT = 260;
<pre><code>var fieldWidth = 0.76 * FLAGHEIGHT;
var fieldHeight = FLAGHEIGHT * 7 / 13;
```

Is there a way to prevent this (apart from removing every blank line, I suppose)?

**Comment by xDEADC0DE** [comment] 2019-01-09 14:41
(I've added a <pre> tag to deal with that issue: https://github.com/TryGhost/Ghost/issues/5587#issuecomment-296359030 )

**Comment by xDEADC0DE** [comment] 2019-01-09 14:42
It does work if I remove every blank line from my script. Kinda annoying, but at leat that fixes it.

**Comment by kevinansfield** [comment] 2019-01-09 16:06
@xDEADC0DE the behaviour you are seeing is in accordance with the commonmark (markdown) spec. Blank lines inside a HTML tag indicate the switch back to markdown, the `<pre><code>` you are seeing is because you have your script content indented which the markdown parser interprets as a code block.

Closing as this is the expected behaviour.

**Closed by kevinansfield** 2019-01-09 16:06 UTC

**Comment by xDEADC0DE** [comment] 2019-01-10 13:38
Ok, I'll keep that in mind.

That wasn't the behavior in Ghost 1.0, or am I misremembering it?

**Comment by kevinansfield** [comment] 2019-01-10 13:46
@xDEADC0DE it's been the behaviour since Ghost 1.0.0

**Comment by xDEADC0DE** [comment] 2019-01-10 13:58
That's odd, it worked in october 2017: https://web.archive.org/web/20171014111540/http://www.epinardscaramel.eu/diagrammes-de-factorisation-de-drapeau/

**Comment by xDEADC0DE** [comment] 2019-01-10 13:59
Anyways it's not that important, I don't plan to use a lot of javascript in blog posts :)
Thanks for the quick answer.
