### ISSUE TITLE
Ghost ignores remote mysql in production config

### ISSUE THREAD

**Issue by chrisdlangton** [TryGhost/Ghost#9213] opened 2017-11-05 07:47 UTC
Ghost 1.16.2
Ghost-CLI 1.2.0
Node Version: 6.11.5

Installed via ghost cli, run via pm2.

config.production.json located in /var/www/ghost/current
```
{
  "url": "http://www.langton.cloud",
  "server": {
    "port": 80,
    "host": "127.0.0.1"
  },
  "database": {
    "client": "mysql",
    "connection": {
      "host": "ghost-rds.langton.cloud",
      "user": "user_for_ghost",
      "password": "incorrect",
      "database": "db_for_ghost"
    }
  },
  "mail": {
    "transport": "Direct"
  },
  "logging": {
    "transports": [
      "file",
      "stdout"
    ]
  },
  "process": "systemd"
}
```

Error:
```
[2017-11-05 04:05:40] ERROR

NAME: InternalServerError
CODE: ECONNREFUSED
MESSAGE: The server has encountered an error.

level:normal

InternalServerError: The server has encountered an error.
    at new GhostError (/var/www/ghost/versions/1.16.2/core/server/errors.js:9:26)
    at /var/www/ghost/versions/1.16.2/index.js:38:15
    at tryCatcher (/var/www/ghost/versions/1.16.2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/1.16.2/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/ghost/versions/1.16.2/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/1.16.2/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/versions/1.16.2/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/var/www/ghost/versions/1.16.2/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/www/ghost/versions/1.16.2/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/www/ghost/versions/1.16.2/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
    --------------------
    at Protocol._enqueue (/var/www/ghost/versions/1.16.2/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/var/www/ghost/versions/1.16.2/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at Connection.connect (/var/www/ghost/versions/1.16.2/node_modules/mysql/lib/Connection.js:130:18)
    at /var/www/ghost/versions/1.16.2/node_modules/knex/lib/dialects/mysql/index.js:106:18
    at Promise._execute (/var/www/ghost/versions/1.16.2/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/var/www/ghost/versions/1.16.2/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/var/www/ghost/versions/1.16.2/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL.acquireRawConnection (/var/www/ghost/versions/1.16.2/node_modules/knex/lib/dialects/mysql/index.js:104:12)
    at Object.create (/var/www/ghost/versions/1.16.2/node_modules/knex/lib/client.js:239:16)
    at Pool._createResource (/var/www/ghost/versions/1.16.2/node_modules/generic-pool/lib/generic-pool.js:354:17)
    at Pool.dispense [as _dispense] (/var/www/ghost/versions/1.16.2/node_modules/generic-pool/lib/generic-pool.js:314:10)
    at Pool.acquire (/var/www/ghost/versions/1.16.2/node_modules/generic-pool/lib/generic-pool.js:436:8)
    at /var/www/ghost/versions/1.16.2/node_modules/knex/lib/client.js:289:19
    at Promise._execute (/var/www/ghost/versions/1.16.2/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/var/www/ghost/versions/1.16.2/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/var/www/ghost/versions/1.16.2/node_modules/bluebird/js/release/promise.js:79:10)
```
As you can see it tries to use `127.0.0.1` ignoring the config, any chance there is a bug here or the docs are out of date? Maybe i'm missing something..

**Comment by kevinansfield** [comment] 2017-11-06 09:54
@chrisdlangton it looks like your config file is in the wrong place, for a Ghost-CLI install the config file should be placed in the install root (`/var/www/ghost`), not in the `current` directory.

I'm closing this issue because we don't offer support via Github - it's our "office" and we use it solely for bug tracking and feature development. You can use [slack](https://slack.ghost.org) to get community support if you're not able to find the answer in the [docs](https://docs.ghost.org).

**Closed by kevinansfield** 2017-11-06 09:54 UTC

**Comment by chrisdlangton** [comment] 2017-11-06 10:16
@kevinansfield
You should reopen

The config was copied as-is from the install root, this the report is still unresolved. 

Did you test the null hypothesis at all before dismissal?

**Comment by acburdine** [comment] 2017-11-06 10:20
@chrisdlangton how are you running Ghost via pm2? (Meaning: what was the exact pm2 start command you used?)

**Comment by chrisdlangton** [comment] 2017-11-06 10:33
@acburdine something like “NODE_ENV=production pm2 start /var/www/ghost/current/index.js” off the top of my head. I’ll double check if that seems incomplete (I use Node and pm2 enough I’m 99% sure that’s the command)

**Comment by chrisdlangton** [comment] 2017-11-06 10:48
i changed the value of this file `/var/www/ghost/versions/1.16.2/core/server/config/env/config.production.json` and it worked.

The only thing i can think of is the files i placed;
`/var/www/ghost/config.production.json` and `/var/www/ghost/current/config.production.json` are being read in the wrong order.

**Comment by acburdine** [comment] 2017-11-06 10:54
So that's not _exactly_ the issue. The `config.<env>.json` file is read from the current working directory of the process that runs Ghost. Because your pm2 process doesn't specify a CWD, that's likely where the problem is occurring.

You might try running this command (from inside your ghost install directory /var/www/ghost): `NODE_ENV=production pm2 start ./current/index.js --name "Ghost"` - that should fix the issue.

**Comment by chrisdlangton** [comment] 2017-11-06 10:57
i see - i guess the default CWD is `pwd` right? not intuitive to first timers but I see the ease of that choice.
Might want to make a call out in the docs or something on how to define or "handle" the CWD.

I'll update my init.d script to change the working dir. thanks.
