### ISSUE TITLE
Author URL returns path to homepage instead of author page

### ISSUE THREAD

**Issue by ahmadajmi** [TryGhost/Ghost#9101] opened 2017-10-05 06:46 UTC
### Issue Summary

The `{{url}}` within the author context return `/` instead of the author URL, example:

```hbs
{{#author}}
  <a href="{{url}}">{{name}}</a>
{{/author}}
```

This happens after I did the last update to `1.11.1` from `1.9.0` and `1.6.2`. I launched an instance with DigitalOcean which uses `1.6.2` and did incremental updates based on release numbers, and the issue started to happen from version `1.10.0`.

### Technical details:

* Ghost Version: 1.11.1

**Comment by AileenCGN** [comment] 2017-10-05 06:57
I can confirm this behaviour! `{{url}}` in `author` context does currently not return the author's page.

**Comment by AileenCGN** [comment] 2017-10-05 07:22
This is caused by this commit https://github.com/TryGhost/Ghost/commit/506a0c3e9e51ff4a2ae5bfe0afe84cc5d0bcee18#diff-7a2fe80302d7d6bf67f97cdccef1f71fR213 where we don't expose the `status` field anymore and the `author` context is therefore not detected here https://github.com/TryGhost/Ghost/blob/master/core/server/data/schema/checks.js#L13

Fix for this is coming!

**Closed** 2017-10-05 11:50 UTC
Labels: bug, in review, server
