### ISSUE TITLE
Meta Description not being Auto Generated

### ISSUE THREAD

**Issue by shubhank008** [TryGhost/Ghost#8115] opened 2017-03-08 19:25 UTC
I am using the official Ghost image from Docker (yes, running Ghost in docker) and it doesn't seem to auto-generate the Meta Description, which I am pretty sure it should (since it does other meta-tags).  

I have not changed any settings or theme files and using everything as in stock.

**Comment by kevinansfield** [comment] 2017-03-08 19:55
@shubhank008 the meta description field should not be auto-generated, it has a specific use which is to provide a crafted short description of the content for use by search engines in the results display (although it will only get used if the search engine hasn't found what it feels is more relevant text on the page).

If you enter a custom meta description then the meta description element will be rendered, if you don't enter a custom meta description the field isn't rendered in order to let search engines do what they do best which is to match the results display to the user's query.

I'm going to close this as it's not a bug, if you have any further questions about functionality please head over to our [Slack channel](https://slack.ghost.org), thanks 😄

**Closed by kevinansfield** 2017-03-08 19:55 UTC

**Comment by ErisDS** [comment] 2017-03-09 10:41
Think this might be referring to #4424 which I have on my list to fix for 1.0.
