### ISSUE TITLE
Cannot leave post editor after inserting relative image URL in HTML card

### ISSUE THREAD

**Issue by daniellockyer** [TryGhost/Ghost#12362] opened 2020-11-12 14:35 UTC
### Issue Summary

Inserting a relative image URL into an HTML card prohibits exiting the post editor.

### To Reproduce

1. Create a new post
1. Create a HTML card and insert the following `<img src="img_url" />` where `img_url` is a **relative** image you already had within `content/images`
1. Save the post
1. Try and leave the editor via the back button
1. 💥 See popup asking whether you're sure you want to leave or not
1. Also see a console message talking about `mobiledoc is different`

It looks like the mobiledoc + scratch JSON are different because the relative URL is turned into an absolute one, but they are not kept in sync. This is picked up by Admin and it tries to stop you leaving even though you've saved. The following can be seen in the console:

```
context: Object { 
	current: "{\"version\":\"0.3.1\",\"atoms\":[],\"cards\":[[\"html\",{\"html\":\"<img src=\\\"http://localhost:2368/content/images/banana.jpg\\\"/>\"}]],\"markups\":[],\"sections\":[[10,0],[1,\"p\",[]]]}",
	scratch: "{\"version\":\"0.3.1\",\"atoms\":[],\"cards\":[[\"html\",{\"html\":\"<img src=\\\"/content/images/banana.jpg\\\"/>\"}]],\"markups\":[],\"sections\":[[10,0],[1,\"p\",[]]]}"
}
reason: "mobiledoc is different"
status: "draft"
```

Workaround is to use absolute URLs. 

### Technical details:

* Ghost Version: 3.37.1
* Node Version: 12.18.1
* Browser/OS: Firefox/Linux
* Database: SQLite

**Comment by matthanley** [comment] 2020-11-12 14:40
Closing as this is intended behaviour for now.

**Closed by matthanley** 2020-11-12 14:40 UTC
Labels: customer, editor, later, publishing
