### ISSUE TITLE
л typed in editor shows ц instead

### ISSUE THREAD

**Issue by Khangeldy** [TryGhost/Ghost#9630] opened 2018-05-12 14:15 UTC
I am using ghost to my personal blog. It is awesome. But since nearly update i have one troulbe. In admin not all cyrillic symbols correct showing.

https://i.imgur.com/I6I5ylc.png
There correct word is бөлісу. But in this picture it is like showing ц symbol.

Please correct this mini bug.

**Comment by kevinansfield** [comment] 2018-05-14 08:58
Hey @Khangeldy 👋 Unfortunately I'm not able to reproduce, if I copy/paste "бөлісу" into Ghost's editor (at least with Safari/Chrome on macOS) everything looks fine.

Are you able to provide some reproduction steps?

**Comment by Khangeldy** [comment] 2018-05-15 11:51
I have using arch linux , chromium 66. And i have kk keyboard layout. Step to reproduce is just open editor and type dollar sign in keyboard, when  kazakh language keyboard layout is on.

**Comment by kevinansfield** [comment] 2018-05-15 11:54
OK, I think this will need someone from the community with the respective OS and keyboard environment to test and open a PR with a fix.

**Comment by Khangeldy** [comment] 2018-05-15 12:02
@kevinansfield  OOO sorry it is not dollar sign. It is minus sign  -  adjacent to equal keyboard sign. And i can reproduce this bug just coping ө and pasting it in editor.

**Comment by kevinansfield** [comment] 2018-05-15 12:05
@Khangeldy does the character render correctly when you view it on the published post or in the side-by-side preview?

If it does then that suggests the problem is with the system font on archlinux not having the correct symbols rather than a bug in Ghost.

**Comment by Khangeldy** [comment] 2018-05-15 12:08
@kevinansfield Yes. And when i change font-family to other fonts everything is correct, except monospace font

**Comment by Khangeldy** [comment] 2018-05-15 12:08
Ghost version 1.20.0

**Comment by kevinansfield** [comment] 2018-05-15 12:10
OK, that's a bug in archlinux then, there's not much we can do about that so I'm going to close this issue.

We have a [new editor](https://github.com/TryGhost/Ghost/issues/9311) in development which is not based on markdown so doesn't require a monospace font. It will be launching in beta with next weeks release so keep an eye on that if you're interested in testing it out.

**Closed by kevinansfield** 2018-05-15 12:10 UTC
Labels: admin-client, bug, help wanted

**Comment by Khangeldy** [comment] 2018-05-18 07:47
@kevinansfield You would be right. After installing sudo pacman -S ttf-dejavu and updating system everything works great. Thanks
