### ISSUE TITLE
Post settings menu date picker doesn't use site timezone

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#15497] opened 2022-09-28 18:23 UTC
### Issue Summary

The timezone of post settings menu date picker doesn't match the site's timezone. This prevents a user from editing the publication date of a post when the publication date is published the following day relative to the user's current timezone.

### Steps to Reproduce

- Set the site's timezone to one that is a day ahead of your current timezone
- Start a new draft
- Open the post settings menu, note that the publish date is set to the right date (one day ahead of you)
- Try to edit that value:
<img width="357" alt="image" src="https://user-images.githubusercontent.com/101513/192858508-1ac67e9e-2098-438c-a2e7-9684b7a75cb3.png">

Note that although the date in the box is correct (the 29th in the screenshot), the selected date in the date picker is the previous day (the 28th), or today in your current timezone. Today in the site timezone (29th) is not selectable.

### Ghost Version

5.16

### Node.js Version

16

### How did you install Ghost?

ghost install

### Database type

MySQL 8

### Browser & OS version

Tested in latest Mac Chrome

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by parulgupta26** [comment] 2022-09-30 20:00
Hi @ErisDS  I would like to work on this issue. Please assign to me.

**Comment by ErisDS** [comment] 2022-10-02 08:47
@parulgupta26 we only assign issues to regular contributors. There is no open PR for this issue so it's free to work on.

**Comment by ozanuslan** [comment] 2022-10-02 15:29
Hi, I have a question regarding the intended behavior of this component. Similar to the example you've given above, what should happen when the site's timezone is earlier than the user's timezone? Should the component always enforce the site's timezone?

**Comment by ErisDS** [comment] 2022-10-03 08:16
Correct, the component should be enforcing the site's timezone, not the users.

**Comment by ozanuslan** [comment] 2022-10-03 12:33
I seem to have located the lines that cause this behavior. In the source file [`ghost/admin/app/components/gh-date-time-picker.js`](https://github.com/ozanuslan/Ghost/blob/ee40c9275841e82c46cebce389094d5e536f9038/ghost/admin/app/components/gh-date-time-picker.js) there's the [code block](https://github.com/ozanuslan/Ghost/blob/ee40c9275841e82c46cebce389094d5e536f9038/ghost/admin/app/components/gh-date-time-picker.js#L131-L132) responsible for the `'now'` option that sets the `maxDate`  for the picker. Instead of using `moment.tz()` function it uses the regular `moment()` function which does not consider the timezone of the site. Same behavior can be observed for the `minDate` attribute of the component [here](https://github.com/ozanuslan/Ghost/blob/ee40c9275841e82c46cebce389094d5e536f9038/ghost/admin/app/components/gh-date-time-picker.js#L123-L124). To resolve this issue, I propose that `moment.tz()` to be used along with the [`blogTimezone`](https://github.com/ozanuslan/Ghost/blob/ee40c9275841e82c46cebce389094d5e536f9038/ghost/admin/app/components/gh-date-time-picker.js#L38-L39) variable that is available in the component class for the two instances I mentioned previously (`minDate` and `maxDate`). This change will fix both the minimum date, and maximum date available in the picker to use the site's timezone.

The blocks will change from this:
```js
if (maxDate === 'now') {
    this.set('_maxDate', moment(moment().format(DATE_FORMAT)));
}
```

To this:
```js
if (maxDate === 'now') {
    this.set('_maxDate', moment.tz(moment().format(DATE_FORMAT), blogTimezone));
}
```

If my proposed solution is acceptable I would like to work on this issue.

**Comment by ErisDS** [comment] 2022-10-05 15:03
Please raise a PR 🙂

**Closed** 2022-10-06 18:09 UTC
Labels: bug, admin client, help wanted, Hacktoberfest
