### ISSUE TITLE
Ember Test Errors

### ISSUE THREAD

**Issue by jtwebman** [TryGhost/Ghost#6550] opened 2016-02-20 00:23 UTC
### Issue Summary

When I run grunt validate on Linux I get 1 to 7 fails. Every time I run it I get a different number. Here are some of the errors.

This one always happens:
```
not ok 290 Chrome 48.0 - Global error: Uncaught TypeError: Cannot read property 'get' of undefined at http://localhost:7357/assets/ghost.js, line 8731
    ---
        Log: |
            { type: 'error',
              text: 'Uncaught TypeError: Cannot read property \'get\' of undefined at http://localhost:7357/assets/ghost.js, line 8731\n' }
    ...
```

These sometimes error with no stack trace:
```
not ok 17 Chrome 48.0 - Acceptance: Settings - General when logged in handles private blog settings correctly

not ok 62 Chrome 48.0 - Integration: Component: gh-cm-editor handles editor events

not ok 85 Chrome 48.0 - Integration: Component: gh-navitem-url-input toggles .fake-placeholder on focus

not ok 307 Firefox 44.0 - Acceptance: Settings - General when logged in handles private blog settings correctly

not ok 352 Firefox 44.0 - Integration: Component: gh-cm-editor handles editor events

not ok 375 Firefox 44.0 - Integration: Component: gh-navitem-url-input toggles .fake-placeholder on focus

```
### Steps to Reproduce

1. grunt validate or grunt test-ember

I am running it in Linux Mint 17.3 so maybe it is an environment issue vs Mac?

### Technical details:

* Ghost Version: Current Master Changeset 5429ef4
* Node Version: 4.3.1
* Browser/OS: Firefox 44 (latest) and Chrome 48 (latest)
* Database: Tests use Sqlite

**Comment by acburdine** [comment] 2016-02-20 00:24
Note: these failures were occurring randomly on Travis as well.

**Comment by acburdine** [comment] 2016-02-20 16:47
Here's what I've discovered so far (will continue to update as I research this more)

- 'gh-cm-editor': This is caused by the focus/blur events of the codemirror editor not responding correctly (or fast enough?) in tests. Updating to the newest version of codemirror did not fix the issue.
- Can't read 'get' of undefined: As @jtwebman [pointed out](https://ghost.slack.com/archives/dev/p1455921860000722) in slack, this is being caused by [this line](https://github.com/TryGhost/Ghost/blob/master/core/client/app/mixins/editor-base-controller.js#L131). Not 100% sure why yet.

**Comment by ErisDS** [comment] 2016-06-11 18:21
There's a commit against this PR, just wondering @acburdine if this is all fixed now or if there are outstanding issues?

**Comment by acburdine** [comment] 2016-06-11 18:27
They don't happen often, but they are most often related to timing issues. They don't occur on travis but I occasionally get the gh-cm-editor one locally.

Probably can close this and if one crops up that causes recurring issues we can reopen it.

**Closed by acburdine** 2016-06-11 18:27 UTC
