### ISSUE TITLE
Formatting Issues

### ISSUE THREAD

**Issue by megan201296** [TryGhost/Ghost#9600] opened 2018-04-23 20:52 UTC
### Issue Summary

I am trying to draft and then publish a post. Various authors on multiple machines are encountering the same issue on our platform. What is showing in the preview pane is not what is showing when previewing the page/publishing. Below are screenshots displaying what I mean. I have not been able to get the format properly posted on the blog. It looks perfect in the preview pane, but not on the blog.

<img width="813" alt="screen shot 2018-04-23 at 3 47 47 pm" src="https://user-images.githubusercontent.com/19668285/39152542-54f21c08-470e-11e8-9cb9-e275458cd113.png">
<img width="1214" alt="screen shot 2018-04-23 at 3 48 04 pm" src="https://user-images.githubusercontent.com/19668285/39152545-56b14924-470e-11e8-8f5a-0cfc1ac9cf9a.png">

We are running version `1.20.0` w/ `mysql` db

**Comment by vikaspotluri123** [comment] 2018-04-23 22:17
Hey @megan201296 👋 

If I understand what you're saying properly, you're seeing a difference between the rendered side-by-side preview in the admin interface (i.e. your.blog/ghost/#/editor/{random}) and the rendered post preview in your blog (i.e. your.blog/p/{random}). This is expected behavior, as the purpose of the side-by-side preview is to make sure the _content_ of your post is correct (i.e. did you format your markdown properly), while the post preview is used to make sure the _content **and** layout_ of your post is correct before publishing (i.e. did the code injection apply properly). The side-by-side preview is just a raw rendering of the markdown, with your theme having _no_ influence on the layout / design, while the post-preview is what your post will look like when published, which is _completely_ dictated by your theme.

**Comment by AileenCGN** [comment] 2018-04-24 02:37
Hey @megan201296 

as mentioned by @kevinansfield in the forum, this is not a bug in Ghost, if you're referring to the styles. It is not possible for Ghost to apply the styles from the theme that you're using to the preview in the editor.

I will close the issue here, as we already have an open thread for it in the forum here:

https://forum.ghost.org/t/strange-formatting-issues/1050

If it turns out to be an issue with Ghost, we can always reopen this issue.

**Closed by AileenCGN** 2018-04-24 02:37 UTC
