### ISSUE TITLE
Author meta data

### ISSUE THREAD

**Issue by kaiserhase** [TryGhost/Ghost#9142] opened 2017-10-12 19:18 UTC
### Issue Summary

Modify Author page meta data, similar to how Tags or Pages are handled.

### Steps to Reproduce

```
   } else if (_.includes(context, 'author') && data.author) {
        // The usage of meta data fields for author is currently not implemented.
        // We do have meta_description and meta_title fields
        // in the users table, but there's no UI to populate those.
```

Maybe my OCD is kicking in, but having the author page title show up Brett - Brett seems weird and bad for SEO.

**Comment by AileenCGN** [comment] 2017-10-13 08:08
Hey @kaiserhase 👋 

The meta title for the author page is by default the author's name and the blog title. In your case, both seem to be named the same, which is not a common use case.

The code snippet in your comment actually refers to the meta description, which is currently not implemented for authors.

I will close this issue, as it's not a bug with Ghost. To discuss feature requests, please swing by in our [Slack](https://slack.ghost.org).

**Closed by AileenCGN** 2017-10-13 08:08 UTC

**Comment by kaiserhase** [comment] 2017-10-13 20:31
Hi @AileenCGN 

I guess I should have clarified a bit better:

I want to be able to edit the Meta Title **and** Meta Description for the Author page, just like the Tags, Posts, and Pages do. As it stands, I re-title pages to make them shorter for SEO. In reality, the Title now shows up as Brett Mahoney - Bostons Technical Support Specialist | Brett Mahoney.

My tags all go Tag Name | Brett Mahoney. Short, but descriptive. Or Posts go Short Article | Brett Mahoney. Home Page goes Bostons Technical Support Specialist | Brett Mahoney

It would be more advantageous for me to be able to change the meta title to Author Page | Brett Mahoney, to kill the redundant titling.

The snippet was mostly to show the comment tag "meta data fields for author not implemented" ... Because my author pages also show zero meta description (which some SEO checkers complain about). 

It's _not_ imperative or a deal breaker. More of a feature request. Didn't know if there was a feature suggestion section. Slack tends to take forever to get a response, if any at all. Only get responses if I @ someone and pester a dev directly, which I didnt want to do.
