### ISSUE TITLE
Embedding instagram post not showing picture

### ISSUE THREAD

**Issue by philnord** [TryGhost/Ghost#7683] opened 2016-11-05 09:27 UTC
### Issue Summary

Mac OS X El Capitan, Chrome.
I'm embedding an instagram post by going to instagram.com and hitting "embed" on one of the pictures. This gives me the following snippet:

```
<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="7" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:33.3333333333% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAMUExURczMzPf399fX1+bm5mzY9AMAAADiSURBVDjLvZXbEsMgCES5/P8/t9FuRVCRmU73JWlzosgSIIZURCjo/ad+EQJJB4Hv8BFt+IDpQoCx1wjOSBFhh2XssxEIYn3ulI/6MNReE07UIWJEv8UEOWDS88LY97kqyTliJKKtuYBbruAyVh5wOHiXmpi5we58Ek028czwyuQdLKPG1Bkb4NnM+VeAnfHqn1k4+GPT6uGQcvu2h2OVuIf/gWUFyy8OWEpdyZSa3aVCqpVoVvzZZ2VTnn2wU8qzVjDDetO90GSy9mVLqtgYSy231MxrY6I2gGqjrTY0L8fxCxfCBbhWrsYYAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://www.instagram.com/p/BMaGum_homr/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_blank">Check mate! #SinFrancisco</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A photo posted by San Francisco Native (@adriansky) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2016-11-05T00:12:01+00:00">Nov 4, 2016 at 5:12pm PDT</time></p></div></blockquote>
<script async defer src="//platform.instagram.com/en_US/embeds.js"></script>
```

I then post this in the ghost admin editor but the picture does not show up. In the console I get this error, not sure if related: 

`Redirect from 'http://fonts.gstatic.com/s/opensans/v13/k3k702ZOKiLJc3WVjuplzBampu5_7CjHW5spxoeN3Vs.woff2' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://[my-domain]' is therefore not allowed access.`

### Steps to Reproduce

1. Go to instagram desktop web, select any picture and hit "embed"
2. Paste the snippet in the Ghost Admin Editor
3. See elements appear but no image in it

### Technical details:

* Ghost Version: 0.7.1
* Node Version: 0.12.0 (not sure which node is running but this is the engine I found in package.json)

**Comment by Saytuamin** [comment] 2016-11-11 14:38
Hey, i've attempted to reproduce this issue on windows 10 using chrome and I'm able to embed instagram posts with the images.

**Comment by AileenCGN** [comment] 2017-01-13 04:55
Hey @philnord,

sorry for the delayed reply and also to hear that you're having trouble!

I tested it with our latest LTS release (0.11.4) and the embedded Instagram worked perfectly fine for me.

I also tested it with your setup (Ghost 0.7.1 and Node 0.12.0), but it works just fine for me:

![image](https://cloud.githubusercontent.com/assets/8037602/21918667/5af371d4-d986-11e6-8c50-7fce46e7c4bb.png)

Might it be, that this error

>Redirect from 'http://fonts.gstatic.com/s/opensans/v13/k3k702ZOKiLJc3WVjuplzBampu5_7CjHW5spxoeN3Vs.woff2' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://[my-domain]' is therefore not allowed access.

Is unrelated to the Instagram issue? Can you check this please?

I'll close this issue for now, but if it turns out, that we have a real issue with Ghost here, I'll reopen it.
In the meantime, you can always swing by in our [Slack team](https://slack.ghost.org) to get further help.

Cheers, Aileen

**Comment by JohnONolan** [comment] 2017-01-13 04:59
@philnord Heyo -- I get what you mean. This is actually intentional, we block scripts from executing inside the Ghost editor so that no malicious code can damage your content from the admin area. But if you publish the post, the embed should show up just fine on your site, like @AileenCGN demonstrated above!

**Closed by JohnONolan** 2017-01-13 04:59 UTC
