### ISSUE TITLE
Error 404/500 template not overridden on Alpha

### ISSUE THREAD

**Issue by gomesphoto** [TryGhost/Ghost#8534] opened 2017-06-06 15:03 UTC
### Issue Summary

The template `error.hbs` for error page 404/500 on the theme is not overriding the `core/server/views/error.hbs` on latest alpha release

### Steps to Reproduce

0. Stop server (if running)
1. Create template error.hbs on active theme
2. Start the server
3. Type an unknown route

### Behaviour

Expected: Custom error page template to be rendered
Actual: Default error page template is rendered
### Technical details:

* Ghost Version: v1.0-alpha-21
* Node Version: 7.2.0
* Browser/OS: macOS
* Database: sqLite

**Comment by AileenCGN** [comment] 2017-06-07 05:18
Hey @gomesphoto! Sorry to hear that you're having trouble. 

Unfortunately, I am not able to reproduce this. Switched to Node 7.2 to see if this might be it, but it works fine for me. As soon as I add an `error.hbs` file in to my themes directory and restart Ghost, that's the one which is used.

I will close this issue for now, but we can reopen it, when it turns out to be an issue in the end.

We were talking on [Slack](https://slack.ghost.org) already. Might be worth it to continue there again and you'll share some more information, like screenshots or share your theme to investigate?

**Closed by AileenCGN** 2017-06-07 05:18 UTC
