### ISSUE TITLE
Markdown not rendering just after embedded html.

### ISSUE THREAD

**Issue by satwikkansal** [TryGhost/Ghost#7010] opened 2016-06-19 13:30 UTC
So I have a theme on my blog which uses highlight.js for syntax highlighting. 
For content is of the form
-----------------------------------------------------------------------------------------------------------------
```
-------- Markdown Code----------
 <pre> <code class="Python">
            ..... Some python code
</code> </pre>
--------- Markdown code----------
```
----------------------------------------------------------------------------------------------------------

So the issue is markdown above the embedded html is working fine but the markdown below the embedded html is not rendering at all. As soon as I remove that embedded html , the markdown starts rendering again.
PS : I've checked that all my tags are closed before the markdown code.

I don't know if the following info. is useful or not, but this thing was working fine before and I started to face this issue just after I was prompted to re-authenticate.

**Comment by rawsh** [comment] 2016-06-19 15:34
Happens to me too. My solution was to put a space before the html, and it works because it places the blog in a separate <p> tag.

**Comment by ErisDS** [comment] 2016-09-19 20:01
@satwikkansal sorry for taking so long to reply. I'm afraid I'm not able to reproduce this issue using just the snippet you provided. If you could show me a real broken example that would be great.

I'm going to close this for now, as I cannot reproduce it based on the information provided. If more information is added so that I can reproduce it easily, I will reopen 👍

**Closed by ErisDS** 2016-09-19 20:01 UTC
