### ISSUE TITLE
Meta data's Auto Saving and Publishing

### ISSUE THREAD

**Issue by mskian** [TryGhost/Ghost#10603] opened 2019-03-13 06:00 UTC
After updating to the latest version
I noticed While Editing the `Post Metadata`, `Twitter card`, and `Facebook Card` It's automatically saving & Published the Content
I noticed while Editing Canonical URL in Metadata
I don't know it's a bug or New feature?

**Comment by gargol** [comment] 2019-03-13 06:05
Hi @mskian! Thanks for the report! Is it publishing a draft or just updating content on an already published post? Can you please provide step by step list of what's going on and what you think is expected to happen instead? Cheers ;)

**Comment by mskian** [comment] 2019-03-13 06:12
@gargol 

- No Issues on Draft post 

yes just updating content (Meta Data's) on an already published post

**Comment by gargol** [comment] 2019-03-13 06:14
Will take a look at this now. Thanks, @mskian!

**Comment by mskian** [comment] 2019-03-13 06:17
I checking from My local Ghost side
Sometimes Content goes to Draft while updating Existing Post
I don't how it happens but while update the post content no issue while update post Meta Data's I notice it content goes to Draft

**Comment by gargol** [comment] 2019-03-13 06:22
Oh. Just re-read the message "on an already published post", that's expected behavior :) If you the post is published updating metadata instantly goes into effect :+1:

**Comment by gargol** [comment] 2019-03-13 06:24
> I don't know how it happens but while updating the Existing post Content no issue while updating the Existing Post Meta Data's I notice it Post (Currently Edited Post) goes to Draft

Do you mean that already `published` post is becoming a `draft`?

**Comment by mskian** [comment] 2019-03-13 06:25
@gargol it's new Feature or bug :confused: 
But In the previous Version No Auto-Saving (While updating the Existing Post Meta data)

**Comment by mskian** [comment] 2019-03-13 06:26
> Do you mean that already published post is becoming a draft?

ya Sometimes I face this issue only on Local Development Site

**Comment by gargol** [comment] 2019-03-13 06:41
Could you please provide a reproducible step by step guide (or a quick screencast) of published post becoming a draft problem? And also please include all the information we asked in our bug report template like Ghost version, steps to reproduce and what you expect to happen instead :+1:  

>it's new Feature or bug confused
But In the previous Version No Auto-Saving (While updating the Existing Post Meta data)

I have just checked on version 2.16.0 and the behavior is exactly the same, it always has updated meta information on published post after editing it. Not sure with which version you are comparing it to? Could you please point out when the behavior was different?

**Comment by mskian** [comment] 2019-03-13 07:05
Notice this issue on `2.17.1`
While Update the post meta data's 
It will automatically saved and Published changes

**Comment by gargol** [comment] 2019-03-13 07:47
On which version do you remember not autosaving metadata for a published post? Can't recall Ghost having such limitation :thinking:

**Comment by mskian** [comment] 2019-03-13 07:53
> On which version do you remember not autosaving metadata for a published post? Can't recall Ghost having such limitation

`2.16.4`

**Comment by mskian** [comment] 2019-03-13 08:03
version: Latest
Updating an Existing Post's Meta Data

![gst-bgautsv1](https://user-images.githubusercontent.com/10300271/54262585-8c219c00-4594-11e9-9c31-6bb913238808.gif)

**Comment by gargol** [comment] 2019-03-13 08:15
@mskian , just checked 2.16.4 and it had the exact same behavior as in latest release :thinking:

**Comment by mskian** [comment] 2019-03-13 08:24
@gargol oops Just Now Me too Checked the behavior on `2.16.4`
anyways But if we use Ghost + Gatsby every second It will Deploy the Update while updating the Post Meta's

**Comment by gargol** [comment] 2019-03-13 08:27
> every second It will Deploy the Update while updating the Post Meta's

This is intended behavior ;) it's rather rare to edit posts heavily after publishing. Will close this issue for now, but feel free to report anything new you find with clear reproduction steps :wink:

**Closed by gargol** 2019-03-13 08:27 UTC
Labels: needs info
