### ISSUE TITLE
Published posts with no content sometimes display `null` as content

### ISSUE THREAD

**Issue by frantzypants** [TryGhost/Ghost#10612] opened 2019-03-14 16:53 UTC
### Issue Summary

When a post is published without any content, the content is populated with a value of `null` on the frontend. 

### To Reproduce

1. Create a post without any content and publish it
2. View the published post, see `null` as the content

I would expect the post to be published with no content, rather than seeing `null`

See screenshot:

<img width="1093" alt="Screen Shot 2019-03-14 at 12 52 55 PM" src="https://user-images.githubusercontent.com/6034248/54375808-20a10280-4658-11e9-97a5-97e05d571f28.png">

### Technical details:

Version 2.18.0
Environment production
Database mysql
Mail SMTP
Browser: Chrome/Safari/Firefox

**Comment by kirrg001** [comment] 2019-03-14 17:23
Cannot reproduce locally, nor on my production blog 🤔 @frantzypants Can you?

**Comment by kirrg001** [comment] 2019-03-14 19:53
Steps to reproduce:

1. Create new post
2. Click inside the title (but don't type anything)
3. Then click next to the + menu to start typing. Enter in a single empty space with spacebar, and then delete it
4. Publish post
5. See `null`

**Comment by e-ol** [comment] 2019-03-16 16:00
I believed the problem was on the Ghost-Admin side, with maybe Mobiledoc or the auto-saving system, but then, I saw that the `null` message wasn't displayed when managed by the excerpt helper but by the content helper.

So the question is to know if this `null` state is an expected behavior or not. If not, my solution patches the problem without resolving it.

**Comment by gargol** [comment] 2019-03-18 12:04
After discussing the current conversion of empty `mobiledoc` to `html` with @kevinansfield , it turned out that we had a bug in the converter which wasn't converting default [blank mobiledoc structure](https://github.com/TryGhost/Ghost/blob/master/core/server/lib/mobiledoc/converters/mobiledoc-converter.js#L124) properly as well (should've resulted in `null` similarly to the case in this issue). It is a rare use case, and probably would affect developers experimenting with empty content for posts, but will nice to have consistency across the board. The fix for will land in master shortly which will close this issue :+1:

**Closed** 2019-03-18 12:07 UTC
Labels: bug, help wanted, server
