### ISSUE TITLE
* Bullets change to NaN on intermediate new line

### ISSUE THREAD

**Issue by mrkwse** [TryGhost/Ghost#9438] opened 2018-01-31 19:39 UTC
Welcome to Ghost's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫. Found a bug? Please fill out the sections below... thank you 👍

If your issue is with Ghost CLI, please report it on the CLI repo ➡️ https://github.com/TryGhost/Ghost-CLI/issues/new.

### Issue Summary

Using enter to make a new line between existing `*` bullets in the editor replaces the `*` bullet with `NaN` and if there is no text inserts `undefined` after `NaN`

### Steps to Reproduce

1. Write a two `*` bullet lines in the editor
2. Select the end of a line before another `*` bullet
3. Hit return

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 1.19.2
* Node Version: 6.12.3
* Browser/OS: Safari 11.0.3 on macOS 10.13.3 
* Database: SQLite

**Comment by mrkwse** [comment] 2018-01-31 20:18
I can't reproduce this on a local dev build, so probably localised to my live install. I'll leave open incase someone else wants to try to reproduce, but it's probably just my old and struggling VPS.

**Comment by kevinansfield** [comment] 2018-02-01 07:53
Duplicate of https://github.com/TryGhost/Ghost/issues/9372 and https://github.com/TryGhost/Ghost/issues/9302.

Please use the search before raising a new issue. Thanks 👍

**Closed by kevinansfield** 2018-02-01 07:53 UTC
