### ISSUE TITLE
Text only browsers cannot open posts

### ISSUE THREAD

**Issue by jonathonwiebe** [TryGhost/Ghost#9572] opened 2018-04-16 17:26 UTC
### Issue Summary

Using the Lynx browser to view the site, I cannot open posts to view the content. The link navigation jumps to the article author and just displays the authors page. 
Using Ubuntu 16.04 & Lynx Version 2.8.9dev.8 (21 Dec 2015)

### Steps to Reproduce

1. Install Lynx
2. Press g
3. Enter site URL
4. Navigate using up/down arrows
5. Watch the selection cursor jump past the titles

I would expect article titles to be links so content pages are navigable.

### Technical details:

* Ghost Version: 1.22.1
* Node Version: ghost pro
* Browser/OS: Lynx 2.8.9/Ubuntu 16.04
* Database: ghost pro

**Comment by kevinansfield** [comment] 2018-04-17 08:12
Hi @jonathonwiebe 👋 I believe this issue belongs on the [Casper](https://github.com/TryGhost/Casper) (Ghost's default theme) rather than here, however I am unable to reproduce the issue you are seeing using Lynx 2.8.8 on macOS.

I'm going to close this issue because it's not reproducible and is on the wrong repo. If you re-open it on [Casper](https://github.com/TryGhost/Casper) (if that's the theme you are using) then please provide a screencast to show the issue and help others reproduce.

**Closed by kevinansfield** 2018-04-17 08:12 UTC
