### ISSUE TITLE
Semver Naming issues in Themes

### ISSUE THREAD

**Issue by nywillb** [TryGhost/Ghost#9595] opened 2018-04-20 20:57 UTC
### Issue Summary

When I upload a theme with the [semver compliant](https://semver.org/#spec-item-11) `1.0.0-beta` version, I am told that it is not semver compliant. 

### Steps to Reproduce

1. Upload a theme with `1.0.0-beta` as the version
2. Look for error message

### Technical details:

* Ghost Version: `v1.22.3`
* Node Version: `v6.9.5`
* Browser/OS: `Firefox 60.0b13`
* Database: `mysql`

**Comment by AileenCGN** [comment] 2018-04-23 07:04
Hey @nywillb 

I am sorry to hear that your having trouble. Unfortunately, I am not able to reproduce this behaviour.

Could you please provide more information? Show the error message from [gscan](https://gscan.ghost.org), or provide the theme that causes this issue?

**Comment by AileenCGN** [comment] 2018-05-14 09:08
Closing this, at it's not reproducible and no further info upon request was provided. We can always reopen this issue, when it appears again, or we are able to reproduce this certain situation.

**Closed by AileenCGN** 2018-05-14 09:08 UTC
Labels: needs info
