### ISSUE TITLE
Reference Error define is not defined

### ISSUE THREAD

**Issue by javajohnHub** [TryGhost/Ghost#8782] opened 2017-07-30 11:57 UTC
### Issue Summary
After Inviting a team member, when they click the link in their email it takes them to the signup page but page is blank.

Client is using:
OS: Ubuntu 16
Browsers: Firefox, Chrome
### Steps to Reproduce

1. Invite Author Team member.
2. Team member receives email and clicks link.
3. Team member is taken to my blogs signup page.
4. Page displayed is empty. Chrome dev tools Errors.

I expected no errors because when I performed a test using an personal alternate email, it worked fine. This test was done on Mac and chrome.

### Technical details:

* Ghost Version: 0.11.9
* Node Version: 4.2.6
* Browser/OS: Ubuntu 16.0.4
* Database: Mysql

![image](https://user-images.githubusercontent.com/9591445/28753102-9f8cc70c-74fc-11e7-8131-b35e32b4cb18.png)

**Comment by ErisDS** [comment] 2017-08-02 12:47
Not sure what might be causing this yet, however I just wanted to recommend setting up SSL at least for your admin panel :)

**Comment by kirrg001** [comment] 2017-08-10 21:27
I would like to close this issue. I am not able to reproduce this. 

We can always re-open this issue. I hope you sorted your problem out 👋

**Closed by kirrg001** 2017-08-10 21:27 UTC
Labels: admin-client, LTS

**Comment by javajohnHub** [comment] 2017-08-11 00:57
sorry i think the problem was a bad mailgun setup. Once i set it up correctly the user was able to join.
