### ISSUE TITLE
Inconsistent membership count

### ISSUE THREAD

**Issue by os72** [TryGhost/Ghost#12494] opened 2020-12-23 23:28 UTC
ghost  3.40.1

I think this is a bug – the “members” admin panel shows inconsistencies when filtering by all/free/paid

For example, I’m seeing:

    All: 245
    Free: 130
    Paid: 112

The “paid” list seems to be correct, the “free” one is missing users

https://forum.ghost.org/t/inconsistent-membership-count/19042

**Comment by matthanley** [comment] 2020-12-24 17:01
Closing as duplicate of #12160

**Closed by matthanley** 2020-12-24 17:01 UTC

**Comment by os72** [comment] 2020-12-24 18:02
I think the missing users in this case are free but not canceled (never paid). However, they do seem to have a stripe account.
I'm not sure how that comes about, maybe they clicked on the plan link (to stripe) but didn't end up completing the purchase (?)
