### ISSUE TITLE
The content of the post is not shown on the AMP pages.

### ISSUE THREAD

**Issue by godofredoninja** [TryGhost/Ghost#10552] opened 2019-03-01 04:43 UTC
Hello 😄 

— I will be very brief in explaining. The content of the article is not shown on the AMP pages.

![amp](https://user-images.githubusercontent.com/10253167/53616861-987c2100-3bb2-11e9-8e5c-91730a13fa62.jpg)

### Technical details:

* Ghost Version: 2.16.2
* Node Version: v10.15.1

**Comment by kirrg001** [comment] 2019-03-01 19:12
Duplicate of https://github.com/TryGhost/Ghost/issues/10547. Will be released asap 👍

**Closed by kirrg001** 2019-03-01 19:12 UTC
