### ISSUE TITLE
Disable automatic image optimization from Animated GIF images

### ISSUE THREAD

**Issue by truekasun** [TryGhost/Ghost#9939] opened 2018-10-03 07:27 UTC
### Issue Summary

When a user imports an animated GIF image into ghost admin, it automatically optimized the image and removes all the animated frames and image becomes a normal static image.

### To Reproduce

1. Create a new post with Ghost admin
2. Import an animated GIF image into the post
3. Preview the article (and the optimized files through FTP)

### Technical details:

* Ghost Version: 2.1.0
* Node Version: v8.11.1
* Browser/OS: Chrome/Debain 9
* Database: MySQL

**Comment by kevinansfield** [comment] 2018-10-03 08:35
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/9848. This was fixed in [Ghost 2.1.1](https://github.com/TryGhost/Ghost/releases/tag/2.1.1)

**Closed by kevinansfield** 2018-10-03 08:35 UTC
