### ISSUE TITLE
Raw, unaltered input in post

### ISSUE THREAD

**Issue by m0nhawk** [TryGhost/Ghost#9176] opened 2017-10-24 14:29 UTC
I'm using KaTeX for rendering math equations.

I found, that on multi-line input Ghost is "altering" the input, so KaTeX is unable to render the equation.

Say, I have the following equation, KaTeX will only render if it's unaltered:

```
$$
\begin{aligned}
   a&=b+c \\
   d+e&=f
\end{aligned}
$$
```

But, on page it look like:

```
<p>$$<br>
\begin{aligned}<br>
a&amp;=b+c \<br>
d+e&amp;=f<br>
\end{aligned}<br>
$$</p>
```

The `<p>` tag is not a problem, but altering ampersand and slashes with `<br>` tag are.

Is it possible to have "raw" tag, which won't change the input (`<code>` is not an option here)? Or is it available right now?

**Comment by kevinansfield** [comment] 2017-10-24 14:40
@m0nhawk anything wrapped in HTML tags will be output as-is, so you could use a `<div>` or `<span>`, eg:

```markdown
# KaTeX example

<div>
$$
\begin{aligned}
   a&=b+c \\
   d+e&=f
\end{aligned}
$$
</div>

More markdown...
```

Inserting the KaTeX code without wrapping in HTML isn't supported as there is no support in CommonMark for "raw" output like that.

There will likely be more options in the future once our full mobiledoc editor lands where you could add a raw/html card, or there may be a way to add custom markdown-it extensions such as [markdown-it-katex](https://github.com/waylonflinn/markdown-it-katex).

Closing this issue as it's not a bug. In the future please direct any support requests to our [Slack channel](https://slack.ghost.org), our GitHub repo is _not_ the right place for these type of issues - our [support guide](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md) was linked in the GitHub notification above the issue creation form as well as the default issue text and it has details about what issues you should raise here and which issues should be handled elsewhere. (Many projects have their own support guidelines and GitHub highlights them for you, please read them before opening issues 😄)

**Closed by kevinansfield** 2017-10-24 14:40 UTC
