### ISSUE TITLE
Author twitter card does not have an image

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [TryGhost/Ghost#10988] opened 2019-08-05 08:46 UTC
Author and tag pages are missing the proper meta (<meta name="twitter:image")  and therefore do not display an images on twitter cards.

### Example
https://twitter.com/Syknapse/status/1136530592395399168

### To Reproduce
Include a url of an author page in a tweet.

![image](https://user-images.githubusercontent.com/4591597/62450942-f7535100-b775-11e9-99f9-f3cd3e6c88c9.png)

freeCodeCamp/news-theme#18

**Comment by gargol** [comment] 2019-08-05 15:25
Hey @ahmadabdolsaheb :wave: 	

> Author and tag pages are missing the proper meta (<meta name="twitter:image")

This is not completely true because [currently](https://github.com/TryGhost/Ghost/blob/df7e64f/core/frontend/meta/structured_data.js#L30) `twitter:image` is being set to the `cover_image` attribute of the displayed resource. If you go into Admin UI and upload a cover photo at the author page (at `ghost/#/staff/{author_slug}`) or use "upload tag image" button when editing the tag on tags page (at `/ghost/#/tags/{tag_slug}`) you will get those images in `twitter:image` meta tag :wink:

**Comment by gargol** [comment] 2019-08-06 09:42
Additionally, the `profile_image` is not being used for this meta tag deliberately to avoid low quality, deformed images popping up in the feed. 

With that said we had some considerations within the team and think adding an additional fallback to newly introduced site-wide SEO fields `twitter_image` and `og_image` would make sense here :wink: 

Closing this issue as it's and intended behavior.

**Closed by gargol** 2019-08-06 09:42 UTC

**Comment by ahmadabdolsaheb** [comment] 2019-08-06 09:47
Thanks for the clarification @gargol.
