### ISSUE TITLE
User invite duplication and broken errors

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8692] opened 2017-07-14 16:32 UTC
It turns out you can invite a user email address that already has an account (this should not be possible) - and if you do, then they get this really ugly error when they try to accept the invitation (there should be an english error here, in case a user tries to manually put in an email address which already exists):

![image](https://user-images.githubusercontent.com/120485/28221188-3ef7f1bc-68ba-11e7-8c9a-6ab38cca62bc.png)

**Comment by kirrg001** [comment] 2017-07-14 19:58
Good catch 👍 This only happens on the invite screen for me. I've pushed a PR.

@kevinansfield The error handling need's improving, because no matter which error the api returns, the admin always shows: 

> Failed to send 1 invitation: katharina.irrgang@gmail.com. Please check your email configuration, see https://docs.ghost.org/v1.0.0/docs/mail-config for instructions

In my case, the API returned a validation error saying `ValidationError: User is already registered`.

**Comment by PaszaVonPomiot** [comment] 2017-07-14 22:36
I couldn't invite user with the same email address from team menu.

**Comment by letsjustfixit** [comment] 2017-07-14 22:45
try inviting a user other than your own :)

**Comment by PaszaVonPomiot** [comment] 2017-07-14 23:47
It didn't word for me:
![image](https://user-images.githubusercontent.com/5560454/28234399-76ba758a-68ff-11e7-9a32-3db81e4777c3.png)

**Comment by kevinansfield** [comment] 2017-07-18 21:39
With the server-side changes and the changes in https://github.com/TryGhost/Ghost-Admin/pull/786 I'm not sure what else is left to do here?

It would be useful to know how the duplicate user was created in the first place - as @kirrg001 mentioned the only place this _should_ have been possible was inviting the owner user on the setup/three invite screen which should now be fixed. I've not been able to invite an existing or invited user via the team screen.

**Comment by ErisDS** [comment] 2017-07-19 06:32
@kevinansfield to get exact steps you would need to ask @johnonolan. However, I would guess at this happening after an import, inviting a user that was locked.

**Comment by JohnONolan** [comment] 2017-07-19 12:48
Yes it was after an import. I don't remember which order, actually, it could have been either: 

- Import content, including user x@y.com
- Invite x@y.com

or the other way around

**Comment by kirrg001** [comment] 2017-07-20 00:38
I am not able to reproduce this with latest master. 

Closing - please re-open if you discover this again!

**Comment by JohnONolan** [comment] 2017-07-20 13:00
In RC1 I just successfully imported a user, who had a pending invitation to the blog - no duplicate entry detected. 

![image](https://user-images.githubusercontent.com/120485/28418398-9a0f9b48-6d6c-11e7-9dbc-c71616bbc6e0.png)

Then when I clicked on the accept invitation link in the email, I got redirected to the login screen

The invitation still shows up in Ghost admin - but there is no way to accept it.

**Comment by kevinansfield** [comment] 2017-07-20 13:06
@JohnONolan this has been resolved in master, the fix isn't in RC1

**Closed by kevinansfield** 2017-07-20 13:06 UTC
Labels: admin-client, bug, server
