### ISSUE TITLE
Content-Length is returned on OPTIONS requests

### ISSUE THREAD

**Issue by jloh** [TryGhost/Ghost#11441] opened 2019-12-13 04:53 UTC
### Issue Summary

When doing an `OPTIONS` request to Ghost it returns a `Content-Length` header of 8. Upstream webservers choke over this as they are expecting more data to be returned and think the upstream (Ghost) is closing the connection prematurely.

### To Reproduce

1. Put a webserver in front of Ghost, Nginx for example
2. Do an `OPTIONS` request to Ghost and see the webservers logs complain about the upstream closing the connection
    ```
    curl -v -X OPTIONS <your ghost host>
    ```

### Technical details:

* Ghost Version: 3.1.1
* Node Version: v10.16.3
* Browser/OS: Chrome
* Database: MySQL

**Comment by ErisDS** [comment] 2020-07-09 17:26
Closing this because it's expected behaviour! 

E.g. `curl -v -X OPTIONS https://demo.ghost.io`

Returns: `GET,HEAD`, which is 8 characters.

The content-length is therefore correct.

**Closed by ErisDS** 2020-07-09 17:26 UTC
Labels: bug, pinned, server
