### ISSUE TITLE
Migration to v4: AMP error - style tag not authorised by Google

### ISSUE THREAD

**Issue by louisnt-prod** [TryGhost/Ghost#12786] opened 2021-03-18 16:12 UTC
### Issue Summary

I migrated my ghost blog to the latest version yesterday, received this morning an alert from the Google Search Console regarding the AMP pages:

_Only "amp-boilerplate" and "amp-custom" style tags are allowed, and only in the document header._

This is linked to this part of the code is the AMP page:

`<style>:root {--ghost-accent-color: #E65C5C;}</style>
`

### To Reproduce

1. Open any ghost post AMP page (for example: https://beyondmatching.com/lets-build-the-new-roast-together/amp/)

2. Inspect the page

3. Line 84 is causing the issue: <style>:root {--ghost-accent-color: #E65C5C;}</style>

**Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?**

The AMP tag is missing, the AMP page will not be indexed on Google due to this

### Technical details:

* Ghost Version: 4.0.1
* Node Version: 12.21.0
* Browser/OS: 
* Database:

**Comment by kevinansfield** [comment] 2021-03-18 16:15
Closing as duplicate of https://github.com/TryGhost/Ghost/issues/12770

**Closed by kevinansfield** 2021-03-18 16:15 UTC
