### ISSUE TITLE
Problem with Links while using `_`

### ISSUE THREAD

**Issue by akshaybabloo** [TryGhost/Ghost#6880] opened 2016-05-24 02:10 UTC
### Issue Summary

I don't know if this is happening to everyone or not, but when I try to create links with `_`, the `_` is removed, and all the texts are merged (see the screenshot).

![screen shot 2016-05-24 at 2 02 16 pm](https://cloud.githubusercontent.com/assets/7360286/15490002/a689951e-21b8-11e6-9a11-a824225692ba.png)

### Steps to Reproduce

1. Just do what I have done from the screenshot. You should get the same result.

### Technical details:

* Ghost Version: 0.8.0
* Node Version: 4.4.3
* Browser/OS: Chrome/OSX 10.11.5
* Database: SQLite

**Comment by acburdine** [comment] 2016-05-24 03:05
@akshaybabloo This isn't an issue because underscores are actually a way to italicize text in markdown 😉

I _think_ you can use a backslash to escape the italics? Like so: \_some\_underscored\_text\_here (I put \ in front of each underscore)

**Comment by akshaybabloo** [comment] 2016-05-24 03:08
But this doesn't happen in in GitHub - [this_is_a_very_long_text](#somelink)

**Comment by acburdine** [comment] 2016-05-24 03:18
Ghost uses a different markdown parser than Github, which means it's likely a bug in Ghost's markdown parser Showdown (which has likely been fixed since, Ghost is just operating on an older fork of it).

At the moment, I would just use backslashes to work around the issue 😄 I'll go ahead and re-open this issue though for the sake of logging it

**Comment by akshaybabloo** [comment] 2016-05-24 03:24
@acburdine I think it's time to update the parser 😜

**Comment by ErisDS** [comment] 2016-05-24 16:06
Gonna close it again as it's a duplicate of #1501 😉

**Closed by ErisDS** 2016-05-24 16:06 UTC
Labels: bug, editor
