### ISSUE TITLE
Night Shift - Backgrounds White When Should Be Dark

### ISSUE THREAD

**Issue by dbalders** [TryGhost/Ghost#8564] opened 2017-06-10 18:39 UTC
### Issue Summary

Some backgrounds are still white when they should be dark for nightshift

(timezone should have dark background)
<img width="696" alt="screen shot 2017-06-10 at 11 33 39 am" src="https://user-images.githubusercontent.com/4715098/27005308-08808ee0-4dd1-11e7-810c-d228d86caacf.png">
<img width="1010" alt="screen shot 2017-06-10 at 11 33 48 am" src="https://user-images.githubusercontent.com/4715098/27005311-08834478-4dd1-11e7-9701-5548f5763b64.png">

(writing area should have dark background, currently white text on white background)
<img width="874" alt="screen shot 2017-06-10 at 11 34 06 am" src="https://user-images.githubusercontent.com/4715098/27005310-0882658a-4dd1-11e7-90c7-86c2c4faafc1.png">
<img width="853" alt="screen shot 2017-06-10 at 11 34 11 am" src="https://user-images.githubusercontent.com/4715098/27005312-0886f9b0-4dd1-11e7-8117-1e51786204f3.png">
<img width="882" alt="screen shot 2017-06-10 at 11 34 22 am" src="https://user-images.githubusercontent.com/4715098/27005313-08874bb8-4dd1-11e7-97e0-900ad7ce3e6f.png">
<img width="1021" alt="screen shot 2017-06-10 at 11 34 35 am" src="https://user-images.githubusercontent.com/4715098/27005314-089849f4-4dd1-11e7-98c0-d171542d6e15.png">
<img width="592" alt="screen shot 2017-06-10 at 11 34 40 am" src="https://user-images.githubusercontent.com/4715098/27005315-089a0550-4dd1-11e7-8776-2a54c3867c2f.png">
<img width="442" alt="screen shot 2017-06-10 at 11 34 52 am" src="https://user-images.githubusercontent.com/4715098/27005316-089a7c2e-4dd1-11e7-96a1-06fb3b34e2bb.png">

### Technical details:

* Ghost Version: 1.0-beta-1
* Node Version: 4.6.2
* Browser/OS: Chrome Mac OS
* Database: MySQL

**Comment by PaszaVonPomiot** [comment] 2017-06-11 00:20
Same as #8560

**Comment by nuclearpengy** [comment] 2017-06-11 00:26
This is going to be so epic

**Comment by acburdine** [comment] 2017-06-11 01:24
Closing as a duplicate of #8560.

**Closed by acburdine** 2017-06-11 01:24 UTC
