### ISSUE TITLE
Discord webhooks don't seem to function anymore (via Slack integration)

### ISSUE THREAD

**Issue by elijahsgh** [TryGhost/Ghost#18723] opened 2023-10-23 06:39 UTC
### Issue Summary

The documentation for Discord integration says to use the Slack integration as they are compatible.
However I receive a generic error.

### Steps to Reproduce

1. Create incoming webhook in discord
2. Paste into slack integration
3. Press test button

Expected to see a test message in discord. Instead I receive this error in the console logs.

### Ghost Version

5.64.0

### Node.js Version

18.18

### How did you install Ghost?

Kubernetes

### Database type

MySQL 8

### Relevant log / error output

```shell
2023-10-23 00:26:08.699 CST
[2023-10-23 06:26:08] [36mINFO[39m "POST /ghost/api/admin/slack/test/" [32m200[39m 21ms
2023-10-23 00:26:08.731 CST
[2023-10-23 06:26:08] [36mINFO[39m "GET /ghost/api/admin/stats/member_count/" [32m200[39m 50ms
2023-10-23 00:26:08.869 CST
[2023-10-23 06:26:08] [31mERROR[39m The server has encountered an error.
2023-10-23 00:26:08.869 CST
[31m
2023-10-23 00:26:08.869 CST
[31mThe server has encountered an error.[39m
2023-10-23 00:26:08.869 CST
{}
2023-10-23 00:26:08.869 CST
[37m"The slack service was unable to send a ping request, your site will continue to function."[39m
2023-10-23 00:26:08.869 CST
[33m"If you get this error repeatedly, please seek help on https://ghost.org/docs/."[39m
2023-10-23 00:26:08.869 CST
{}
2023-10-23 00:26:08.869 CST
[1m[37mError ID:[39m[22m
2023-10-23 00:26:08.869 CST
    [90m0d9ab240-716d-11ee-a2f3-6dfaacfea57f[39m
2023-10-23 00:26:08.869 CST
{}
2023-10-23 00:26:08.869 CST
[90m----------------------------------------[39m
2023-10-23 00:26:08.869 CST
{}
2023-10-23 00:26:08.869 CST
[90mHTTPError: Response code 400 (Bad Request)     at /var/lib/ghost/versions/5.64.0/core/server/services/slack.js:147:27     at EventEmitter.<anonymous> (/var/lib/ghost/versions/5.64.0/node_modules/@tryghost/request/node_modules/got/source/as-promise.js:74:19)     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[39m
2023-10-23 00:26:08.869 CST
[39m
```
```


### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment] 2023-10-23 09:19
Duplicate of https://github.com/TryGhost/Ghost/issues/17452 - please see the solution in there

**Closed by daniellockyer** 2023-10-23 09:19 UTC
Labels: needs:triage
