### ISSUE TITLE
Error : Invalid salt version: 2

### ISSUE THREAD

**Issue by Pluto-Y** [TryGhost/Ghost#5692] opened 2015-08-20 08:42 UTC
When I setup my ghost blog and submit the form.
The right bottom showed the infomation "Invalid salt version: 2".
Then I also can't login the blog.
What should I do?

**Comment by ErisDS** [comment] 2015-08-20 10:11
Hi @PlutoZhang, sorry to hear you're having trouble. If you need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. This is a bug tracker for ongoing development of the Ghost software, and we're not able to do support here!

**Comment by sebgie** [comment] 2015-08-29 17:26
Hey @PlutoZhang, while testing migrations from 0.4.2 was able to reproduce your issue :). I think you came across that issue when trying to add a new user via API call?

I'm about to send a fix that hopefully solves this problem!

**Comment by ErisDS** [comment] 2015-08-29 17:27
@sebgie the problem is already fixed in #5706?

**Comment by sebgie** [comment] 2015-08-29 17:34
ok, would be great to link this issue to the fix :)

**Closed** 2015-09-02 16:53 UTC
