### ISSUE TITLE
Outgoing links during editing

### ISSUE THREAD

**Issue by bretthayes** [TryGhost/Ghost#5058] opened 2015-03-20 21:11 UTC
When you are editing a post and you include a markdown link `[link text](//domain.com)` in the editor, clicking on it in the preview uses the parent window and you lose your changes. There should be a prompt asking me "Are you sure you want to leave this page?" or at least make the links open with `_blank` when in the edit mode. I just lost changes because of this.

**Comment by novaugust** [comment] 2015-03-20 21:55
Hey @bretthayes, that sounds weird. We do have a built in "Are you sure?" dialogue that pops up if you have changes that aren't saved and you're about to leave the page. I just checked, and that's what happens for me. Can you come back and [list out a scenario](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs) where I can recreate this issue?

**Comment by ErisDS** [comment] 2015-03-25 10:07
Hi @bretthayes, I'm really sorry you lost changes whilst using Ghost. As @novaugust said, we do have that 'Are you sure?' dialog built into Ghost, but it only fires if there are changes since the last autosave. As far as we are aware, this feature is working correctly in Ghost 0.5.10, but there have been bugs in previous versions which may be the cause.

Without a little bit more information like what version of Ghost you were using, your environment and particularly whether autosave was firing correctly at the time, there's no way for us to track down or determine what happened here, therefore I'm going to close the issue for now. Please do come back and let us know if you are able to reproduce the issue on 0.5.10 and we'll reopen and investigate.

**Closed by ErisDS** 2015-03-25 10:07 UTC
