### ISSUE TITLE
Issue in Timezone handling

### ISSUE THREAD

**Issue by pbeckmann** [TryGhost/Ghost#11717] opened 2020-04-06 15:09 UTC
#### Issue Summary
There is an issue with the timezone handling, i think. If i publish a new post, it’ll show in the internal post list as published, but in two hours. This results in failures in editing, as for the republish the date must be in the past. This failure is reproduced in the rss-feed too.
I could reproduce it on 2 of my blogs.
### To Reproduce

Server and Ghost Time is UTC+2
1. Publish new Post
2. In the Post List now stands published in 2 hours
### Technical details:

Version 3.12.1
Environment production
Database mysql
Mail Direct
Browser: Safari

**Comment by tobimori** [comment] 2020-04-18 13:25
I'm having the same issue.

**Comment by gargol** [comment] 2020-04-20 04:50
Probable duplicate of https://github.com/TryGhost/Ghost/issues/11659

**Comment by kevinansfield** [comment] 2020-04-23 23:18
Closing as duplicate of https://github.com/TryGhost/Ghost/issues/11749.

@pbeckmann please see that issue for further details. It would help if you shared how you installed Ghost there too, thank you!

**Closed by kevinansfield** 2020-04-23 23:18 UTC
Labels: bug
