### ISSUE TITLE
Keyboard shortcut "Control-Alt-P" to publish post does not work in Ubuntu/Firefox browser

### ISSUE THREAD

**Issue by fieldse** [TryGhost/Ghost#6682] opened 2016-04-07 07:50 UTC
Keyboard shortcut listed at http://support.ghost.org/shortcuts:

> Ctrl/⌘ + Alt + P 	Publish post

Does not work under Firefox / Ubuntu 15.10

Please confirm if this bug is the same for you.

**Comment by acburdine** [comment] 2016-04-09 17:49
Hey @fieldse, I just tried this on my Mac, firefox version 45.0.1, and couldn't replicate this.

Do you have any more info that you can provide about this?

**Comment by fieldse** [comment] 2016-04-11 04:30
Hi Austin. I'm using Firefox most recent version (44?) on Ubuntu 15.10,
with Gnome desktop / compiz window manager. (Ubuntu standards.) Other
keyboard shortcuts work (such as Control-S to "save draft"). I love Ghost's
use of keyboard shortcuts, so hope this minor issue could be resolved.

Thanks!

**Comment by acburdine** [comment] 2016-04-14 02:35
Does the other shortcut that uses the Alt key (the HTML copy/paste shortcut), work? If not it might be something to do with the alt key but otherwise I have no idea.

You might also consider dropping by our [slack](https://ghost.org/slack/) channel. Communication is a _bit_ faster there :wink:

**Comment by sakulstra** [comment] 2016-06-07 11:32
I'm using firefox in the exact same environment and can't reproduce the bug.

**Comment by acburdine** [comment] 2016-06-07 11:34
I'm going to close this then. @fieldse if it's still an issue please swing by our [slack](http://ghost.org/slack) channel. If it turns out to be more of a bug then we can re-open this 😄

**Closed by acburdine** 2016-06-07 11:34 UTC
