### ISSUE TITLE
Blog showing gibberish HTML

### ISSUE THREAD

**Issue by JoshWillik** [TryGhost/Ghost#6183] opened 2015-12-07 20:43 UTC
# Problem

Ghost outputs scrambled strings into the page sent to the browser.

Here is an example of the output HTML.

```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="HandheldFriendly" content="True" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title>__aSyNcId_&lt;_BOmoIcLx__</title>
  <meta name="description" content="__aSyNcId_&lt;_audDrhlT__">

  <link rel="alternate" type="application/rss+xml" title="RSS" href="https://blog/rss/">
  <link rel="stylesheet" href="/assets/css/main.css?v=f4550be16f">

  __aSyNcId_&lt;_MPpY_qmQ__
</head>

<body class="__aSyNcId_&lt;_JJdlJTyf__">
<div class="main-wrapper">
  <header class="main-header">
    <div class="title-wrapper">
      <h1><a href="https://blog">My Blog</a></h1>
      <p>It&#x27;s end of tagline</p>
    </div>

    <nav class="main-menu">
      <ul>
  <li class="">
    <a href="https://blog/author/josh">Josh</a>
  </li>
  <li class="">
    <a href="https://blog/author/thomas">Thomas Jefferson</a>
  </li>
  <li class="">
    <a href="https://blog/author/bill">Bill Murray</a>
  </li>
</ul>

    </nav>
  </header>

  <main>
  
<div class="columns">
__aSyNcId_<_pwRjpHQV__</div>

  </main>

  <footer class="main-footer">
    <nav class="main-menu"><ul>
  <li class="">
    <a href="https://blog/author/josh">Josh</a>
  </li>
  <li class="">
    <a href="https://blog/author/thomas">Thomas Jefferson</a>
  </li>
  <li class="">
    <a href="https://blog/author/bill">Bill Murray</a>
  </li>
</ul>
</nav>
    <p><a href="https://blog/rss/">Subscribe to RSS</a> updates.</p>
    <p>
      <a href="https://www.ghost.org">Ghost</a>
      +
      <a href="https://www.github.com/joshwillik/bard-theme">Bard</a>
      =
      &hearts;
    </p>
  </footer>
  __aSyNcId_&lt;_fyaXUCCu__
</div>
</body>
</html>

```

# When

I first noticed this problem when trying to make a theme that showcases the posts of 3 authors side by side. ( JoshWillik/bard-theme )

It happens way more often on my 3 author theme, but this problem still pops up from time to time on the Casper 1.1.7

**Comment by ErisDS** [comment] 2015-12-07 22:20
Hi @JoshWillik, this is a duplicate of https://github.com/TryGhost/Ghost/issues/5850. Looks to me like your bard theme is using the beta features, these are expected to be buggy :wink:

**Closed by ErisDS** 2015-12-07 22:20 UTC

**Comment by JoshWillik** [comment] 2015-12-08 01:20
Ah, I didn't see this one.
I expected it to be buggy, so this is the bug report :wink: 

Glad to see you guys are aware of it.

**Comment by ErisDS** [comment] 2015-12-08 07:46
Very aware, it's even documented in the get helper docs 😉



—

**Comment by JoshWillik** [comment] 2015-12-08 14:57
Ah, so it is. I guess that's what I get for not fully reading the docs.

Sorry to have wasted your time!
