### ISSUE TITLE
No support for Polish language in Stories

### ISSUE THREAD

**Issue by papcorp** [TryGhost/Ghost#10442] opened 2019-02-01 12:35 UTC
Trying to enter any Polish specific characters (diacritical ones) results in a number of other functionalties to open/start. Like ALT C, ALT L opens spellchecking and numbered list. I know this is an issue for many other languages using diacritical characters as I found reports on forums from other countries/languages.
Basically this makes the editor unusable, i have to write stories in WORD then copy it and format in the ghost editor.

This problem applies to all Ghost versions so far no matter the browser or OS.

**Comment by kevinansfield** [comment] 2019-02-01 12:52
Those shortcuts are only present in the markdown card as of 2.0. Closing this as a duplicate of https://github.com/TryGhost/Ghost/issues/8687. Upstream issue in SimpleMDE is tracked here 
https://github.com/sparksuite/simplemde-markdown-editor/issues/616

**Closed by kevinansfield** 2019-02-01 12:52 UTC
