### ISSUE TITLE
Specifying "fields" in a GET request to /posts is broken

### ISSUE THREAD

**Issue by john-mcgowan1992** [TryGhost/Ghost#9763] opened 2018-07-31 17:31 UTC
When making a request with `fields` specified in the query string, the request fails. 
 ```
Request.get('https://www.yourdomain.com/ghost/api/v0.1/posts/', {
            qs: {
                client_secret: ghostClientSecret,
                client_id: ghostClientId,
                filter: 'tag:-press,featured:true',
                fields: '[id,slug]'
            }
        })
```

with the following error:

```
{"errors":[{"message":"select `id`, `slug`, `published_at`, `author_id` from `posts` left outer join `posts_tags` on `posts_tags`.`post_id` = `posts`.`id` left outer join `tags` on `posts_tags`.`tag_id` = `tags`.`id` where (`posts`.`status` = \'published\' and `posts`.`page` = false) and (`tags`.`slug` != \'press\' or `posts`.`featured` = true) group by `posts`.`id` order by CASE WHEN posts.status = \'scheduled\' THEN 1 WHEN posts.status = \'draft\' THEN 2 ELSE 3 END ASC,posts.published_at DESC,posts.updated_at DESC,posts.id DESC limit 15 - ER_NON_UNIQ_ERROR: Column \'id\' in field list is ambiguous","errorType":"InternalServerError"}]}
```
I'm using `request-promise` in node

**Comment by kevinansfield** [comment] 2018-08-01 10:47
@john-mcgowan1992 I think you may need to use `fields: 'post.id,post.slug'` but I may be wrong.

@kirrg001 should this be handled automatically?

**Comment by kirrg001** [comment] 2018-08-01 11:01
See https://github.com/TryGhost/Ghost/issues/8649.

**Comment by kevinansfield** [comment] 2018-08-01 11:08
Closing as a duplicate of #8649, #5604, #5615. There's on-going work on the underlying [GQL library](https://github.com/TryGhost/GQL) that will either resolve this or put us in a position where it can be resolved.

@john-mcgowan1992 for now the recommendation is to not use `fields` with the `filter` param.

**Closed by kevinansfield** 2018-08-01 11:08 UTC

**Comment by john-mcgowan1992** [comment] 2018-08-01 17:20
@kevinansfield apologies for the duplicate. One more quick question, and I was unable to find a ticket for this after doing a quick search. Is there also a known issue when combining `fields` and `include` in the same query? I also tried the following query string to no avail: 
```
          qs: {
               client_secret: ghostClientSecret,
               client_id: ghostClientId,
               fields: '[id,slug]',
               include: 'tags'
           }
```
Basically, I need a way to query the slug and id of my posts and then filter them by tag. Given the previously mentioned tickets, the only other way is to do the filtering on the client side. However, the above query only returns the id and slug, leaving out the tags. This leaves me with the only option of querying the entire post object in order to filter down these properties, which is overkill. Anyway, I understand you guys have your hands full. Just wanted to check if combining `fields` and `include` is also a no op
