### ISSUE TITLE
wrong word count for non western languages

### ISSUE THREAD

**Issue by SimonHausdorf** [TryGhost/Ghost#11819] opened 2020-05-17 06:12 UTC
I have the following words in Thai:

> จะถูกเปิดตัว

Pages (word for mac) and word it self gives me a word count of 4 while ghost only counts 1 word. This breaks the x minutes to read feature.

An option would be to estimate the time by characters rather than words so an estimation would be also possible for Thai or Chinese. And maybe an option to display characters inside the editor?

**Comment by kevinansfield** [comment] 2020-05-17 20:22
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/11599

**Closed by kevinansfield** 2020-05-17 20:22 UTC
