### ISSUE TITLE
Sidepane does not close

### ISSUE THREAD

**Issue by sumukshashidhar** [TryGhost/Ghost#11753] opened 2020-04-19 14:03 UTC

**Comment by sumukshashidhar** [comment] 2020-04-19 14:09
Summary:
In the draft view, when you open the sidepane (the one with the SEO optimisations, the image selection, and socials), it sometimes does not close.

This happens pretty sporadically, though I do not use ghost enough to document how often this occurs

Technical Details
Ghost Version: 3.13.3
Node Version: 12.10.x
Browser: Safari on MacOS 10.15 Catalina
OS: Ubuntu 18.04 on amazon EC2
Database: sqlite3

I've been working around this by exiting out of the drafts view and re-entering it, but just thought it would be good to document it here.

(PS: I run two ghost sites, two separate instances, on a t2.micro . I believe it is 1 gig of RAM, and the recommended RAM is 600 mb per site, but all other aspects work flawlessly with the current setup, as the number of visitors are a bare minimum, so I did not think this is a RAM issue.)

**Comment by kevinansfield** [comment] 2020-04-19 14:47
Closing as duplicate of https://github.com/TryGhost/Ghost/issues/9925

**Closed by kevinansfield** 2020-04-19 14:47 UTC

**Comment by sumukshashidhar** [comment] 2020-04-19 15:37
@kevinansfield  Extremely sorry if I'm missing something, but wasn't that post closed as it was stale?

Also, it looks like the issue referenced was with relation to the scroll of the PSM, does it apply to the closing of the PSM as well?

I also did read  that this is an issue particularly with safari, is there a fix in the works?
