### ISSUE TITLE
Recommand: Use 302 instead of 301, or add an option.

### ISSUE THREAD

**Issue by jinchizhong** [TryGhost/Ghost#6671] opened 2016-04-03 10:03 UTC
### Issue Summary

Ghost use 301 to redirect url, such as domain not match, resource not found.
But 301 is dangerous. For example, if you set a wrong domain. 
(https://xxx.con, you want .com but you make a mistake).
Then all users after access http://xxx.com, will cannot access the right url anyway.

### Steps to Reproduce

1. Set config.url, and access website by ip or other domain.
2. You got a 301

### Technical details:

* Ghost Version: 0.7.8
* Node Version: 4.4.2
* Browser/OS: any
* Database: any

**Comment by kevinansfield** [comment] 2016-04-03 10:17
Hey @jinchizhong, `301` redirects have been purposefully chosen as they are the only type that transfer page rank and other SEO benefits and will cause search engines to overwrite the old page with the new page in their indexes.

Whilst you are setting up/configuring it's possible to clear your cache or run with dev tools open so that 301's don't get cached.

I'm going to close this as it's not a bug, if you want to suggest configurable redirects as a new feature we have a wishlist at ideas.ghost.org where features can be suggested and voted upon.

**Closed by kevinansfield** 2016-04-03 10:17 UTC
