### ISSUE TITLE
Public API is blocking the render

### ISSUE THREAD

**Issue by rawsh** [TryGhost/Ghost#8968] opened 2017-09-03 18:30 UTC
Enabling the public api gives a "Eliminate render-blocking JavaScript and CSS in above-the-fold content" from google pagespeed insights. This can be fixed by moving it to the footer.

Here is a page that gets the error: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.devpy.me%2F&tab=desktop

**Comment by kevinansfield** [comment] 2017-09-03 19:19
Closing as a duplicate of #7299. FYI, simply moving the script may not be the best solution as it would likely break any site that includes scripts relying on `ghost-sdk.js` to already be loaded.

**Closed by kevinansfield** 2017-09-03 19:19 UTC
