### ISSUE TITLE
Portal script loading can’t be disabled

### ISSUE THREAD

**Issue by morremeyer** [TryGhost/Ghost#12865] opened 2021-04-10 20:38 UTC
### Issue Summary

With ghost 4.x `{{ ghost_head }}` loads a script from unpkg.com

```
<script defer src="https://unpkg.com/@tryghost/portal@~1.1.0/umd/portal.min.js" data-ghost="https://isabelmeyer.de/"></script>
```

This can’t be disabled anywhere currently. As privacy is important to me and my customers and in the EU sideloading a script without the users consent is at least problematic from a privacy perspective, it puts ghost users in some jurisdictions (at least Germany) into an impossible situation: We need to have a contract with each party we send our users data to. 

So in this case, I’d need to have a contract with unpkg.com as they are processing personal data (at least the IP) of my customers customers.

### To Reproduce

1. Use ghost 4.x
2. Check any page source for `<script defer src="https://unpkg.com`

I consider this a bug because it is a new behavior that 

a) can’t be disabled 
b) is at least in a legal grey area in some jurisdictions

### Technical details:

* Ghost Version: 4.2.0

### Proposal

I propose to package the script with ghost in some way (I prefer this solution because it removes the external dependency. If I can help in any way to implement it, I'm happy to.

**Comment by Louvki** [comment] 2021-04-12 11:19
Same issue. It also impacts the load page speed as the script is huge
![image](https://user-images.githubusercontent.com/24243356/114386507-99ede500-9b91-11eb-8f33-b59e4386564d.png)

**Comment by joseftw** [comment] 2021-04-12 20:17
Please give us an option to remove this script (and disable the portal altogether).

**Comment by ErisDS** [comment] 2021-04-13 09:48
This is a duplicate of #12835. 

If you want to load a different portal.min.js file you can do so by modifying your Ghost config.environment.json file.

The default config is:

```
"portal": {
        "url": "https://unpkg.com/@tryghost/portal@~1.1.0/umd/portal.min.js",
        "version": "~1.1.0"
    }
```

You can add this to your config.environment.json to change it if you want to load locally or a forked version or not load anything.

Again though, I stress, the script is used for theme-based Members features, not just portal and so it's in use more than people realise.

**Closed by ErisDS** 2021-04-13 09:48 UTC

**Comment by morremeyer** [comment] 2021-04-13 20:21
@ErisDS Thank you for this information. I still think **there should be an option to turn it off completely**; if one is not using any members features, leaving the `url` empty leaves a `script` tag with an empty `src` attribute in the page which is not valid. 

At least Firefox will note this in the console.

So there has to be a valid URL set which does not do anything - in this case requiring a workaround.

## Workaround with nginx

This is the workaround I used with nginx. To anybody with the same issue, feel free to copy it for your setup.

`config.production.json`:

```json
  "portal": {
    "url": "https://example.com/empty-script.js",
    "version": "1.0.0"
  }
```

nginx configuration snippet (drop this in the `server` block for your ghost setup):

```
location = /empty-script.js {
  add_header Content-Type text/javascript;
  return 200;
}
```

**Comment by joshperry** [comment] 2024-01-02 03:39
I agree that having this config value set to `false` (like `sodoSearch__url`) should elide the portal script tag (instead it sets `src="false"`).

I set these env vars in my container:
```yaml
portal__url: "data:text/javascript,(function(){}())"
sodoSearch__url: "false"
```

Portal still creates a script tag, but my browser doesn't seem to complain.

```html
<script defer="" src="data:text/javascript,(function(){}())" data-i18n="false" data-ghost="https://curiouslynerdy.com/" data-key="ca5fe45a37fb27c668b94ef819" data-api="https://curiouslynerdy.com/ghost/api/content/" crossorigin="anonymous"></script>
```

**Comment by ltoinel** [comment] 2024-12-17 21:40
The issue seems to be back ...  since the 5.104.0 or maybe before.

When "false" is used as URL like described in the documentation : https://ghost.org/docs/config/

"The script can be relocated by changing the URL, or disabled entirely by setting "url": false."

The member script is injected in the page with "false" as a URL creating 404 error on Web Spiders  : 

`<script defer src="[false](https://www.geeek.org/benq-screenbar-pro-test-avis/false)" data-i18n="true" data-ghost="https://www.geeek.org/" data-key="81c2fe03bca1f308d4f99f1e54" data-api="https://www.geeek.org/ghost/api/content/" data-locale="fr" crossorigin="anonymous"></script>`
