### ISSUE TITLE
Complimentary subscriptions disappear on save

### ISSUE THREAD

**Issue by brainandbrain** [TryGhost/Ghost#13010] opened 2021-06-04 21:30 UTC
### Issue Summary

When I saved edits to existing member accounts who had complimentary subscriptions, the subscriptions vanished. The “Add complimentary subscription” option is also missing on these accounts, though it's still visible on other members (both free members and paid).

### To Reproduce

1. Add label to existing member who has a complimentary subscription.
2. Save changes.

I tested one of the affected accounts and can confirm that it can no longer access paid content. I also tested creating a new member with a complimentary account, and I was able to replicate the issue with it as well.

It's also worth noting that after I cancelled another member's complimentary subscription, the “Add complimentary subscription" option was also missing from their account page. The expected behavior would be for it to appear once there's no longer a subscription for the account.

### Technical details:

* Ghost Version: 4.6.4
* Node Version: 14.17.0
* Browser/OS: Safari 13.1.3, Catalina 10.15.7
* Database: DigitalOcean

**Comment by chiragnd** [comment] 2021-06-07 03:36
@brainandbrain Hey, I’d reported this to support last week 
(I ran into it when changing the member’s email address), they confirmed the issue of losing a complimentary subscription and that a fix is on the way. 

And to resolve the subscription, I had to attach a subscription to the same member on Stripe and then it showed up in Ghost, if that helps.

**Comment by ErisDS** [comment] 2021-06-07 10:45
Hi @brainandbrain and @chiragnd this is a duplicate of https://github.com/TryGhost/Ghost/issues/13003, which was fixed and closed last week, but had (incorrectly) not yet been released.

It is now released as the only change in 4.6.5.

**Closed by ErisDS** 2021-06-07 10:45 UTC

**Comment by brainandbrain** [comment] 2021-06-07 13:53
Hi @ErisDS, I'm unfortunately still seeing that the “Add complimentary subscription" is missing on all of these members after updating to 4.6.5, so I'm still unable to add back the complimentary subscriptions that were lost. Should that have been part of this fix or is it something still being worked on?

**Comment by ErisDS** [comment] 2021-06-07 20:14
Sorry I believe this was fixed and released in 4.6.6

**Comment by brainandbrain** [comment] 2021-06-07 20:18
Thanks, @ErisDS! Works great now.
