### ISSUE TITLE
Ghost content directory write error deploying with now

### ISSUE THREAD

**Issue by colinmeinke** [TryGhost/Ghost#7359] opened 2016-09-11 17:31 UTC
### Issue Summary

Ghost throws an error when deploying with [now](https://zeit.co/now).

```
ERROR: Unable to access Ghost's content path
EACCES: permission denied, open '/home/nowuser/src/content/apps/17e84fd4f8afb461'
Error [Error: Command node index ended with code 235]
```

### Steps to Reproduce

1. Download a fresh copy of Ghost and cd to directory
2. Install now with `npm install -g now`
3. Deploy with `now`

See example deploy: https://ghost-wmpodxshwt.now.sh/

This is expected as `core/server/utils/startup-test.js` tries to write a random file to each subdirectory within the content directory to make sure it has write access.

The now server is not persistent (like heroku), and does not allow write access to any directory apart from `/tmp`.

As now suggest using external services for writing to file, and Ghost supports using services such as RDS and S3 for storing content, I can't see a reason to force the content directory to be writable (unless I'm missing something?).

I'd suggest adding a config variable `contentWritable`, that can be set to `false` if the deploy is using external services to write all content. The content directory writable test will run in `core/server/utils/startup-test.js` *unless* `contentWritable` is set to `false`. I will add a PR for this behaviour.

### Technical details:

* Ghost Version: 0.10.1
* Node Version: 4.4.5
* Browser/OS: OSX
* Database: sqlite

**Comment by acburdine** [comment] 2016-09-11 18:39
@colinmeinke quick question: has deployment using this method worked in the past?

The reason I'm asking is those content path checks were added 2 years ago - and haven't changed since then afaik. There _could_ have been some things that changed in a different place for the theme upload/download feature that broke it somewhere else, but it's unlikely.

The changes you're suggesting sound like a good start - will leave this open though for further review.

/cc @ErisDS

**Comment by colinmeinke** [comment] 2016-09-11 18:46
Now is really new, and I've never tried deploying Ghost to it before. From searching their slack channel I'm the only one mentioning Ghost, so I assume nobody else has tried either. It will have never worked if these checks have been around for some time. PR coming right up!

**Comment by colinmeinke** [comment] 2016-09-17 17:13
This check **is** required, and will be until [all file writes use storage adapters](https://github.com/TryGhost/Ghost/issues/5926). Only image files currently use a storage adapter. Other files such as database backups, logs etc. are still written locally. Until a time when we can guarantee no files will be written to the content directory, and [the content directory writable check can be turned off](https://github.com/TryGhost/Ghost/pull/7360), Ghost will not work with [now](https://zeit.co/now).

**Comment by ErisDS** [comment] 2016-09-19 13:40
Going to close this for now with the same reason as I closed the PR: https://github.com/TryGhost/Ghost/pull/7360 - it's not a bug, but rather there's a larger refactor needed to make anything like this possible.

**Closed by ErisDS** 2016-09-19 13:40 UTC
