### ISSUE TITLE
Navigation settings prevent using https for links in same domain while ghost site is in http.

### ISSUE THREAD

**Issue by Allu2** [TryGhost/Ghost#6121] opened 2015-11-24 05:20 UTC
### Issue Summary:
Navigation settings prevent using https for links in same domain while setup is in http
[Image of the problem page http://puu.sh/lwHUh/fb3b4f8c37.png](http://puu.sh/lwHUh/fb3b4f8c37.png)

### What I tried:
I tried adding the World Map navigation link, but when ever I'd press save it replaces the https part with http making the link broken.

### What was expected:
Ghost should've added https link as any link.

### What happened:
The https link was replaced with "http" version of the link.

### Steps to repeat:
* Go to /ghost/settings/navigation/
* Try setup link with same domain as ghost but with https while ghost runs on http
* Press "SAVE"

### System:
Ghost Version: 0.7.1
Database: sqlite3
NodeJS: 0.10.40-1nodesource1~vivid1
OS: Ubuntu 15.04 vivid
Linux: 2.6.32-042stab108.7 SMP Wed Jul 15 15:49:08 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux
Tested on: Firefox 43.0b5

### Background:
Currently I have Apache2 serving another site on 443 over ssl but any references to that site are impossible to add in the navigation bar since it replaces the https with http.
I've tested however that it does allow https links to other domains with no problems.

**Comment by kevinansfield** [comment] 2015-11-24 09:53
@Allu2 the issue is that navigation urls to the same domain as the blog are always saved in a relative format (eg. you enter `https://koodaacraft.org/map/` but it will be saved as `/map/`) so that whichever protocol is being used on the site is respected.

The UI however will show the full url as we had a number of people confused about relative vs absolute urls. If you change your `url` setting in `config.js` to use the `https` version of the domain then the UI will reflect that, although in the background all your same-domain navigation urls are still saved as relative.

**Comment by ErisDS** [comment] 2015-12-01 10:15
Hi @Allu2 really appreciate the in depth bug report here. Can you explain why you have a single page of your Ghost blog that needs to be served via HTTPS and not the rest of it? Not sure I fully understand the use case here.

**Comment by Allu2** [comment] 2015-12-02 03:34
@ErisDS  I hope this helps to clarify the scenario ^^

Originally I had website for a Minecraft server using Octopress as the blogging platform and Apach2 to serve it.

I had set up the Apache to work with https and serve the site only using it.

The old system had setup for viewing the Minecraft servers live world map rendered by dynmap plugin at https://koodaacraft.org/map/ so users could see the whole world map from their browsers. This was done by configuring the dynmap plugin itself to work with Apache instead of using it own internal webserver.

Now when I wanted to move to using Ghost I set it up to the default http and 80 port, which worked fine since Apache wasn't using it. This way  I could have both site up and running while I set things up and test them. It would also safe me the trouble of re-configuring the dynmap plugin if I could just serve it trough https with the existing Apache configuration.

So this is how I ended up with having Apache serving the existing setup with https://koodaacraft.org/map
and Ghost running at http://koodaacraft.org/

I've since then made small workaround by adding subdomain "blog" to the address making it https://blog.koodaacraft.org/map which I then could add to the navigation section without it being replaced with http.

Probably this kind of problem would be completely avoided if I wouldn't try to use pieces of the old setup, so this problem might be rather "specific" to me :S

**Comment by ErisDS** [comment] 2015-12-02 04:15
Hi @allu2, I think this is a very special case and that fixing it would likely cause problems for other much more common cases. I'd like to close this for now as something we can't fix, but I'll happily revisit if we find more people running into this.

**Closed by ErisDS** 2015-12-02 04:15 UTC
