### ISSUE TITLE
Can not edit links that flow over two lines in editor

### ISSUE THREAD

**Issue by tvld** [TryGhost/Ghost#11640] opened 2020-03-05 08:03 UTC
When a link flows over two lines, the edit- popup appears in the middle. Too far from the cursor to reach it without disappearing:
![Screenshot from 2020-03-05 08-59-35](https://user-images.githubusercontent.com/986182/75960267-0a6f0080-5ec0-11ea-8a92-ea409c848592.png)
The only way to edit this link, is to first temporary delete some text in front of it so it no longer flows over two lines.

**Comment by kevinansfield** [comment] 2020-03-05 09:03
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/9792

**Closed by kevinansfield** 2020-03-05 09:03 UTC
