### ISSUE TITLE
URLs (e.g. images) in RSS broken if blog in subdirectory

### ISSUE THREAD

**Issue by aseigo** [TryGhost/Ghost#5064] opened 2015-03-22 17:46 UTC
Version: 0.5.10

If your blog is not top-level but in a subdirectory, e.g.: https://example.com/blogs/user/ then URLs for assets such as images will appear in the RSS feed with the subdir duplicated in the URL. Example: 

https://example.com/blogs/user/content/images/2015/03/Image.jpg

becomes:

https://example.com/blogs/user/blogs/user/content/images/2015/03/Image.jpg

Note the duplication of "blogs/user/"

**Comment by aseigo** [comment] 2015-03-22 18:30
FWIW, the offending line is this in core/server/controllers/frontend.js

     baseUrl = attributeValue[0] === '/' ? siteUrl : item.url;

The issue is that (some?) images (such as the post image) have the starting slash, but also already include the blogs subdir, so the subsequent concatenation with siteUrl results in two copies of the subdir portion. Not familiar enough with the code base to know what the preferred solution would be, but the path prefixes of siteUrl and attributeValue need comparison.

**Comment by novaugust** [comment] 2015-03-22 19:35
This may be a dupe of #5033 / closed by #5056? Haven't looked into the details, but sounds similar

**Comment by ianlopshire** [comment] 2015-03-22 21:08
I don't believe #5056 will resolve this issue. The offending section doesn't appear to be using `config.urlFor` to compose absolute URLs.

**Comment by aseigo** [comment] 2015-03-23 06:49
Indeed, this URL Is put together manually with concatenation:

     attributeValue = baseUrl + attributeValue;

**Comment by ianlopshire** [comment] 2015-03-24 00:12
I would't mind tackling this one, but I'm not sure what the best approach is. Should it be somehow tied into `urlFor` or should it be done in-line where it's at?

**Comment by ErisDS** [comment] 2015-03-28 07:44
@ianlopshire eventually we want all URL generation to go through urlFor, so I think that would be the right approach.

**Comment by ianlopshire** [comment] 2015-03-31 19:18
I hope to look at this sometime this week

**Comment by ErisDS** [comment] 2015-04-03 13:13
:+1: Let me know if you need to discuss the approach any further. It might be a case of needing a quick fix for now if the urlFor approach ends up too involved.

**Closed** 2015-04-09 14:35 UTC
Labels: blocker, bug
