### ISSUE TITLE
Allow to use uppercased env variables

### ISSUE THREAD

**Issue by mahnunchik** [TryGhost/Ghost#8935] opened 2017-08-24 16:00 UTC
### Issue Summary

Current implementation allows to use only lowercased env variables: `database__connection__host`.

It is better to support both styles: uppercased an lowercased.

`nconf` module supports this feature:  https://github.com/indexzero/nconf#env

```
nconf.env({ lowerCase: true });
var port = nconf.get('port') // 3001
```

### Technical details:

* Ghost Version: 1.7.1

**Comment by kirrg001** [comment] 2017-08-28 20:34
Hey @mahnunchik 👋

I agree to your suggestion. Thanks! 

I would still like to close this issue, as it's not a bug. We use Github sorely for bug tracking and feature development only. 

Are you able to PR your suggestion and assign it to me? 👋

**Closed by kirrg001** 2017-08-28 20:34 UTC
