### ISSUE TITLE
Migration update from 5.17.1 to 5.22.4 failed

### ISSUE THREAD

**Issue by Zagur** [TryGhost/Ghost#15766] opened 2022-11-03 16:06 UTC
### Issue Summary

Can't update from 5.17.1 to 5.22.4

### Steps to Reproduce

1. ghost update
2. It is successfully updated to version 5.22.4, but some links in the administrative part do not work correctly.
3. Click on Post - Published. (Error: "Request not understood error, cannot list posts. Could not understand request.")

### Ghost Version

5.17.1

### Node.js Version

v16.18.0

### How did you install Ghost?

Local Install. Debian 11.

### Database type

MySQL 5.7

### Browser & OS version

Firefox 106.0.4. Kubuntu 22.04

### Relevant log / error output

```shell
[2022-11-03 17:04:44] ERROR "GET /ghost/api/admin/posts/?formats=mobiledoc%2Clexical&limit=30&page=1&filter=status%3Apublished" 400 22ms

NAME: BadRequestError
CODE: ER_BAD_FIELD_ERROR
MESSAGE: Could not understand request.

level: normal

Error: select `posts`.*, (with `k` as (select `member_id` from `members_subscription_created_events` where posts.id = members_subscription_created_events.attribution_id union select `member_id` from `members_created_events` where posts.id = members_created_events.attribution_id) select count(*) from `k`) as `count__conversions`, `posts`.*, (select count(distinct `members_click_events`.`member_id`) from `members_click_events` inner join `redirects` on `members_click_events`.`redirect_id` = `redirects`.`id` where posts.id = redirects.post_id) as `count__clicks`, `posts`.*, (select COALESCE(ROUND(AVG(score) * 100), 0) from `members_feedback` where posts.id = members_feedback.post_id) as `count__sentiment`, `posts`.*, (select count(*) from `members_feedback` where posts.id = members_feedback.post_id AND members_feedback.score = 0) as `count__negative_feedback`, `posts`.*, (select sum(`score`) from `members_feedback` where posts.id = members_feedback.post_id) as `count__positive_feedback` from `posts` where (`posts`.`status` = 'published' and `posts`.`type` = 'post') order by CASE WHEN posts.status = 'scheduled' THEN 1 WHEN posts.status = 'draft' THEN 2 ELSE 3 END ASC,CASE WHEN posts.status != 'draft' THEN posts.published_at END DESC,posts.updated_at DESC,posts.id DESC limit 30 - Unknown column 'posts.id' in 'where clause'
    at /var/www/vhosts/mydomain.com/www/versions/5.22.4/node_modules/@tryghost/bookshelf-pagination/lib/bookshelf-pagination.js:259:27
    at Packet.asError (/var/www/vhosts/mydomain.com/www/versions/5.22.4/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/var/www/vhosts/mydomain.com/www/versions/5.22.4/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/var/www/vhosts/mydomain.com/www/versions/5.22.4/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/var/www/vhosts/mydomain.com/www/versions/5.22.4/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/var/www/vhosts/mydomain.com/www/versions/5.22.4/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/var/www/vhosts/mydomain.com/www/versions/5.22.4/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment] 2022-11-03 16:58
Duplicate of https://github.com/TryGhost/Ghost/issues/15743 - you also need to upgrade mysql to v8 as Ghost v5 does not support mysql 5.

**Closed by ErisDS** 2022-11-03 16:58 UTC
Labels: needs triage
