### ISSUE TITLE
Error suggesting edits in api docs

### ISSUE THREAD

**Issue by cotterjd** [TryGhost/Ghost#8450] opened 2017-05-11 18:16 UTC
### Issue Summary

Can't suggest edits for api docs. Errors upon submit.
This was the edit I was trying to make. Pretty sure it's syntactically correct: 

**Note:** You need Public API enabled for this. You can make sure it's enabled in the Labs section of your blogs admin area.

### Steps to Reproduce

1. Make an edit
2. Fill out form at the bottom
3. Click "suggest edits" button. 

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I expected it to be submitted. You guys need a lot of help on your docs.

### Technical details:

* Ghost Version:
* Node Version:
* Browser/OS: Chrome(Version 60.0.3088.3 (Official Build) dev (64-bit))/Firefox Developer Edition (54.0a2(2017-04-29)(64-bit)/Safari(Version 10.1 (12603.1.30.0.34))/macOS Sierra Version 10.12.4
* Database: 

here's the actual error: 
Error: err.data is undefined
submitForm/<@webpack:///./_legacy/public/directives/smart/smart.js?:124:17
$http/promise.error/<@webpack:///./bower_components/angular/angular.js?:9442:11
processQueue@webpack:///./bower_components/angular/angular.js?:13318:27
scheduleProcessQueue/<@webpack:///./bower_components/angular/angular.js?:13334:27
$eval@webpack:///./bower_components/angular/angular.js?:14570:16
$digest@webpack:///./bower_components/angular/angular.js?:14386:15
$apply@webpack:///./bower_components/angular/angular.js?:14675:13
done@webpack:///./bower_components/angular/angular.js?:9725:36
completeRequest@webpack:///./bower_components/angular/angular.js?:9915:7
requestLoaded@webpack:///./bower_components/angular/angular.js?:9856:9
EventHandlerNonNull*createHttpBackend/<@webpack:///./bower_components/angular/angular.js?:9839:7
sendReq@webpack:///./bower_components/angular/angular.js?:9694:9
serverRequest@webpack:///./bower_components/angular/angular.js?:9406:16
processQueue@webpack:///./bower_components/angular/angular.js?:13318:27
scheduleProcessQueue/<@webpack:///./bower_components/angular/angular.js?:13334:27
$eval@webpack:///./bower_components/angular/angular.js?:14570:16
$digest@webpack:///./bower_components/angular/angular.js?:14386:15
$evalAsync/<@webpack:///./bower_components/angular/angular.js?:14609:15
completeOutstandingRequest@webpack:///./bower_components/angular/angular.js?:4940:7
Browser/self.defer/timeoutId<@webpack:///./bower_components/angular/angular.js?:5328:7
setTimeout handler*Browser/self.defer@webpack:///./bower_components/angular/angular.js?:5326:17
$evalAsync@webpack:///./bower_components/angular/angular.js?:14607:11
$QProvider/this.$get</<@webpack:///./bower_components/angular/angular.js?:13222:7
scheduleProcessQueue@webpack:///./bower_components/angular/angular.js?:13334:5
then@webpack:///./bower_components/angular/angular.js?:13282:36
when@webpack:///./bower_components/angular/angular.js?:13498:12
$http@webpack:///./bower_components/angular/angular.js?:9410:21
createShortMethodsWithData/</$http[name]@webpack:///./bower_components/angular/angular.js?:9628:18
action@webpack:///./_legacy/public/js/hub.js?:1095:7
submitForm@webpack:///./_legacy/public/directives/smart/smart.js?:110:13
link/<@webpack:///./_legacy/public/directives/smart/smart.js?:105:15
dispatch@webpack:///./bower_components/jquery/dist/jquery.js?:4434:15
add/elemData.handle@webpack:///./bower_components/jquery/dist/jquery.js?:4121:6
EventListener.handleEvent*add@webpack:///./bower_components/jquery/dist/jquery.js?:4167:7
on/<@webpack:///./bower_components/jquery/dist/jquery.js?:4861:4
each@webpack:///./bower_components/jquery/dist/jquery.js?:374:14
each@webpack:///./bower_components/jquery/dist/jquery.js?:139:10
on@webpack:///./bower_components/jquery/dist/jquery.js?:4860:10
jQuery.fn[name]@webpack:///./bower_components/jquery/dist/jquery.js?:7486:4
link@webpack:///./_legacy/public/directives/smart/smart.js?:71:11
invokeLinkFn@webpack:///./bower_components/angular/angular.js?:8281:9
nodeLinkFn@webpack:///./bower_components/angular/angular.js?:7791:11
compositeLinkFn@webpack:///./bower_components/angular/angular.js?:7140:13
nodeLinkFn@webpack:///./bower_components/angular/angular.js?:7786:24
compositeLinkFn@webpack:///./bower_components/angular/angular.js?:7140:13
compositeLinkFn@webpack:///./bower_components/angular/angular.js?:7143:13
compositeLinkFn@webpack:///./bower_components/angular/angular.js?:7143:13
compositeLinkFn@webpack:///./bower_components/angular/angular.js?:7143:13
compositeLinkFn@webpack:///./bower_components/angular/angular.js?:7143:13
nodeLinkFn@webpack:///./bower_components/angular/angular.js?:7786:24
compositeLinkFn@webpack:///./bower_components/angular/angular.js?:7140:13
compositeLinkFn@webpack:///./bower_components/angular/angular.js?:7143:13
publicLinkFn@webpack:///./bower_components/angular/angular.js?:7019:30
bootstrapApply/<@webpack:///./bower_components/angular/angular.js?:1460:11
$eval@webpack:///./bower_components/angular/angular.js?:14570:16
$apply@webpack:///./bower_components/angular/angular.js?:14669:18
bootstrapApply@webpack:///./bower_components/angular/angular.js?:1458:9
invoke@webpack:///./bower_components/angular/angular.js?:4219:14
doBootstrap@webpack:///./bower_components/angular/angular.js?:1456:5
bootstrap@webpack:///./bower_components/angular/angular.js?:1476:12
angularInit@webpack:///./bower_components/angular/angular.js?:1370:5
@webpack:///./bower_components/angular/angular.js?:26446:5
fire@webpack:///./bower_components/jquery/dist/jquery.js?:3099:10
fireWith@webpack:///./bower_components/jquery/dist/jquery.js?:3211:7
ready@webpack:///./bower_components/jquery/dist/jquery.js?:3417:3
completed@webpack:///./bower_components/jquery/dist/jquery.js?:3433:2
EventListener.handleEvent*jQuery.ready.promise@webpack:///./bower_components/jquery/dist/jquery.js?:3451:4
@webpack:///./bower_components/jquery/dist/jquery.js?:3461:1
@webpack:///./bower_components/jquery/dist/jquery.js?:26:4
@webpack:///./bower_components/jquery/dist/jquery.js?:15:2
@https://d2sl9eawlu179j.cloudfront.net/js/bundle-hub1.js?1493992046010:28:2
__webpack_require__@https://d2sl9eawlu179j.cloudfront.net/js/bundle-hub1.js?1493992046010:2:119
@webpack:///./bower_components/jquery/dist/jquery.js?./~/expose-loader?jQuery:1:83
@webpack:///./bower_components/jquery/dist/jquery.js?./~/expose-loader?jQuery:1:29
@https://d2sl9eawlu179j.cloudfront.net/js/bundle-hub1.js?1493992046010:22:2
__webpack_require__@https://d2sl9eawlu179j.cloudfront.net/js/bundle-hub1.js?1493992046010:2:119
@webpack:///./bower_components/jquery/dist/jquery.js?:1:78
@webpack:///./bower_components/jquery/dist/jquery.js?:1:29
@https://d2sl9eawlu179j.cloudfront.net/js/bundle-hub1.js?1493992046010:16:2
__webpack_require__@https://d2sl9eawlu179j.cloudfront.net/js/bundle-hub1.js?1493992046010:2:119
  angular.js:11706:18

**Comment by ErisDS** [comment] 2017-05-11 18:40
Hi @cotterjd - the api docs are managed by readme.io - I'm afraid we have no power to fix errors there, although I've emailed their support with this issue.

The wording of your issue sounds like you meant to include your edits but I didn't understand what it was you were trying to add where? Going to close this issue as it's not a bug in Ghost.

**Closed by ErisDS** 2017-05-11 18:40 UTC
