### ISSUE TITLE
/ghost/signup jumps to /ghost/signin

### ISSUE THREAD

**Issue by twtww** [TryGhost/Ghost#4949] opened 2015-02-25 05:30 UTC
After I successfully install the ghost stable and solve the admin blank page, I tried to test the signup page in a incognito Chrome page.
I found the url /ghost/signup jumps to /ghost/signin and that's all. I can't find how to get the signup page unless I send the invite link from my admin page.
Is that a issue?

**Comment by novaugust** [comment] 2015-02-25 06:01
Hi @twtww, you can't go to `/ghost/signup` without following exactly the link you received in your email invitation to sign up.  In other words, it only works if you go to `/ghost/signup/<a-valid-token>`; anything else gets redirected to `/ghost/signin`
I'm going to close this as not a bug, but feel free to keep commenting if I've misunderstood something :)

**Closed by novaugust** 2015-02-25 06:01 UTC

**Comment by twtww** [comment] 2015-02-25 06:30
Wow, I get it now. Thanks.
