### ISSUE TITLE
Installing ghost on Windows 10 using NPM v3 running on Node 4.3.2 causes a dependency error 

### ISSUE THREAD

**Issue by alanosman** [TryGhost/Ghost#6583] opened 2016-03-07 14:54 UTC
### Issue Summary

We recently upgraded to Node 4.3.2 on a project we are working on. We have a mixture of developers on Mac and Windows.  The Mac developers upgraded with no issues, but the Windows developers had issues installing Ghost using NPM.  

We tried a variety of commands that did not work:

npm install ghost
npm install ghost --no-optional
npm install ghost --no-bin-links

It would seem that NPM would always fail with the following:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm WARN Gonzah@0.0.1 No repository field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aosman\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "ghost"
npm ERR! node v4.3.2
npm ERR! npm  v3.8.1
npm ERR! path D:\elastc-app\node_modules\ghost
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'D:\elastc-app\node_modules\ghost' -> 'D:\elastc-app\node_modules\.ghost.DELETE'
npm ERR!     at moveAway (C:\Users\aosman\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Users\aosman\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'D:\elastc-app\node_modules\ghost' -> 'D:\elastc-app\node_modules\.ghost.DELETE'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'D:\elastc-app\node_modules\ghost' -> 'D:\elastc-app\node_modules\.ghost.DELETE'] parent: 'Gonzah' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\elastc-app\npm-debug.log
```

The workaround we came up with was to downgrade to NPM version 2, but my concern is that this is a short term fix.  We would like the windows developers to use the same tools as the Mac developers so I am reaching out to ask if someone here knows the proper solution to this problem?

### Technical details:

* Ghost Version: 0.7.8
* Node Version: 4.3.2
* Browser/OS: n/a
* Database: n/a

**Comment by kevinansfield** [comment] 2016-03-07 15:18
That doesn't appear to be a dependency issue (the `fsevents` incompatibility is just a warning) but instead a file permissions error when `npm` tries to rename the ghost module directory:

> npm ERR! Error: EPERM: operation not permitted, rename 'D:\elastc-app\node_modules\ghost' -> 'D:\elastc-app\node_modules\.ghost.DELETE'

To me this suggests that this behaviour is different between npm v2 and v3 which is why you're only seeing the problem on v3. I can't find any issues specifically about the folder rename problem on windows which suggests that it may be unique to your setup and file permissions.

Have you tried running `npm` with administrator privileges as the error message suggests?

> npm ERR! Please try running this command again as root/Administrator.

In any case this is not a bug in Ghost itself so I'll close this issue. We use Github for bug and feature dev tracking only but if you require any further help/support we have a [slack channel](https://ghost.org/slack/) that's better suited for installation issues.

**Closed by kevinansfield** 2016-03-07 15:18 UTC

**Comment by alanosman** [comment] 2016-03-07 15:59
Hi Kevin, thanks for the quick response.  Yes, I always run my console with admin privs. I tried with Powershell in Admin mode, checked folder privs (thought that didn't make much sense because it works with Npm v2).  In fact when its running, I do see the folder it creates node_modules.ghost.DELETE.  

We also tried it on another Windows machine and it has exactly the same issue. 

I will check out the channel.. thx.
