### ISSUE TITLE
Markdown Tables

### ISSUE THREAD

**Issue by balintant** [TryGhost/Ghost#4777] opened 2015-01-09 13:03 UTC
The compiler doesn't support generating tables with markdown syntax, but HTML. And HTML makes our articles hard to maintain.

It needs a bigger update, as all themes should have their own table syntax (eg. bootstrap classes) or must fit some CSS to our syntax, but it worth it. It's a commonly used feature.

# Example

    | Name            | Phone       |
    |-----------------|-------------|
    | Peter Russo     | +0123456789 |
    | Frank Underwood | +0123987654 |

| Name            | Phone       |
|-----------------|-------------|
| Peter Russo     | +0123456789 |
| Frank Underwood | +0123987654 |

# Related Links

- [Tables in GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/#tables)
- [Generate Markdown Tables](http://www.tablesgenerator.com/markdown_tables)

**Comment by balintant** [comment] 2015-01-09 13:09
@ErisDS just linked this issue (https://github.com/TryGhost/Ghost/issues/1670) on IRC when I opened the topic.

It says changes to the markdown editor will only come sometime before `v0.7` as it's hard to get done before the rebuilt editor, so the issue was closed.

**Comment by ErisDS** [comment] 2015-01-09 13:11
Hi @balintant as you have spotted this is a duplicate of #1670. If you'd like to contribute to the discussion there, please repost on that issue :+1:

**Closed by ErisDS** 2015-01-09 13:11 UTC

**Comment by Kerrick** [comment] 2018-06-13 20:32
@ErisDS #1670 is closed or else I would have posted this there, but... the links in your closing remarks are all broken. They say they go to a wishlist, but I just get redirected to the ghost.org homepage.

**Comment by kirrg001** [comment] 2018-06-13 20:38
@Kerrick If you would like to suggest an idea, you can use our [forum](https://forum.ghostorg).

**Comment by kevinansfield** [comment] 2018-06-14 08:17
@Kerrick Ghost has had markdown table support since Ghost 1.0

**Comment by johnbiundo** [comment] 2019-03-30 04:08
@kevinansfield Do you have a link to any docs?  This feature eludes the power of Google to find any documentation.

**Comment by kevinansfield** [comment] 2019-04-01 09:12
@johnbiundo

- https://markdown-it.github.io - scroll down for table examples
- https://help.github.com/en/articles/organizing-information-with-tables
- https://github.github.com/gfm/#tables-extension-

**Comment by johnbiundo** [comment] 2019-04-01 14:21
Thanks @kevinansfield.  So is the implication that Ghost supports full GFM?  I couldn't find anywhere that said so -- in fact, your comment is the only one that I've found that suggests that tables are supported in MD at all.  For example the built in help in the editor, and this page which it references, do not include it: https://docs.ghost.org/faq/using-the-editor/#using-markdown

Slightly off topic, and I know I can probably research this, but if any of the developers/maintainers want to comment: are the docs in a github repo and are community contributions to the docs welcome?  If so, I'd be glad to research the topic further and do a PR to add some info on tables.

**Comment by kevinansfield** [comment] 2019-04-01 15:50
> So is the implication that Ghost supports full GFM?

No. Ghost supports CommonMark plus some extensions such as tables and strikethrough.

We use https://github.com/markdown-it/markdown-it as the markdown parser with the default options plus `html`, `breaks` and `linkify` (without fuzzyLink) enabled.

As for extensions we have a few in order to keep a reasonable level of backwards compatibility with Ghost 0.x. Those are:

- https://github.com/markdown-it/markdown-it-footnote
- https://github.com/markdown-it/markdown-it-mark
- https://github.com/Galadirith/markdown-it-lazy-headers
- our own backwards-compatible `id` generation for headers that converts "Header Text" to an id of `headertext`

> are the docs in a github repo and are community contributions to the docs welcome?

The repo is here https://github.com/TryGhost/docs although some content is in a private Ghost instance rather than in github. PRs and/or issues suggesting changes are always welcome.
