### ISSUE TITLE
Saving failed. There was an error saving this post: OK 

### ISSUE THREAD

**Issue by iloabn** [TryGhost/Ghost#5229] opened 2015-05-06 20:39 UTC
### Issue Summary
While trying to save a post in the editor on a... suboptimal connection I frequently get this error while trying to save manually.

### Steps to Reproduce

1. Open up a draft
2. Edit the draft
3. Have shaky connection (hard to reproduce)
4. Save the draft
5. Notice the strange error message with the text "OK" in it

This is a bug because the error message "There was an error saving this post: OK" doesn't say anything noteworthy to the user except it didn't save. It is an error, because the text says so and the modal is red. But the error says "OK" which sounds like it's ok...

### Technical details

Using dev tools I can see that a call is made to `/api/v0.1/posts/[postNr]/?include=tags` with all the data about the post. However the reply body I'm getting is:
```
<B>ERROR : Method Not Implemented</B>

PUT
```
(with HTTP-status 200)

And as such a red modal on the bottom left is shown with this text:
```
Saving failed.
There was an error saving this post: OK 
```

Hypothesis:

1. My session ended and I was automatically logged out. However I read somewhere here that another modal where I then could log in should be visible to me at that moment.
2. Update error. I upgraded to 0.6.2. a couple of days ago and this is my first serious attempt at writing anything in it. Might be that I've made some strange mistake during the update
3. Network error. The network was very unreliable, could be something because of that. But if that was the case, the error message didn't lead me closer to that realization.

* Ghost Version: master - latest commit:  INSERT COMMIT REF
* Client OS: Windows 8.1
* Server OS: Azure
* Node Version: v0.10.29
* Browser: IE 11.0.18
* Database: sqlite3

Haven't managed to reproduce in Firefox, but I think that's because the internet is now reliable again (getting saved in both IE11 and Firefox at the moment).

I hope that I've supplied enough information for someone either to spot what I'm doing wrong or know of any information I've left out that is needed.

To everyone that might read this... You're awesome!

**Comment by ErisDS** [comment] 2015-10-09 15:58
Hi @iloabn I'm sorry this got ignored it slipped through my net! 
Did you manage to find a resolution? I have a feeling that unreliable network is the most likely cause unless you found issues with your upgrade? Either way this is likely to be an environment specific issue, and unless we can tie down the cause such that we can improve the error message to be clearer there isn't much to do here. Closing as this issue is ancient but will reopen if there is more info.

**Closed by ErisDS** 2015-10-09 15:58 UTC

**Comment by iloabn** [comment] 2015-10-17 16:30
Thanks for taking the time to respond @ErisDS !
I agree with you, it's most probably because unreliable network.

Thanks for the response!
