### ISSUE TITLE
Bug: Not updating slug after title has changed

### ISSUE THREAD

**Issue by gabrielcsapo** [TryGhost/Ghost#5289] opened 2015-05-19 14:33 UTC
### Issue Summary

When starting a new draft before publishing, the slug name is not changed when the title of the article has changed.

### Steps to Reproduce

1. Start a new draft
2. Add a title
3. Save the draft
4. Check the slug by pressing the cog wheel in the lower left hand corner and viewing the slug field.
5. Change the title in the document.
6. Save the draft.
7. Verify the slug has not changed.

This is a bug because if the title has changed before it has been published the slug should also be updated.

### Technical details

* Ghost Version: master - latest commit:  26548a734a3572b656eabd51e9a848a4cf83df21
* Client OS: OSX 10.10
* Server OS: Ubuntu 12.04
* Node Version: v0.12.3
* Browser: Safari [Version 8.0.6 (10600.6.3)]

**Comment by acburdine** [comment] 2015-05-19 14:47
This sounds like a duplicate of #5062 , and I'm pretty sure there's a PR in to fix this.

**Comment by gabrielcsapo** [comment] 2015-05-19 15:09
@acburdine Thank you, I was looking through the open issues and glossed over that issue because the language it used was off. I was going to fork and put a request in to fix this, but it seems like it is going to get resolved.

**Comment by ErisDS** [comment] 2015-05-19 15:55
Closing as a duplicate of #5062

**Closed by ErisDS** 2015-05-19 15:55 UTC

**Comment by dgonzalez** [comment] 2015-05-19 16:49
There is a pr but needs further discussion. Ill continue with it once I am
back to the real world (I am on hols)

**Comment by gabrielcsapo** [comment] 2015-05-21 16:42
@dgonzalez can you reference the PR? Maybe I could help.

**Comment by acburdine** [comment] 2015-05-21 16:49
#5216

**Comment by dgonzalez** [comment] 2015-05-22 08:05
https://github.com/TryGhost/Ghost/pull/5216

2015-05-21 17:43 GMT+01:00 Gabriel Csapo <notifications@github.com>:
