### ISSUE TITLE
Ghost generated Schema that has error.

### ISSUE THREAD

**Issue by Andrewyg** [TryGhost/Ghost#9773] opened 2018-08-09 13:01 UTC
### Issue Summary

So I found out an issue while Google is validating my AMP page, where after discussing with my theme developer ([Haunted Themes](https://www.hauntedthemes.com/)) it seems like the issue occurs at the schema generated by Ghost.

So take [my blog post](https://andrew.at.tw/im-not-fine/) as an example, testing schema with Google on the [AMP page](https://andrew.at.tw/im-not-fine/amp/) returned out [this report](https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fandrew.at.tw%2Fim-not-fine%2Famp%2F) which shows the following error:

`https://andrew.at.tw/content/images/2018/08/banner-1.png (The attribute logo.itemtype has an invalid value.)`

Which marks the error in the code:

![image](https://user-images.githubusercontent.com/20808546/43900089-643a8ac6-9c16-11e8-9ab6-537e97624c3d.png)

But it looks like the error doesn't occur at authors' logo.

So as we guess it may be the issue because of the image since it works on my theme developer's theme demo, we've scaled the image to 700x80px and 500x70px too, and also uploaded the SVG version. But the error still remains there.

By the way, the ghost version of the theme demo (which is working) is 1.23, with the [AMP page](https://poveglia.hauntedthemes.com/the-interpretation-of-reality/amp/) we've test and [the report](https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fpoveglia.hauntedthemes.com%2Fthe-interpretation-of-reality%2Famp%2F).

### To Reproduce

1. Installed ghost as 1.25.2 (though I'm not sure if version really matters, 1.25.3 has the issue too.)
2. Upload publication logo.
3. Test it with [Google Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool/)

### Technical details:

* Ghost Version: 1.25.2 (1.25.3 seems to have it too)
* Node Version: v8.11.3
* Browser/OS: Chrome 67.0.3396.99 (Official Build) (64-bit) (cohort: Stable)
* Database: Google Cloud SQL (remoted, second generation, MySQL)

**Comment by kevinansfield** [comment] 2018-08-09 13:07
Hey @Andrewyg 👋 This is a duplicate of https://github.com/TryGhost/Ghost/issues/7396 - please see that issue for more details 😄

**Closed by kevinansfield** 2018-08-09 13:07 UTC
