### ISSUE TITLE
there is a bug in server.model.user.format(), not calling super format

### ISSUE THREAD

**Issue by baogechen** [TryGhost/Ghost#5066] opened 2015-03-24 10:33 UTC
should be fixed as follow: 

    format: function (options) {
        if (!_.isEmpty(options.website) &&
            !validator.isURL(options.website, {
            require_protocol: true,
            protocols: ['http', 'https']})) {
            options.website = 'http://' + options.website;
        }
        return ghostBookshelf.Model.prototype.format.call(this, options);
    },

**Comment by letsjustfixit** [comment] 2015-03-24 11:15
create a pull request :)

**Comment by ErisDS** [comment] 2015-03-25 10:09
Hi @baogechen, can you please provide details of the bug so that we can verify what the issue is, and that your code change fixes it? We have a handy bug template over in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bug-reports), which provides handy tips on what sort of information to include when raising a bug (or a PR).

**Comment by baogechen** [comment] 2015-03-25 11:50
### Issue Summary

Fail to save profile while using a ralational db such as Mysql

### Steps to Reproduce

1. Use a new version of Mysql, Which will check dateTime format while saving

2 Change any info of your Profile in Ghost Setting and save

This is a bug because...
The server.model.User 's override function format() do not calling it's super, which is used for dateTime fixing.  So any change on User will simply fail.

### Technical details

* Ghost Version: master - latest commit:  INSERT COMMIT REF
* Client OS:  Mac OSX 10.10.2 (14C1510)
* Server OS:  Mac OSX 10.10.2 (14C1510)
* Node Version:  0.5.10
* Browser:  chrome
* Database: Mysql

**Comment by ErisDS** [comment] 2015-03-25 12:02
Ok, so you're talking about the same issue as #5050, which can also be fixed by editing the my.cnf file as mentioned on that issue.

The user format method change was released in 0.5.4, meaning this issue has been present since that version and yet we've only just had this raised twice in quick succession. I'm saying all this more as a point of interest rather than anything else.

**Comment by baogechen** [comment] 2015-03-25 12:23
I think you should fix this simple bug for sake of other non-tech guy.

**Comment by sebgie** [comment] 2015-03-31 09:20
This bug is an oversight :-(. Although only 2 ppl reported it, it is possible that a lot of installations have problems without knowing about it. Visibility depends on your OS and DB setup.

@baogechen would you like to send a PR with the fix proposed in the original description of the issue? If not I'll send your fix ;-).

**Comment by ErisDS** [comment] 2015-03-31 09:41
There is an open PR #5070 but the commit message format is incorrect - hence why the issue is not linked. I asked for it to be updated and as soon as that is done it can be merged :)

**Comment by sebgie** [comment] 2015-03-31 09:42
ty, didn't see that :+1:

**Comment by baogechen** [comment] 2015-03-31 12:08
Ii had tried to fix the commit message on that , but failed, shamefully. Should I post another one ?

**Comment by ErisDS** [comment] 2015-03-31 14:34
No need to open another one `git commit --amend` should do the trick :+1:

**Closed** 2015-04-03 19:26 UTC

**Comment by lifehome** [comment] 2015-04-11 06:57
Uhm, wondering if this could be patched to my current installation? cuz I'm experiencing the same issue right now, and might want to get it done instead of working with dev-ver.

**Comment by baogechen** [comment] 2015-04-11 08:22
@lifehome yes, of course.

**Comment by lifehome** [comment] 2015-04-11 09:41
@baogechen Screwed up with it... :neutral_face:  Should I just change that line, then reboot forever, or somewhat rebuild from grunt...?

**Comment by baogechen** [comment] 2015-04-11 10:47
just patch and restart node， that should be enough ：）

從我的 iPhone 傳送

**Comment by lifehome** [comment] 2015-04-11 10:48
@baogechen Got it working now! Thanks :smile_cat:
