### ISSUE TITLE
Post-card issue when updating Ghost from ghost_cli from 2.14.0 to 2.16.2

### ISSUE THREAD

**Issue by thangherodientu** [TryGhost/Ghost#10550] opened 2019-02-28 15:26 UTC
### Issue Summary

My Production host is Linux Ubuntu 18.04 and the local is MacOS latest version

The post-card is working fine at the home of casper, but the it lose the description in a post footer

### To Reproduce

1. Install ghost 2.14.0 with default casper theme
2. Write some articles
3: Update ghost to 2.16.2 (self host)
![screen shot 2019-02-28 at 10 21 30 pm](https://user-images.githubusercontent.com/38425724/53577196-cf990500-3ba7-11e9-9cbc-79ba55a93719.png)

### Technical details:

* Ghost Version: 2.14.0  to 2.16.2
* Node Version:
* Browser/OS: Chrome
* Database: Both production MySQl and Sqlite

**Comment by kirrg001** [comment] 2019-02-28 16:41
Duplicate of https://github.com/TryGhost/Ghost/issues/10546.
Will be released asap 👍

**Closed by kirrg001** 2019-02-28 16:41 UTC
