### ISSUE TITLE
Database migration fails at creating backup: Unknown column 'tags.visibility' in 'where clause'

### ISSUE THREAD

**Issue by eserozvataf** [TryGhost/Ghost#7326] opened 2016-09-06 07:04 UTC
### Issue Summary

```bash
$ FORCE_MIGRATION=true npm start

> ghost@0.10.0 start /srv/eser.ozvataf.com
> node index

WARNING: Ghost is attempting to use a direct method to send email.
It is recommended that you explicitly configure an email service.
Help and documentation can be found at http://support.ghost.org/mail.

Migrations: Creating database backup

ERROR: select count(distinct tags.id) as aggregate from `tags` where `tags`.`visibility` = 'public' - ER_BAD_FIELD_ERROR: Unknown column 'tags.visibility' in 'where clause'

 Error: ER_BAD_FIELD_ERROR: Unknown column 'tags.visibility' in 'where clause'
    at Query.Sequence._packetToError (/srv/eser.ozvataf.com/node_modules/mysql/lib/protocol/sequences/Sequence.js:30:14)
    at Query.ErrorPacket (/srv/eser.ozvataf.com/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
    at Protocol._parsePacket (/srv/eser.ozvataf.com/node_modules/mysql/lib/protocol/Protocol.js:202:24)
    at Parser.write (/srv/eser.ozvataf.com/node_modules/mysql/lib/protocol/Parser.js:62:12)
    at Protocol.write (/srv/eser.ozvataf.com/node_modules/mysql/lib/protocol/Protocol.js:37:16)
    at Socket.<anonymous> (/srv/eser.ozvataf.com/node_modules/mysql/lib/Connection.js:72:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
    --------------------
    at Protocol._enqueue (/srv/eser.ozvataf.com/node_modules/mysql/lib/protocol/Protocol.js:110:48)
    at Connection.query (/srv/eser.ozvataf.com/node_modules/mysql/lib/Connection.js:165:25)
    at /srv/eser.ozvataf.com/node_modules/knex/lib/dialects/mysql/index.js:124:18
    at Promise._execute (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/promise.js:77:14)
    at Client._query (/srv/eser.ozvataf.com/node_modules/knex/lib/dialects/mysql/index.js:118:12)
    at Client.query (/srv/eser.ozvataf.com/node_modules/knex/lib/client.js:187:24)
    at Runner.<anonymous> (/srv/eser.ozvataf.com/node_modules/knex/lib/runner.js:129:36)
    at Runner.tryCatcher (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/method.js:15:34)
    at /srv/eser.ozvataf.com/node_modules/knex/lib/runner.js:55:21
    at tryCatcher (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/util.js:16:23)
    at /srv/eser.ozvataf.com/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/promise.js:630:18)
    at PromiseArray._resolve (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/promise.js:566:26)
    at Promise._settlePromise0 (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/srv/eser.ozvataf.com/node_modules/bluebird/js/release/async.js:17:14)
```

### Steps to Reproduce

1. I was following the steps of official version upgrade document located at: http://support.ghost.org/how-to-upgrade/
2. It had failed on executing `npm start --production`

### Technical details:

* Ghost Version: 0.10.0
* Node Version: v6.5.0
* OS: Ubuntu 14.04.5 LTS
* Database: MariaDB 5.5.51-MariaDB-1~trusty ~~sqlite~~

**Comment by ErisDS** [comment] 2016-09-06 07:21
Hi @eserozvataf, sorry to hear you're having troubles upgrading. This issue is a duplicate of #7297. We are currently in the process of testing fixes before doing a bugfix release. I recommend downgrading until we release 0.10.1.

**Closed by ErisDS** 2016-09-06 07:21 UTC
