### ISSUE TITLE
Creation of #internal tags on story/post level doesn't set them as #internal

### ISSUE THREAD

**Issue by erikstern-r7** [TryGhost/Ghost#8979] opened 2017-09-06 10:59 UTC
### Issue Summary

In the past i had setup an #internal tag and it was excluded from the site no problem due to the visibility="public" by default. I recently added 2 more #internal tags to a few posts using the # to indicate that they were internal. They were set and the same format was defined like the one i did in the first place. But what happens when you go to /ghost/#/settings/tags, the extra blue label next to the tag name doesn't show up here like it does for the one created previously. Plus this tag now shows on the post level page like all other public tags.

My guess at what is going on here is that, you can't create #internal tags from the post/story page and have the system recognize them as #internal. Maybe this is by design, but the system allows you to try to...

I was able to modify the tag urls on the edit tags section by removing the "hash-" part and making it "#". This then created a new tag with a "-2" at the end of it. I proceeded to remove the "-2" part and save it, which then finally applied the blue #internal label, and then hiding it from the site like the other #internal tag.

I think that there is a bug in the process on a story edit page where #internal tags are not being set as #internal.  

### Steps to Reproduce

1. Edit a Story/Post.
2. Set a new tag with the internal "#" on it, click add new tag to make sure this gets set. 
3. Save the post
4. Got to /ghost/#/settings/tags to see that the tag was created
4.1. But you can see that it doesn't have the internal blue label next to them.
5. You can edit the tag as described above to remove/add the # again and save, which converts this tag to an internal tag.

I would check the service that is used to create and define tags and internal tags on the edit post page.

Other tricky thing was that this was not happening on my local build in dev mode, and only showed up on our production box. Not sure why as it is usually 1 for 1 with these types of things. 

### Technical details:

* Ghost Version: 1.7 (prod), 1.8.1 (local for testing)
* Browser/OS: Mac Safari

**Comment by ErisDS** [comment] 2017-09-06 11:02
Duplicate of #8943

Thanks for the report @erikstern-r7 - if you read the related issue, you'll find it was fixed recently, but the issue is still open pending one extra change.

**Closed by ErisDS** 2017-09-06 11:02 UTC
