### ISSUE TITLE
"¿" and "special/accented characters" in post-content h2 & h3 id# urls are showing enconded

### ISSUE THREAD

**Issue by testtest0121** [TryGhost/Ghost#14179] opened 2022-02-20 19:51 UTC
### Issue Summary

While the Post URL sanitizes any special characters and converts them to "A-Z","a-z","0-9" or removes them altogether for vanity purposes, the URLs containing "¿" and "special/accented characters" in **post-content** h2 & h3 id# URLs are enconded. While only "?" is properly removed from the generated URL.

You end up with pretty ugly URLs like id="%C2%BF%C3%A9-this-is-a-post"

Any ideas.

**Comment by matthanley** [comment] 2022-02-21 10:25
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/13876 - see [this comment](https://github.com/TryGhost/Ghost/issues/13876#issuecomment-1007563922) for more info.

**Closed by matthanley** 2022-02-21 10:25 UTC
Labels: needs triage
