### ISSUE TITLE
Cannot properly handles text "asp.net"

### ISSUE THREAD

**Issue by Magentaize** [TryGhost/Ghost#9023] opened 2017-09-19 07:41 UTC
### Issue Summary

Ghost cannot properly handles text "asp.net", the plain text becomes a hyperlink.

### Steps to Reproduce

Just write a new story with content "asp.net"

![20170919164042](https://user-images.githubusercontent.com/11793304/30580931-4b2b7868-9d59-11e7-94f4-3d114d118445.png)

**Comment by kevinansfield** [comment] 2017-09-19 08:12
Duplicate of #8987

**Closed by kevinansfield** 2017-09-19 08:12 UTC
