### ISSUE TITLE
User profile pages return 404

### ISSUE THREAD

**Issue by theDustRoom** [TryGhost/Ghost#8645] opened 2017-06-30 20:48 UTC
### Issue Summary

When viewing a blog post, clicking the author name/link should take you to the profile page with their blog posts.

This works for the administrator but not other users; these users get a 404.

### Steps to Reproduce

Create a ghost blog instance using Ghost-CLI.

Import data from previous blog with multiple users.

Users are imported and can be viewed in admin; clicking their links in the blog returns 404 page.

### Technical details:

* Ghost Version: 1.0.0 Beta 2
* Node Version: 6.11.0
* Browser/OS: N/A
* Database: sqlite3

**Comment by PaszaVonPomiot** [comment] 2017-07-03 09:58
I can replicate that on my installation. Apparently the reason for that is that when you import team members they are imported with status "locked". The problem is that you can't see that from admin panel as per #8652. The workaround is to suspend that user and unsuspend.

**Comment by theDustRoom** [comment] 2017-07-03 10:27
Ah cool; thanks @PaszaVonPomiot

**Comment by kirrg001** [comment] 2017-07-12 23:17
@theDustRoom Thanks for your report 👋

Closing as it is related to #8652.

> The workaround is to suspend that user and unsuspend.

If a user is locked on import, he get's a random password. So simply suspending, un-suspending won't resolve this completely, because the affected user can't login, but he can reset his password, but it's harder to guess for the user, because he would get an error message that his password is incorrect instead of showing "You account was locked, please reset your password".

**Comment by ErisDS** [comment] 2017-07-14 10:27
I think this needs to be reopened. I am not sure when this bug was introduced, however it means that content on a blog may 404 if a user accidentally locks themselves out of their account, as well as meaning that a blog is effectively missing content after an import until all the users have unlocked their accounts.

**Comment by kirrg001** [comment] 2017-07-14 10:58
@ErisDS Agree. I thought the behaviour for locked users is expected, i was wrong. We will fix this before releasing 1.0 officially 👍

**Closed** 2017-07-20 11:45 UTC
Labels: blocker/critical, bug, server
