### ISSUE TITLE
Bullet list followed by numbered list breaks editor

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#5040] opened 2015-03-16 09:33 UTC
I can't think of any reason why this would be invalid. Just like #5039 this breaks in editor as well as on the front-end.

![image](https://cloud.githubusercontent.com/assets/120485/6663528/28228fa8-cbd0-11e4-8d26-5182aac8bfdf.png)

**Comment by ErisDS** [comment] 2015-03-16 19:44
This one is an issue in showdown itself, not to do with or caused by any of our extensions (for once). 

According to [Babelmark](http://johnmacfarlane.net/babelmark2/?normalize=1&text=*+List+Item%0A*+Other+List+Item%0A%0A1.+New+list%0A2.+More+list+items) (a tool for comparing markdown conversions), this is how the original Markdown.pl tool worked, and is the output you get from both showdown and marked (the top 2 JS markdown convertors).

I agree it's quite bizarre, and I'm not sure why this works the way it does - as you can also see from the Babelmark output, the majority of markdown convertors have changed this to work the way you would expect. Therefore I'm going to raise it against showdown in a hope that we can get it resolved there.

**Comment by Tiagojdferreira** [comment] 2015-03-19 09:15
As a temporary fix use an invisible character between lists such as &#8203;

**Comment by ErisDS** [comment] 2015-04-02 19:52
Closing this as it is raised against showdown, which is the cause of the problem.

**Closed by ErisDS** 2015-04-02 19:52 UTC
Labels: bug, editor

**Comment by ConnorKrammer** [comment] 2015-09-13 22:10
Showdown has this fixed in their main repo [as of August](https://github.com/showdownjs/showdown/issues/142#issuecomment-126951117), so pulling those changes into showdown-ghost should fix this now.
