### ISSUE TITLE
Embedded JS is parsed as Markdown

### ISSUE THREAD

**Issue by kerberjg** [TryGhost/Ghost#8244] opened 2017-03-31 19:34 UTC
### Issue Summary

Post-embedded JS scripts are being recognized by the editor, but they're treaded as part of Markdown when the post is viewed on the blog. Example:

**Editor contents:**
```html
<script type="text/javascript">
    var getUrlParameter = function getUrlParameter(sParam) {
        var sPageURL = decodeURIComponent(window.location.search.substring(1)),
            sURLVariables = sPageURL.split('&'),
            sParameterName,
            i;

        for (i = 0; i < sURLVariables.length; i++) {
            sParameterName = sURLVariables[i].split('=');

            if (sParameterName[0] == sParam) {
                return sParameterName[1] == undefined ? true : sParameterName[1];
            }
        }
    };

...
```

**Resulting HTML on the post page:**
```html
<script type="text/javascript">  
    var getUrlParameter = function getUrlParameter(sParam) {
        var sPageURL = decodeURIComponent(window.location.search.substring(1)),
            sURLVariables = sPageURL.split('&'),
            sParameterName,
            i;

        for (i = 0; i < sURLVariables.length; i++) {
            sParameterName = sURLVariables[i].split('=');

            if (sParameterName[0] <mark> sParam) {
                return sParameterName[1] </mark> undefined ? true : sParameterName[1];
            }
        }
    };

...
```

As you can see, the `==` symbols are being parsed as `<mark>` tags. This results in broken scripts.

### Steps to Reproduce

1. Open the editor
2. Write an embedded JS script containing Markdown formatting characters
3. Preview/publish
4. View the post (and open the Inspector)

The parser should recognize embedded JS tags, not parsing them as MD.

### Technical details:

* Ghost Version: 0.11.7
* Node Version: 6.10
* Browser/OS: Safari, OSX
* Database: SQLite

EDIT: added details

**Comment by kirrg001** [comment] 2017-04-03 14:01
Hey @kerberjg Thanks for your report and sorry you are having trouble with your embedded javascript snippet.

I can confirm this behaviour. The regex to match highlighted markdown in our showdown dependency seems to have a bug. See https://github.com/ErisDS/showdown/blob/master/src/extensions/highlight.js#L16

**Comment by kirrg001** [comment] 2017-04-03 16:17
Similar issue to https://github.com/TryGhost/Ghost/issues/4627.

**Comment by ErisDS** [comment] 2017-04-03 17:51
I believe this is a duplicate of #5587

**Closed by ErisDS** 2017-04-03 17:51 UTC
Labels: showdown
