### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jaguart** [TryGhost/Ghost#11272] opened 2019-10-26 20:41 UTC
### Issue Summary

Since upgrade to 3.0.0 I see the following error regularly in the system logs:

    Oct 26 08:55:11 myhost node[625349]: [2019-10-26 07:55:11] #033[36mINFO#033[39m "GET /modules/ps_banner/img/29357807cb912883def1a6f58174cecc.jpg" #033[36m301#033[39m 2ms
    Oct 26 08:55:11 myhost node[625349]: [2019-10-26 07:55:11] #033[31mERROR#033[39m Cannot read property 'length' of undefined
    Oct 26 08:55:11 myhost node[625349]: #033[31m
    Oct 26 08:55:11 myhost node[625349]: #033[31mCannot read property 'length' of undefined#033[39m
    Oct 26 08:55:11 myhost node[625349]: #033[90m----------------------------------------#033[39m
    Oct 26 08:55:11 myhost node[625349]: #033[90mTypeError: Cannot read property 'length' of undefined
    Oct 26 08:55:11 myhost node[625349]:     at handleCount (/var/www/blog.mydomain/versions/3.0.0/core/frontend/helpers/has.js:21:29)
    Oct 26 08:55:11 myhost node[625349]:     at handleAuthor (/var/www/blog.mydomain/versions/3.0.0/core/frontend/helpers/has.js:71:16)
    Oct 26 08:55:11 myhost node[625349]:     at Object.author (/var/www/blog.mydomain/versions/3.0.0/core/frontend/helpers/has.js:128:24)
    Oct 26 08:55:11 myhost node[625349]:     at /var/www/blog.mydomain/versions/3.0.0/core/frontend/helpers/has.js:157:28
    Oct 26 08:55:11 myhost node[625349]:     at /var/www/blog.mydomain/versions/3.0.0/node_modules/lodash/lodash.js:4079:18
    Oct 26 08:55:11 myhost node[625349]:     at /var/www/blog.mydomain/versions/3.0.0/node_modules/lodash/lodash.js:4905:15
    Oct 26 08:55:11 myhost node[625349]:     at baseForOwn (/var/www/blog.mydomain/versions/3.0.0/node_modules/lodash/lodash.js:2990:24)
    Oct 26 08:55:11 myhost node[625349]:     at /var/www/blog.mydomain/versions/3.0.0/node_modules/lodash/lodash.js:4874:18
    Oct 26 08:55:11 myhost node[625349]:     at baseSome (/var/www/blog.mydomain/versions/3.0.0/node_modules/lodash/lodash.js:4078:7)
    Oct 26 08:55:11 myhost node[625349]:     at Function.some (/var/www/blog.mydomain/versions/3.0.0/node_modules/lodash/lodash.js:9897:14)
    Oct 26 08:55:11 myhost node[625349]:     at Object.has (/var/www/blog.mydomain/versions/3.0.0/core/frontend/helpers/has.js:156:16)
    Oct 26 08:55:11 myhost node[625349]:     at Object.eval [as main] (eval at createFunctionContext (/var/www/blog.mydomain/versions/3.0.0/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:257:23), <anonymous>:22:68)
    Oct 26 08:55:11 myhost node[625349]:     at main (/var/www/blog.mydomain/versions/3.0.0/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
    Oct 26 08:55:11 myhost node[625349]:     at ret (/var/www/blog.mydomain/versions/3.0.0/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
    Oct 26 08:55:11 myhost node[625349]:     at ret (/var/www/blog.mydomain/versions/3.0.0/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
    Oct 26 08:55:11 myhost node[625349]:     at Object.invokePartial (/var/www/blog.mydomain/versions/3.0.0/node_modules/handlebars/dist/cjs/handlebars/runtime.js:283:12)
    Oct 26 08:55:11 myhost node[625349]:     at Object.invokePartialWrapper [as invokePartial] (/var/www/blog.mydomain/versions/3.0.0/node_modules/handlebars/dist/cjs/handlebars/runtime.js:68:39)
    Oct 26 08:55:11 myhost node[625349]:     at eval (eval at createFunctionContext (/var/www/blog.mydomain/versions/3.0.0/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:257:23), <anonymous>:6:28)
    Oct 26 08:55:11 myhost node[625349]:     at prog (/var/www/blog.mydomain/versions/3.0.0/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    Oct 26 08:55:11 myhost node[625349]:     at execIteration (/var/www/blog.mydomain/versions/3.0.0/core/frontend/helpers/foreach.js:64:27)
    Oct 26 08:55:11 myhost node[625349]:     at _.each (/var/www/blog.mydomain/versions/3.0.0/core/frontend/helpers/foreach.js:83:17)
    Oct 26 08:55:11 myhost node[625349]:     at arrayEach (/var/www/blog.mydomain/versions/3.0.0/node_modules/lodash/lodash.js:516:11)#033[39m
    Oct 26 08:55:11 myhost node[625349]: #033[39m
    Oct 26 08:55:11 myhost node[625349]: [2019-10-26 07:55:11] #033[36mINFO#033[39m "GET /modules/ps_banner/img/29357807cb912883def1a6f58174cecc.jpg/" #033[33m404#033[39m 46ms

### To Reproduce

I consider this a bug because it fills system logs, obscuring other issues that need resolving.

### Technical details:

* Ghost Version: 3.0.0
* Node Version: 10.16.3
* Browser/OS: unknown - not logged
* Database: MariaDB 10.1.41 as MySQL 15.1

**Comment by allouis** [comment] 2019-10-28 06:37
This error being in the logs is definitely not a bug, but the error occurring might be! 

It seems to be originating from the `has` helper - which theme are you using? Maybe there is some incorrect usage of the helper in there or maybe there's a bug in the helper!

**Comment by kevinansfield** [comment] 2019-10-29 14:50
This was resolved in https://github.com/TryGhost/Ghost/commit/d78cbed84de992ac473f2d3cccbc9c0eddf997c2 and https://github.com/TryGhost/Casper/pull/639

**Closed by kevinansfield** 2019-10-29 14:50 UTC
Labels: needs info
