### ISSUE TITLE
Can't change themes when NODE_ENV=production

### ISSUE THREAD

**Issue by cesarvargas00** [TryGhost/Ghost#6357] opened 2016-01-18 04:30 UTC
Basically, whenever I start my express server with ghost as a npm module using NODE_ENV=production, I'm unable to change the theme. If I just run it in developer environment, I have the option on the dropdown menu to change the theme to my own theme.What am I doing wrong?

**Comment by ErisDS** [comment] 2016-01-18 12:02
Hi @cesarvargas00, sorry to hear you're having trouble. It's not clear from what you've written what the problem is here (is the UI missing, is it the theme update that's not working, etc) but it sounds very much like an environment issue rather than a bug with Ghost.

As mentioned in the readme & contrib guide, if you need help, please head on over to slack - https://ghost.org/slack/ - and post in the #help channel. There you can get help & support from the Ghost community, which we're not able to do here in the GitHub bug tracker.

If you think this is a reproducible bug, then please update your issue with enough information to make it clear what you're seeing. There is a [bug report template](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs) in our [contributing guidelines](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md) that should give you a good idea what sorts of info to include. 

Closing as a support request, will reopen if there's a bug.

**Closed by ErisDS** 2016-01-18 12:02 UTC
