### ISSUE TITLE
Redirecting `/` causes infinite loop

### ISSUE THREAD

**Issue by unitof** [TryGhost/Ghost#18778] opened 2023-10-26 20:36 UTC
### Issue Summary

Uploading a `redirects.yaml` containing

```
302:
  # temp landing page
  /: /welcome
```

causes site frontpage to redirect to an infinite loop of `/welcome/welcome/welcome/`etc.

### Steps to Reproduce

1. Create `redirects.yaml` containing:
```
302:
  # temp landing page
  /: /welcome
```
2. Upload to Redirects in `/ghost/#/settings` Labs.
3. Visit site root domain.

### Ghost Version

5.70.2+moya

### Node.js Version

Ghost(Pro) Stable

### How did you install Ghost?

Hosted on Ghost(Pro)

### Database type

MySQL 5.7

### Browser & OS version

Safari 17.1 on macOS 14.1

### Relevant log / error output

```shell
Browser error: too many redirects (eventually)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by unitof** [comment] 2023-10-26 20:37
Use case: we are trying to put up a temporary landing page (`/welcome/`) directing visitors to a Kickstarter before we launch and start regular posts.

**Comment by cathysarisky** [comment] 2023-11-03 19:51
Not a bug.  You need to start the left part with ^, to indicate that it's the start of the path.  That should fix you right up!

**Comment by unitof** [comment] 2023-11-06 05:43
Aha! Didn't know it was RegEx—will try. Thanks!

**Comment by daniellockyer** [comment] 2023-11-08 15:52
Thanks for the suggestion @cathysarisky! 🙂

We have some docs here that mention some use-cases: https://ghost.org/tutorials/implementing-redirects/. Given there's a workaround for the root page, I'm going to close this issue 🙂

**Closed by daniellockyer** 2023-11-08 15:52 UTC
Labels: needs:triage
