### ISSUE TITLE
Installation/runtime memory requirements?

### ISSUE THREAD

**Issue by ChrisRus** [TryGhost/Ghost#5849] opened 2015-09-18 18:09 UTC
I'm trying to set up Ghost from sources on a small 512MB Centos7 x64 droplet on DigitalOcean.

However, I cannot execute npm install because seemingly I run out of memory and Linux kills npn. I believe I've got a swapfile configured on this VPS.

Is this expected? Just what is the minimum configuration required to install/configure/run a baseline Ghost instance? 

```
Sep 18 14:02:43 ghost0 kernel: Out of memory: Kill process 3021 (npm) score 778 or sacrifice child
Sep 18 14:02:43 ghost0 kernel: Killed process 3021 (npm) total-vm:1532112kB, anon-rss:389168kB, file-rss:0kB
Sep 18 14:03:46 ghost0 su: (to root) cdr on pts/0
```

Thanks.

P.S. Quick update - turns out the swapfile wasn't correctly mounted on the VPS which explains the memory exception. Still curious about the answer to the original question however.

**Comment by sebgie** [comment] 2015-09-18 18:40
Closing as duplicate of #5107.

**Closed by sebgie** 2015-09-18 18:40 UTC

**Comment by ChrisRus** [comment] 2016-01-19 00:46
@sebgie would you please explain a bit further? I don't see how running out of memory on npm install related to #5107. Thanks.

**Comment by halfdan** [comment] 2016-01-19 08:01
@ChrisRus https://github.com/TryGhost/Ghost/issues/5107#issuecomment-140910614 and the following comment. DigitalOcean has a one-click install for Ghost which might be easier for you to set up.

Ghost, at this point, usually takes 80-90mb of memory when run.

**Comment by sebgie** [comment] 2016-01-21 12:06
@ChrisRus I referred to the problem @halfdan linked to. According to the DO forum this is common problem with npm (https://www.digitalocean.com/community/questions/npm-gets-killed-no-matter-what) and adding swap space should hopefully solve the problem. Glad you got it working :-).
