### ISSUE TITLE
Database error while migrating from 0.8.0 to 0.11.12

### ISSUE THREAD

**Issue by octave** [TryGhost/Ghost#9371] opened 2018-01-05 00:15 UTC
Hi guys,

I'm getting this error after upgrading from 0.8.0 to 0.11.12:

```
Unhandled rejection Error
  at Error.IncorrectUsage (/app/node_modules/ghost/core/server/errors/incorrect-usage.js:3:18)
  at Object.getStorage (/app/node_modules/ghost/core/server/storage/index.js:36:19)
  at setupMiddleware (/app/node_modules/ghost/core/server/middleware/index.js:131:44)
  at /app/node_modules/ghost/core/server/index.js:190:9
  at tryCatcher (/app/node_modules/ghost/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (/app/node_modules/ghost/node_modules/bluebird/js/release/promise.js:512:31)
  at Promise._settlePromise (/app/node_modules/ghost/node_modules/bluebird/js/release/promise.js:569:18)
  at Promise._settlePromise0 (/app/node_modules/ghost/node_modules/bluebird/js/release/promise.js:614:10)
  at Promise._settlePromises (/app/node_modules/ghost/node_modules/bluebird/js/release/promise.js:693:18)
  at Promise._fulfill (/app/node_modules/ghost/node_modules/bluebird/js/release/promise.js:638:18)
  at PromiseArray._resolve (/app/node_modules/ghost/node_modules/bluebird/js/release/promise_array.js:126:19)
  at PromiseArray._promiseFulfilled (/app/node_modules/ghost/node_modules/bluebird/js/release/promise_array.js:144:14)
  at Promise._settlePromise (/app/node_modules/ghost/node_modules/bluebird/js/release/promise.js:574:26)
  at Promise._settlePromises (/app/node_modules/ghost/node_modules/bluebird/js/release/promise.js:693:18)
  at Async._drainQueue (/app/node_modules/ghost/node_modules/bluebird/js/release/async.js:133:16)
  at Promise._settlePromise0 (/app/node_modules/ghost/node_modules/bluebird/js/release/promise.js:614:10)
  at Async._drainQueues (/app/node_modules/ghost/node_modules/bluebird/js/release/async.js:143:10)
  at Immediate.Async.drainQueues (/app/node_modules/ghost/node_modules/bluebird/js/release/async.js:17:14)
  at runCallback (timers.js:672:20)
  at tryOnImmediate (timers.js:645:5)
  at processImmediate [as _immediateCallback] (timers.js:617:5)
```

Did the database got corrupt?

Thank you!

**Comment by acburdine** [comment] 2018-01-05 01:55
@octave As seen in the stack trace, this is likely because you're using a custom storage adapter - and there were breaking changes introduced for storage adapters in Ghost 0.10 (see the 0.10.0 [release post](https://github.com/TryGhost/Ghost/releases/tag/0.10.0)). You will have to install an updated version of the storage adapter that works with the changes in Ghost 0.10, or swap it out for a different one.

At any rate, this is not a bug with Ghost, and therefore I'm going to close this issue 😄 . If you have further issues please drop by our [slack channel](https://slack.ghost.org) where you can get more help.

**Closed by acburdine** 2018-01-05 01:55 UTC
