### ISSUE TITLE
Unable to include embedded content.

### ISSUE THREAD

**Issue by SeanWrightSec** [TryGhost/Ghost#11673] opened 2020-03-18 18:00 UTC
### Issue Summary

Unable to include embedded content (such as bookmarks). 

### To Reproduce

1. In a post, attempt to include embedded content such as a bookmark.
2. Observer that an error is returned with the error message "There was an error when parsing the URL."
3. View the request and/or logs and the error message returned is something similar to the following in the error JSON: "message":"Validation error, cannot read oembed.","context":"No provider found for supplied URL. https://skillcrush.com/blog/remote-work-tools/","type":"ValidationError"

This has happened ever since I updated to version 3.11.0 of Ghost. This did not happen with previous versions (v3.6.0).

View the logs, I found the following stacktrace:

"stack": "ValidationError: No provider found for supplied URL.\n    at new ValidationError (/var/www/ghost/versions/3.11.0/node_modules/ghost-ignition/lib/errors/index.js:134:23)\n    at unknownProvider (/var/www/ghost/versions/3.11.0/core/server/api/canary/oembed.js:79:27)\n    at fetchBookmarkData.catch (/var/www/ghost/versions/3.11.0/core/server/api/canary/oembed.js:219:34)\n    at <anonymous>\n    at runMicrotasksCallback (internal/process/next_tick.js:122:5)\n    at _combinedTickCallback (internal/process/next_tick.js:132:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:219:9)"

### Technical details:

* Ghost Version: 3.11.0
* Node Version: 12.16.1
* Browser/OS: Brave 1.4.96
* Database: MySQL

**Comment by SeanWrightSec** [comment] 2020-03-18 20:28
I've tried to revert to an older version (change the sym link /var/www/ghost/current to an older version), and I still get the same error. I wonder if this might have to do with a change to Node.JS?

**Comment by kevinansfield** [comment] 2020-03-18 21:48
@SeanWrightSec unfortunately I'm not able to reproduce this.

I tested with the URL https://skillcrush.com/blog/remote-work-tools/ - embed worked for me but doesn't display very well due to the html that wordpress' oembed endpoint returns, bookmark worked fine though. Is that the exact url that you are using? Is it all urls or only some of them?

**Comment by SeanWrightSec** [comment] 2020-03-18 21:52
Yep, that's correct. It's in fact for any URL I try embed. It's even happening for YouTube videos. I tested it with ghost run and it works fine then. I don't know if there's any additional logging I can look at? I did try change the log level, but as far as I understand, ghost run is the way to debug?

**Comment by kevinansfield** [comment] 2020-03-18 21:52
> I wonder if this might have to do with a change to Node.JS?

@SeanWrightSec sorry I missed this. It could well be, which version of node.js are you on? You can find out which version ghost is using if you run `ghost doctor` inside your ghost site's directory on your server.

**Comment by SeanWrightSec** [comment] 2020-03-18 21:58
The versions which I have are:

* Ghost-CLI version: 1.13.1
* Ghost Version: 3.11.0
* Node Version: 12.16.1
* Database: MySQL
* OS: Ubuntu 18.04.4 LTS

I've tested it on 3 instances and both have the same issue. I'll in the meantime try to do a bit more digging.

**Comment by SeanWrightSec** [comment] 2020-03-18 22:02
Ok getting somewhere! If I run `/usr/bin/node /usr/bin/ghost run` it results in the error. But if I run `ghost run`, it works fine.

**Comment by kevinansfield** [comment] 2020-03-18 22:17
If you run `/usr/bin/node --version` what is the output?

**Comment by SeanWrightSec** [comment] 2020-03-18 22:20
Found the issue, so on Ubuntu apt installs node to `/usr/bin` but when you install the updated version (using npm to install) it installs it to `/usr/local/bin`. The versions are as follows:
* /usr/bin/node - v8.17.0
* /usr/local/bin/node - v12.16.1

I edited the .service file (in the directory `/var/www/ghost/system/files`) for my instance and changed the ExecStart command to have the `/usr/local/bin/node` instead. I reloaded the daemon (`sudo systemctl daemon-reload`) and restart ghost and it's now working.

Apologies for creating the unnecessary work trying to investigate this, but might find others who might run into the same issue so this might be helpful for them at least.

**Comment by kevinansfield** [comment] 2020-03-19 10:35
Thanks for the investigation @SeanWrightSec. The issue is certainly coming from node.js v8.x. In our server-side embed code we use `new URL()` without an explicit import, that fails in v8.x because it wasn't made a global until node.js v10.x.

I'm closing this issue because node.js 8.x is no longer supported. If anyone else finds this issue, please upgrade to the latest supported node version and double-check that your Ghost instance is using the version of node that you expect 🙂

**Closed by kevinansfield** 2020-03-19 10:35 UTC
Labels: needs info

**Comment by preslavrachev** [comment] 2021-09-09 13:23
> I edited the .service file (in the directory `/var/www/ghost/system/files`) for my instance and changed the ExecStart command to have the `/usr/local/bin/node` instead. I reloaded the daemon (`sudo systemctl daemon-reload`) and restart ghost and it's now working.

@SeanWrightSec thank you so much! This solution solved my embed issues as well. The funny thing was that I had Node v14.x set globally, and v12.x used by Ghost. According to @kevinansfield, this should not have been an issue after v10.x.

Anyway, I am glad that it worked. Hopefully, this helps others too.
