### ISSUE TITLE
Issues installing with ghost-cli (port already in use, db, sudo)

### ISSUE THREAD

**Issue by awbacker** [TryGhost/Ghost#9207] opened 2017-11-03 11:12 UTC
### Issue Summary

I've had 2 issues when installing ghost v1 via ghost cli, which are unrelated but since they are both setup stuff i'm including it here.  I was hoping to install them side-by-side and place one on a subdomain.  

### 1. Port already in use (existing instance is running)

When installing with a running instance of ghost (v0.11.x) the installer fails when it finds the port in use.  After failing it appears to only have a partially written configuration file, and it looks like it tries to connect to mysql by default.

During Install:
```bash
 /opt/ghost-v1/$ ghost install --db=sqlite3
  ✔ Finishing install process
  ? Enter your blog URL: https://theblog.io
  ✖ Configuring Ghost
  A ConfigError occurred.
  Error detected in the undefined configuration.
  Message: Port '2368' is in use.
  Configuration Key(s): server.port
  Current Value(s): 2368
  Help: Run `ghost config <key> <new value>` for each key to fix the issue.

/opt/ghost-v1/$ ghost config server.port 2369
/opt/ghost-v1/$ ghost run

  NAME: InternalServerError
  CODE: ECONNREFUSED
  MESSAGE: The server has encountered an error.
  level:normal
  InternalServerError: The server has encountered an error.
  ... lots of node stack traces ... 
  Error: connect ECONNREFUSED 127.0.0.1:3306
```

```
/opt/ghost-v1/$ cat config.production.json
{
  "server": {
    "port": 2369
  },
  "paths": {
    "contentPath": "/opt/ghost-v1/content"
  }
}
```

#### 2. Installing as non-root or non-sudo

I naively assumed it would be good to `su` to the ghost user when running ghost install, so everything was properly owned, like I did before and for other software. 

The installer could check for `sudo` or `root` level access before proceeding, and error out.  I don't know for sure if it really *needs* root, but I'd sure be happy with `chown -R ghost:ghost` on the install directory entirely. 

```bash
root@lo:/ $ npm install -g ghost-cli@latest
root@lo:/ $ add-user ghosty ..
root@lo:/ $ cd /opt/
root@lo:/ $ mkdir /opt/ghost-v1
root@lo:/ $ chown ghosty:ghosty /opt/ghost-v1
root@lo:/ $ su ghosty
ghosty@lo:/opt/ghost-v1/$ ghost install --db=sqlite3
✔ Checking system Node.js version
....
✔ Configuring Ghost
✔ Setting up instance
Running sudo command: chown -R ghost:ghost /opt/ghost-v1/content
? Password [hidden] 
An error occurred.
Message: 'Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#'  chown -R ghosty:ghosty /opt/ghost-v1/content
```

I'm off to try an install as root this time :-/

**Comment by vikaspotluri123** [comment] 2017-11-03 11:22
Regarding your issue w/ MySQL, it looks like it's because you didn't specify dbpath - the [docs](https://docs.ghost.org/docs/cli-install#section-options) say "If you want to specify Sqlite3 as command line argument, you have to specify both db and dbpath."

Regarding ports, I think this is something that's known, but Austin (the CLI lead) would be able to give more input regarding this. However, as a workaround (or the expected behaviour), use the [port passthrough](https://docs.ghost.org/docs/cli-config)

Combining the two things I said, your updated command would be something like `ghost install --db sqlite3 --dpbath ./content/data/ghost_production.db --port 2369`

**Comment by awbacker** [comment] 2017-11-03 11:38
@vikaspotluri123 The configuration files has only 2 lines, so it was not fully processed or written.  Its defaulting to mysql, fine under the circumstances (maybe a malformed config error would be better).

Also, should I move this to the cli repo (I didn't notice i was in ghost and not ghost-cli)

**Comment by kirrg001** [comment] 2017-11-03 13:07
> Also, should I move this to the cli repo (I didn't notice i was in ghost and not ghost-cli)

Yeah that would be great - thank you 👍 
Closing.

**Closed by kirrg001** 2017-11-03 13:07 UTC
Labels: cli-issue
