### ISSUE TITLE
Code injection Site Header does not work when setting "sodoSearch": { "url": false }

### ISSUE THREAD

**Issue by ZhelinCheng** [TryGhost/Ghost#16706] opened 2023-04-24 11:50 UTC
### Issue Summary

I have disabled the native search feature (sodoSearch) on my Ghost site by setting the "url" option to false. However, this causes the Code injection Site Header feature to stop working. The custom code that I have added to the Site Header is not injected into the <head> tag of the pages. This affects the styles and scripts that I want to apply to my site. Is this a bug or a conflict between sodoSearch and Code injection Site Header? How can I fix this?

### Steps to Reproduce

1. Set sodoSearch.url = false to reproduce the issue.

I expect the Code injection Site Header feature to work normally even when setting `"sodoSearch": { "url": false }`. The custom code that I have added to the Site Header should be injected into the <head> tag of the pages regardless of the sodoSearch settings. 

### Ghost Version

5.44.0

### Node.js Version

18.16.0 LTS

### How did you install Ghost?

Ubuntu 22.04

### Database type

MySQL 8

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment] 2023-06-15 13:46
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/16120

**Closed by daniellockyer** 2023-06-15 13:46 UTC
Labels: needs:triage

**Comment by ZhelinCheng** [comment] 2023-06-21 02:35
@daniellockyer I have installed the latest version, but the issue still persists.
