### ISSUE TITLE
"url" field is undefined when restricting returned fields via the API

### ISSUE THREAD

**Issue by Windyo** [TryGhost/Ghost#6625] opened 2016-03-22 14:43 UTC
### Issue Summary
When querying a posts list with the API, the "url" field returns "undefined" if the fields to be returned have been specified.

Interestingly, if one wants to construct a full list of post urls with no further information, a list of all fields except the url is returned.

### Steps to Reproduce

This first query returns a list of all posts with all their fields.
````
$.get(ghost.url.api('posts', {limit: "all"})).done(function(data) {
    var allposts = data.posts;
    console.log(allposts);
})
````

The following query, which should return exactly the same thing, returns all fields except "url" and "author".
 ````
$.get(ghost.url.api('posts', {limit: "all", fields: "id,uuid,title,slug,markdown,html,image,featured,page,status,language,meta_title,meta_description,created_at,created_by,updated_at,updated_by,published_at,published_by,author,url"})).done(function(data) {
    var allfields = data.posts;
    console.log(allfields);
})
````
The "author" can be added by using "include: "author", so this may be a feature and not a bug.
Using the syntax author_id also returns the expected result.

To test what happens if a list of URLs needs to be generated, the following query can be used :
````
$.get(ghost.url.api('posts', {limit: "all", fields: "url"})).done(function(data) {
    var urlquery = data.posts;
    console.log(urlquery);
})
````

### Technical details:

* Ghost Version: 0.7.8
* Node Version: 2.14.7
* Browser/OS: all tested.
* Database: sqlite3

**Comment by Windyo** [comment] 2016-04-12 15:27
Hi @jaswilli, thanks for taking a look at this! 

Seeing as you committed yesterday,  I take it that if I install the latest master I should be able to finish up testing and close the issue? 

Thanks

**Comment by jaswilli** [comment] 2016-04-12 16:07
Hi @Windyo,

The fix won't be in the master branch until #6657 gets merged.

**Comment by ErisDS** [comment] 2016-05-18 13:52
I'm reopening this as I've just spotted it is not fixed / has regressed.

E.g:

adding `?fields=url` to an API request seems to have no effect
adding `?fields=title,url` to an API request results in this (using blog.ghost.org as an example here):

```
{"posts":[{
  "title":"It's our birthday! Three years down, $600,000 annual revenue, and what's coming next",
  "url":"/undefined/"
}]...
```

**Comment by kirrg001** [comment] 2016-07-14 07:03
I am not able to reproduce this bug on current master. I've tested with postman and test-wise.
When i did it test-wise, i got `"url":"/undefined/"`, but this was a problem from test setup.

**Comment by kirrg001** [comment] 2016-07-14 10:28
Thanks @ErisDS , will try later again and then review #7089

**Closed** 2016-07-18 20:21 UTC
Labels: api, bug
