### ISSUE TITLE
Docker: connect ECONNREFUSED 127.0.0.1:3306 on docker.io/library/ghost:latest

### ISSUE THREAD

**Issue by Tuinslak** [TryGhost/Ghost#15326] opened 2022-08-27 05:07 UTC
### Issue Summary

I usually pull the latest ghost image (docker.io/library/ghost:latest)

Latest couple of images have the following error:

```
[2022-08-27 04:18:30] INFO Ghost is running in production...
[2022-08-27 04:18:30] INFO Your site is now available on https://shanwong.design/
[2022-08-27 04:18:30] INFO Ctrl+C to shut down
[2022-08-27 04:18:30] INFO Ghost server started in 0.799s
[2022-08-27 04:18:30] ERROR connect ECONNREFUSED 127.0.0.1:3306

connect ECONNREFUSED 127.0.0.1:3306

"Unknown database error"

Error ID:
    500

Error Code:
    ECONNREFUSED

----------------------------------------

Error: connect ECONNREFUSED 127.0.0.1:3306
    at /var/lib/ghost/versions/5.12.0/node_modules/knex-migrator/lib/database.js:57:19
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)

[2022-08-27 04:18:30] WARN Ghost is shutting down
[2022-08-27 04:18:30] WARN Ghost has shut down
[2022-08-27 04:18:30] WARN Your site is now offline
[2022-08-27 04:18:30] WARN Ghost was running for a few seconds
```

### Steps to Reproduce

1. Download latest Docker Ghost image
2. run with `docker run -d --restart always --name shan-ghost -v /srv/shan-ghost/blog:/var/lib/ghost/content -e url=https://shanwong.design -p 3001:2368 ghost`

Using version 5.8 does not have this problem, I can get it to work using `docker run -d --restart always --name shan-ghost -v /srv/shan-ghost/blog:/var/lib/ghost/content -e url=https://shanwong.design -p 3001:2368 ghost:5.8`

### Ghost Version

latest

### Node.js Version

latest (docker)

### How did you install Ghost?

Docker

### Database type

SQLite (I think)

### Browser & OS version

Linux OS

### Relevant log / error output

```shell
connect ECONNREFUSED 127.0.0.1:3306
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by BorisBrock** [comment] 2022-08-27 19:30
I can confirm this error. It occurs on my Synology NAS, too. Every image after 5.8 seems to be broken and produces the error mentioned above.

**Comment by ErisDS** [comment] 2022-08-27 20:18
This is a duplicate of https://github.com/TryGhost/Ghost/issues/15244. The repo for the docker image (maintained by Docker, not Ghost) is here: https://github.com/docker-library

**Closed by ErisDS** 2022-08-27 20:18 UTC
Labels: needs triage

**Comment by DennisYildirim** [comment] 2023-04-02 13:03
still having the same identical problem after 9 months, incredible work ghost developers. Does anyone have any ideas why this is happening ?
