### ISSUE TITLE
Accesing Ghost from AWS Ubuntu Server in production

### ISSUE THREAD

**Issue by muscaiu** [TryGhost/Ghost#7800] opened 2016-12-23 11:45 UTC
I'm trying to deploy my Ghost Blog on AWS Ubuntu Server. Here are the steps i made:
- git cloned myBlog
- cd myBlog , npm install --production
- npm start or npm start --production console sais site is running OK

 **If i try to acces it from my pc via http://x.x.x.x:2368 i get the site can't be reached**

- The port 2368 is open on AWS, i also did `sudo ufw disable`

**Versions:**
* Ghost Version: v0.11.3
* Node Version: v6.9.2
* Browser/OS: Amazon Ubuntu Server

**Config file**
```
var path = require('path'),
    config;

config = {
    production: {
        url: 'http://127.0.0.1:2368',
        mail: {},
        database: {
            client: 'sqlite3',
            connection: {
                filename: path.join(__dirname, '/content/data/ghost.db')
            },
            debug: false
        },

        server: {
            host: '127.0.0.1',
            port: '2368'
        }
    },
    development: {
        url: 'http://127.0.0.1:2368',
        database: {
            client: 'sqlite3',
            connection: {
                filename: path.join(__dirname, '/content/data/ghost-dev.db')
            },
            debug: false
        },
        server: {
            host: '127.0.0.1',
           port: '2368'
        },
        paths: {
            contentPath: path.join(__dirname, '/content/')
        }
    }
}
```

**Comment by kevinansfield** [comment] 2016-12-24 22:40
Hey @muscaiu, I think the problem is that your `host` field is set to `127.0.0.1` which will only listen on the local loopback interface rather than the public interface which is what's accessible via your server's IP address. If you change the `host` field to match your server's IP you may have more luck although it's not a recommended setup, it's much more preferable to have apache or nginx acting as a reverse proxy to your ghost instance.

I'm going to close this issue as we use github solely for bug tracking and feature development. If you require further installation help or configuration advice please come say hello on [our slack team](https://slack.ghost.org) where you can get help from the community as well as the Ghost devs 😄

**Closed by kevinansfield** 2016-12-24 22:40 UTC

**Comment by muscaiu** [comment] 2016-12-28 15:04
@kevinansfield hey i tried changing the server part from 127.0.0.1 to the external ip 54.171.95.112 , and now it won't start. Here is a picture to see all errors, maybe u have a clue?

This issue is also posted on [StackOverflow](http://stackoverflow.com/questions/41302860/accesing-ghost-aws-ubuntu-server-in-production)

![2016-12-28_16h58_3](https://cloud.githubusercontent.com/assets/11426309/21524528/67e8a7e2-cd1f-11e6-9c3f-f45d1393baff.png)
