### ISSUE TITLE
the spell-check of Koenig Editor is very not friendly to Chinese！

### ISSUE THREAD

**Issue by NameIsEward** [TryGhost/Ghost#9943] opened 2018-10-04 04:39 UTC
![test](https://user-images.githubusercontent.com/8791349/46453081-0f62e880-c7d2-11e8-8e4a-e9fd3f56f928.gif)

### description:
The first word of every sentence is invalid，and it's flash；

### Technical details:

* Ghost Version: 2.2.0
* Node Version:  8.12.0
* Browser:  chrome & ghost Desktop & firefox
* OS: macOS
* Database: mysql5.7

**Comment by kevinansfield** [comment] 2018-10-04 09:08
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/9801. The flickering spellcheck is a known issue in the upstream editor library and is tracked here https://github.com/bustle/mobiledoc-kit/issues/621

**Closed by kevinansfield** 2018-10-04 09:08 UTC

**Comment by NameIsEward** [comment] 2018-10-04 10:39
ok, thanks
