### ISSUE TITLE
Post image by URL

### ISSUE THREAD

**Issue by loskiq** [TryGhost/Ghost#8838] opened 2017-08-03 15:03 UTC
How to set post image by URL?

![image](https://user-images.githubusercontent.com/22175047/28928192-4a09be80-7875-11e7-838b-abc3054d633c.png)

### Technical details:

* Ghost Version: 1.4.0
* Node Version: 6.11.2
* Browser/OS: Google Chrome 60 / Windows 7
* Database: MySQL

**Comment by ErisDS** [comment] 2017-08-03 15:08
Duplicate of #8653, this feature was removed in 1.0 see #8032

**Closed by ErisDS** 2017-08-03 15:08 UTC
