### ISSUE TITLE
400 Request made from incorrect origin on login after upgrading to v2.2.1.

### ISSUE THREAD

**Issue by turekj** [TryGhost/Ghost#9972] opened 2018-10-09 20:07 UTC
### Issue Summary

Can't login to the ghost instance after upgrading to `v2.2.1` from `v2.2.0` using CLI. It can be reproduced in latest version of Chrome and Safari browsers with clearing cache with hard reload, too.

### To Reproduce

1. Head to https://jakubturek.com/admin.
2. Enter valid credentials.

I receive 400 `Request made from incorrect origin.` error page. Stacktrace:

```
[2018-10-09 15:54:18] ERROR "GET /ghost/api/v2/admin/users/me/?include=roles" 400 7ms

NAME: BadRequestError
MESSAGE: Request made from incorrect origin.

level: normal

empty
empty
ERROR DETAILS:
    empty

BadRequestError: Request made from incorrect origin.
    at new BadRequestError (/var/www/ghost/versions/2.2.1/node_modules/ghost-ignition/lib/errors/index.js:94:23)
    at cookieCsrfProtection (/var/www/ghost/versions/2.2.1/core/server/services/auth/session/middleware.js:108:21)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/route.js:137:13)
    at /var/www/ghost/versions/2.2.1/node_modules/express-session/index.js:489:7
    at SessionModel.findOne.then (/var/www/ghost/versions/2.2.1/core/server/services/auth/session/store.js:26:17)
    at tryCatcher (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)

[2018-10-09 15:54:18] ERROR "GET /ghost/api/v2/admin/settings/?type=blog%2Ctheme%2Cprivate" 400 10ms

NAME: BadRequestError
MESSAGE: Request made from incorrect origin.

level: normal

empty
empty
ERROR DETAILS:
    empty

BadRequestError: Request made from incorrect origin.
    at new BadRequestError (/var/www/ghost/versions/2.2.1/node_modules/ghost-ignition/lib/errors/index.js:94:23)
    at cookieCsrfProtection (/var/www/ghost/versions/2.2.1/core/server/services/auth/session/middleware.js:108:21)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/ghost/versions/2.2.1/node_modules/express/lib/router/route.js:137:13)
    at /var/www/ghost/versions/2.2.1/node_modules/express-session/index.js:489:7
    at SessionModel.findOne.then (/var/www/ghost/versions/2.2.1/core/server/services/auth/session/store.js:26:17)
    at tryCatcher (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/www/ghost/versions/2.2.1/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
```

### Technical details:

* Ghost Version: 2.2.1
* Node Version: v6.11.1
* Browser/OS: OS X Mojave, latest Chrome / latest Safari
* Database: MySQL

**Comment by kevinansfield** [comment] 2018-10-09 20:12
@turekj what URL are you trying to log in on and what is the configured url/adminUrl in your config file?

**Comment by turekj** [comment] 2018-10-09 20:17
From the config file:

```
{
  "url": "https://jakubturek.com",
}
```

I have no `adminUrl` specified in the config file. I am trying to log in via https://jakubturek.com/admin (redirected to https://jakubturek.com/ghost/#/signin)

**Comment by turekj** [comment] 2018-10-09 20:27
@kevinansfield I can confirm that rolling back to 2.2.0 by using `ghost update --rollback` solved the issue.

**Comment by olivierlambert** [comment] 2018-10-09 20:57
I'm experiencing the same issue on a fresh `v2.2.1` install here (behind a Nginx reverse). Trying `v2.2.0` now.

**Comment by olivierlambert** [comment] 2018-10-09 20:59
… and I confirm it works perfectly in `v2.2.0`!

**Comment by allouis** [comment] 2018-10-10 02:01
@turekj The new authentication for ghost checks that a request is made from the same origin as the session was initiated from. We determine the origin via the `Origin` header or the `Referrer` if that is missing. It's possible that cloudflare is messing with that. What's strange is that upon login, an error should occur if neither of those headers are present. So it seems that the value of the header is changing between the login request and the subsequent ones.

@olivierlambert I cannot replicate this when behind an nginx proxy - would you share your config with me?

**Comment by allouis** [comment] 2018-10-10 03:17
@turekj @olivierlambert It would be really useful if you can provide the `Origin` and `Referrer` headers from your browsers network console for both the 200 request to `/session/` and the 400's afterwards.

**Comment by allouis** [comment] 2018-10-10 06:00
@turekj @olivierlambert I was able to replicate this locally when using an nginx configuration that supported both `https:` and `http:` logging in on one protocol and accessing the admin on the other caused the issue. Does this match how either of your blogs are configured?

**Comment by olivierlambert** [comment] 2018-10-10 07:36
I have a very similar configuration and same results than @turekj

**Comment by allouis** [comment] 2018-10-10 07:46
@turekj @olivierlambert Thanks so much for your input - I believe the bug is caused by a misspelling of the "Referer" header in ghost - which I only noticed after reading through your comment! I've raised a PR for it now :relaxed:

**Comment by turekj** [comment] 2018-10-10 07:52
You guys rock! 12 hours passed since the report and there’s already a PR to fix the issue :heart: 

Will be happy to test the new release and see whether the issue is gone, but it sounds very reasonable. Once again, thank you, you’re doing an amazing job with Ghost!

**Comment by allouis** [comment] 2018-10-10 08:59
Thanks for the love! <3

I haven't merged that PR yet, because looking at the express source code, they handle misspellings of the Referer/Referrer header - which means it's unlikely to be the cause. I am still trying to replicate this locally though.

Would you be okay to help us debug this some more by adding some logs on your end?

Specifically in `<ghost-install>/current/core/server/services/auth/session/middleware.js`

On line 107

```diff,javascript
if (req.session.origin !== getOrigin(req)) {
+   const msg = `Expected ${req.session.origin}, got ${getOrigin(req)}`;
    return next(new common.errors.BadRequestError({
-       message: common.i18n.t('errors.middleware.auth.mismatchedOrigin')
+       message: common.i18n.t('errors.middleware.auth.mismatchedOrigin') + msg
    }));
}
```

Thanks so much for bearing with us :relaxed:

**Comment by turekj** [comment] 2018-10-10 09:33
@allouis The output is:

`Expected https://jakubturek.com, got null`.

I think that it's not terribly useful to you, so I've copy pasted bunch of `getOrigin(req)` method, too:

```
    if (req.session.origin !== getOrigin(req)) {
        const origin = req.get('origin');
        const referrer = req.get('referrer');
        const msg = `Expected ${req.session.origin}, got ${getOrigin(req)}`;
        return next(new common.errors.BadRequestError({
            message: common.i18n.t('errors.middleware.auth.mismatchedOrigin') + msg + ' origin: ' + origin + ' referrer: ' + referrer
        }));
    }
```

And it printed out: `origin: null referrer: https://jakubturek.com/ghost/`. Still not terribly useful

**Comment by turekj** [comment] 2018-10-10 09:35
But I think this might be the interesting part for you:

```
    if (req.session.origin !== getOrigin(req)) {
        const origin = req.get('origin');
        const referrer = req.get('referrer');
        const referrerOrg = new URL(req.get('referrer')).origin;
        const msg = `Expected ${req.session.origin}, got ${getOrigin(req)}`;
        return next(new common.errors.BadRequestError({
            message: common.i18n.t('errors.middleware.auth.mismatchedOrigin') + msg + ' origin: ' + origin + ' referrer: ' + referrer + ' origin x2: ' + referrerOrg
        }));
    }
```

The `referrerOrg` part I took from `getOrigin` method. Now I get server error 500 with: `URL is not a constructor` stack trace, which might explain why it's impossible to extract origin from the referrer only!

**Comment by turekj** [comment] 2018-10-10 09:40
This would mean that node v6 is the issue in here.

**Comment by olivierlambert** [comment] 2018-10-10 09:50
FYI I'm running `v6.14.3`

**Comment by allouis** [comment] 2018-10-10 10:34
@turekj Wow that's really useful! Thanks - i'll write a breaking test and get a patch out for this a$ap :+1:

**Closed** 2018-10-10 13:07 UTC
Labels: needs info

**Comment by allouis** [comment] 2018-10-10 13:09
@turekj Thank very much for the bug report and the debugging - couldn't have solved this without that!

@olivierlambert Thanks for helping out :+1: 

A fix for this has landed on master, I will release tomorrow morning as v2.2.2

:ghost:

**Comment by olivierlambert** [comment] 2018-10-10 20:06
Thanks!

**Comment by migolovanov** [comment] 2018-10-15 20:37
Expirienced same issue on 2.2.2, which was related to nginx configuration, so had to change it with additional headers. Not sure, if that is optimal solution, but at least working one:
```
...
    location / {
+       add_header 'Access-Control-Allow-Origin' 'https://www.hostname.com';
+       add_header 'Access-Control-Allow_Credentials' 'true';
+       add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
+       add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
+       add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
+
+       if ($request_method = 'OPTIONS') {
+           add_header 'Access-Control-Max-Age' 1728000;
+           add_header 'Content-Type' 'text/plain charset=UTF-8';
+           add_header 'Content-Length' 0;
+           return 204;
+       }

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:3000;
    }
...
```

**Comment by allouis** [comment] 2018-10-16 04:00
@migolovanov What issue were you seeing? Was nginx not forwarding the `Origin` or `Referer` headers?

**Comment by migolovanov** [comment] 2018-10-16 05:47
I saw 400 response code on login attempt with same message in logs: `BadRequestError: Request made from incorrect origin. Expected 'https://www.hostname.com' received ''.`
There was missing `Origin` header in requests sent from browser, so upstream hasn't received them either.

**Comment by allouis** [comment] 2018-10-16 08:02
@migolovanov Yeah the authentication needs either an `Origin` or `Referer` header to work. I'm interested as to why these CORS headers make it work for you though?

What browser are you using?
