### ISSUE TITLE
Certain code tag content breaks AMP output

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9716] opened 2018-07-04 12:36 UTC
### Issue Summary

Adding `'$example$'` to the markdown truncates the AMP output before the second `$` causing broken browser rendering through missing closing tags.

<img width="612" alt="screen shot 2018-07-04 at 13 33 07" src="https://user-images.githubusercontent.com/415/42277306-d645d6d8-7f8e-11e8-9052-57a4456bd0d2.png">

### To Reproduce

1. Create a new post and set the content to:
```
Testing

`'$example$'` asdf

123
```
2. Publish the post and open the AMP version on the blog front-end. Note the broken display and missing content after `'$example`.

The HTML output is clearly malformed. the trailing `$'` is removed and the rest of the helper output is added to the bottom of the post with the final section duplicated:

<img width="864" alt="screen shot 2018-07-04 at 14 07 19" src="https://user-images.githubusercontent.com/415/42279064-7733602e-7f94-11e8-9a66-f8d06ccfaac7.png">

This results in the browser injecting lots of extra `<code></code>` tags to try and deal with the malformed HTML.

Removing the [SafeString](https://github.com/TryGhost/Ghost/blob/master/core/server/apps/amp/lib/helpers/amp_content.js#L200) call so that handlebars outputs the raw string appears to show that there's a nested async helper issue:

```handlebars
<div class="kg-card-markdown">
  <p>Testing</p>
  <p>
    <code>'$example__aSyNcId_<_ZziCMbqm__#x27;</code>
    asdf
  </p>
  <p>123</p>
</div>
```

Narrowing the troublesome content down it appears to be caused by a trailing `$` or `$'` in any element. This can be demonstrated with simply putting `$` as the only markdown content in a post.

### Technical details:

* Ghost Version: 1.24.7
* Node Version: 8.10.0
* Browser/OS: n/a
* Database: SQLite

**Comment by lunaticmonk** [comment] 2018-08-20 17:26
Seems the problem is at https://github.com/TryGhost/Ghost/blob/c186347f0ca8d21136e804758e2ec4d719ec890b/core/server/apps/amp/lib/helpers/amp_content.js#L193 . `ampHTML` if logged, prints the code fine to the console. But when we pass it to the `sanitizeHtml` function, it breaks. Don't know if we missed something in options passed to the `sanitizeHtml`. Taking a look at this.

**Comment by jtwebman** [comment] 2018-08-21 21:30
My guess it is a markdown issue as even the non-amp page adds the end code block in the wrong place. I am taking a look at this as well.

**Comment by jtwebman** [comment] 2018-08-21 22:15
I was wrong it looks like the mobiledoc issue as this is what gets posted to the server: `"mobiledoc": {
  "version": "0.3.1",
  "atoms": [],
  "cards": [
    [
      "code",
      {
        "code": "`'$example$'` asdfg\n\n123"
      }
    ]
  ],
  "markups": [],
  "sections": [
    [
      10,
      0
    ],
    [
      1,
      "p",
      []
    ]
  ]
}` Notice code seems to be nested. Will keep digging deeper.

**Comment by jtwebman** [comment] 2018-08-21 22:46
Ok on the hunt farther down as this might be a handlebars issue as the output from everything in amp_content.js is `<p><code>'$example$'</code> asdf</p>
<p>123</p>` which looks correct.

**Comment by jtwebman** [comment] 2018-08-22 00:28
Opened an issue in express-hds to solve this issue: https://github.com/barc/express-hbs/issues/144

**Comment by jtwebman** [comment] 2018-08-22 00:43
Opened a PR. https://github.com/barc/express-hbs/pull/145 

Once it is merged we can open a PR to update the version in this repo.

**Comment by m1guelpf** [comment] 2018-12-02 23:32
The PR was merged! 🎉

**Comment by ErisDS** [comment] 2019-01-24 15:12
This bug is known and understood, it is expected to be fixed by the update to express-hbs, which has an open PR #10288. Currently waiting on a bug check/fix before merging.

**Comment by kevinansfield** [comment] 2019-03-27 17:14
Re-opening because we had to revert the express-hbs bump. See https://github.com/TryGhost/Ghost/issues/10643 for further details.

**Comment by gargol** [comment] 2019-06-25 20:53
@allouis as https://github.com/TryGhost/Ghost/pull/10750 landed in master this issue can be now closed?

**Closed** 2019-06-26 03:04 UTC
Labels: bug, server, themes
