### ISSUE TITLE
Ghost-cli warning on ubuntu 20.4

### ISSUE THREAD

**Issue by Abdullah-Bin-Hasan** [TryGhost/Ghost#12107] opened 2020-08-04 16:12 UTC
Ghost-cli warning on ubuntu 20.4 but ghost is working fine with node 12.

> System checks failed with message: 'Linux version is not Ubuntu 16 or 18'
Some features of Ghost-CLI may not work without additional configuration.
For local installs we recommend using `ghost install local` instead.

**Comment by acburdine** [comment] 2020-08-04 16:26
Closing as a duplicate of https://github.com/TryGhost/Ghost-CLI/issues/1265

**Closed by acburdine** 2020-08-04 16:26 UTC
