### ISSUE TITLE
Permalink structure from routes.yaml not shown in editor

### ISSUE THREAD

**Issue by ajpocus** [TryGhost/Ghost#12193] opened 2020-09-08 21:06 UTC
### Issue Summary

When I create a new blog on ghost.org, and change the routes.yaml permalink structure for blog posts, this structure is not reflected in the editor settings pane. For example, if the routes.yaml says the permalink is `/blog/{year}/{month}/{day}/{slug}` the editor settings pane will only show the original structure, `/{slug}`

### To Reproduce

1. Create a new Ghost blog (I used ghost.org hosting but it might work on self-hosted instances).
2. Save a new blog post with a title
3. Download the routes yaml file, in the "Labs" section of the site settings.
4. Change the downloaded routes.yml file so that the root collection's `permalink` property is `/{year}/{month}/{day}/{slug}/`
5. Rename `routes.yml` to `routes.yaml` before uploading or you'll get an error saying only yaml is supported (I'll file a separate bug report for this issue).
6. Upload the new `routes.yaml` file in Settings
7. Reopen the blog post. The url structure in routes.yaml is not reflected in the settings pane. 

In addition, if you delete the blog post and start a new one with the same title, it won't reflect the new structure as expected.

### Technical details:

* Ghost Version: ghost.org hosted, not sure
* Node Version: ghost.org hosted
* Browser/OS: macOS Catalina 10.15.6, Brave browser
* Database: ghost.org hosted

**Comment by ErisDS** [comment] 2020-09-09 11:49
This is a duplicate of https://github.com/TryGhost/Ghost/issues/12090

**Closed by ErisDS** 2020-09-09 11:49 UTC
