### ISSUE TITLE
can't nest code within a list using Markdown

### ISSUE THREAD

**Issue by DemoJameson** [TryGhost/Ghost#5647] opened 2015-08-10 17:29 UTC
1. item1
2. item2

    ```
    4 space, dindn't show a code block
    show some
    single line
    ```
3. item3

↓ preview in ghost ↓
![qq 20150811012621](https://cloud.githubusercontent.com/assets/181192/9178154/48dcc814-3fc8-11e5-9b81-96a9fd84d7d6.png)

**Comment by ErisDS** [comment] 2015-08-10 17:31
Hi @DemoJameson this is a known issue. Closing as a duplicate of #5632

**Closed by ErisDS** 2015-08-10 17:31 UTC
