### ISSUE TITLE
Enable modifying the date published with free form text

### ISSUE THREAD

**Issue by leolorenzoluis** [TryGhost/Ghost#10473] opened 2019-02-10 17:49 UTC
Please allow the date controls to be free form. It's hard to modify a date that is no longer in the current year. You have to go through the control's previous/next button in order to select those dates.

**Comment by kevinansfield** [comment] 2019-02-10 19:42
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/9256

**Closed by kevinansfield** 2019-02-10 19:42 UTC
