### ISSUE TITLE
backdrop-filter: blur on Chrome

### ISSUE THREAD

**Issue by carlokok** [TryGhost/Ghost#9854] opened 2018-09-06 05:26 UTC
### Issue Summary

backdrop-filter: blur() causing blur issues on Chrome with Experimental Web Platform enabled.

### To Reproduce

In chrome chrome://flags enable Enable Experimental Web Platform Features.
Visit a standard ghost blog page (for example ours:
https://blogs.remobjects.com/2018/08/30/the-delphi-vcl-comes-to-oxygene/
)
Note it looks blurred (example: 
![afbeelding](https://user-images.githubusercontent.com/238568/45136804-20eeab80-b1a6-11e8-9c9c-cc7882219589.png))

### Technical details:

* Ghost Version: 2.1.0
* Browser/OS: Chrome
* Database: SQLite

**Comment by kevinansfield** [comment] 2018-09-06 09:47
Closing as a duplicate of https://github.com/TryGhost/Casper/issues/340

**Closed by kevinansfield** 2018-09-06 09:47 UTC
