### ISSUE TITLE
image gallery broken when sodoSearch.url == false 

### ISSUE THREAD

**Issue by smoebody** [TryGhost/Ghost#16601] opened 2023-04-10 08:45 UTC
### Issue Summary

The display of the image gallery element is broken when viewing a post.
The edit-view is working.

### Steps to Reproduce

1. install vanilla ghost v5.42.2
2. create a post with the image gallery element and add some images
3. save and view the post

The images are not arranged as expected. Compare with latest working version 5.4.1

### Ghost Version

5.42.2

### Node.js Version

16

### How did you install Ghost?

docker image (tested alpine and default)

### Database type

SQLite3

### Browser & OS version

chromium 111.0.5563.146 and firefox 111.0.1 (64-bit)

### Relevant log / error output

```shell
on serverside I see this:

ERROR scriptUrl.includes is not a function

scriptUrl.includes is not a function

----------------------------------------

TypeError: scriptUrl.includes is not a function
    at getFrontendAppConfig (/var/lib/ghost/versions/5.42.0/core/frontend/utils/frontend-apps.js:7:19)
    at getMembersHelper (/var/lib/ghost/versions/5.42.0/core/frontend/helpers/ghost_head.js:51:25)
    at Object.ghost_head (/var/lib/ghost/versions/5.42.0/core/frontend/helpers/ghost_head.js:231:23)
    at async Object.returnAsync (/var/lib/ghost/versions/5.42.0/core/frontend/services/helpers/handlebars.js:16:30)
```
Nothing on clientside though.
```


### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by smoebody** [comment] 2023-04-10 08:59
I forgot to mention, that i disabled the sodoSearch and the portal.

**Comment by daniellockyer** [comment] 2023-04-10 11:29
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/16120

**Closed by daniellockyer** 2023-04-10 11:29 UTC
Labels: needs:triage
