### ISSUE TITLE
Bug: New posts are added to the bottom of the post list 

### ISSUE THREAD

**Issue by Trendy** [TryGhost/Ghost#4788] opened 2015-01-11 00:00 UTC
### Issue Summary
When you create a new post, the latest post appears at the bottom of the post list until refreshing, or leaving then revisiting the admin interface.

![new_post_issue](https://cloud.githubusercontent.com/assets/3655670/5693745/4eeff4b2-98fa-11e4-98e6-a08a4fea4f21.gif)

### Steps to Reproduce

1. Login to Ghost, note the order of the posts.
2. Create a new post, and publish it.
3. Return to the "Content" menu and note the new post appears at the bottom of the list.

This is a bug because the default ordering of the post list is reverse chronological order, thus the latest post should appear at the top of the list.

### Technical details

* Ghost Version: 0.5.7
* Client OS: Mac OS X 10.10.1
* Server OS: Mac OS X 10.10.1 & Ubuntu Linux 14.04
* Node Version: 0.10.30
* Browser: Chrome 39.0.2171.95 (64-bit)
* Database: SQLite

## Additional Information

I'm really new to Ember, so please feel free to call me on my ignorance, but I thought this was relevant. It seems that when the new post is added to the store (loosely assuming it has something to do with Ember Data), it is just stored as the last item until we do a completely new request to the server (refresh).

![screen shot 2015-01-10 at 8 08 49 pm](https://cloud.githubusercontent.com/assets/3655670/5693939/cc5f4cea-9904-11e4-9c1e-36fff21050b8.png)

**Comment by ErisDS** [comment] 2015-01-11 10:27
Hi @Trendy, thanks for this :)

I believe this is a result of the changes done in #4674, whereby the ID sorting is having unintentional sideeffects.

**Comment by ErisDS** [comment] 2015-01-11 12:42
Confirmed the bug is not there in 0.5.6, but I haven't yet tracked down a change between 0.5.6 and 0.5.7 that would cause this. Quite baffled.

**Comment by cobbspur** [comment] 2015-01-11 15:06
I've been testing this out. The bug does not seem to occur until [#4594](https://github.com/TryGhost/Ghost/pull/4594)

**Comment by ErisDS** [comment] 2015-01-11 15:30
So that *sort of* makes sense to me:

That change changes the way items in the content list are rendered from being what I assume is the proxied items  in the `ArrayController` that is the PostController:

`{{#each itemController="posts/post" itemView="post-item-view" itemTagName="li"}}`

To explicitly grabbing posts from the model: 

`{{#each post in model itemController="posts/post" itemView="post-item-view" itemTagName="li"}}`

But the documentation for Ember SortableMixin, which provides the ability to sort items in an ArrayController, says this:

> Ember.SortableMixin provides a standard interface for array proxies to specify a sort order and maintain this sorting when objects are added, removed, or updated without changing the implicit order of their underlying model array

So as I understand it, the model itself is not sorted. Ember adds the new post at the end, and it works when you refresh because then the items are provided from the server in the right order.

*(I'm typing this out because I'm trying to improve my understanding of the Ember internals and perhaps someone can point out mistakes in my understanding or terminology that will help me in future)*

I've done a bit of reading and it seems SortableMixin is supposed to be being deprecated, and I also believe Ember is moving away from using ObjectController and ArrayController where the model gets proxied, in order to reduce a little bit of the 'magic' and our dependence on the magic in Ghost is also what is causing #4766. 

I've read a couple of references to Ember.computed.sort, but I'm not sure how to apply it in this case. I *think* the right answer is to have a more explicit sorted version of the posts? Something like:

`{{#each sortedPosts}}` ?

**Comment by Trendy** [comment] 2015-01-11 15:41
While searching to see if this had been reported previous, I came across #2640, which we might want to consider here since it's going to deal with filtering and presumably sorting the posts list.

*Again, green to Ember, fair warning/apology.*

How could we go about filtering/sorting the model in the most reusable way?

**Comment by ErisDS** [comment] 2015-01-11 16:05
@Trendy You're spot on that this would be good to consider, although I've classified this as a blocker, meaning it needs to be fixed before we do another release - I cannot believe this hasn't been noticed before now it's awful :(

I am playing with `Ember.computed.sort` and I think it might be the right way to go in order to make resolving #2640 easier as well (although it would be good to get @LevelbossMike to confirm as he has the most experience with the filtering concept).

The original reason for requiring this [massive amount of ugly extra sorting code](https://github.com/TryGhost/Ghost/blob/master/core/client/controllers/posts.js#L40) was that the 'sortProperties' for SortableMixin all had to be in the same direction, and our post list is sorted with status:asc, and all the other properties as desc. This prevents us having to do a big union query to get drafts and published posts in the right order, but one day we'll need to do that anyway.

It seems that `Ember.computed.sort` takes a list of properties and directions, which at first look seems to mean we can remove the orderBy function completely and replace it with:

```
 sortProperties: ['status:asc', 'published_at:desc', 'updated_at:desc', 'id:desc'],
 sortedPosts: Ember.computed.sort('model', 'sortProperties'),
```

And change the template to `{{#each post in sortedPosts}}`

If it doesn't work we can replace sortProperties with our custom orderBy function again. Further when thinking about #2640, we can dynamically update sortProperties, or again use a custom function and it should be a logical extension to this change.

 I'm currently taking it for a spin to see if the order stays correct without needing all that code.

**Comment by jaswilli** [comment] 2015-01-11 16:07
> {{#each post in model itemController="posts/post" itemView="post-item-view" itemTagName="li"}}

Should probably be `{{#each post in controller ...}}`

**Comment by Trendy** [comment] 2015-01-11 16:11
@jaswilli Just made that change locally and it seems to have fixed it :+1:

**Comment by ErisDS** [comment] 2015-01-11 16:11
@jaswilli but isn't ArrayController and SortableMixin going away anyway?

**Comment by ErisDS** [comment] 2015-01-11 16:30
I've pushed e585c11 as my attempt to fix this, not sure if it's the right approach but we have swapping `model` for `controller` in the template as a fallback fix.

**Comment by jaswilli** [comment] 2015-01-11 16:35
@ErisDS Down the road, yeah. Basically, all Controllers are going away in favor of route-backed components.

If you want you could convert this to a bare controller and handle the model directly, along with whatever transformations are needed by way of CPs.  But ArrayController hasn't even been deprecated yet so it's not urgent.

**Comment by ErisDS** [comment] 2015-01-11 16:43
I'm still playing around just because I'm trying to get a better grasp of things. However, I've now bumped into this old chestnut: https://github.com/TryGhost/Ghost/issues/3008. I'm interested to find out what is the correct way to sort items and ensure the correct item is 'active' in the future vision of ember without object/array controllers.

Certainly not urgent though.

**Closed** 2015-01-11 17:01 UTC
Labels: blocker, bug
