### ISSUE TITLE
Cannot destructure property 'message' of 'message.error' as it is undefined.

### ISSUE THREAD

**Issue by gonzolively** [TryGhost/Ghost#13843] opened 2021-12-05 01:13 UTC
### Issue Summary

After a fresh install of ghost 4.25.1 on Ubuntu 20.04 I get the following error message:

"TypeError: Cannot destructure property 'message' of 'message.error' as it is undefined."

This does not seem to prevent Ghost from starting, though I spent quite a while thinking it did as it looks more severe than it is.

### Steps to Reproduce

1. Install ghost 4.25.1
2. run 'ghost start'

### Ghost Version

4.25.1

### Node.js Version

14.18.2

### How did you install Ghost?

Ubuntu 20.04

### Database type

MySQL 8

### Relevant log / error output

```shell
ghost-admin@host:/var/www/website$ ghost start
+ sudo systemctl is-active ghost_website-com
✔ Checking system Node.js version - found v14.18.2
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
+ sudo systemctl is-active ghost_dismantleyourself-com
✔ Validating config
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
✔ Checking memory availability
✔ Checking binary dependencies
✔ Checking systemd unit file
✔ Checking systemd node version - found v14.18.2
+ sudo systemctl start ghost_dismantleyourself-com
☴ Starting Ghost: dismantleyourself-com/usr/lib/node_modules/ghost-cli/lib/utils/port-polling.js:68
                    let {message: errMsg} = message.error;
                                  ^

TypeError: Cannot destructure property 'message' of 'message.error' as it is undefined.
    at Server.<anonymous> (/usr/lib/node_modules/ghost-cli/lib/utils/port-polling.js:68:35)
    at Object.onceWrapper (events.js:519:28)
    at Server.emit (events.js:400:28)
    at emitCloseNT (net.js:1677:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by nt-nguyencse** [comment] 2021-12-05 09:55
I got the same problem.

**Comment by LevTramana** [comment] 2021-12-05 10:14
Same issue

**Comment by Lucifer1590** [comment] 2021-12-06 06:52
yah there is some bug in 4.25.1 just downgrade as mentioned in #13840

**Comment by daniellockyer** [comment] 2021-12-06 08:10
Closing as duplicate of https://github.com/TryGhost/Ghost/issues/13837.

**Closed by daniellockyer** 2021-12-06 08:10 UTC
