### ISSUE TITLE
Autosave & Preview bugs

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#8604] opened 2017-06-19 17:31 UTC
Recently focus was moved to the content by default:

https://github.com/TryGhost/Ghost/issues/8525

Unfortunately, this means that the new -> edit transition is never triggered. This in turn means autosave is never triggered. This means your post is not saved unless you press the keyboard shortcut, as there is no save button.

Also (this should possibly be a separate bug, but the case may never happen if the first issue is fixed), if you try to get a preview link, it will always be `http://localhost:2368/ghost/` for unsaved posts. Which is very confusing.

**Comment by kirrg001** [comment] 2017-06-19 17:40
Isn't this a duplicate of #8501?

**Comment by ErisDS** [comment] 2017-06-19 18:01
No, this is a direct result of #8525, autosave is no longer working until you trigger it by pressing the keyboard shortcut.

**Comment by cobbspur** [comment] 2017-06-20 11:51
I think the best short-term solution here is to re-open #8525 and revert the changes.

**Comment by kirrg001** [comment] 2017-06-20 13:12
I can take a look at this issue tomorrow and if i am not able to find a proper fix, we can revert #8525 👍

**Comment by kirrg001** [comment] 2017-06-20 19:39
When should the transition from new to edit happen?

Reverting #8525 does in my opinion not really help, because i was able to skip the post title transition (on focus out) somehow and then i ended up in the same situation: i am editing the content, but i can only save the post with a shortcut - no autosave, no save button.

I would suggest to wait for the content input from the user (max one word?) and then transition after 3 seconds. Any other opinions?


> Also (this should possibly be a separate bug, but the case may never happen if the first issue is fixed), if you try to get a preview link, it will always be http://localhost:2368/ghost/ for unsaved posts. Which is very confusing.

Yeah this is a bug caused by the none working auto save behaviour.

**Comment by kirrg001** [comment] 2017-06-21 05:23
We will revert #8525 for now and figure this out post 1.0.

**Comment by kirrg001** [comment] 2017-06-21 05:38
I am going to close this bug issue now, because it was a direct result of #8525. The revert PR for #8525 was created, see https://github.com/TryGhost/Ghost-Admin/pull/755.

**Closed by kirrg001** 2017-06-21 05:38 UTC
Labels: admin-client, bug
