### ISSUE TITLE
Uploaded GIF files are converted to PNG by default

### ISSUE THREAD

**Issue by shawntoffel** [TryGhost/Ghost#9848] opened 2018-09-05 04:27 UTC
### Issue Summary

In release 2.1.0 GIF files are converted to PNG files by default, likely the result of https://github.com/TryGhost/Ghost/pull/9837. Is this desired? Previously I was able to upload GIF files using the "plus" in the editor, or by dragging the GIF into the browser. Now, after clicking publish the GIF maintains the .gif extension but does not play. After downloading the file I can see that it has been converted to a PNG. 

Upon adding the following configuration to my config file the ability to upload & publish GIFs is restored.

```
"imageOptimization": {
    "resize": false
 }
```

### To Reproduce

1. Create story on release 2.1.0 and upload a GIF.
2. See that the GIF is playing.
3. Click publish and view the post or refresh the editor. The GIF does not play.

Downloading and inspecting the file we can see it has been converted to a PNG even though it has kept the .gif extension. 

### Technical details:

* Ghost Version: 2.1.0
* Node Version: 8.11.4
* Browser/OS: Chrome/Windows

**Comment by kevinansfield** [comment] 2018-09-05 06:47
Confirmed. Not always apparent in the editor because Chrome sometimes doesn't switch from the `data:` URL used for preview to the final URL when the upload finishes but is definitely visible on the published page.

**Comment by kirrg001** [comment] 2018-09-06 09:45
@gargol I think we close this issue, because of https://github.com/TryGhost/Ghost/pull/9853#issuecomment-419021047

**Comment by gargol** [comment] 2018-09-06 13:13
@kirrg001 agreed :+1:

**Closed by gargol** 2018-09-06 13:13 UTC
Labels: bug, server
