### ISSUE TITLE
Images (with size) 404

### ISSUE THREAD

**Issue by stefanovazzocell** [TryGhost/Ghost#10306] opened 2018-12-31 00:16 UTC
### Issue Summary

After updating from 2.8.0 to 2.9.1, all the blog images were 404. I had to roll back.
Although the images were there, the image generation `/size/...` was not working for me.

### To Reproduce

1. Update from 2.8.0 to 2.9.1
2. (Maybe this was it) Fully restart the server
3. All the images on the blog should not give 404

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

Possibly the issue was caused due to a full system reboot soon after the update. But I didn't look at how the images are generated (if dynamically on request or on update... idk).
The setup looks something like `[Ghost -> Nginx] -> [Cloudflare] -> [User]`

### Technical details:

* Ghost Version: (2.8.0) 2.9.1
* Node Version: v6.16.0
* Browser/OS: Chrome 71.0.3578.98 on Windows 10
* Server OS: Ubuntu 16.04.5 LTS

**Comment by gargol** [comment] 2019-01-02 13:42
Hi @stefanovazzocell! I wasn't able to reproduce the bug you are describing locally and we didn't have any similar issues reported, so would need to get some more information to check if it's a bug :smiley: 

Would be good to know more about what kinds of images are returning 404 for you, ideally would be great to have a reproducible example. The images are being resized on the fly when a request comes in for an unexistent image, so they should've been populated automatically. 

Did you check the log output when 404's were served, maybe they could shed some light on the underlying issue?

**Comment by kirrg001** [comment] 2019-01-02 16:38
Are you using a custom storage adapter?

**Comment by stefanovazzocell** [comment] 2019-01-02 16:52
@kirrg001 No, I'm not.

(@)gargol, I'm going to check some logs now, I'll get back to you

**Comment by stefanovazzocell** [comment] 2019-01-02 16:55
Oh actually... my nginx config might be trying to redirect the request and access directly the file from the directory... I'll try to fix that, I'll get back on that.

... I really should check this things first...

**Comment by stefanovazzocell** [comment] 2019-01-02 17:09
Ok, I verified the issue. So sorry @gargol @kirrg001 for taking your time. It was quite 'unclever' on my side not to double check the nginx configuration.

Just in case somebody elses comes across this:

What to look for?
- All the custom images in the sites fail to show
- The images still show up on the admin `/ghost/` page
How to solve?
- Check nginx configuration for any custom rules for the `location /content/images`

My configuration included `alias /path/to/ghost/content/images/` which, looking back, was quite a bad practice.

This GitHub issue can be considered closed.

**Comment by gargol** [comment] 2019-01-02 17:26
No worries @stefanovazzocell :) Happy the problem is resolved! As for `.svg`, could be something that will be resolved with https://github.com/TryGhost/Ghost/pull/10315

**Closed by gargol** 2019-01-02 17:26 UTC
Labels: needs info

**Comment by cmnstmntmn** [comment] 2019-07-12 20:51
@stefanovazzocell how did you wrote this block in order to make it work with `/size` paths ? 

```
location ^~/content/images {
        alias /var/www/html/blockvera.com/content/images;
        access_log off;
        expires max;
        proxy_redirect off;
    }
```

**Comment by vikaspotluri123** [comment] 2019-07-13 15:26
@cmnstmntmn this forum post seems to be what you're looking for:

https://forum.ghost.org/t/ghost-blog-nginx-location-content/8049
