### ISSUE TITLE
Optimise performance of ghost-sdk.js in themes

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#9991] opened 2018-10-12 04:36 UTC
Currently we inject ghost-sdk.js into themes as follows:

```
<script src="/public/ghost-sdk.min.js?v=30b82fce68"></script>
<script>
ghost.init({
    clientId: "ghost-frontend",
    clientSecret: "f84a07a72b17"
});
</script>
```

and Google Pagespeed doesn't like it

![image](https://user-images.githubusercontent.com/120485/46848106-3775cb80-ce12-11e8-84ae-a4e0850c4641.png)

---

## Question 1:

Can we add `async` to the script? or, preferably:

## Question 2: 

Could we not just inline the whole thing? It's tiny anyway, and would actually be a reduction of 2 script tags to 1:

```
<script>
!function(){var o,i,n,e,r="https://demo.ghost.io/ghost/api/v0.1/";n={api:function(){var n,e=Array.prototype.slice.call(arguments),t=r;return(n=e.pop())&&"object"!=typeof n&&(e.push(n),n={}),(n=n||{}).client_id=o,n.client_secret=i,e.length&&e.forEach(function(n){t+=n.replace(/^\/|\/$/g,"")+"/"}),t+function(n){var e,t=[];if(!n)return"";for(e in n)n.hasOwnProperty(e)&&(n[e]||!1===n[e])&&t.push(e+"="+encodeURIComponent(n[e]));return t.length?"?"+t.join("&"):""}(n)}},e=function(n){o=n.clientId?n.clientId:"",i=n.clientSecret?n.clientSecret:"",r=n.url?n.url:r.match(/{\{api-url}}/)?"":r},"undefined"!=typeof window&&(window.ghost=window.ghost||{},window.ghost.url=n,window.ghost.init=e),"undefined"!=typeof module&&(module.exports={url:n,init:e})}();
ghost.init({
    clientId: "ghost-frontend",
    clientSecret: "f84a07a72b17"
});
</script>
```

## Question 3:

Could this also move to `</body>` instead of `</head>` ?

**Comment by kirrg001** [comment] 2018-10-12 11:01
This was initially raised [here](https://github.com/TryGhost/Ghost/issues/8918) and looks like a duplicate of [this issue](https://github.com/TryGhost/Ghost/issues/7299).

**Comment by kevinansfield** [comment] 2018-10-15 09:33
I've closed the other issue in favour of this one because we can't get rid of the script injection completely just yet.

> Can we add `async` to the script? or, preferably:

Unfortunately this would be a breaking change because it means there's no longer a guarantee for on-page scripts (in-post, code injection, theme header/footer) that the API is available/has been initialised when they run.

> Could we not just inline the whole thing?

This should be doable 🤔 It would keep behaviour the same for on-page scripts and remove the network call. I think it would need testing to see if PageSpeed still complains about it being a render-blocking script.

**Comment by ErisDS** [comment] 2019-01-02 17:18
Closing this as ghost-sdk.js is being deprecated with the old v0.1 api, and we've got a whole new approach in the v2 API.

**Closed by ErisDS** 2019-01-02 17:18 UTC
Labels: performance, server
