### ISSUE TITLE
Unable to install Ghost on D.O.

### ISSUE THREAD

**Issue by n-gon** [TryGhost/Ghost#9849] opened 2018-09-05 10:07 UTC
Hi! I'm completely new to this, I'm a writer, not a developer, and I've been happy to simply follow the instructions on [this page](https://docs.ghost.org/docs/install). However, for the last few days, I haven't been able to install Ghost on Digital Ocean with these instructions despite multiple attempts. I follow all of them to the T but when I type `ghost install` and hit enter, I get the following output:

`Checking system Node.js version`
`✔ Checking logged in user`
`✔ Checking current folder permissions`
`✔ Checking operating system compatibility`
`✔ Checking for a MySQL installation`
`✔ Checking memory availability`
`✖ Checking for latest Ghost version`
`A ProcessError occurred.`
` `
`Message: Command failed: yarn info ghost versions --json`
`{"type":"error","data":"An unexpected error occurred: \"EACCES: permission denied, scandir '/home/sero/.config/yarn/link'\"."}`
` `
`{"type":"info","data":"If you think this is a bug, please open a bug report with the information provided in \"/var/www/ghost/yarn-error.log\"."}`
`{"type":"info","data":"Visit https://yarnpkg.com/en/docs/cli/info for documentation about this command."}`
` `
`Exit code: 1`
` `
`Debug Information:`
`    OS: Ubuntu, v16.04`
`    Node Version: v8.11.4`
`    Ghost-CLI Version: 1.9.3`
`    Environment: production`
`    Command: 'ghost install'`

`Additional log info available in: /home/sero/.ghost/logs/ghost-cli-debug-2018-09-05T09_57_10_230Z.log`

`Try running ghost doctor to check your system for known issues.`

`Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.`

I'm trying to do this on a 1GB Digital Ocean VPS (Ubuntu 16.04), Node 8.11.4 and Ghost CLI 1.9.3.

**Comment by vikaspotluri123** [comment] 2018-09-05 13:15
Hey @n-gon the issue you're having seems like the same one that posted on the [forum](https://forum.ghost.org/t/an-unexpected-error-occurred-eacces-permission-denied/2834) which was linked in the issue template


refs / duplicate of tryghost/ghost-cli#675

**Comment by kevinansfield** [comment] 2018-09-05 13:52
@n-gon Please keep support questions on the forum, thank you! 😄

**Closed by kevinansfield** 2018-09-05 13:52 UTC

**Comment by n-gon** [comment] 2018-09-06 02:57
Thanks @vikaspotluri123 and sorry about that @kevinansfield :)
