### ISSUE TITLE
The 'get' helper for posts is limited to current author if inside 'post'

### ISSUE THREAD

**Issue by tsvetant** [TryGhost/Ghost#8751] opened 2017-07-25 07:55 UTC
### Steps to Reproduce

1. Create several authors (ex. 2)
2. Have 1-2 posts with each
3. Create a post.hbs with a posts get inside 
```
{{!< default}}
{{#post}}
   {{#get "posts" filter="id:<{{id}}" limit=5 include="author" as |more_posts|}}
    ...postdata
   {{/get}}
{{/post}}
```
4. Reach the post where the next post is from another author

there are no next posts if the author is not the same

* Ghost Version: 1.0.0
* Node Version: v6.11.1
* Browser/OS: win 10 x64
* Database: sqlite

**Comment by ErisDS** [comment] 2017-07-25 12:51
Hi @tsvetant I am not able to reproduce this issue I'm afraid. Given how the get helper works, I also can't imagine how this ever could happen. 

Maybe swing by the #themes channel in [slack](https://ghost.org/slack) and post more of your code and we can debug it. 

I'm fairly confident there is no Ghost bug here, so closing.

**Closed by ErisDS** 2017-07-25 12:51 UTC
Labels: themes
