### ISSUE TITLE
Bug: `grunt dev` requires running twice

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5322] opened 2015-05-24 17:52 UTC
Something weird is happening with `grunt dev`, whereby running it once doesn't seem to work. Nothing changes, or at least the changes aren't picked up.

Running `grunt dev` again makes everything work as expected.

The first few times this happens, you think you're just losing it, but no.. it's really happening.

I think @halfdan was looking into this, not sure where that got to but he said:

> grunt clean seems to kill core/client/dist/assets and grunt init seems to fail to create it again

**Comment by ErisDS** [comment] 2015-06-01 21:26
Something really weird is going on here and I can't figure it out - anyone got any ideas?

**Comment by jaswilli** [comment] 2015-06-01 22:48
Part of the problem (perhaps all, but definitely part) is that `ember build` is being run in the background asynchronously, which means that the express server instance gets fired up before the client assets have been (re)built.  In theory the file system watch should notice the change when the assets are built and put into place and restart express, but that's not consistently happening (at least for me).

**Comment by acburdine** [comment] 2015-06-09 03:22
@ErisDS @jaswilli I'm not sure how to reproduce this in my copy, and since the ember-cli update was merged is this still occurring?

**Closed** 2015-06-23 08:08 UTC
Labels: blocker, bug, ember
