### ISSUE TITLE
Ghost v3.0.2 crashes Safari v13.0.3 on saving HTML element

### ISSUE THREAD

**Issue by digitall-it** [TryGhost/Ghost#11348] opened 2019-11-06 19:45 UTC
### Issue Summary

Ghost v3.0.2 crashes Safari v13.0.3 on saving HTML element, after update from Ghost v2.x. 

### To Reproduce

1. Create/modify a post
2. Add an HTML code element
3. Safari should crash, Google Chrome on OSX shouldn't

I consider it a bug in the Safari browser (a site shouldn't be able to crash a browser). However, as Ghost v3 triggers the problem, and the same content on v2 didn't issue the problem, it maybe be resolved somehow. 

### Technical details:

* Ghost Version: 3.0.2
* Node Version: 10.17.0
* Browser/OS: OSX Safari 13.0.3
* Database: SQLite

**Comment by digitall-it** [comment] 2019-11-06 19:45
I would like to also thank the Ghost developers for creating such a wonderful piece of software.

**Comment by kevinansfield** [comment] 2019-11-07 02:44
It sounds like this may be a duplicate of https://github.com/TryGhost/Ghost/issues/11162

Safari 13.0.2 (15608.2.30.1.1) doesn't have any problems, however earlier versions of 13.0.2 and 13.0.1 were crashing. It would appear that Safari may have re-introduced a bug 😕

**Comment by gargol** [comment] 2019-11-13 02:29
@digitall-it please feel free to reopen if this issue still persists and you think it's not a duplicate ;)

**Closed by gargol** 2019-11-13 02:29 UTC

**Comment by radionoise** [comment] 2019-11-22 06:53
The issue still persists. It just hangs whenever I try to edit a post.
- macOS Mojave 10.14.6
- Safari 13.0.3 (14608.3.10.10.1)
- ghost 3.0.3
