### ISSUE TITLE
routes.yaml file erroneously downloaded as routes.yml

### ISSUE THREAD

**Issue by ajpocus** [TryGhost/Ghost#12194] opened 2020-09-08 21:11 UTC
### Issue Summary

If you download `routes.yml`, you can't reupload it as-is -- you have to rename it to `routes.yaml` first.

### To Reproduce

1. Download `routes.yml` from the Labs section of the site settings.
2. Try reuploading it (I did it with a change to the permalink structure). It should give you an error message, that says "only yaml is supported", which is erroneous because it's the same file.

To work around this, rename the file to `routes.yaml` (instead of `.yml`, in case you're playing "spot the difference" ;))

### Technical details:

* Ghost Version: ghost.org hosted, not sure
* Node Version: ghost.org hosted
* Browser/OS: macOS Catalina 10.15.6, Brave browser "Version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)"
* Database: ghost.org hosted

**Comment by ErisDS** [comment] 2020-09-09 11:19
This is a duplicate of https://github.com/TryGhost/Ghost/issues/12090

**Comment by ErisDS** [comment] 2020-09-09 11:49
Closed wrong issue

**Closed by ErisDS** 2020-09-09 11:49 UTC

**Comment by dtgay** [comment] 2022-05-25 22:33
@ErisDS As far as I can tell, this issue is not resolved. I just downloaded the routes file in Ghost 5.0.1 and got it as `routes.yml`. I went to go submit a patch myself, but I'm not a node guy and a `grep` didn't reveal an obvious incorrect file name.

Can this be re-opened, or shall I open a new issue?

**Comment by kevinansfield** [comment] 2022-05-26 08:22
@dtgay we provide the file with the right `.yaml` extension but some OS's will rename it themselves when saving
