### ISSUE TITLE
Previewing a post that has been unpublished results in a 404

### ISSUE THREAD

**Issue by stromfeldt** [TryGhost/Ghost#12356] opened 2020-11-11 04:57 UTC
### Issue Summary

I have a published post that I decided to unpublish – "Revert this post to a private draft" – so that I could work on it again before re-publishing it. I tried to preview the newly created draft after having made some changes, but the resulting preview ended up giving me a 404.

### To Reproduce

1. Publish a post
2. Unpublish the post
3. Hover over the Preview button, which will show that the URL is in fact `https://yourblog.com/p/{id}/`.
4. Click the Preview button to see the draft
5. The new tab will initially have the URL `https://yourblog.com/p/{id}/`, but which will then re-direct to the URL of the previously published post – `https://yourblog.com/title-of-the-post/` – and thus result in a 404.

### Technical details:

* Ghost Version: 3.37.1
* Browser/OS: Firefox 82.0.3
* Database: mysql

**Comment by matthanley** [comment] 2020-11-11 15:07
Hey @stromfeldt 👋 
I've tried to reproduce this issue but have been unsuccessful. Could you test and confirm the steps again? Please also let us know how you installed Ghost, and how you're hosting it (whether behind a CDN etc).

I'll close for now as not able to reproduce, but happy to reopen once we have a reproducible case.

**Comment by yaroslavvb** [comment] 2021-08-05 10:04
I'm running into the same issue. One thing I noticed is that the preview link "https://machine-learning-etc.ghost.io/p/90934736-31e4-4b29-9ffd-cafa43c814a4/" automatically redirects to "published post" link "https://machine-learning-etc.ghost.io/average-value-of-quadratic-form-on-a-circle/" which is 404 since post is no longer published.

So perhaps an issue is that "automatic redirect" should be turned off

Ghost version: (whatever is currently on Ghost Pro)

**Comment by matthanley** [comment] 2021-08-06 15:23
I've managed to repro this:

1. Preview an unpublished post
2. Publish the post
3. Access the old preview URL -> redirects to the published URL
4. Unpublish the post
5. Try and view the preview - the redirect is cached and now redirects to a 404

**Comment by ErisDS** [comment] 2021-08-24 08:29
I think this is a wontfix 🙂 

When a post is published, the `/p/[uuid]` url is 301 redirected to the new correct URL to prevent duplicate content issues. 301 redirects have heavy cache headers on them because they are permanent. This behaviour is as intended and required to prevent SEO issues.

Unpublishing a post is not a common use case, but in the case that you do unpublish, you'd need to clear your browser and any other caches to ensure that you don't get the cached 301 response.

We could regenerate UUIDs but that would only partially solve the problem, whilst creating others e.g. if. your old link is cached it will still redirect, and if it isn't cached it won't work at all.

I understand this was a frustrating issue to experience, however as this feature has existed for the majority of Ghost's lifetime and this is the first report of this issue, I will close this as a wontfix until such time as it becomes a more widespread issue.

**Closed by ErisDS** 2021-08-24 08:29 UTC

**Comment by underthehoodlearning** [comment] 2021-10-10 00:02
I'm unable to preview a draft post that has not been published before. Does any one know of a solution?

**Comment by Razzile** [comment] 2022-07-16 22:25
I am experiencing this on my blog. Were any solutions to this problem found?

**Comment by ErisDS** [comment] 2022-07-26 14:54
I am going to lock this for comments, as the last comment I wrote details what has happened, why and what the solution is.
