### ISSUE TITLE
url renaming in create post context

### ISSUE THREAD

**Issue by sakulstra** [TryGhost/Ghost#6869] opened 2016-05-20 10:46 UTC
### Issue Summary

When using slashes in the url, like "/en/home" ghost silently accepts the inserted url.
As soon as pressing save the url gets deslahified to "en-home" without any notification.

What should happen instead?
1. Allow "/" in url or
2. Somehow notify the user about url changes and validate the url field while typing 
## Reproduction

Create a post.
Open "post settings" and change the url manually to something containing a "/".
Close the "post settings" and save.
### Technical details:

Ghost Version: Ghost 0.8
Node Version: 4.x
Browser/OS: chrome/ firefox
Database: default

**Comment by ErisDS** [comment] 2016-05-20 10:58
Hi @sakulstra! When reporting bugs, it would be super helpful if you could follow the format laid out in the issue template. This makes it much much easier for us to pick up and replicate your issue 👍 

What should happen here, is the slug should be replaced with a valid one as soon as the field loses focus (although there can be a delay if the network is slow). 

I can see in some cases (it seems to be a second updated), the slug isn't being replaced at all, so it appears there's an issue with ember updating to reflect the value.

**Comment by sakulstra** [comment] 2016-05-20 11:14
@ErisDS sry, i edited my issue now.
I have to admit that I just didn't see the replacement on focus leave because I closed the settings after entering the url. So the replacement happened after/while the post settings got out of view. 
It could be handled better, but it's already handled. After knowing this, i'm not sure if it was worth reporting. Feel free to close this as it doesn't seem important.

**Comment by ErisDS** [comment] 2016-05-23 08:55
I think there is a bug in that it isn't updated on a 2nd change.. it seems like it gets stuck to me:

Repo:

- go to PSM, add a slug which contains a slash
- focus out, and watch the slug get updated, `/` becomes `-`
- click back in, change `-` back to `/` again...
- focus out, click out, hit save, reopen PSM = the slug hasn't updated

**Comment by dbalders** [comment] 2016-08-03 22:27
I couldn't reproduce this on current master. All `/` are always reverted back to `-`.

**Comment by Jabark** [comment] 2016-12-21 16:59
I think the OP is referencing this issue:
![2016-12-21 at 16-26-35](https://cloud.githubusercontent.com/assets/9607853/21397279/15c93a14-c79b-11e6-8d98-e338446e1084.gif)

Notice the closing of the menu before the focus is lost. It's just not very intuitive.

That aside, a "/" is perfectly acceptable in a URL. Why are they being removed? I'm actually wanting to have them so I can mimic the current URL structure of a site I'm replacing...

**Comment by Jabark** [comment] 2016-12-22 09:29
As an aside, if anyone gets here wondering how to add forward slashes in URL's, here's a guide that helped me achieve it: http://www.mathachew.com/blog/add-category-to-urls-in-ghost-0-11-0/

**Comment by ErisDS** [comment] 2017-01-17 17:54
Going to close this as it wasn't reproducible and we haven't had further reports. Can reopen if it is experienced by more people.

**Closed by ErisDS** 2017-01-17 17:54 UTC
Labels: admin-client, bug
