### ISSUE TITLE
getPosts does not get 'derived' fields such as "excerpt" and "reading_time"

### ISSUE THREAD

**Issue by tvld** [TryGhost/Ghost#11623] opened 2020-02-26 08:50 UTC
With ``getPosts`` we do not want to load the full, heavy, html in a post overview list, so we like to use ``fields`` to only retrieve what we need.

We would like to receive derived(?) fields such as ``reading_time`` and ``excerpt`` which does not work. 

For example:
```js
const posts = await api.posts
    .browse({
      include: 'tags,authors',
      fields: 'title,url,excerpt,feature_image,featured,primary_author,published_at,reading_time,slug,updated_at'
    })
```
This will return all fields _except_ the ``reading_time`` and ``excerpt``.  If I use ``custom_excerpt`` that works, but for ``reading_time`` there is no alternative... unless I calculate it myself with getting ``html``, which obsoletes the whole point of the fields reduction...

**Comment by tvld** [comment] 2020-02-26 08:54
Maybe related to  #10482?

**Comment by kevinansfield** [comment] 2020-02-26 08:56
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/10396.

**Closed by kevinansfield** 2020-02-26 08:56 UTC
