### ISSUE TITLE
Editor unusable in firefox (hangs and collapses unexpectedly; sometimes viewport jumps)

### ISSUE THREAD

**Issue by marcelklehr** [TryGhost/Ghost#6233] opened 2015-12-16 17:43 UTC
Hey, I just upgraded my ghost installation and intended to continue work on my new post, when I discovered that the editor is pretty much unusable. At least in firefox. I tried chrome and everything seems to work fine. Instead of discribing what happens I'll just show you:

![unusable-ghost-editor](https://cloud.githubusercontent.com/assets/986878/11848812/e6d40ada-a424-11e5-82a0-c3b85598a92f.gif)

Ghost version: 0.7.2

**Comment by kevinansfield** [comment] 2015-12-16 18:52
Which version of Firefox are you using? I've just tested with version 41 and 0.7.3 and have been unable to reproduce.

**Comment by marcelklehr** [comment] 2015-12-16 19:23
Firefox 42. I'm using ghost 0.7.2, though. Will update asap and try to
reproduce.

**Comment by ErisDS** [comment] 2015-12-19 10:10
Can you also please try testing with any addons disabled?

**Comment by brightbits** [comment] 2015-12-22 16:20
the whole backend hangs randomly for me, in chrome and safari, safari has no add-ons. Seems to be worst when I use the search feature to find a post

**Comment by ErisDS** [comment] 2016-01-05 12:10
@brightbits the issue you described was definitely different as we know from #6274 :+1: 

@marcelklehr did you manage to reproduce the error on 0.7.4 without any addons enabled?

**Comment by ErisDS** [comment] 2016-01-25 13:30
I'm going to close this for now, will reopen if we get more reproduction details.

**Closed by ErisDS** 2016-01-25 13:30 UTC
