### ISSUE TITLE
Deleting a feature image becomes "" instead of null and breaks filter query

### ISSUE THREAD

**Issue by NistorCristian** [TryGhost/Ghost#9085] opened 2017-10-03 09:25 UTC
Hello,
I was trying to get all posts that have set a featured image.

`{{#get "posts" limit="5" filter="id:-{{id}}+feature_image:-null"}}`

First ... I imported all the content from another blog. And the rule `feature_image:-null` was ignored.
I created a new post without the featured image and the filter works. It doesn't get the post. Then I set a featured image, saved the post, removed the featured image and saved again the post. Now the rule `feature_image:-null` gets ignored and the query selects the new post, even if it doesn't have an image.

So something is set in db instead of `null` after the featured image gets removed. 

I exported the json and checked the `feature_image` value.
When I created the post the value was `"feature_image": null` and it was good, but after I set the image and removed it, it became `"feature_image": ""`.

This breaks the filter query.

P.S. In this url: https://api.ghost.org/docs/filter ... it says `filter="featured:true,image:-null"` and should, probably, be `filter="featured:true,feature_image:-null"` and `images:-null` shoud be `feature_image:-null`

* Ghost Version: 1.10.0

**Comment by kirrg001** [comment] 2017-10-03 10:47
Hey @NistorCristian 

Using `{{#get "posts" filter="feature_image:-null"}}` definitely works. Everything else depends on your code e.g. i can't guess if this `id:-{{id}}` is used in the correct context with a correct value.

> P.S. In this url: https://api.ghost.org/docs/filter ... it says filter="featured:true,image:-null" and should, probably, be filter="featured:true,feature_image:-null" and images:-null shoud be feature_image:-null

Thanks will update our docs.

Closing, because this is not a bug. Please wait for help in slack, thanks!

**Comment by NistorCristian** [comment] 2017-10-03 10:59
As I said `{{#get "posts" filter="feature_image:-null"}}` works. 

But it doesn't work after I do this:
Add featured image. Save post.
Remove image. Save post.

The problem is not really with the filter tag. Is more with the fact that when I delete the featured image the value in json becomes `""` instead of `null`.

**Comment by kirrg001** [comment] 2017-10-03 11:55
Okay i see what you mean. This affects all images, because the admin client sends an empty string instead of null. 

@kevinansfield Could we change this behaviour in the admin client?

@NistorCristian I don't have a workaround for you, because our parser does not allow checking for empty strings.

**Comment by NistorCristian** [comment] 2017-10-03 12:06
@kirrg001 No problem, I'm on local. Just testing 😄

**Comment by kevinansfield** [comment] 2017-10-03 12:08
@kirrg001 the client behaviour can be changed but it's probably something that needs to be enforced at the server level too along with a migration to ensure consistency between old and new posts

**Closed** 2018-03-05 08:10 UTC
Labels: bug, optimisation, server
