### ISSUE TITLE
Image upload via Chrome rotated sideways

### ISSUE THREAD

**Issue by leotm** [TryGhost/Ghost#9038] opened 2017-09-22 12:08 UTC
### Issue Summary

See: https://streamable.com/sg0to

The image I uploads fine, but automatically rotates 90° clockwise, giving wrong orientation.

### Steps to Reproduce

1. Go to _Team_ and select an _Active users_
2. Click _EDIT PICTURE_
3. Upload an image

My image is my face cropped with a 1:1 aspect ratio.
The image shouldn't be rotating.

I've noted https://github.com/TryGhost/Ghost/issues/1688 and https://github.com/TryGhost/Ghost/issues/4453 remains under investigation.

### Technical details:

* Ghost Version: 0.11.9
* Node Version: 4.2.6
* Browser/OS: Version 63.0.3221.0 (Official Build) canary (64-bit)
* Database: MySQL

Many thanks

**Comment by kevinansfield** [comment] 2017-09-22 12:15
Closing as a duplicate of #1688.

Ghost doesn't do any image processing so this is a browser issue rather than a Ghost issue. Browsers will rotate images based on any EXIF orientation data that's encoded in the image, you'll need to strip that exif data before uploading if you want consistent results.

**Closed by kevinansfield** 2017-09-22 12:15 UTC

**Comment by leotm** [comment] 2017-09-22 13:26
Thanks @kevinansfield .
Used verexif.com/en/ in the end.
It resulted in the original sideways photo with Exif removed.
Chrome still kept rotating it.
I discovered the Windows 10 Photos app was re-adding the Exif, when using it to rotate.
So just used an image editor (e.g. Paint, Photofiltre), which rotated without re-adding Exif.
Beware of image previewers than can do a touch of editing!

**Comment by josefglatz** [comment] 2017-09-26 19:14
@kevinansfield is it really intended to not add support for basic image processing?

**Comment by knopkem** [comment] 2019-11-07 09:23
Here is a simple tool for anyone that wants to upload images to his (photo) blog and needs to automatically reorient and resize them: https://sourceforge.net/projects/exiforientationfix/
Thanks for creating ghost, it's awesome!
