### ISSUE TITLE
General - Publication upload image buttons do nothing

### ISSUE THREAD

**Issue by ankh2054** [TryGhost/Ghost#9294] opened 2017-11-30 12:35 UTC
Welcome to Ghost's GitHub repo! 👋🎉

Do you need help or have a question? Please come chat in Slack: https://ghost.org/slack 👫. Found a bug? Please fill out the sections below... thank you 👍

If your issue is with Ghost CLI, please report it on the CLI repo ➡️ https://github.com/TryGhost/Ghost-CLI/issues/new.

### Issue Summary

Install new version of Ghost and using chrome or safari the publication image upload buttons do nothing.

### Steps to Reproduce

1. Installed new version of Ghost & uploaded previous posts from over version.
2. Visit General settings
3. Publication identity - try using image upload button 

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version:  1.3.0
* Node Version: v6.10.3
* Browser/OS: Safari & Chrome on OSX High Sierra
* Database: MySQL

**Comment by AileenCGN** [comment] 2017-11-30 12:45
Duplicate of #9292

**Closed by AileenCGN** 2017-11-30 12:45 UTC
