### ISSUE TITLE
Ghost-CLI 1.5.2 fails in a loop with NodeJS 8.10

### ISSUE THREAD

**Issue by gh0-0st** [TryGhost/Ghost#9511] opened 2018-03-18 15:40 UTC
### Issue Summary

Following the information from https://docs.ghost.org/v1/docs/supported-node-versions 
it's indicated that Ghost supports NodeJS version >=8.9 (Node v8 carbon LTS).

Having already Ghost installed and working well with NodeJS version 6.13, 
I wanted to try with version 8.10 on an identical linux server (same machine, same OS) in order to realize a benchmark as it's indicated that version 8.x is more powerful than version 6.x (according to the site nodesource.com).

But, on a Debian Stretch Linux (9.4), with NodeJS v8.10.0 installed, when I run Ghost-CLI v1.5.2, it starts and runs in a loop with the following messages :

```
npm WARN deprecated yarn@1.3.2: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
npm WARN deprecated fs-promise@0.5.0: Use mz or fs-extra^3.0 with Promise Support 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/ghost-cli/node_modules/dtrace-provider/.node-gyp/8.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ghost-cli/node_modules/dtrace-provider/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/ghost-cli/node_modules/dtrace-provider/.node-gyp/8.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ghost-cli/node_modules/dtrace-provider/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/ghost-cli/node_modules/dtrace-provider/.node-gyp/8.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ghost-cli/node_modules/dtrace-provider/.node-gyp"
```

I can only exit this loop with a break "Ctrl+C" but the installation failed.

### Steps to Reproduce

1. Installation NodeJS v8.10.0 and NPM
```
apt install apt-transport-https
curl -sL https://deb.nodesource.com/setup_8.x | bash -
apt install -y nodejs
apt install -y build-essential
```

2. Check NodeJS and NPM versions
```
node -v && npm -v
v8.10.0
5.6.0
```

3. Installation Ghost-CLI v1.5.2 (for now the lasted)
```
npm i -g ghost-cli@latest
npm WARN deprecated yarn@1.3.2: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
npm WARN deprecated fs-promise@0.5.0: Use mz or fs-extra^3.0 with Promise Support 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/ghost-cli/node_modules/dtrace-provider/.node-gyp/8.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ghost-cli/node_modules/dtrace-provider/.node-gyp"
...
```

I clean up then remove NodeJS v8.10.0
I use the same processus with NodeJS v6.13 :
```
node -v && npm -v
v6.13.1
3.10.10
```
then install Ghost-CLI v1.5.2
Ghost-CLI is successfully installed (even if it indicates 1 time the same kind of line as the loop with NodeJS v8.10) :

```
npm WARN deprecated yarn@1.3.2: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.13.1"          
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ghost-cli/node_modules/dtrace-provider/.node-gyp"
> dtrace-provider@0.8.6 install /usr/lib/node_modules/ghost-cli/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js
make : on entre dans le répertoire « /usr/lib/node_modules/ghost-cli/node_modules/dtrace-provider/build »
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make : on quitte le répertoire « /usr/lib/node_modules/ghost-cli/node_modules/dtrace-provider/build »
/usr/lib
└─┬ ghost-cli@1.5.2 
  ├── abbrev@1.1.1 
  ├── adm-zip@0.4.7 
  ├── bluebird@3.5.1 
.
.
.
  │ ├── y18n@3.2.1 
  │ └─┬ yargs-parser@8.1.0 
  │   └── camelcase@4.1.0 
  └── yarn@1.3.2 
```

Check :
```
ghost version
Ghost-CLI version: 1.5.2
```

### Technical details:

* Ghost-CLI Version: 1.5.2
* Ghost Version: N/A
* Node Version: 8.10.0
* Browser/OS: Debian 9.4 (Stretch)
* Database: MariaDB

**Comment by acburdine** [comment] 2018-03-18 17:51
@gh0-0st When installing ghost-cli globally, you'll need to use `sudo` with npm - e.g.`sudo npm i -g ghost-cli@latest` (note: this is what the [official docs](https://docs.ghost.org/docs/install#section-install-ghost-cli) say to use 😉 

Going to close this as it's not a bug in Ghost-CLI, and any further issues should be opened in the Ghost-CLI repo (https://github.com/TryGhost/Ghost-CLI).

**Closed by acburdine** 2018-03-18 17:51 UTC

**Comment by gh0-0st** [comment] 2018-03-19 03:49
Thank you for your reply.

But even when proceeding with the standard "ghostuser" account and use "sudo", there is the same problem.

Here are the details below:

### Steps to Reproduce

1. Create a New User
```
adduser ghostuser
cat /etc/passwd
ghostuser:x:1002:1002:Ghost User,,,:/home/ghostuser:/bin/bash
```

2. Super User Privileges
```
usermod -aG sudo ghostuser
```

3. Installation NodeJS v8.10.0 and NPM
```
ghostuser@host:~$ sudo apt install apt-transport-https
ghostuser@host:~$ curl -sL https://deb.nodesource.com/setup_8.x | bash -
ghostuser@host:~$ sudo apt install -y nodejs
ghostuser@host:~$ sudo apt install -y build-essential
```

4. Check NodeJS and NPM versions
```
ghostuser@host:~$ node -v && npm -v
v8.10.0
5.6.0
```

5. Installation Ghost-CLI v1.5.2 (for now the lasted)
```
ghostuser@host:~$ sudo npm i -g ghost-cli@latest
npm WARN deprecated yarn@1.3.2: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
npm WARN deprecated fs-promise@0.5.0: Use mz or fs-extra^3.0 with Promise Support 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/ghost-cli/node_modules/dtrace-provider/.node-gyp/8.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ghost-cli/node_modules/dtrace-provider/.node-gyp"
...
```

Sorry but same issue with 'sudo' and need a break 'Ctrl+C' to exit this loop.

BUT, really curious, if repeat install Ghost-CLI, this upgrade and done :

```
ghostuser@host:~$ sudo npm i -g ghost-cli@latest                                                             
[sudo] Mot de passe de ghostuser : 
npm WARN deprecated yarn@1.3.2: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
npm WARN deprecated fs-promise@0.5.0: Use mz or fs-extra^3.0 with Promise Support                            
/usr/bin/ghost -> /usr/lib/node_modules/ghost-cli/bin/ghost                                                  
+ ghost-cli@1.5.2
updated 1 package in 7.703s
```

Check :
```
ghostuser@host:~$ ghost version                                                                              
Ghost-CLI version: 1.5.2
```

I repeated the same test twice and it reproduces the same problem well: 
first install failed in loop and second install upgrade and done.

**Comment by AileenCGN** [comment] 2018-03-19 03:55
> any further issues should be opened in the Ghost-CLI repo (https://github.com/TryGhost/Ghost-CLI)

**Comment by gh0-0st** [comment] 2018-03-19 04:57
Ok i open a new ticket : [#675](https://github.com/TryGhost/Ghost-CLI/issues/675).
