### ISSUE TITLE
AMP errors from google search console after upgrading to Ghost v4

### ISSUE THREAD

**Issue by ZsharE** [TryGhost/Ghost#12805] opened 2021-03-22 05:51 UTC
### Issue Summary

After upgrading to Ghost v4 from dashboard on a **PRO** account, we are now receiving an error from google search console: _"Only amp-boilerplate and amp-custom 'style' tags are allowed, and only in the document head"_.

![Only amp-boilerplate and amp-custom 'style' tags are allowed, and only in the document head](http://dev.seomat.com/sources/f5bfffeb-5952-425d-be1f-59019d9f9e43.png)

### To Reproduce

Nothing to reproduce.

### Technical details:

* Ghost Version: **PRO**

**Comment by shubhank008** [comment] 2021-03-22 15:29
Seems was a bug in Ghost v4.0 and has been fixed in v4.1 - https://github.com/TryGhost/Ghost/releases/tag/v4.1.0  
So, just update your Ghost to v4.1 and resubmit the links (else wait for google to automatically crawl them again)

**Comment by louisnt-prod** [comment] 2021-03-22 20:46
Fixed in 4.1.0, update ghost

**Comment by ErisDS** [comment] 2021-03-23 08:05
Duplicate of https://github.com/TryGhost/Ghost/issues/12770, which is fixed in the latest version.

**Closed** 2021-03-23 08:05 UTC
