### ISSUE TITLE
Invite your team image is squished

### ISSUE THREAD

**Issue by novaugust** [TryGhost/Ghost#6380] opened 2016-01-25 15:17 UTC
## Repro

Setup a blog, and on step two you'll see a squished image:

<img width="832" alt="screen shot 2016-01-25 at 08 15 28" src="https://cloud.githubusercontent.com/assets/1207005/12554909/e626308c-c33b-11e5-836f-32eeaf3e24ae.png">

## Specs

- latest master `e5e375057e7b8ed0ec797775a962553a57f18588`
- chrome 48

**Comment by ckousik** [comment] 2016-01-27 13:42
I tried to reproduce this bug but it works fine for me

**Comment by samhattangady** [comment] 2016-01-29 09:12
I managed to successfully reproduce the bug.

Working on Linux, Chrome version 48

**Comment by samhattangady** [comment] 2016-01-29 10:18
I discovered what the problem was.
The y size of the image is fixed, while the x size varies with width of the window.
![screenshot - 01292016 - 03 45 02 pm](https://cloud.githubusercontent.com/assets/15143832/12672939/a7c1b9da-c69f-11e5-8837-5c37475a0748.png)
![screenshot - 01292016 - 03 45 24 pm](https://cloud.githubusercontent.com/assets/15143832/12672950/b0f5048a-c69f-11e5-835b-e71312e36a11.png)

I shall try to fix this, but if anybody else can do it, please go ahead.

**Comment by ErisDS** [comment] 2016-02-02 11:53
Marking this as a blocker as it's pretty fugly. The fix in #6415 works, however setting width and height on an image is an old technique. I believe it was once included in Google's pagespeed guide but has since been removed. Hopefully there's a more modern fix?

**Comment by kevinansfield** [comment] 2016-02-02 15:32
> The fix in #6415 works, however setting width and height on an image is an old technique

The width/height in that PR isn't the fix but just an extra that @jamesslock has added - it does still help with rendering performance but on a single image the performance change is imperceptibly small and hardcodes information that would need to be modified if the image is changed at any point. It's definitely still a useful performance tweak when displaying a lot of images where the width/height of the container element is dependent on the image dimensions.

The fix in #6415 and my fix in #6427 are both equally valid however I erred on the side of caution and avoided removing the `display: flex` on `.gh-flow-content` as it's used in a number of places across the app and I wasn't sure exactly what's depending on that behaviour. @JohnONolan do you remember the reasoning behind having using flexbox in `.gh-flow-content`?

**Comment by JohnONolan** [comment] 2016-02-02 16:37
I don't remember precisely - but I'm fairly certain it was needed, I usually don't add flex until there's a reason for it... but it may be on another screen in the flow, or a transient element.

Reason 23498 why we need visual front-end tests I guess :(

**Closed** 2016-02-03 07:18 UTC
Labels: beginner, blocker, bug, css
