### ISSUE TITLE
Unable to add emojis with iPadOS Safari

### ISSUE THREAD

**Issue by tonilampela** [TryGhost/Ghost#11541] opened 2020-01-25 18:30 UTC
Ghost version 3.3.0. When using editor with Safari of iPadOS 13.3 typing emojis results just mangled characters. On macOS Safari emojis work just fine.
![5BCD0EA1-C91E-4FB3-AE7B-25736442C632](https://user-images.githubusercontent.com/930866/73125611-5e2d2680-3fb1-11ea-8fec-04a6bf1c2ae7.jpeg)

**Comment by s00500** [comment] 2022-08-08 14:09
This is neither stale nor fixed, I have the same issue on the latest 5.6.0

**Comment by s00500** [comment] 2022-08-08 14:09
Is there anyway one can reopen this or do I have to create the same issue again ?

**Comment by s00500** [comment] 2022-08-08 16:32
Hm I can take a look.... but if anybody has pointers it would be useful...

It seems to work just fine if I create the emoji in the ios notes app and then paste it over... could it be that ghosts editor truncates the second half of the unicode char when inserting? It is definitely a problem in the editor, display and storage work fine... and it really only happens on ios browsers

**Comment by ErisDS** [comment] 2022-08-08 18:39
I've reopened the issue - but short of letting you know that the admin client lives in `ghost/admin` now I wouldn't know where to look for this issue. It may well be upstream in [mobiledoc-kit](https://github.com/bustle/mobiledoc-kit) maybe something similar to [this bug](https://github.com/bustle/mobiledoc-kit/issues/761).

Ghost doesn't officially support mobile editing at present - there's another thread where I [explained this recently here](https://github.com/TryGhost/Ghost/issues/14968#issuecomment-1196577845). 

Very very happy for people to get involved and help make the experience better though.

**Comment by s00500** [comment] 2022-08-08 21:33
Thanks for reopening @ErisDS 
And thanks for the pointers, as it seems it is indeed an upstream bug, as it has the same behavior when trying on the official demo of the editor lib here:

https://bustle.github.io/mobiledoc-kit/demo/

I might take a look into this next week....

Generally I can confirm that the ios editing experience is pretty good, there are some glitches here and there but nothing that lead to an unrecoverable situation

For now the workaround with pasting emojis from the notes app also seems to be a viable option in the shirt term

**Comment by JBYoshi** [comment] 2022-08-13 19:03
A fix has been added to mobiledoc-kit v0.14.1. This should be fixed whenever that gets pulled into Ghost.

**Comment by ErisDS** [comment] 2022-08-15 13:28
Oh cool cc @daniellockyer our fork of mobiledoc-kit needs to pull in this patch: https://github.com/bustle/mobiledoc-kit/commit/305b1a2f33c51abd910d6b8ac6ec072347f26eeb

**Closed** 2022-08-16 09:25 UTC
Labels: bug, editor, admin client

**Comment by daniellockyer** [comment] 2022-08-16 09:44
Hey all 👋🏻 I've backported the patch into our mobiledoc-kit fork and bumped it in Ghost. The fix will be available with the next Ghost release 🙂
