### ISSUE TITLE
Ghost 4.3.0 (docker, alphine) keeps crashing

### ISSUE THREAD

**Issue by danielnachtrub** [TryGhost/Ghost#12895] opened 2021-04-22 07:29 UTC
### Issue Summary

Upgrading ghost to 4.3.0 (running on a docker swarm) keeps crashing with error 139 (which might be a segmentation fault). Downgrading to 4.2.2 works fine again.

### To Reproduce

1. Upgrade to 4.3.0
2. Visit blog frontend

### Technical details:

* Ghost Version: 4.3.0
* Node Version: unknown
* Browser/OS: Any
* Database: mysql 8.0.24

**Comment by teddy-ferdinand** [comment] 2021-04-23 08:32
Same issue here, running on K3S, with Sqlite database.

**Comment by noahsbwilliams** [comment] 2021-04-23 19:43
Oh, got the same result here with both Sqlite and MySQL

**Comment by noahsbwilliams** [comment] 2021-04-24 19:05
I'd love to post logs but sadly, there are one. The container exits and restarts without any output. Looking in `docker logs ghost` just shows a regular startup message.

**Comment by Gelmo** [comment] 2021-04-25 23:53
I am able to reproduce this issue consistently by uploading a page image. Reproducible on 4.3.2, not reproducible on 4.2.0

**Comment by braedon** [comment] 2021-04-26 04:27
Seems to be theme dependent for me. The `ruby` theme appears to work fine, for example, but switching to `alto` results in crashing. 

On `alto`, some post images don't load on the home page, and Ghost crashes. Loading posts where the images do load on the home page works fine (once Ghost restarts). Loading posts where the images don't load on the home page results in another crash.

**Comment by ErisDS** [comment] 2021-04-26 05:46
Seeing as this is a docker-only issue, can someone (or all of you) provide a dockerfile and proper reproduction steps please?

**Comment by fsgmhoward** [comment] 2021-04-26 07:47
Using: https://hub.docker.com/_/ghost
Theme: https://github.com/eddiesigner/liebling/releases/tag/v1.0.2

Docker-compose's stack.yml:
```
ghost:
    hostname: ghost
    image: ghost:alpine
    restart: unless-stopped
    volumes:
      - /home/wwwroot/XXXXXX/:/var/lib/ghost/content/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 127.0.0.1:65500:2368
      - ::1:65500:2368
    networks:
      - mariadb_network
      - outside
    environment:
      url: https://XXXXXX
      database__client: mysql
      database__connection__host: mariadb
      database__connection__user: ghost
      database__connection__password: XXXXXX
      database__connection__database: ghost
      mail__transport: SMTP
      mail__options__host: smtp.sendgrid.net
      mail__options__port: 587
      mail__options__auth__user: apikey
      mail__options__auth__pass: XXXXXX
```

Logs:
```
[2021-04-26 07:36:19] INFO Ghost booted in 3.477s
[2021-04-26 07:36:28] INFO Ghost is running in production...
[2021-04-26 07:36:28] INFO Your site is now available on https://XXXXX/
[2021-04-26 07:36:28] INFO Ctrl+C to shut down
[2021-04-26 07:36:28] INFO Ghost server started in 0.808s
[2021-04-26 07:36:29] INFO Database is in a ready state.
[2021-04-26 07:36:29] INFO Ghost database ready in 1.255s
[2021-04-26 07:36:29] WARN Theme's file locales/zh-CN.json not found.
[2021-04-26 07:36:29] WARN Falling back to locales/en.json.
[2021-04-26 07:36:30] WARN Theme's file locales/zh-CN.json not found.
[2021-04-26 07:36:30] WARN Falling back to locales/en.json.
[2021-04-26 07:36:31] INFO Ghost booted in 3.373s
[2021-04-26 07:37:15] WARN Ghost is shutting down
[2021-04-26 07:37:15] WARN Ghost has shut down
[2021-04-26 07:37:15] WARN Your site is now offline
[2021-04-26 07:37:15] WARN Ghost was running for a minute
[2021-04-26 07:37:54] INFO Ghost is running in production...
[2021-04-26 07:37:54] INFO Your site is now available on https://XXXXX/
[2021-04-26 07:37:54] INFO Ctrl+C to shut down
[2021-04-26 07:37:54] INFO Ghost server started in 0.811s
[2021-04-26 07:37:54] INFO Database is in a ready state.
[2021-04-26 07:37:54] INFO Ghost database ready in 1.29s
[2021-04-26 07:37:55] WARN Theme's file locales/zh-CN.json not found.
[2021-04-26 07:37:55] WARN Falling back to locales/en.json.
[2021-04-26 07:37:55] WARN Theme's file locales/zh-CN.json not found.
[2021-04-26 07:37:55] WARN Falling back to locales/en.json.
[2021-04-26 07:37:56] INFO Ghost booted in 3.427s
```

The image is fresh and I pulled it just now.
```
root@bhs-1:/docker# docker image ls ghost
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ghost               alpine              10f8283cfe2f        3 days ago          422MB
```

Boot loop confirms for the latest alpine build of ghost. I am trying whether ghost with other image as base has the same problem.

**Comment by ErisDS** [comment] 2021-04-26 15:39
In that case I'm going to close this as a support request (belongs on the forum to be solved by the community) as it is an issue with the community-maintained docker image using an OS that falls outside of our recommended stack.

**Closed** 2021-04-26 15:39 UTC
Labels: support-request
