### ISSUE TITLE
ER_NO_SUCH_TABLE: Table 'ghost_production.offers' doesn't exist when upgrading v2->v4

### ISSUE THREAD

**Issue by jlengrand** [TryGhost/Ghost#13647] opened 2021-10-21 22:54 UTC
Welcome 👋   
Please keep in mind that GitHub is our office. We invite you to share any bug reports here 🐛..  
For anything else please use https://forum.ghost.org 👫

### Issue Summary

Trying to upgrade from v2.38.3 to v4 fails due to 4.19.1 . Impossible to rollback, site is down :).

### To Reproduce

1. This is the first step
2. This is the second step, etc.

Create a ghost install on latest v2, run `ghost update`, wait. 

### Technical details:

```
Debug Information:
    OS: Ubuntu, v18.04.1 LTS
    Node Version: v14.18.1
    Ghost Version: 4.19.1
    Ghost-CLI Version: 1.17.4
    Environment: production
    Command: 'ghost start'
```

error in the journal : 

```
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at Immediate.Async.drainQueues [as _onImmediate] (/var/www/ghost/versions/4.19.1/node_modules/bluebird/js/release/async.js:15:14)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at processImmediate (internal/timers.js:464:21)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]: Error: ER_NO_SUCH_TABLE: Table 'ghost_production.offers' doesn't exist
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at Query.Sequence._packetToError (/var/www/ghost/versions/4.19.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at Query.ErrorPacket (/var/www/ghost/versions/4.19.1/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at Protocol._parsePacket (/var/www/ghost/versions/4.19.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at Parser._parsePacket (/var/www/ghost/versions/4.19.1/node_modules/mysql/lib/protocol/Parser.js:433:10)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at Parser.write (/var/www/ghost/versions/4.19.1/node_modules/mysql/lib/protocol/Parser.js:43:10)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at Protocol.write (/var/www/ghost/versions/4.19.1/node_modules/mysql/lib/protocol/Protocol.js:38:16)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at Socket.<anonymous> (/var/www/ghost/versions/4.19.1/node_modules/mysql/lib/Connection.js:88:28)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at Socket.<anonymous> (/var/www/ghost/versions/4.19.1/node_modules/mysql/lib/Connection.js:526:10)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at Socket.emit (events.js:400:28)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at addChunk (internal/streams/readable.js:293:12)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at readableAddChunk (internal/streams/readable.js:267:9)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at Socket.Readable.push (internal/streams/readable.js:206:10)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     --------------------
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at Protocol._enqueue (/var/www/ghost/versions/4.19.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at Connection.query (/var/www/ghost/versions/4.19.1/node_modules/mysql/lib/Connection.js:198:25)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at /var/www/ghost/versions/4.19.1/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:134:18
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at new Promise (<anonymous>)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at Client_MySQL._query (/var/www/ghost/versions/4.19.1/node_modules/knex-migrator/node_modules/knex/lib/dialects/mysql/index.js:128:12)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at Client_MySQL.query (/var/www/ghost/versions/4.19.1/node_modules/knex-migrator/node_modules/knex/lib/client.js:168:17)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at Runner.query (/var/www/ghost/versions/4.19.1/node_modules/knex-migrator/node_modules/knex/lib/runner.js:151:36)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at Runner.queryArray (/var/www/ghost/versions/4.19.1/node_modules/knex-migrator/node_modules/knex/lib/runner.js:243:19)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at /var/www/ghost/versions/4.19.1/node_modules/knex-migrator/node_modules/knex/lib/runner.js:38:25
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at /var/www/ghost/versions/4.19.1/node_modules/knex-migrator/node_modules/knex/lib/runner.js:277:24
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at async runColumnMigration (/var/www/ghost/versions/4.19.1/core/server/data/schema/commands.js:388:27)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at async columnMigration (/var/www/ghost/versions/4.19.1/core/server/data/schema/commands.js:401:13)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:     at async Object.down (/var/www/ghost/versions/4.19.1/core/server/data/migrations/utils.js:272:13)
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]: [2021-10-21 22:48:18] WARN Ghost is shutting down
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]: [2021-10-21 22:48:18] WARN Ghost has shut down
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]: [2021-10-21 22:48:18] WARN Your site is now offline
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]: [2021-10-21 22:48:18] WARN Ghost was running for a few seconds
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]: [2021-10-21 22:48:18] INFO Bootstrap client was closed.
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 systemd[1]: Stopping Ghost systemd service for blog: lengrand-fr...
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]: [2021-10-21 22:48:18] WARN Ghost is shutting down
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]: [2021-10-21 22:48:18] WARN Ghost has shut down
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]: [2021-10-21 22:48:18] WARN Your site is now offline
Oct 21 22:48:18 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]: [2021-10-21 22:48:18] WARN Ghost was running for a few seconds
Oct 21 22:48:19 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]: /usr/local/lib/node_modules/ghost-cli/lib/process-manager.js:46
Oct 21 22:48:19 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:         throw error;
Oct 21 22:48:19 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:         ^
Oct 21 22:48:19 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]: {
Oct 21 22:48:19 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]:   message: "Ghost was able to start, but errored during boot with: show columns from `offers` - ER_NO_SUCH_TABLE: Table 'ghost_production.offers' doesn't exist"
Oct 21 22:48:19 blog20210801-s-1vcpu-1gb-intel-ams3-01 node[9343]: }
Oct 21 22:48:19 blog20210801-s-1vcpu-1gb-intel-ams3-01 systemd[1]: ghost_lengrand-fr.service: Main process exited, code=exited, status=1/FAILURE
Oct 21 22:48:19 blog20210801-s-1vcpu-1gb-intel-ams3-01 systemd[1]: ghost_lengrand-fr.service: Failed with result 'exit-code'.
Oct 21 22:48:19 blog20210801-s-1vcpu-1gb-intel-ams3-01 systemd[1]: Stopped Ghost systemd service for blog: lengrand-fr.
```

I have seen this error pop up with v3 here : https://github.com/TryGhost/Ghost/issues/11855. However, the same seems to happen to me with v4. Maybe it is a regression issue? 

In any case, the install failed and it is impossible to rollback, so I am apparently stuck now :).

**Comment by jlengrand** [comment] 2021-10-21 22:57
This is what happens when I try to rollback : 

```
✖ Rolling back database migrations
A ProcessError occurred.

Message: It's not possible to roll back database changes from 4.19.1 to 2.38.3. Please restore from a backup instead

Debug Information:
    OS: Ubuntu, v18.04.1 LTS
    Node Version: v14.18.1
    Ghost Version: 4.19.1
    Ghost-CLI Version: 1.17.4
    Environment: production
    Command: 'ghost update --rollback'

Additional log info available in: /home/ghost-mgr/.ghost/logs/ghost-cli-debug-2021-10-21T22_56_56_866Z.log

Try running ghost doctor to check your system for known issues.
```

and 

```
ghost-mgr@blog20210801-s-1vcpu-1gb-intel-ams3-01:/var/www/ghost$ cat /home/ghost-mgr/.ghost/logs/ghost-cli-debug-2021-10-21T22_56_56_866Z.log
Debug Information:
    OS: Ubuntu, v18.04.1 LTS
    Node Version: v14.18.1
    Ghost Version: 4.19.1
    Ghost-CLI Version: 1.17.4
    Environment: production
    Command: 'ghost update --rollback'
Message: It's not possible to roll back database changes from 4.19.1 to 2.38.3. Please restore from a backup instead
--------------- stderr ---------------
[2021-10-21 22:56:56] ERROR Unable to rollback
```

**Comment by jlengrand** [comment] 2021-10-21 23:01
Well, after following the documentation and doing a `ghost upgrade --force` all previous installs seem to have been removed sooooo I am open for advice over here :)

```
✖ Starting Ghost: lengrand-fr
A GhostError occurred.

Message: Ghost was able to start, but errored during boot with: show columns from `offers` - ER_NO_SUCH_TABLE: Table 'ghost_production.offers' doesn't exist
Suggestion: journalctl -u ghost_lengrand-fr -n 50

Debug Information:
    OS: Ubuntu, v18.04.1 LTS
    Node Version: v14.18.1
    Ghost Version: 4.19.1
    Ghost-CLI Version: 1.17.4
    Environment: production
    Command: 'ghost start'

Additional log info available in: /home/ghost-mgr/.ghost/logs/ghost-cli-debug-2021-10-21T23_00_06_770Z.log

Try running ghost doctor to check your system for known issues.

You can always refer to https://ghost.org/docs/ghost-cli/ for troubleshooting.
```

and no more option to rollback :)

```
ghost-mgr@blog20210801-s-1vcpu-1gb-intel-ams3-01:/var/www/ghost$ ghost update --rollback
+ sudo systemctl is-active ghost_lengrand-fr
+ sudo systemctl reset-failed ghost_lengrand-fr
✔ Checking system Node.js version - found v14.18.1
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
✔ Checking memory availability
✔ Checking free space
✔ Checking for available migrations
✔ Checking for latest Ghost version

# 4.19.1

* 🐛 Fixed handling of "incomplete" subscriptions - Fabien O'Carroll
* 🐛 Fixed "Send" publish type not being reset when closing publish menu - Kevin Ansfield

---

View the changelogs for full details:
* Ghost - https://github.com/tryghost/ghost/compare/v4.19.0...v4.19.1
* Admin - https://github.com/tryghost/admin/compare/v4.19.0...v4.19.1

✔ Fetched release notes
ℹ Downloading and updating Ghost [skipped]
+ sudo /var/www/ghost/current/node_modules/.bin/knex-migrator-rollback --force --v 4.19.1 --mgpath /var/www/ghost/current
✔ Rolling back database migrations
✔ Linking latest Ghost and recording versions
ℹ Removing old Ghost versions [
```

**Comment by jlengrand** [comment] 2021-10-21 23:13
Ok, interestingly, I decided to do a fresh install and try to sort myself out of this problem. 

HOWEVER, even with a fresh install I meet the very same error! 

What I did : 

```
$ mv /var/www/ghost /var/www/ghost-backup
$ mkdir /var/www/ghost, chmod and chown....
$ ghost install, follow instructions.
$ ghost start
```

The result : 

```
ghost-mgr@blog20210801-s-1vcpu-1gb-intel-ams3-01:/var/www/ghost$ ghost start
✔ Checking system Node.js version - found v14.18.1
ℹ Ensuring user is not logged in as ghost user [skipped]
ℹ Checking if logged in user is directory owner [skipped]
✔ Checking current folder permissions
✔ Validating config
✔ Checking memory availability
✔ Checking binary dependencies
✖ Starting Ghost: lengrand-fr
A GhostError occurred.

Message: Ghost was able to start, but errored during boot with: show columns from `offers` - ER_NO_SUCH_TABLE: Table 'ghost_production.offers' doesn't exist

Debug Information:
    OS: Ubuntu, v18.04.1 LTS
    Node Version: v14.18.1
    Ghost Version: 4.19.1
    Ghost-CLI Version: 1.17.4
    Environment: production
    Command: 'ghost start'

Additional log info available in: /home/ghost-mgr/.ghost/logs/ghost-cli-debug-2021-10-21T23_10_36_037Z.log

Try running ghost doctor to check your system for known issues.

You can always refer to https://ghost.org/docs/ghost-cli/ for troubleshooting.
```

**Comment by daniellockyer** [comment] 2021-11-22 21:34
@jlengrand Can you try updating to the latest version of Ghost (4.22.4)?

We recently [fixed an issue](https://github.com/TryGhost/Ghost/issues/13426#issuecomment-966264799) where the rollback function of migrations would run even if the migration had not been executed yet. When we've seen this happen, unexpected actions would happen. The problem is that this has been hiding the actual error that caused the rollback to happen.

If you can try this and paste the full server log, we should be able to see if it's a bug with Ghost or not 🙂 

Slightly related: what version of MySQL are you running? Have you updated it recently? I suspect this is a duplicate of https://github.com/TryGhost/Ghost/issues/13736 and therefore https://github.com/TryGhost/Ghost/issues/13426#issuecomment-966264799

**Closed** 2021-12-06 22:05 UTC
Labels: needs info
