### ISSUE TITLE
outbound link tagging breaks links with a '#' in them

### ISSUE THREAD

**Issue by halphalp** [TryGhost/Ghost#20492] opened 2024-07-01 09:15 UTC
### Issue Summary

specific links that have '#' in them are broken when ghost appends the ref= tags to them, as it inserts the referral tag before the '#' instead of after.

### Steps to Reproduce

1. link to a site with '#' in the link
2. publish post
3. notice the link is now broken because of the outbound tag

### Ghost Version

5.87.0

### Node.js Version

Latest supported

### How did you install Ghost?

Docker

### Database type

MySQL 5.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by vikaspotluri123** [comment] 2024-07-01 15:20
Can you share an example? That sounds like the correct behavior

**Comment by cmraible** [comment] 2024-07-04 22:44
@halphalp I agree that this seems like the correct behavior. Can you please share an example link that is broken because of the outbound tag?

**Comment by cmraible** [comment] 2024-07-30 19:14
Closing this issue as we don't have enough information to evaluate if this is a bug or expected behavior. If you can share an example link, feel free to open again.

**Closed by cmraible** 2024-07-30 19:14 UTC
Labels: needs:info
