### ISSUE TITLE
Broken preview inside the admin UI

### ISSUE THREAD

**Issue by timurguseynov** [TryGhost/Ghost#14416] opened 2022-04-03 23:06 UTC
### Issue Summary

The preview modal is zoomed in and only a part of it visible on the screen. 

Which resolves by removing this line:
`./versions/4.42.0/core/built/assets/vendor.min-ba66b98f7c24fa40e061c7ffc94f4e23.css:1279:  transform: translate(0, -30vh) scale(1.1);`
And adding `height: 100%`

I tried to find this line in the source code but couldn't. 

### Steps to Reproduce

Installed the latest version.

### Ghost Version

4.42.0

### Node.js Version

16

### How did you install Ghost?

Initially with using DO image. But then using ghost cli

### Database type

MySQL 8

### Browser & OS version

Chrome Version 100.0.4896.60, OSX 10.15.7

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment] 2022-04-04 07:07
@timurguseynov Thank you for the report! I'm closing it as a duplicate of https://github.com/TryGhost/Ghost/issues/14415, so please follow progress in there 🙂

**Closed by daniellockyer** 2022-04-04 07:07 UTC
Labels: needs triage

**Comment by daniellockyer** [comment] 2022-04-04 13:14
This was fixed and released in Ghost v4.42.1 🙂

**Comment by timurguseynov** [comment] 2022-04-04 13:49
Thanks, Daniel :)
