### ISSUE TITLE
Member Import "Cannot convert undefined or null to object"

### ISSUE THREAD

**Issue by Gabriel416** [TryGhost/Ghost#16917] opened 2023-06-01 21:17 UTC
### Issue Summary

On self hosted ghost, when trying to import a csv of member emails I get an error saying Cannot convert undefined or null to object. My csv is only one column with email as the header of it. 

### Steps to Reproduce

On a self hosted ghost instance try importing a csv with single email column with member emails

### Ghost Version

5.22.6

### Node.js Version

16.x

### How did you install Ghost?

Digital Ocean

### Database type

MySQL 8

### Browser & OS version

Chrome, Mac OS Big Sur

### Relevant log / error output

```shell
Message: "Cannot convert undefined or null to object", context: null, type: "InternalServerError",
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by daniellockyer** [comment] 2023-06-02 00:34
Would you be able to provide the CSV (or at least a redacted version)? 🙂

**Comment by Gabriel416** [comment] 2023-06-02 01:02
> Would you be able to provide the CSV (or at least a redacted version)? 🙂

[test-member-import.csv](https://github.com/TryGhost/Ghost/files/11630900/test-member-import.csv)

**Comment by Rahulcheerio** [comment] 2023-06-07 15:18
Can I work on this issue?

**Comment by vershwal** [comment] 2023-06-22 16:35
I was checking this issue and here are my findings. 

> On self hosted ghost, when trying to import a csv of member emails I get an error saying Cannot convert undefined or null to object. My csv is only one column with email as the header of it.

The issue is not with number of columns but with the encoding of the file. The file you have provided is of type `charset=utf-8` 

I tried uploading two files with exactly same text, the only difference was that one file was `us-ascii` encoded and other was `utf-8`
<img width="348" alt="image" src="https://github.com/TryGhost/Ghost/assets/17474532/7e356834-c6a0-40de-96c0-74e78f4be2df">

You can try uploading these files yourself:-
ascii : [test-ascii.csv](https://github.com/TryGhost/Ghost/files/11836971/test-ascii.csv)
utf8 : [test-utf8.csv](https://github.com/TryGhost/Ghost/files/11836946/test-utf8.csv)


With the current code only ascii file will be uploaded successfully. This is because the current code does not handle the BOM characters that are generally present in the Unicode-based encoding files.

Read here: [Byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark)

I figured out the issue when I saw this in my debug console 🤯 
<img width="444" alt="image" src="https://github.com/TryGhost/Ghost/assets/17474532/8324a8b1-2e4c-41cb-91f6-9220cf667de1">

Here,  _header === 'email' is false because there are BOM characters present.

@Gabriel416 @daniellockyer Adding a PR to fix this.

**Comment by Gabriel416** [comment] 2023-06-22 20:14
> Byte order mark

Wow great find, really appreciate you working on this!

**Comment by daniellockyer** [comment] 2023-06-23 06:31
@vershwal That's a great find - thanks! Merged for the next release 🙂

**Closed** 2023-06-23 06:31 UTC
Labels: bug
