### ISSUE TITLE
Unable to manipulate image

### ISSUE THREAD

**Issue by 1kevinson** [TryGhost/Ghost#17278] opened 2023-07-11 06:32 UTC
### Issue Summary

Since the last ghost update (`5.53.3`), I'm unable to upload a gif (its size is 6MB) to my blog.

In my container logs, I have the error you see in the screenshot. 

How can I configure the `limitInputPixels` or resolve this issue please ?

### Steps to Reproduce

1. Adding a Gif via the Ghost Editor

2. Expected : Showing the gif in the blog like before

3. What Happened 👇🏾

### In ghost editor
![CleanShot 2023-07-11 at 08 17 47](https://github.com/TryGhost/Ghost/assets/59510116/c6a80f48-762f-4ff9-b59f-a408db413068)

### Ghost container Logs

![CleanShot 2023-07-11 at 08 17 55](https://github.com/TryGhost/Ghost/assets/59510116/7cd53597-08ab-4a44-a3f9-e784e5187cae)

### Ghost Version

5.53.3

### Node.js Version

16.20.1

### How did you install Ghost?

Self-Hosted in a container on a Ubuntu 20 OS

### Database type

MySQL 8

### Browser & OS version

Brave & Mac OS Monterey

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ngeorger** [comment] 2023-07-17 12:39
How did you host your images? Directly? First of all, check permissions and ownerships, then if the script needs some special library in the container

**Comment by markstos** [comment] 2023-07-18 14:20
@ngeorger If Ghost is throwing the error "Input image exceeds pixel limit" when there's a permissions problem, I'd say that's a bug in Ghost.

**Comment by daniellockyer** [comment] 2023-07-20 07:02
This seems to be due to the limit within Sharp - `limitInputPixels`: https://sharp.pixelplumbing.com/api-constructor

We'd probably consider accepting a PR that would make this configurable 🙂

**Comment by 1kevinson** [comment] 2023-07-23 03:21
> How did you host your images? Directly? First of all, check permissions and ownerships, then if the script needs some special library in the container

It's not a permission issue, like @markstos stated, it's a bug in ghost

**Comment by ericalli** [comment] 2023-07-25 04:38
Also experiencing this issue with GIF's. When added:

```
"imageOptimization": {
  "resize": false
}
```

To my Ghost config, it allows me to upload GIF's. But obviously not ideal as it disables optimizations of all other non-GIF images.

**Comment by 1kevinson** [comment] 2023-07-25 06:06
> Also experiencing this issue with GIF's. When added:
> 
> ```
> "imageOptimization": {
>   "resize": false
> }
> ```
> 
> To my Ghost config, it allows me to upload GIF's. But obviously not ideal as it disables optimizations of all other non-GIF images.

Does the difference "before/after" is huge for non-GIF images ?

**Comment by markstos** [comment] 2023-07-25 15:28
For some context, the default for `limitInputPixels` is 268402689 pixels. Some conversions:
 
  * That's 268 Megapixels
  * If the image was square it would have dimensions greater than 16,000 pixels per side.
  * A high resolution 4k screen has dimensions of 4096 x 2160

In other words, it appears this limit is set quite high for typical images. GIFs are not a typical image because it's more a video format-- it contains many frames and thus many pixels.

The GIF format is also horribly inefficient. The format is so bad,  that when large website display "GIFs", they are not actually using the GIF format, but they have instead converted the files to a video format where they be compressed much better. Like,  possibly more than 90% better.

I'm not not sure it makes sense to adapt Ghost to better support this ancient and bloated format that works like video but is actually an image format.

Consider converting the image to another format like `webp` or `mp4` before uploading it. 

https://www.pixx.io/en/blog/gif-alternative

**Comment by 1kevinson** [comment] 2023-07-30 07:46
yes @markstos, I finally use `mp4` format for video, but I compress it before uploading in my articles.

**Comment by Sahil-K123** [comment] 2023-09-28 17:24
Hey @1kevinson , Please assign this issue to me.

**Comment by itsAnuga** [comment] 2023-10-01 00:29
> This seems to be due to the limit within Sharp - `limitInputPixels`: https://sharp.pixelplumbing.com/api-constructor
> 
> We'd probably consider accepting a PR that would make this configurable 🙂

Thats one lazy Core Developer comment, right there...

**Comment by MyWay** [comment] 2023-10-01 10:25
Same here, using docker. Probably has to do with some unsupported operation by my vps cpu. Would it be possible to add an option to disable sharp completely?

**Comment by markstos** [comment] 2023-10-01 16:14
> Would it be possible to add an option to disable sharp completely?

@MyWay It's a modern blog system, it's fairly essential to generate images of different sizes-- for desktop and mobile. It's also a major convenience to have the blog system downsize a huge original photo to the right size that works.   

Unless you have some specific logs to implicate a missing CPU feature, I doubt that's the issue in your environment.

**Comment by 1kevinson** [comment] 2023-10-01 17:58
> Hey @1kevinson , Please assign this issue to me.

Unfortunately I cannot

**Comment by Pratik1603** [comment] 2023-10-03 16:01
Please assign this to me

**Comment by markstos** [comment] 2023-10-03 19:21
@Sahil-K123 @Pratik1603 You don't have to wait for an issue to be assigned to you, just leave a comment that "I'm working on a PR" for this and start on one. Describe how you'd solve the problem if you'd like. Whether the issue is assigned to you or not, there's not guarantee that the pull request you submit later will accepted-- that will depend on the solution you submit and the quality of code. 

By declaring that you are working on it, anyone else reading the issue can decide they want to wait for your PR to be done or pursue another solution for themselves.

**Comment by MyWay** [comment] 2023-10-11 13:58
> > Would it be possible to add an option to disable sharp completely?
> 
> @MyWay It's a modern blog system, it's fairly essential to generate images of different sizes-- for desktop and mobile. It's also a major convenience to have the blog system downsize a huge original photo to the right size that works.   
> 
> Unless you have some specific logs to implicate a missing CPU feature, I doubt that's the issue in your environment. 

No useful logs, unfortunately. I moved the exact same installation on another server (still with docker) and everything works fine.

I bet it's due to some cpu instruction needed by sharp, in my case (my issue wasn't depending on the size of the image, it was crashing for every image I tried to upload).

**Comment by markstos** [comment] 2023-10-11 18:27
OK, I recommend closing this issue then, since it's not happening on your new server, and there no logs to confirm if might be a bug in Ghost or some environmental issue.

**Closed** 2023-10-11 20:23 UTC
Labels: bug
