### ISSUE TITLE
Strange editing behavior: Some key not working 

### ISSUE THREAD

**Issue by shuron** [TryGhost/Ghost#6192] opened 2015-12-09 11:22 UTC
At some point of editing some Keys stop to work...
E.g [o], [Enter] all types of arrows... 
Is there some interference with Keyboard-shortcuts? I tried different PC's and browsers. Same result... :(
Very strange.

**Comment by kevinansfield** [comment] 2015-12-09 11:30
Hey @shuron, on which version of ghost are you seeing this issue? There's a known issue with 0.7.2 but we're currently unable to reproduce on master.

Do you have any concrete steps to reproduce the issue? The one we currently know of:

1. Go to the tags management screen
2. Click on the "new post" link in the sidebar
3. Click in the editor and start typing - you should be unable to type the main shortcut keys c, o, etc, or use the arrow keys

**Comment by B1aZer** [comment] 2015-12-09 11:47
This happened to me yesterday as well on OSX and Firefox 42. The 'c' key was not working so I switched to Chrome.

But today I'm not able to reproduce it using your steps. 
Ghost 0.7.2

**Comment by kevinansfield** [comment] 2015-12-09 17:53
@shuron 0.7.1 fixed the issue that was present in 0.7.0.

There's been a regression in 0.7.2 related to the tags screen.

**Comment by shuron** [comment] 2015-12-09 17:59
Ok, i'll try to update this soon (today or tomorrow.)

**Comment by kevinansfield** [comment] 2015-12-09 18:39
@acburdine did you get very far with your investigations into this?

I think it probably has something to do with these lines https://github.com/TryGhost/Ghost/blob/master/core/client/app/components/gh-tag-settings-form.js#L94-L100. I'm going to have a look into this tomorrow morning as they are also messing with the modals refactor, it's a bit of a tricky one as we want the navigation/selection shortcuts but at the same time we need to disable them for any inputs on the form that's displayed on the same screen.

First port of call will be making `gh-input` change the keymaster scope on focus/blur - I'm not aware of anywhere in the app that we want keymaster shortcuts to work whilst an input has focus.

**Comment by acburdine** [comment] 2015-12-09 20:21
@kevinansfield I messed around with it for a bit and couldn't get the issue to replicate on master. My thought is that the Ember 2.x upgrade could have changed how focusIn/focusOut works with route transitions and that means the focusOut call in tags-settings actually gets called all of the time.

Either that or #6078 .

I can add something to the text-input mixin to change scope on focus/blur, but I think the bug has been fixed. :fingers_crossed:

**Comment by kevinansfield** [comment] 2015-12-10 12:04
Ok, I've tracked down the 0.7.2 issue and @acburdine is correct, the fix was in #6078, specifically ensuring `_super` is called in the `deactivate` hooks for [tag settings routes](https://github.com/TryGhost/Ghost/pull/6078/files#diff-33) so that the shortcuts are removed when leaving those routes.

I also have another PR ready to go that should further improve the shortcuts handling in the tag settings screen.

**Comment by kevinansfield** [comment] 2015-12-10 12:33
Closing for now as I've not been able to find any reproducible cases on master since #6078 landed. Will re-open if any further issues are reported.

**Closed by kevinansfield** 2015-12-10 12:33 UTC
Labels: blocker, bug, ember
