### ISSUE TITLE
New instance - Error prevents Theme change (Validation (FieldIsRequired) failed for ref)

### ISSUE THREAD

**Issue by NicolaGenesin** [TryGhost/Ghost#13715] opened 2021-11-05 22:38 UTC
### Issue Summary

New installation on a brand new server. Error appears while trying to apply a (any) theme. 

<img width="648" alt="Screenshot 2021-11-05 at 23 30 15" src="https://user-images.githubusercontent.com/3284778/140585984-1891428c-4d6a-4256-ba77-993ce0119f49.png">

```
[2021-11-05 22:18:20] INFO "GET /ghost/api/canary/admin/themes/" 200 63ms
[2021-11-05 22:18:21] ERROR "POST /ghost/api/canary/admin/themes/install/?source=github" 422 14ms

NAME: ValidationError
MESSAGE: Validation (FieldIsRequired) failed for ref

level: normal

ValidationError: Validation (FieldIsRequired) failed for ref
    at /var/www/ghost/versions/4.22.0/core/server/api/shared/validators/input/all.js:39:25
    at /var/www/ghost/versions/4.22.0/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/var/www/ghost/versions/4.22.0/node_modules/lodash/lodash.js:3032:24)
    at /var/www/ghost/versions/4.22.0/node_modules/lodash/lodash.js:4936:18
    at Function.forEach (/var/www/ghost/versions/4.22.0/node_modules/lodash/lodash.js:9410:14)
    at validate (/var/www/ghost/versions/4.22.0/core/server/api/shared/validators/input/all.js:37:7)
    at Object.all (/var/www/ghost/versions/4.22.0/core/server/api/shared/validators/input/all.js:97:32)
    at allShared (/var/www/ghost/versions/4.22.0/core/server/api/shared/validators/handle.js:35:37)
    at /var/www/ghost/versions/4.22.0/node_modules/@tryghost/promise/lib/sequence.js:10:31
    at tryCatcher (/var/www/ghost/versions/4.22.0/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/var/www/ghost/versions/4.22.0/node_modules/bluebird/js/release/reduce.js:168:18)
    at Object.gotAccum (/var/www/ghost/versions/4.22.0/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/var/www/ghost/versions/4.22.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/4.22.0/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/www/ghost/versions/4.22.0/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/var/www/ghost/versions/4.22.0/node_modules/bluebird/js/release/promise.js:641:10)
```

### To Reproduce

Goto {hostname}/ghost/#/settings/design/change-theme/Journal then click on "Use Journal" at the top right of the screen

```
/var/www/ghost$ ghost doctor
✔ Checking system Node.js version - found v14.18.1
✔ Checking logged in user
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
✔ Checking system compatibility
✔ Checking for a MySQL installation
+ sudo systemctl is-active ghost_aviational-net
Instance is currently running
ℹ Validating config [skipped]
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
✔ Checking memory availability
✔ Checking binary dependencies
✔ Checking free space
✔ Checking systemd unit file
✔ Checking systemd node version - found v14.18.1
```

### Technical details:

* Ghost Version:  v4.22.0 / Cli: v1.18.0
* Node Version: v14.18.1
* Browser/OS: Chrome 95.0.4638.69 (Official Build) (arm64) / ubuntu0.20.04.1
* Database: 8.0.27-0ubuntu0.20.04.1

**Comment by ShivanS93** [comment] 2021-11-20 19:45
Yes, I'm getting this problem as well. Stuck on Casper for now.

**Comment by ericmaxwell** [comment] 2021-11-21 10:31
Having similar issue in two different blogs. 

`ghost-mgr@ghost-ubuntu:/var/www/ghost$ ghost log
+ sudo systemctl is-active ghost_blog-ericmaxwell-com
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/config/" 200 17ms
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/settings/?group=site%2Ctheme%2Cprivate%2Cmembers%2Cportal%2Cnewsletter%2Cemail%2Camp%2Clabs%2Cslack%2Cunsplash%2Cviews%2Cfirstpromoter%2Coauth%2Ceditor" 200 46ms
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/notifications/" 200 47ms
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/members/stats/count/" 200 130ms
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/members/events/?limit=5" 200 146ms
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/members/?filter=email_open_rate%3A-null&order=email_open_rate%20desc&limit=5&include=labels%2CemailRecipients" 200 117ms
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/emails/?filter=email_count%3A-0&order=submitted_at%20desc&limit=5" 200 117ms
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/products/?include=monthly_price%2Cyearly_price&limit=all" 200 121ms
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/members/?filter=status%3Apaid&order=created_at%20asc&limit=5&include=labels%2CemailRecipients" 200 86ms
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/members/stats/mrr/" 200 80ms
[2021-11-21 10:28:39] INFO "GET /ghost/api/canary/admin/settings/?group=site%2Ctheme%2Cprivate%2Cmembers%2Cportal%2Cnewsletter%2Cemail%2Camp%2Clabs%2Cslack%2Cunsplash%2Cviews%2Cfirstpromoter%2Coauth%2Ceditor" 200 73ms
[2021-11-21 10:28:39] INFO "GET /ghost/api/canary/admin/custom_theme_settings/" 200 71ms
[2021-11-21 10:28:39] INFO "POST /" 200 78ms
[2021-11-21 10:28:39] INFO "GET /ghost/api/canary/admin/themes/" 200 25ms
[2021-11-21 10:28:39] INFO "GET /public/cards.min.js?v=d0ecbc557c" 200 2ms
[2021-11-21 10:28:39] INFO "GET /members/api/member/" 204 2ms
[2021-11-21 10:28:39] INFO "GET /members/api/site/" 200 17ms
[2021-11-21 10:28:46] INFO "GET /ghost/api/canary/admin/themes/" 200 25ms
[2021-11-21 10:28:49] INFO "GET /ghost/api/canary/admin/themes/" 200 22ms
[2021-11-21 10:28:50] ERROR "POST /ghost/api/canary/admin/themes/install/?source=github" 422 12ms

NAME: ValidationError
MESSAGE: Validation (FieldIsRequired) failed for ref

level: normal

ValidationError: Validation (FieldIsRequired) failed for ref
    at /var/www/ghost/versions/4.22.4/core/server/api/shared/validators/input/all.js:39:25
    at /var/www/ghost/versions/4.22.4/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/var/www/ghost/versions/4.22.4/node_modules/lodash/lodash.js:3032:24)
    at /var/www/ghost/versions/4.22.4/node_modules/lodash/lodash.js:4936:18
    at Function.forEach (/var/www/ghost/versions/4.22.4/node_modules/lodash/lodash.js:9410:14)
    at validate (/var/www/ghost/versions/4.22.4/core/server/api/shared/validators/input/all.js:37:7)
    at Object.all (/var/www/ghost/versions/4.22.4/core/server/api/shared/validators/input/all.js:97:32)
    at allShared (/var/www/ghost/versions/4.22.4/core/server/api/shared/validators/handle.js:35:37)
    at /var/www/ghost/versions/4.22.4/node_modules/@tryghost/promise/lib/sequence.js:10:31
    at tryCatcher (/var/www/ghost/versions/4.22.4/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/var/www/ghost/versions/4.22.4/node_modules/bluebird/js/release/reduce.js:168:18)
    at Object.gotAccum (/var/www/ghost/versions/4.22.4/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/var/www/ghost/versions/4.22.4/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/4.22.4/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/www/ghost/versions/4.22.4/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/var/www/ghost/versions/4.22.4/node_modules/bluebird/js/release/promise.js:641:10)

`

`ghost-mgr@ghost-ubuntu:/var/www/ghost$ ghost doctor
✔ Checking system Node.js version - found v14.18.1
✔ Checking logged in user
✔ Ensuring user is not logged in as ghost user
✔ Checking if logged in user is directory owner
✔ Checking current folder permissions
✔ Checking system compatibility
✔ Checking for a MySQL installation
+ sudo systemctl is-active ghost_blog-ericmaxwell-com
Instance is currently running
ℹ Validating config [skipped]
✔ Checking folder permissions
✔ Checking file permissions
✔ Checking content folder ownership
✔ Checking memory availability
✔ Checking binary dependencies
✔ Checking free space
✔ Checking systemd unit file
✔ Checking systemd node version - found v14.18.1
`

**Comment by ericmaxwell** [comment] 2021-11-21 10:36
Yes, same issue here on two different blogs. Same error: 

ghost-mgr@ghost-ubuntu:/var/www/ghost$ ghost log
+ sudo systemctl is-active ghost_blog-xxxxxxx-com
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/config/" 200 17ms
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/settings/?group=site%2Ctheme%2Cprivate%2Cmembers%2Cportal%2Cnewsletter%2Cemail%2Camp%2Clabs%2Cslack%2Cunsplash%2Cviews%2Cfirstpromoter%2Coauth%2Ceditor" 200 46ms
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/notifications/" 200 47ms
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/members/stats/count/" 200 130ms
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/members/events/?limit=5" 200 146ms
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/members/?filter=email_open_rate%3A-null&order=email_open_rate%20desc&limit=5&include=labels%2CemailRecipients" 200 117ms
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/emails/?filter=email_count%3A-0&order=submitted_at%20desc&limit=5" 200 117ms
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/products/?include=monthly_price%2Cyearly_price&limit=all" 200 121ms
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/members/?filter=status%3Apaid&order=created_at%20asc&limit=5&include=labels%2CemailRecipients" 200 86ms
[2021-11-21 10:28:33] INFO "GET /ghost/api/canary/admin/members/stats/mrr/" 200 80ms
[2021-11-21 10:28:39] INFO "GET /ghost/api/canary/admin/settings/?group=site%2Ctheme%2Cprivate%2Cmembers%2Cportal%2Cnewsletter%2Cemail%2Camp%2Clabs%2Cslack%2Cunsplash%2Cviews%2Cfirstpromoter%2Coauth%2Ceditor" 200 73ms
[2021-11-21 10:28:39] INFO "GET /ghost/api/canary/admin/custom_theme_settings/" 200 71ms
[2021-11-21 10:28:39] INFO "POST /" 200 78ms
[2021-11-21 10:28:39] INFO "GET /ghost/api/canary/admin/themes/" 200 25ms
[2021-11-21 10:28:39] INFO "GET /public/cards.min.js?v=d0ecbc557c" 200 2ms
[2021-11-21 10:28:39] INFO "GET /members/api/member/" 204 2ms
[2021-11-21 10:28:39] INFO "GET /members/api/site/" 200 17ms
[2021-11-21 10:28:46] INFO "GET /ghost/api/canary/admin/themes/" 200 25ms
[2021-11-21 10:28:49] INFO "GET /ghost/api/canary/admin/themes/" 200 22ms
[2021-11-21 10:28:50] ERROR "POST /ghost/api/canary/admin/themes/install/?source=github" 422 12ms

NAME: ValidationError
MESSAGE: Validation (FieldIsRequired) failed for ref

level: normal

ValidationError: Validation (FieldIsRequired) failed for ref
    at /var/www/ghost/versions/4.22.4/core/server/api/shared/validators/input/all.js:39:25
    at /var/www/ghost/versions/4.22.4/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/var/www/ghost/versions/4.22.4/node_modules/lodash/lodash.js:3032:24)
    at /var/www/ghost/versions/4.22.4/node_modules/lodash/lodash.js:4936:18
    at Function.forEach (/var/www/ghost/versions/4.22.4/node_modules/lodash/lodash.js:9410:14)
    at validate (/var/www/ghost/versions/4.22.4/core/server/api/shared/validators/input/all.js:37:7)
    at Object.all (/var/www/ghost/versions/4.22.4/core/server/api/shared/validators/input/all.js:97:32)
    at allShared (/var/www/ghost/versions/4.22.4/core/server/api/shared/validators/handle.js:35:37)
    at /var/www/ghost/versions/4.22.4/node_modules/@tryghost/promise/lib/sequence.js:10:31
    at tryCatcher (/var/www/ghost/versions/4.22.4/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/var/www/ghost/versions/4.22.4/node_modules/bluebird/js/release/reduce.js:168:18)
    at Object.gotAccum (/var/www/ghost/versions/4.22.4/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/var/www/ghost/versions/4.22.4/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/4.22.4/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/www/ghost/versions/4.22.4/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/var/www/ghost/versions/4.22.4/node_modules/bluebird/js/release/promise.js:641:10)

**Comment by ericmaxwell** [comment] 2021-11-21 11:31
@ShivanS93 FYI you can download other Themes from the internet and upload them. Then, under Advanced in the Theme selection area you can switch between the themes you have uploaded yourself. That way you won't be stuck on Casper if you don't want to be.

**Comment by ShivanS93** [comment] 2021-11-21 19:39
> @ShivanS93 FYI you can download other Themes from the internet and upload them. Then, under Advanced in the Theme selection area you can switch between the themes you have uploaded yourself. That way you won't be stuck on Casper if you don't want to be.

Ahh, you are a lifesaver. Thank you!

**Comment by matthanley** [comment] 2021-11-22 16:34
Thanks for the report! I've been unable to reproduce this on the latest version of Ghost. In order to troubleshoot further, I'd be grateful if you could:

- Upgrade to the latest Ghost version and verify that the issue still exists
- Confirm the issue still exists in a different browser without any plugins or extensions enabled (it may be that a privacy plugin is stripping the `ref=` query parameter we use to identify the theme being installed)

**Comment by MikeRossXYZ** [comment] 2021-11-28 14:18
Your tip about a vanilla browser worked for me! I'm a Firefox user and it wasn't working. I disabled all my extensions and the built-in tracking protection, but still no luck. Installed Chromium (shudder) and everything works fine. Not a solution, per se, but a good workaround while the Ghost team investigates.

**Comment by aadilayub** [comment] 2022-05-21 10:32
I wouldn't consider this issue solved. Switching to Chromium is a workaround, but users shouldn't have to change their browsers to perform a common action like switching a theme.

**Comment by matthanley** [comment] 2022-05-31 11:35
@aadilayub could you provide some more info on your environment, along with reproduction steps? I'm unable to reproduce the issue in Safari/Firefox/Chrome on macOS.

**Comment by aadilayub** [comment] 2022-06-02 12:03
I was able to pinpoint the issue. Once I disabled the [ClearURLs](https://docs.clearurls.xyz/1.23.0/) extension, the error disappeared. Does changing themes require sending a querystring by any chance?

**Comment by matthanley** [comment] 2022-06-02 16:40
Yes, a query param (`?ref=`) is required for theme installation in Admin - thanks for the feedback, and I'm pleased you resolved your issue.

I'll close this for now as the previous report was over 6 months ago, but happy to reopen if anyone else is still experiencing the same problem.

**Closed by matthanley** 2022-06-02 16:40 UTC
Labels: needs info

**Comment by mahyarmirrashed** [comment] 2022-07-08 04:05
> Yes, a query param (`?ref=`) is required for theme installation in Admin - thanks for the feedback, and I'm pleased you resolved your issue.
> 
> I'll close this for now as the previous report was over 6 months ago, but happy to reopen if anyone else is still experiencing the same problem.

Had this problem but as mentioned, it came from the ClearURLs extension.

**Comment by jdaviescoates** [comment] 2023-01-21 14:28
> but happy to reopen if anyone else is still experiencing the same problem.

I hit the same thing last night, but yes I was using Firefox and had ClearURLs addon installed.

**Comment by jhulten** [comment] 2024-07-11 20:57
> I'll close this for now as the previous report was over 6 months ago, but happy to reopen if anyone else is still experiencing the same problem.

I just experienced the same thing today. I also use ClearURLs. `ref=` is probably a poor choice or accepting when it is not provided would work.

**Comment by nabeelio** [comment] 2024-11-30 22:42
I'm getting this error on Firefox and Firefox Nightlys

**Comment by nabeelio** [comment] 2024-11-30 22:42
> > but happy to reopen if anyone else is still experiencing the same problem.
> 
> I hit the same thing last night, but yes I was using Firefox and had ClearURLs addon installed.

Ahh, great tip. I'm running this too
