### ISSUE TITLE
OAuth: Handle intermittent internet connectivity

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6868] opened 2016-05-20 09:35 UTC
For the longest time, poor @JohnONolan has reported constantly being logged out of Ghost. Something myself and other devs have never been able to reproduce.

Today, after another report, I thought I'd check in to see if something had changed in Ember Simple Auth that might cause the session to not refresh, and I stumbled across [this issue about disconnects](https://github.com/simplabs/ember-simple-auth/issues/980).

This is by far and away the best theory I've ever had for why some people can't stay connected - after all John lives somewhere where the internet connectivity is unstable and the rest of the devs all have awesome WiFi. It makes perfect sense that token refresh requests are frequently failing, and if there is no handling or retries this would result in re-auth dialogs popping up on a regular basis.

The [issue on ESA](https://github.com/simplabs/ember-simple-auth/issues/980) outlines some application-level solutions, and apparently there is also a discussion on the slack channel.

I'd really like to see retries after connection drops handled in Ghost in lieu of support perhaps being added to ESA. This would fix one of the most gnarly and annoying issues we have!

**Comment by rhyek** [comment] 2016-05-20 22:12
Hi, Eris. I created the issue you're referencing. Just a caveat on my current working solution which you mention: I am essentially overriding the private method `_refreshAccessToken` by copying the original implementation into my own authenticator. This was necessary because, currently, `_refreshAccessToken` does not reject with the `xhr` object which you need in order to determine the cause of the failure.

Maybe this is something that could change in ESA at a later time. Good luck.

**Comment by ErisDS** [comment] 2016-05-23 08:51
@rhyek thanks for the info 👍

**Comment by ErisDS** [comment] 2016-05-24 15:43
Note here: we also need to check if poor internet connectivity could be interfering with signing in at all - e.g. does the User model hide away connectivity errors and make them look like bad passwords?

**Comment by rhyek** [comment] 2016-05-26 12:23
Eris, I have a created a [gist](https://gist.github.com/rhyek/55e75d6dc45eaa65bceac510196c2a30#file-application-js-L115) with my complete oauth2 authenticator. Maybe it will help you. Features are:

- Ensure only one tab/window is handling token refreshes to avoid 400/401 errors due to concurrent requests and lowering bandwidth used.
- If a token refresh is rejected with 400/401 http status codes, invalidate the session.
- Attempt token refreshes when 90% of the access token's lifetime has transpired, leaving the remaining 10% as an opportunity to retry the refresh in case of connection failures.
- If a token refresh failes due to a connection error, keep trying every 5 seconds until the current access token's lifetime has expired, in which case, the session will be invalidated.

**Closed** 2016-07-21 04:52 UTC
Labels: bug, ember, fix wanted, OAuth
