### ISSUE TITLE
Routes upload not working in 3.13.1 / 3.13.3

### ISSUE THREAD

**Issue by janpersiel** [TryGhost/Ghost#11744] opened 2020-04-16 14:48 UTC
### Issue Summary

Using Safari 13.0.5 / MacOS 10.15.3 I am not able to upload a routes.yaml to the Routes section. Not even the previously downloaded and unmodified routes.yaml will work. The issue is that the file browser does not even offer the file to be selected with that .yaml extension (greyed out).

### To Reproduce

1. Download the routes.yaml
2. open the uploader, browse for the downloaded (or any other .yaml) file
3. The file is not selectable and therefore cannot be uploaded

### Technical details:

* Ghost Version: 3.13.1 and 3.13.3
* Node Version: 10.2.0 and 10.20.0
* Browser/OS: Mac 10.15.3 / Safari 13.0.5
* Database: MySQL

**Comment by vikaspotluri123** [comment] 2020-04-16 14:57
Dupe of #11472 😉 Does https://github.com/TryGhost/Ghost/issues/11472#issuecomment-592234058 help?

**Comment by janpersiel** [comment] 2020-04-16 15:08
@vikaspotluri123 tried that before posting. Unfortunately that does not solve it. The .yml did work indeed and threw an error, but the renaming did not work as a next step.

**Comment by kevinansfield** [comment] 2020-04-16 21:31
Closing as duplicate of https://github.com/TryGhost/Ghost/issues/11472

**Closed by kevinansfield** 2020-04-16 21:31 UTC
