### ISSUE TITLE
Author 404

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8710] opened 2017-07-19 18:48 UTC
Not sure what's happening here:

https://lionsroar.ghst.pro/the-buddha-taught-one-thing-only/

Author is listed as Sharon Salzberg, but when you click on her profile URL at the bottom of the post: https://lionsroar.ghst.pro/author/sharon-salzberg/ you get a 404

Within Ghost admin, the post shows as being authored by another user entirely:

![image](https://user-images.githubusercontent.com/120485/28383980-0f240b42-6cd4-11e7-9fea-1b3806263442.png)

Editing the content and saving/updating the post does not change anything.

This post was imported, so I'm not sure if it might be an import error. I have the import file if anyone wants it - not going to post it here because it has private user email addresses in it.

Wouldn't normally say this was a blocker, but given how much the importer is going to be used it seems like it might be one?

Ghost 1.0-rc1

**Comment by kevinansfield** [comment] 2017-07-19 18:54
This sounds like it may be a duplicate of https://github.com/TryGhost/Ghost/issues/8645? @kirrg001 is looking into that for 1.0 - it's already been identified as a blocker, doesn't look like the tag was added though.

I'll double check the author bug in Ghost-Admin - that's a new detail.

**Comment by kirrg001** [comment] 2017-07-19 22:43
> This sounds like it may be a duplicate of #8645

Yes, duplicate.

> Within Ghost admin, the post shows as being authored by another user entirely:

I guess that might be caused by https://github.com/TryGhost/Ghost/pull/8693.

---

This also relates to https://github.com/TryGhost/Ghost/issues/8652, which suggests adding a new category to the team view e.g. `locked users` (next to suspended and active users). All three categories have a different meaning. Suspended/Inactive users can't do anything anymore. Locked users are still active users, but they have to reset their password to be able to access the admin panel again.

**Closed** 2017-07-20 11:45 UTC
Labels: blocker/critical, bug, server
