### ISSUE TITLE
[Bug] Full Screen Post Preview giving 500 error

### ISSUE THREAD

**Issue by ErikAGriffin** [TryGhost/Ghost#9570] opened 2018-04-16 15:56 UTC
### Issue Summary

Hi, I am hosting a ghost blog on heroku and am getting a 500 error "`[post.hbs] Cannot read property 'length' of undefined`" when trying to preview a draft of a post.  I've tracked the issue down to the  `/core/server/helpers/has.js` file, in which the `var self = this;` statement is returning `undefined`.  However, I don't understand exactly what 'this' in that files context or how ti could be undefined.

### Steps to Reproduce

1. Begin a new draft of a post from the admin panel.
2. Click the Post Settings button on the right hand side.
3. Click Preview
4. 500 error

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 1.22.2 
* Node Version: 8.11.1
* Browser/OS: Chrome Mac OSX 10.13.3
* Database: MySQL (JawsDB)

**Comment by vikaspotluri123** [comment] 2018-04-16 16:02
Duplicate of #9567 😉

**Comment by kevinansfield** [comment] 2018-04-16 16:03
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/9567. New release containing a fix will be out tomorrow.

**Closed by kevinansfield** 2018-04-16 16:03 UTC
