### ISSUE TITLE
Author field in post settings is often buggy 

### ISSUE THREAD

**Issue by tomamity** [TryGhost/Ghost#9590] opened 2018-04-19 00:42 UTC
### Issue Summary

I'm using the desktop app on mac. I often try to change authors on the settings of a post and find it buggy. I'll remove an author and it will say you need at least one author, and adds it back. Then I'll add a second author and try remove the first and both will be removed and then re-added again. The problem is this issue doesn't occur 100% of the time, but does occur enough to be frustrating. 

### Steps to Reproduce

1. Add post content 
2. Go to author 
3. Try remove an author and add another 

### Technical details:

* Ghost Version: 1.5.2
* Node Version:
* Browser/OS: Chrome/Sierra 10.12.6
* Database:

**Comment by kevinansfield** [comment] 2018-04-19 08:53
Hey @tomamity 👋 Thanks for reporting, I'm going to close this as a duplicate of https://github.com/TryGhost/Ghost/issues/9575. I'll be looking into it next week unless we get a community PR sooner 😄

**Closed by kevinansfield** 2018-04-19 08:53 UTC
