### ISSUE TITLE
Posted date on blog post alternates between two dates

### ISSUE THREAD

**Issue by sten626** [TryGhost/Ghost#7858] opened 2017-01-18 00:55 UTC
### Issue Summary

On my self hosted ghost blog, at http://indzeoski.ca, the posted date of my blog post "My Top 10 Albums of 2015" changes randomly. On both the main page and the post itself, sometimes the date is December 31, 2015, and other times it's January 1, 2016. I made the post on December 31 but I'm not sure what time.

### Steps to Reproduce

Seems random. Sorry I'm unable to figure out more details. Sometimes something as simple as refreshing or clicking through to the post changes the date; sometimes it doesn't.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

The date should stay the same.

### Technical details:

* Ghost Version: 0.11.3
* Node Version: 6.9.4
* Browser/OS: Both Chrome and Safari on MacOS
* Database:  Whatever Ghost uses by default

**Comment by acburdine** [comment] 2017-01-18 01:03
@sten626 do you have an explicit timezone set in your settings?

**Comment by sten626** [comment] 2017-01-18 01:05
Yes it's set to my time zone, (GMT -6:00) Saskatchewan.

**Comment by acburdine** [comment] 2017-01-18 01:18
@sten626 ok :) can you go into the post editor for the post that you're seeing it with and show (screenshot or just copy-paste) what the Publish Date says? Just trying to get as much info as possible to try to reproduce this.

**Comment by sten626** [comment] 2017-01-18 01:21
31 Dec 15 @ 18:08

Would have given this right away but didn't know it was there. Good to know. Not as close to midnight as I thought it might be based on the problem.

**Comment by acburdine** [comment] 2017-01-18 01:26
@sten626 Thanks for the info! I'll try and reproduce this as well and see what I can find. Last question: do you use any sort of caching (cloudflare or otherwise)?

**Comment by sten626** [comment] 2017-01-18 02:13
I don't think there's any caching, unless there's something I'm not aware of. It's just hosted on digital ocean with a super basic nginx setup.

**Comment by kevinansfield** [comment] 2017-01-18 12:25
Is this related to https://github.com/TryGhost/Ghost/issues/7655?

**Comment by acburdine** [comment] 2017-01-18 13:54
Probably. @sten626 sorry to ask you to do anything more, but can you try the steps listed in [this comment](https://github.com/TryGhost/Ghost/issues/7655#issuecomment-266225264) and see if they fix the problem? It's still a bug either way, but would be good to reduce duplicate issues 😉

**Comment by sten626** [comment] 2017-01-20 04:22
@acburdine Yeah following those steps seemed to reproduce/resolve the problem. Except I tried just going to the admin page and not actually hitting save on anything and it still worked.

**Comment by acburdine** [comment] 2017-01-20 04:59
ok good to know - I'm going to close this one then as a duplicate of #7655 😄

**Closed by acburdine** 2017-01-20 04:59 UTC
Labels: bug
